kickstarter/android-oss

.gitignore
.gitmodules
Makefile

We're having lots of problems with using submodules for the secrets. Im just gonna copy what we are doing in iOS and clone it straight up...

Don't use a submodule for secrets

---

app/src/main/java/com/kickstarter/ui/viewholders/ProjectCardViewHolder.java

Removed an unused variable of DiscoveryViewModel in ProjectCardViewHolder.

Remove unused class member (viewModel) in ProjectCardViewHolder

---

app/src/main/java/com/kickstarter/ui/activities/HelpActivity.java
app/src/main/java/com/kickstarter/ui/activities/WebViewActivity.java

- This change just fixes to use uppercase letter notation to long value.

Fix to use uppercase letter notation to long value.

---

app/src/main/java/com/kickstarter/libs/ActivityViewModel.java
app/src/main/java/com/kickstarter/libs/BaseActivity.java
app/src/main/java/com/kickstarter/ui/toolbars/KSToolbar.java

CompositeSubscription is RxJava's representation of a group of
Subscriptions.

Replace List<Subscription> with CompositeSubscription

---

app/src/main/java/com/kickstarter/libs/Koala.java
app/src/main/java/com/kickstarter/ui/intentmappers/IntentMapper.java
app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.java
app/src/test/java/com/kickstarter/ui/intents/IntentMapperTest.java

Support for our 🐨 app banner open event.

Add IntentMapper banner helper and tests

---

app/src/main/java/com/kickstarter/libs/Koala.java
app/src/main/java/com/kickstarter/libs/KoalaContext.kt
app/src/main/java/com/kickstarter/libs/KoalaEvent.java
app/src/main/java/com/kickstarter/services/KSUri.java
app/src/main/java/com/kickstarter/ui/activities/CheckoutActivity.java
app/src/main/java/com/kickstarter/ui/activities/HelpActivity.java
app/src/main/java/com/kickstarter/ui/activities/ProjectUpdatesActivity.java
app/src/main/java/com/kickstarter/ui/activities/UpdateActivity.java
app/src/main/java/com/kickstarter/ui/activities/WebViewActivity.java
app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.java
app/src/main/java/com/kickstarter/viewmodels/ProjectUpdatesViewModel.java
app/src/main/java/com/kickstarter/viewmodels/UpdateViewModel.java
app/src/test/java/com/kickstarter/services/DiscoveryParamsTest.java
app/src/test/java/com/kickstarter/services/KSUriTest.java
app/src/test/java/com/kickstarter/viewmodels/ProjectUpdatesViewModelTest.java
app/src/test/java/com/kickstarter/viewmodels/UpdateViewModelTest.java
config/KSWebViewClient.java

A few web view improvements as the last piece of implementing Update comments:
* Koala event for opening external links
* New request handler for additional update index urls in the ProjectUpdatesActivity/VM
* New request handler for additional update urls in the UpdateActivity/VM
* Refactored `back()` logic for web views
And tests and bonus view model cleanups, etc. I'll point out interesting things below via. comments.

Improve webviews for updates

---

app/src/main/java/com/kickstarter/libs/rx/operators/ApiErrorOperator.java
app/src/test/java/com/kickstarter/libs/rx/operators/ApiErrorOperatorTest.java

@mbrandonw I think I unearthed the `else` statement we were looking for (-_-｡)

Catch response.body() in else statement

---

app/src/main/java/com/kickstarter/ui/activities/CheckoutActivity.java
app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.java
app/src/main/java/com/kickstarter/ui/activities/FacebookConfirmationActivity.java
app/src/main/java/com/kickstarter/ui/activities/LoginActivity.java
app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.java
app/src/main/java/com/kickstarter/ui/activities/ProjectSocialActivity.java
app/src/main/java/com/kickstarter/ui/activities/ProjectUpdatesActivity.java
app/src/main/java/com/kickstarter/ui/activities/ResetPasswordActivity.java
app/src/main/java/com/kickstarter/ui/activities/SignupActivity.java
app/src/main/java/com/kickstarter/ui/activities/TwoFactorActivity.java
app/src/main/java/com/kickstarter/ui/activities/UpdateActivity.java
app/src/main/java/com/kickstarter/ui/activities/ViewPledgeActivity.java
app/src/main/java/com/kickstarter/ui/activities/WebViewActivity.java

I fixed missing `override` annotations which should be added at `exitTransition` method.

Fix missing override annotations

---

app/src/main/java/com/kickstarter/libs/Koala.java
app/src/main/java/com/kickstarter/libs/KoalaEvent.java
app/src/main/java/com/kickstarter/ui/activities/SearchActivity.java
app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.java
app/src/test/java/com/kickstarter/viewmodels/SearchViewModelTest.java

- Update the event names and store them in the KoalaEvent constants file
- Add event for clearing the search

Add new event names and missing (clear) event for Search Page

---

app/src/main/java/com/kickstarter/models/SurveyResponse.java
app/src/main/java/com/kickstarter/services/ApiClient.java
app/src/main/java/com/kickstarter/services/ApiClientType.java
app/src/main/java/com/kickstarter/services/ApiService.java
app/src/test/java/com/kickstarter/factories/SurveyResponseFactory.java
app/src/test/java/com/kickstarter/services/MockApiClient.java

In order to add the ability to take surveys in the android client we must first build out the api layer with the app
Add api, model and factory to prepare for surveys feature

Add survey api

---

app/src/main/java/com/kickstarter/ui/activities/SearchActivity.java
app/src/main/java/com/kickstarter/ui/adapters/SearchAdapter.java
app/src/main/java/com/kickstarter/ui/viewholders/PopularSearchTitleViewHolder.java
app/src/main/java/com/kickstarter/ui/viewholders/ProjectSearchResultViewHolder.java
app/src/main/java/com/kickstarter/viewmodels/MessageHolderViewModel.java
app/src/main/java/com/kickstarter/viewmodels/ProjectSearchResultHolderViewModel.java
app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.java
app/src/main/res/layout/featured_search_result_view.xml
app/src/main/res/layout/messages_layout.xml
app/src/main/res/layout/project_search_result_view.xml
app/src/main/res/layout/search_layout.xml
app/src/main/res/layout/search_popular_title_view.xml
app/src/main/res/layout/search_toolbar.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/styles.xml
app/src/test/java/com/kickstarter/ui/adapters/SearchAdapterTest.java
app/src/test/java/com/kickstarter/viewmodels/MessageHolderViewModelTest.java
app/src/test/java/com/kickstarter/viewmodels/ProjectSearchResultHolderViewModelTest.java
app/src/test/java/com/kickstarter/viewmodels/SearchViewModelTest.java

Follow up to #85 containing UI detail and ViewModel cleanup for external release.
Left is Android before, right is current iOS:
After:

Search UI pass

---

app/src/main/java/com/kickstarter/libs/utils/ProjectUtils.java
app/src/main/java/com/kickstarter/ui/adapters/DiscoveryAdapter.java
app/src/main/java/com/kickstarter/ui/viewholders/ProjectCardViewHolder.java
app/src/main/java/com/kickstarter/viewmodels/ProjectCardHolderViewModel.java
app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
app/src/test/java/com/kickstarter/viewmodels/ProjectCardholderViewModelTest.java

yossss first android pr.  going to add explanatory comments in the morning to explain all the new stuff.
This is just modernizing and refactoring the `ProjectCardViewHolder` and `ProjectCardHolderViewModel` and adding a bunch of tests!  No new behavior just trying to clean it up with @luoser.

Project card refactor

---

app/src/main/java/com/kickstarter/ui/activities/ViewPledgeActivity.java
app/src/main/java/com/kickstarter/viewmodels/ViewPledgeViewModel.java
app/src/main/java/com/kickstarter/viewmodels/outputs/ViewPledgeViewModelOutputs.java
app/src/main/res/layout/view_pledge_layout.xml
app/src/test/java/com/kickstarter/viewmodels/ViewPledgeViewModelTest.java

adding an Estimated Delivery Section to the view pledge screen.  More info for our pals, the users.  That's all.

View pledge updates

---

app/src/main/java/com/kickstarter/libs/utils/ProjectUtils.java
app/src/main/java/com/kickstarter/ui/viewholders/ProjectCardViewHolder.java
app/src/main/java/com/kickstarter/viewmodels/ProjectCardHolderViewModel.java
app/src/main/res/drawable/metadata_label_rounded_background.xml
app/src/main/res/drawable/progress_bar_horizontal.xml
app/src/main/res/layout-land/project_card_view.xml
app/src/main/res/layout/project_card_stats_view.xml
app/src/main/res/layout/project_card_view.xml
app/src/main/res/layout/project_metadata_view.xml
app/src/main/res/layout/project_state_view.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/test/java/com/kickstarter/viewmodels/ProjectCardholderViewModelTest.java

Updating our project card styles!  Here are some screens:
successful project:
live project:
unsuccessful project:
cc @maggieKSR lisa @luoser

Project card style updates

---

app/src/main/java/com/kickstarter/ui/activities/ActivityFeedActivity.java

Just a small one – notice this commented out code came along for the ride when merging the survey webview work.

Survey web view cleanup

---

app/src/main/AndroidManifest.xml
app/src/main/assets/json/server-config.json
app/src/main/java/com/kickstarter/libs/FeatureKey.java
app/src/main/java/com/kickstarter/libs/RefTag.java
app/src/main/java/com/kickstarter/services/ApiClient.java
app/src/main/java/com/kickstarter/services/ApiClientType.java
app/src/main/java/com/kickstarter/services/ApiService.java
app/src/main/java/com/kickstarter/services/apiresponses/ProjectsEnvelope.java
app/src/main/java/com/kickstarter/ui/activities/CreatorDashboardActivity.java
app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
app/src/main/java/com/kickstarter/ui/toolbars/DiscoveryToolbar.java
app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardViewModel.java
app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
app/src/main/java/com/kickstarter/viewmodels/outputs/DiscoveryViewModelOutputs.java
app/src/main/res/drawable-v21/button_white_border_gray_500.xml
app/src/main/res/drawable/button_white_border_gray_500.xml
app/src/main/res/layout/creator_dashboard_layout.xml
app/src/main/res/layout/creator_dashboard_toolbar.xml
app/src/main/res/layout/discovery_toolbar.xml
app/src/main/res/layout/project_state_view.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings_i18n.xml
app/src/main/res/values/styles.xml
app/src/test/java/com/kickstarter/factories/ProjectsEnvelopeFactory.java
app/src/test/java/com/kickstarter/services/MockApiClient.java
app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardViewModelTest.java
app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java

intial screen for a creator view.  right now has very basic data that looks like this:
that's all!

Creator tools v0

---

app/src/main/res/layout/creator_dashboard_layout.xml

small changes to https://github.com/kickstarter/android-oss/pull/115 because I didn't add the string to the server first but also we don't need it.  also paddingLeft is old and busted.
👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋  @luoser

Update string, use paddingstart vs paddingleft

---

app/src/internal/java/com/kickstarter/ui/views/DebugPushNotificationsView.java
app/src/internal/res/layout/debug_push_notifications_layout.xml
app/src/main/java/com/kickstarter/libs/KoalaContext.kt
app/src/main/java/com/kickstarter/libs/PushNotifications.java
app/src/main/java/com/kickstarter/models/pushdata/Activity.java
app/src/main/java/com/kickstarter/services/ApiClient.java
app/src/main/java/com/kickstarter/services/ApiClientType.java
app/src/main/java/com/kickstarter/services/apiresponses/PushNotificationEnvelope.java
app/src/main/java/com/kickstarter/services/gcm/MessageService.java
app/src/main/res/values/strings.xml
app/src/test/java/com/kickstarter/services/MockApiClient.java
app/src/test/java/com/kickstarter/viewmodels/MessagesViewModelTest.java

Woohoo push notifications for messages. Tapping on the notification opens the message thread.
I'd like to do some more IRL device testing (I think my notifications are getting batched right now)...but some review on the general gist of this would be great, since I just followed along with our other push infra to do this 😁

[Messages] Push notifications

---

app/src/main/java/com/kickstarter/ui/activities/ProfileActivity.java
app/src/main/java/com/kickstarter/viewmodels/ProfileViewModel.java
app/src/test/java/com/kickstarter/viewmodels/ProfileViewModelTest.java

For all our future builds, this button will no longer be hidden.
🕵️‍♀️

Remove message button feature flag

---

app/src/internal/java/com/kickstarter/ui/views/DebugPushNotificationsView.java
app/src/internal/res/layout/debug_push_notifications_layout.xml
app/src/main/java/com/kickstarter/libs/PushNotifications.java
app/src/main/java/com/kickstarter/models/SurveyResponse.java
app/src/main/java/com/kickstarter/services/ApiClient.java
app/src/main/java/com/kickstarter/services/ApiClientType.java
app/src/main/java/com/kickstarter/services/ApiService.java
app/src/main/java/com/kickstarter/services/apiresponses/PushNotificationEnvelope.java
app/src/main/java/com/kickstarter/services/gcm/MessageService.java
app/src/main/res/values/strings.xml
app/src/test/java/com/kickstarter/services/MockApiClient.java

Enabling survey push. Once [this is merged in the main repo] I can QA, confirm, then merge this. Remaining #todo before surveys release is to remove the feature flag.

Add Survey push notification logic

---

app/src/main/res/layout/message_reply_layout.xml

Sets the text input type to capitalize first letters of sentences in the message reply layout re: feedback from a creator, and general text body UX!

Set message reply input type

---

Makefile
app/src/main/java/com/kickstarter/services/ApiClient.java
app/src/main/java/com/kickstarter/services/ApiClientType.java
app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.java
app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.java
app/src/main/res/drawable/ic_action_icon_heart.xml
app/src/main/res/layout/project_toolbar.xml
app/src/main/res/values/styles.xml
app/src/test/java/com/kickstarter/services/MockApiClient.java
app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.java

:star: -> :heart: for saving projects.
Now using vector drawables.
Updated tests!
We recently moved from :star: to :heart: to represent saving a project.

heart icon for saving projects

---

app/src/main/java/com/kickstarter/ui/viewholders/ProjectCardViewHolder.java
app/src/main/java/com/kickstarter/viewmodels/ProjectCardHolderViewModel.java
app/src/main/res/layout/project_metadata_view.xml
app/src/test/java/com/kickstarter/viewmodels/ProjectCardholderViewModelTest.java

Removing remaining instances of star icon / terminology since we updated the project star to heart in #163. Aligns with iOS.

Remove heart from POTD, update star to heart on metadata

---

app/src/internal/java/com/kickstarter/libs/InternalTools.java
app/src/main/java/com/kickstarter/ApplicationGraph.java
app/src/main/java/com/kickstarter/ApplicationModule.java
app/src/main/java/com/kickstarter/libs/Environment.java
app/src/main/java/com/kickstarter/services/gcm/RegisterService.java
app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
app/src/main/java/com/kickstarter/ui/activities/HelpActivity.java
app/src/main/java/com/kickstarter/ui/toolbars/DiscoveryToolbar.java
app/src/main/java/com/kickstarter/ui/toolbars/KSToolbar.java

Went through some android / architecture stuff w/ dear @christopherwright, was inspired by the eaze of simplifying our dependency graph, had some fidget time on the airplane so here is a PR cleaning our dependency injections via:
* Adding `environment()` to base UI classes when possible, so that components such as `Toolbar`s have access to an `environment` much like an activity or view holder
* Adding once-injected elements (e.g. `WebClient`) to our Environment and making sure there's a `@Provides` in our `ApplicationModule`
* Removing unused injections from `ApplicationGraph` for clarity and a Cleaner Codebase™

Minimize dependency injections

---

app/src/main/java/com/kickstarter/libs/RefTag.java
app/src/main/java/com/kickstarter/libs/utils/ProjectUtils.java
app/src/main/java/com/kickstarter/libs/utils/RefTagUtils.java
app/src/main/java/com/kickstarter/models/Project.java
app/src/main/java/com/kickstarter/services/DiscoveryParams.java
app/src/main/java/com/kickstarter/ui/viewholders/ProjectCardViewHolder.java
app/src/main/java/com/kickstarter/ui/viewholders/ProjectViewHolder.java
app/src/main/java/com/kickstarter/viewmodels/ProjectCardHolderViewModel.java
app/src/main/res/layout/project_metadata_view.xml
app/src/test/java/com/kickstarter/factories/ProjectFactory.java
app/src/test/java/com/kickstarter/libs/utils/DiscoveryParamsUtilsTest.java
app/src/test/java/com/kickstarter/libs/utils/ProjectUtilsTest.java
app/src/test/java/com/kickstarter/viewmodels/ProjectCardHolderViewModelTest.java

we no longer have a POTD (project of the day) for all projects so farewell!
all references have been removed

Remove references to POTD

---

app/src/main/java/com/kickstarter/ui/activities/ProjectSocialActivity.java
app/src/main/java/com/kickstarter/viewmodels/ProjectSocialViewModel.java
app/src/main/java/com/kickstarter/viewmodels/outputs/ProjectSocialViewModelOutputs.java

This is a PR for modernizing ProjectSocialViewModel according to your latest VM architecture doc.

Modernize ProjectSocial ViewModel

---

app/src/main/java/com/kickstarter/KSApplication.java

just copyin this jazz over to android for the most part: https://github.com/kickstarter/ios-oss/pull/82/files
minus the test cases but I don't see anywhere that we have that in android for environment things? correct if I'm wrong though pls.
https://trello.com/c/5i1ntLPO/26-distinctids-shouldnt-reset-on-rails-event-in-android

Unique id tracking

---

app/src/main/java/com/kickstarter/viewmodels/ProjectHolderViewModel.java
app/src/test/java/com/kickstarter/viewmodels/ProjectHolderViewModelTest.java

@luoser and i paried on fixing crash where users with no friends backing on project screen blew up and added a test!

project friends avatar crash

---

app/src/main/java/com/kickstarter/libs/Koala.java
app/src/main/java/com/kickstarter/libs/KoalaEvent.java
app/src/main/java/com/kickstarter/ui/activities/FacebookConfirmationActivity.java
app/src/main/java/com/kickstarter/viewmodels/FacebookConfirmationViewModel.java
app/src/main/java/com/kickstarter/viewmodels/errors/FacebookConfirmationViewModelErrors.java
app/src/main/java/com/kickstarter/viewmodels/inputs/FacebookConfirmationViewModelInputs.java
app/src/main/java/com/kickstarter/viewmodels/outputs/FacebookConfirmationViewModelOutputs.java
app/src/test/java/com/kickstarter/services/MockApiClient.java
app/src/test/java/com/kickstarter/viewmodels/FacebookConfimationViewModelTest.java

Modernizing the `FacebookConfirmationViewModel` i.e. using interfaces, removing I/O class files, consolidating `Errors` with `Outputs`, etc.

[Modernize] Facebook confirmation

---

app/src/main/java/com/kickstarter/libs/utils/Secrets.java.example
app/src/main/java/com/kickstarter/ui/activities/HelpActivity.java

Using production endpoint from Secrets for displaying help links.
cc @lovehandle

settings help bug

---

app/src/main/java/com/kickstarter/libs/utils/ToolbarUtils.kt
app/src/main/java/com/kickstarter/ui/activities/CreatorDashboardActivity.java
app/src/main/res/layout/creator_dashboard_toolbar.xml

Fixing the back button and adding toolbar animation when scrolling.

Creator tools toolbar

---

app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java

Requesting a new config when a user logs in/out because we show the dashboard icon based on the config.
Thank you @justinswart for all your help!

creator tools icon bug

---

app/src/main/java/com/kickstarter/libs/FeatureKey.java
app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java

WE'RE ABOUT TO RELEASE CREATOR TOOLS!!!

Deleting creator tools feature key and updating tests.

---

app/src/main/java/com/kickstarter/libs/PushNotifications.java
app/src/main/java/com/kickstarter/libs/RefTag.java

Tracking project opens from push notifications.
Adding a ref tag to the intent.

Adding "push" ref tag for push notifications

---

app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java

Home sort is now Magic sort.
For fun.

home to magic 🎩

---

app/src/main/java/com/kickstarter/libs/utils/Secrets.java.example

Created Privacy Secret example

---

app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.java
app/src/main/res/layout/settings_layout.xml

Displaying version name in settings.
Making log out a list item.
Adding Privacy header.
cc @dannyalright

Settings UI updates

---

app/src/main/java/com/kickstarter/ui/activities/FacebookConfirmationActivity.java
app/src/main/res/layout/facebook_confirmation_layout.xml

Updated copy on Facebook Confirmation screen.
|￣￣￣￣￣￣|
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;G&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;D&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;P&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;R&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
| ＿＿＿＿＿__| 
(\ _ /)  || 
(•ㅅ•) || 
/ 　 づ

Updated copy on Facebook Confirmation screen

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
app/src/main/java/com/kickstarter/ui/activities/SettingsNewActivity.kt
app/src/main/java/com/kickstarter/viewmodels/SettingsNewViewModel.kt
app/src/main/res/layout/settings_layout_new.xml
build.gradle

- setup SettingsViewModel and SettingsActivity with a different MVVM pattern
- In the process of updating our current settings to our new version.

[Enhancement] - Updated Settings skeleton

---

app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
app/src/main/java/com/kickstarter/ui/activities/SettingsNewActivity.kt
app/src/main/java/com/kickstarter/ui/toolbars/KSToolbar.java
app/src/main/res/layout/settings_layout_new.xml

We have new Settings but they're not ready for release.
Users still need functional settings.

Showing new settings on debug builds and old settings on release builds.

---

Makefile

- Fixed Makefile script error.

fixed makefile script

---

app/src/main/res/layout/settings_layout_new.xml

Small design tweak per this comment: https://github.com/kickstarter/android-oss/pull/286#discussion_r207968029

Small margin update per Danny

---

app/src/main/java/com/kickstarter/extensions/ActivityExt.kt
app/src/main/java/com/kickstarter/libs/utils/TransitionUtils.java
app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.kt
app/src/main/res/anim-v21/settings_bottom_slide.xml
app/src/main/res/anim/settings_bottom_slide.xml

- added bottom slide up animation for settings
- Added extension function for the animation.
- Recommended by @dannyalright plus it looks better.

added bottom slide up animation for settings

---

app/src/main/java/com/kickstarter/viewmodels/NewsletterViewModel.kt

- Fixed the random crash with logging out of the app.

[Bug Fix] - Logout crash fix

---

lib/milkrun/i18n_string_resources.rb

https://github.com/jekyll/jekyll/issues/613#issuecomment-7509149 to make the alpha build pass 🙏🏾

Fixing cgi import

---

fastlane/README.md
fastlane/report.xml
lib/milkrun/slack_webhook_extractor.rb

The slack properties live in /app and not /config.

Updating SlackWebhookExtractor

---

app/src/main/java/com/kickstarter/ui/toolbars/KSToolbar.java

Making the toolbar the accent color so you know you're not hitting production.
Sometimes you don't know you're not hitting production 👀

ENHANCE ❗️Visual Indication when you're not hitting prod

---

app/src/main/java/com/kickstarter/ui/activities/AccountActivity.kt
app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.kt
app/src/main/res/layout/activity_account.xml
app/src/main/res/layout/settings_layout.xml

I thought I'd get away with just making them not visible but we need to see them since we're starting v3 work.

😅 Only showing edit profile and payment methods on debug builds.

---

app/src/main/graphql/schema.json

Updated the schema and ran it locally to make sure it still builds 🚀

Updating the schema 2k18

---

app/src/main/java/com/kickstarter/libs/BaseActivity.java

- Registering the receiver in onResume

added register receiver to onResume

---

app/src/main/java/com/kickstarter/ui/activities/AccountActivity.kt

- Fixed the error icon logic in Account Activity

fixed icon error showing in account

---

app/build.gradle

Nothing broke in the build, I'm suspicious.

[🚀] Updating Apollo from 0.5.0 to 1.0.0-alpha3.

---

app/build.gradle
app/src/main/java/com/kickstarter/ui/activities/VideoActivity.java
app/src/main/res/values-v21/styles.xml

Merging master in settings v3

---

app/src/main/java/com/kickstarter/models/User.java
app/src/main/java/com/kickstarter/services/ApiClient.java
app/src/main/java/com/kickstarter/services/apirequests/SettingsBody.java
app/src/main/java/com/kickstarter/ui/activities/NewsletterActivity.kt
app/src/main/java/com/kickstarter/ui/data/Newsletter.java
app/src/main/java/com/kickstarter/viewmodels/NewsletterViewModel.kt
app/src/main/res/layout/activity_newsletter.xml
app/src/test/java/com/kickstarter/viewmodels/NewsletterViewModelTest.kt
fastlane/report.xml

- added the `Music newsletter` to the existing Newsletter screen.
[Add Music Newsletter to our settings](https://trello.com/c/0p1zVWlB/1095-add-music-newsletter-to-our-settings#)

[Enhancement] - Add Music Newsletter to our Settings

---

Makefile
NOTICE
app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/kickstarter/ApplicationGraph.java
app/src/main/java/com/kickstarter/ApplicationModule.java
app/src/main/java/com/kickstarter/libs/Koala.java
app/src/main/java/com/kickstarter/libs/KoalaTrackingClient.java
app/src/main/java/com/kickstarter/libs/TrackingClientType.java
app/src/main/java/com/kickstarter/libs/qualifiers/KoalaEndpoint.kt
app/src/main/java/com/kickstarter/libs/qualifiers/KoalaRetrofit.kt
app/src/main/java/com/kickstarter/libs/utils/BooleanUtils.java
app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
app/src/main/java/com/kickstarter/libs/utils/ProjectUtils.java
app/src/main/java/com/kickstarter/services/KoalaBackgroundService.kt
app/src/main/java/com/kickstarter/services/KoalaService.kt
app/src/main/java/com/kickstarter/services/firebase/Dispatcher.kt
app/src/main/java/com/kickstarter/ui/IntentKey.java
app/src/test/java/com/kickstarter/KSRobolectricTestCase.java
app/src/test/java/com/kickstarter/libs/KoalaTest.kt
app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
app/src/test/java/com/kickstarter/libs/utils/BooleanUtilsTest.java
config/koala_endpoint.xml.example
gradle/wrapper/gradle-wrapper.properties

Merging mixpanel deletion changes into codebase !_!

Master into v3

---

app/src/main/java/com/kickstarter/libs/utils/UriUtils.kt
app/src/main/java/com/kickstarter/services/KSUri.java

We started getting this very FRUSTRATING crash in the webviews because a URI is null. 
I made some UriUtils so that `getHost`, `getLastPathSegment` and `getPath` never return null.
https://fabric.io/kickstarter2/android/apps/com.kickstarter.kickstarter/issues/5ba280abf8b88c29637da4ba?time=1536364800000%3A1544227199999

[bug fix] KSUri crashes because WEBVIEWs

---

app/src/main/res/layout/two_factor_form_view.xml

The buttons on the 2FA screen looked jank. It's been bothering me for a while.

Fixing button height in 2FA screen.

---

app/build.gradle
app/lint.xml
app/src/main/java/com/kickstarter/KSApplication.java
app/src/main/java/com/kickstarter/libs/utils/Secrets.java.example
build.gradle

[WIP] Heap integration for internal debug builds

---

app/build.gradle

- Updated ConstraintLayout gradle version to `1.1.2`
[External Library Sweep](https://trello.com/c/c8nq6Sin/1147-external-library-sweep)

[Tech Debt] - Updated ConstraintLayout gradle version

---

Gemfile.lock

- Updated Gemlock file with latest Fastlane version

Updated Fastlane version

---

README.md

Update README year

---

app/build.gradle
app/lint.xml
app/src/main/java/com/kickstarter/KSApplication.java
build.gradle
fastlane/report.xml

- Removing Heap to see if it's causing the warnings in the Google play store about READ and WRITE permissions.

removed Heap from the application

---

app/src/main/graphql/schema.json

Updating graphql schema.

---

app/build.gradle

Stripe 8.1.0 -> 8.3.0

---

app/src/main/java/com/kickstarter/libs/utils/Secrets.java.example

Removing heap from secrets example

---

app/src/main/res/layout/discovery_layout.xml

320dp -> 304dp
[Trello](https://trello.com/c/oPMLypl6/721-improve-navigation-and-filtering-on-android-app)

Drawer width

---

app/src/main/java/com/kickstarter/ui/fragments/NewCardFragment.kt

- With the help of @eoji she pointed out that we need to `filter` out if the activity is null that way the `progress_bar` isn't trying to set the visibility to gone on a null view.
- Go to Payment Methods -> Add New Card then proceed to add cards.

[Bug] Add New Card Fragment Bug

---

app/src/main/AndroidManifest.xml

Branched off of #489 
Removing parent activity metadata for Android 4.0 and cleaning up manifest.
[Trello](https://trello.com/c/Qe9DtFbn/1234-remove-parent-activity-meta-data-from-manifest)

Removing parent activity metadata for Android 4.0

---

app/src/main/graphql/schema.json

- Updated `GraphQl` schema so that we can support Union Pay.

updated the schema from kickstarter master

---

app/src/main/java/com/kickstarter/viewmodels/ChangeEmailViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/ChangeEmailViewModelTest.kt

Fixes crash when opening change email screen and server can't be reached. With tests.
Turn on airplane mode and open the Change Email screen.

🐛change email crash

---

app/src/main/java/com/kickstarter/ui/activities/PaymentMethodsSettingsActivity.kt

Addressing feedback from @Scollaco to rename this method for clarity.

method rename

---

app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
app/src/main/res/drawable/ic_menu.xml
app/src/main/res/drawable/ic_menu_indicator.xml
app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java

Showing an indicator on the menu icon when a user has unread messages.
1. Verify the unadorned menu icon is shown when logged out.
2. Verify the unadorned menu icon is shown when logged in and there are no unread messages.
3. Verify the adorned menu icon is shown and animates when logged in and there are unread messages.
[Trello Story](https://trello.com/c/XxDhitMZ/1378-hamburger-animaton-when-new-activity-messages)

🍔✨ Hamburger animation

---

app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt

- Added logic to update pledge amount when Stepper changes value.
[Modifying Pledge amount updates Total](https://trello.com/c/SattkbTC/1375-modifying-pledge-amount-updates-total)

Added logic to update pledge total amount when stepper changes value

---

app/src/main/java/com/kickstarter/ui/viewholders/ProjectViewHolder.java
app/src/main/res/layout-land/project_media_header.xml
app/src/main/res/layout/project_main_layout.xml
app/src/main/res/values/dimens.xml

Slightly restyled the _Created by_ area on the Project layout to remove UI awkwardness and improve usability.
| --- | --- |
| ![portrait-before](https://user-images.githubusercontent.com/3104761/60216111-30270e80-9837-11e9-91f4-76c2ff6f4320.png) | ![portrait](https://user-images.githubusercontent.com/3104761/60215703-2fda4380-9836-11e9-81d7-82fb13d3c28d.png) |
| ![landscape-after](https://user-images.githubusercontent.com/3104761/60216134-3f0dc100-9837-11e9-921c-6c6c028391e3.png)| ![landscape-details](https://user-images.githubusercontent.com/3104761/60215685-251fae80-9836-11e9-92be-bc301feb46e8.png) |

Improve creator callout

---

app/src/main/java/com/kickstarter/services/KSUri.java
app/src/test/java/com/kickstarter/services/KSUriTest.java

See https://github.com/kickstarter/native-secrets/pull/51 for a description about this change.

Add necessary request headers (via interceptor) to GraphQL requests.

---

app/src/main/java/com/kickstarter/libs/models/Country.kt
app/src/test/java/com/kickstarter/models/CountryTest.kt

Adds proper currency symbol for HK projects and tests for all countries.
HK had the wrong currency symbol and there were no tests.
| --- | --- |
| ![screenshot-2019-07-01_121642](https://user-images.githubusercontent.com/1289295/60451614-75ae5780-9bfa-11e9-93d8-7a3b48d26e50.png) | ![screenshot-2019-07-01_121725](https://user-images.githubusercontent.com/1289295/60451505-341dac80-9bfa-11e9-89df-4af87687d3af.png) |
Look at a HK based project.
[Trello Story](https://trello.com/c/bKywyXrp/1441-hk-bug)

🇭🇰🐞 HK bug

---

app/src/main/java/com/kickstarter/ui/viewholders/NativeCheckoutRewardViewHolder.kt
app/src/main/java/com/kickstarter/viewmodels/NativeCheckoutRewardViewHolderViewModel.kt
app/src/main/res/layout/item_reward.xml
app/src/test/java/com/kickstarter/viewmodels/NativeCheckoutRewardViewHolderViewModelTest.kt

When no reward is backed, title is thanks copy and description is hidden. When no reward is not backed, it shows normal no reward copy.
| No reward backed 🐛 | No reward not backed 🦋 |
| --- | --- |
| ![screenshot-2019-07-01_130418](https://user-images.githubusercontent.com/1289295/60454036-ccb72b00-9c00-11e9-8910-d4e278038c85.png) | ![screenshot-2019-07-01_130432](https://user-images.githubusercontent.com/1289295/60454054-d5a7fc80-9c00-11e9-8443-f2692d197d76.png) |
1. View a live backed project where you pledged no reward.
2. View a live backed project where you pledged an actual reward.
[Trello Story](https://trello.com/c/KHD7VV70/1433-reward-states-manage-your-pledge-backer-live-project)

Manage your pledge for no reward

---

app/src/main/java/com/kickstarter/libs/utils/RewardDecoration.kt
app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
app/src/main/java/com/kickstarter/viewmodels/RewardFragmentViewModel.kt
app/src/main/res/layout/fragment_rewards.xml
app/src/test/java/com/kickstarter/viewmodels/RewardFragmentViewModelTest.kt

Adding scrollbar and rewards count as footer in rewards screen.
The circle don't scale.
- Removed circles from `RewardDecoration`.
- Added horizontal scrollbar to rewards.
- Added divider line between new footer and rewards list.
- `RewardFragmentViewModel` now emits `rewardsCount` output.
- Tests.
| --- | --- |
| ![screenshot-2019-08-16_141254](https://user-images.githubusercontent.com/1289295/63188696-11bbe300-c030-11e9-8c09-53d295c21307.png) | ![screenshot-2019-08-16_141339](https://user-images.githubusercontent.com/1289295/63188697-11bbe300-c030-11e9-87be-77a01662c031.png) |
Open the pledge sheet and verify that the count of the rewards matches the footer.
Soon come

[👣] Rewards footer

---

app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt

Handling null expiration dates in backing payment source.
So the app doesn't crash!
If the expiration is `null`, just return an empty string.
The story is...Staging played me.

Handling payment source null values

---

build.gradle

Firebase is missing from sonatype so my build is failing CI.
It doesn't seem like we need these and they're causing more issues by keeping em.
␡
https://circleci.com/gh/kickstarter/android-oss/tree/fix-gradle
N/A
N/A

[🚧] Removing some repos from gradle to fix the build in CI

---

app/src/main/res/layout/fragment_pledge.xml
app/src/main/res/values/styles.xml

Updating our button styles!
So we can stop shouting at users.
Changed our default button style.
```
<item name="android:textAllCaps">false</item>
<item name="cornerRadius">@dimen/grid_2</item>
```
| After 🦋 | Before 🐛 | 
| --- | --- |
| ![screenshot-2019-09-09_165104](https://user-images.githubusercontent.com/1289295/64565710-5e8a9500-d322-11e9-9873-77a26fce29dd.png) | ![screenshot-2019-09-09_165232](https://user-images.githubusercontent.com/1289295/64565715-62b6b280-d322-11e9-8a3a-698963bd5d39.png) |
Open the app
[NT-283]
[NT-283]: https://dripsprint.atlassian.net/browse/NT-283

[✨] NT-283 Button style update

---

app/src/main/java/com/kickstarter/libs/RefTag.java
app/src/main/java/com/kickstarter/ui/viewholders/ThanksShareViewHolder.java
app/src/main/java/com/kickstarter/viewmodels/ThanksShareHolderViewModel.java
app/src/test/java/com/kickstarter/viewmodels/ThanksShareHolderViewModelTest.java

Adding a ref tag when sharing a project via Facebook, Twitter, or another app.
So we know if users navigated to the project page via a link shared from the Android app!
- Added `RefTag.thanksShare` which has a value of `android_thanks_share`.
- Added `RefTag.thanksFacebookShare` which has a value of `android_thanks_facebook_share`.
- Added `RefTag.thanksTwitterShare` which has a value of `android_thanks_twitter_share`.
- The `startShare` output in `ThanksShareHolderViewModel` is now a `Pair<String, String>` representing the project's name and the share URL instead of just the project so we can properly test that the tag is set.
- The `startShareOnFacebook` output in `ThanksShareHolderViewModel` is now a `Pair<Project, String>` representing the project (because we need more than the name) …

[🔗] NT-339 Adding ref tag when sharing projects from the Thanks page

---

app/src/internal/java/com/kickstarter/ui/activities/FeatureFlagsActivity.kt
app/src/internal/java/com/kickstarter/ui/viewholders/FeatureFlagViewHolder.kt

I moved the feature flag work to the internal variant in #643 so it broke the synthetic bindings. And it passed because (like I mentioned in the PR 😛 we run our tests on release builds)

fixing internal tools imports

---

app/src/main/graphql/checkout.graphql
app/src/main/graphql/schema.json
app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
app/src/main/java/com/kickstarter/services/ApolloClientType.kt
app/src/main/java/com/kickstarter/services/KSApolloClient.kt
app/src/main/java/com/kickstarter/services/mutations/UpdateBacking.kt
app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt

Handling new `updateBacking` mutation.
-stares into camera-
- Updated schema and `UpdateBacking` mutation.
- Moved `UpdateBacking` data class to its own class in the `mutations` package.
It looks the same
Update a pledge
[NT-380]
[NT-380]: https://dripsprint.atlassian.net/browse/NT-380

[💳] NT-380 Synchronous updateBacking

---

app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt

Missed some tests in #656 
Twas a large PR and we missed it!
- Added tests for `updateFragments` output in `ProjectViewModel`.
Nothing to see, just tests!
Circle CI is my QA
[NT-344]
[NT-344]: https://dripsprint.atlassian.net/browse/NT-344

[✅] NT-344 Adds missing tests in ProjectViewModel

---

README.md

| --- | --- |
| ![image](https://user-images.githubusercontent.com/1289295/72104859-50fa1180-32fa-11ea-8afd-28e674b30470.png) | ![image](https://user-images.githubusercontent.com/1289295/72104873-57888900-32fa-11ea-8943-ddaa630623ff.png) |

[🎉] Updating the readme for 2k20

---

app/src/main/java/com/kickstarter/libs/utils/ApplicationLifecycleUtil.java
app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java

Removing placeholder Lake Events.
I'm getting ready to add the Real Events™ 
🙈 
Prep to start [NT-654]
[NT-654]: https://kickstarter.atlassian.net/browse/NT-654

[␡] Removing sample Lake events

---

app/src/main/res/layout/qualtrics_prompt.xml
app/src/main/res/values/strings.xml

Updating Qualtrics survey prompt copy
Copy was updated
- `Answer_a_few_quick_questions_to_help_us_build_a_better_Kickstarter` is now `Take_our_survey_to_help_us_make_a_better_app_for_you`
| After 🦋 | Before 🐛 | 
| --- | --- |
| ![screenshot-2020-01-23_144643](https://user-images.githubusercontent.com/1289295/73018550-dcda6600-3def-11ea-9e51-aff60d790f26.png) | ![screenshot-2020-01-21_181227](https://user-images.githubusercontent.com/1289295/73018551-dcda6600-3def-11ea-8e6e-41305f1a8bc8.png) |
Open the app twice (If you have dismissed the survey 3 times, you need to clear the app's data!)
[NT-824]
[NT-824]: https://kickstarter.atlassian.net/browse/NT-824

[📝] NT-824 Updating Qualtrics survey prompt copy

---

app/src/test/java/com/kickstarter/viewmodels/NewCardFragmentViewModelTest.kt

Fixing `NewCardFragmentViewModelTest` validation tests.
So the tests pass.
Added `futureYear` that always returns a year in the future so the expiration date is valid.
Testz only
CircleCI 🙏 
N/A

[✅] Fixing add new cards tests

---

app/src/main/java/com/kickstarter/libs/models/OptimizelyExperiment.kt

^
We're doing experiments.
Added `OptimizelyExperiment.Key.CAMPAIGN_DETAILS` with value `native_project_page_campaign_details`
Nothing 2 c
Nothing 2 QA
[NT-884]
[NT-884]: https://kickstarter.atlassian.net/browse/NT-884

[🔑] NT-884 Adding campaign details experiment key

---

app/src/main/java/com/kickstarter/ApplicationModule.java

Adding datafile and event dispatch intervals to Optimizely.
So we get the latest data file and events dispatched every 10 minutes.
Added datafile and event dispatch intervals to Optimizely client with a value of 10 minutes per example: https://docs.developers.optimizely.com/full-stack/docs/initialize-sdk-android#section-example
Nothing 2 c
Change your variant and wait...10 minutes.
[NT-890]
[NT-890]: https://kickstarter.atlassian.net/browse/NT-890

[⏳] NT-890 Syncing Optimizely every 10 minutes

---

app/src/main/java/com/kickstarter/libs/Koala.java
app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java

Lil Koala refactor, my next mix tape.
We're about to hit the 800 line limit in `Koala.java` so I cleaned it up.
- Added helper method `KoalaUtils.refTagProperties` for setting the `"session_ref_tag"` and `"session_referrer_credit"` properties.
- Removed all unused methods in `Koala.java`
- `trackFacebookLoginSuccess`
- `trackCheckoutNext `
- `trackCheckoutCancel `
- `trackCheckoutLoadFailed `
- `trackCheckoutCancelShareSheet `
- `trackCheckoutShareFinished `
- `trackCancelProjectShareSheet `
- `trackShowProjectFacebookShareView `
- `trackShowProjectTwitterShareView `
- `trackProjectFacebookShare `
- `trackProjectTwitterShare`
The tests are passing™. 
[NT-926]
[NT-926]: https://kickstarter.atlassian.net/browse/NT-926

[🧽🐨] NT-926 Koala clean up

---

app/src/main/java/com/kickstarter/libs/Koala.java
app/src/main/java/com/kickstarter/libs/LakeEvent.kt
app/src/main/java/com/kickstarter/viewmodels/LoginToutViewModel.java
app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.java

Adding `Log In Button Clicked` event.
- Added `LakeEvent.LOG_IN_BUTTON_CLICKED` with value `"Log In Button Clicked"`
- Added `Koala.trackLogInButtonClicked` to track when a user clicks on the log in button in the `LoginToutActivity`.
- Tracking `LOG_IN_BUTTON_CLICKED` in `LoginToutViewModel`
- Added test in `LoginToutViewModelTest`
[NT-920]
[NT-920]: https://kickstarter.atlassian.net/browse/NT-920

[🛤] NT-920 Log In Button Clicked event

---

app/src/main/java/com/kickstarter/libs/Koala.java
app/src/main/java/com/kickstarter/libs/LakeEvent.kt
app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/LoginViewModelTest.kt

Adding `Log In Submit Button Clicked` event.
- Added `LakeEvent.LOG_IN_SUBMIT_BUTTON_CLICKED` with value `"Log In Submit Button Clicked"`
- Added `Koala.trackLogInSubmitButtonClicked` to track when a user clicks the log in button in the `LoginActivity`
- Tracking `LOG_IN_SUBMIT_BUTTON_CLICKED` in `LoginViewModel` when user clicks the log in button
- Added test in `LoginViewModelTest`
[NT-922]
[NT-922]: https://kickstarter.atlassian.net/browse/NT-922

[🛤] NT-922 Log In Submit Button Clicked event

---

app/src/main/java/com/kickstarter/libs/Koala.java
app/src/main/java/com/kickstarter/libs/LakeEvent.kt
app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
app/src/main/java/com/kickstarter/viewmodels/LoginToutViewModel.java
app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/ResetPasswordViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/SignupViewModel.java
app/src/main/java/com/kickstarter/viewmodels/TwoFactorViewModel.java
app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.java
app/src/test/java/com/kickstarter/viewmodels/LoginViewModelTest.kt
app/src/test/java/com/kickstarter/viewmodels/ResetPasswordViewModelTest.kt
app/src/test/java/com/kickstarter/viewmodels/SignupViewModelTest.java
app/src/test/java/com/kickstarter/viewmodels/TwoFactorViewModelTest.java

Log in/sign up events.
We have new Log in/sign up events.
[🛤] NT-917 Log In or Signup Button Clicked event (#760)
[🛤] NT-918 Log In or Sign Up Page Viewed events (#761)
[🛤] NT-919 Facebook Log In or Signup Button Clicked event (#762)
[🛤] NT-920 Log In Button Clicked event (#763)
[🛤] NT-921 Sign Up Button Clicked event (#764)
[🛤] NT-922 Log In Submit Button Clicked event (#765)
[🛤] NT-923 Sign Up Submit Button Clicked event (#766)
[🛤] NT-924 Forgot Password Page Viewed event (#767)
[🛤] NT-925 Two-Factor Confirmation Viewed event (#768) 
No visuals!
[NT-656]
[NT-656]: https://kickstarter.atlassian.net/browse/NT-656

[🛤] NT-656 Login signup events

---

app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
app/src/main/res/layout/fragment_pledge.xml
app/src/main/res/layout/fragment_pledge_section_footer.xml
app/src/main/res/layout/fragment_pledge_section_total.xml

Add Pledge screen footer
We're redesigning the pledge screen.
- Added `fragment_pledge_section_footer` to bottom of `fragment_pledge`
- Removed `pledge_agreement` from `pledge_footer_pledge_total`
| After 🦋| After w/ different currency 🦋 | Before 🐛 |
| ![screenshot-2020-04-02_122719](https://user-images.githubusercontent.com/1289295/78274519-5a9cab00-74de-11ea-97a6-ff0240db3e5a.png) | ![screenshot-2020-04-02_122732](https://user-images.githubusercontent.com/1289295/78274521-5b354180-74de-11ea-946f-7d5af5dde56a.png) | ![screenshot-2020-04-02_123445](https://user-images.githubusercontent.com/1289295/78274522-5b354180-74de-11ea-9407-d84190618d50.png) |
This ticket is UI only
[NT-1104]
[NT-1104]: https://kickstarter.atlassian.net/browse/NT-1104

[🦶🏾] NT-1104 Add Pledge screen footer

---

app/src/main/res/layout/item_reward_placeholder_card.xml
app/src/main/res/layout/loading_placeholder_body.xml
app/src/main/res/layout/loading_placeholder_caption_2.xml

Loading state for payment methods.
The app wants to look good
Properly styling payment method loading state.
- Added `loading_placeholder_body.xml` for `Body` copy placeholders
- Added `loading_placeholder_caption_2.xml` for `Caption2` copy placeholders
| Still | GIF |
| --- | --- |
| <img src=https://user-images.githubusercontent.com/1289295/78815640-86b4a200-799e-11ea-80a7-31561838b60e.png width=330/> | ![device-2020-04-08-133550 2020-04-08 13_36_52](https://user-images.githubusercontent.com/1289295/78815638-861c0b80-799e-11ea-9d39-664bea691ca7.gif) |
L00k
[NT-1124]
[NT-1124]: https://kickstarter.atlassian.net/browse/NT-1124

[⏳] NT-1124 Loading state for payment methods

---

app/src/main/res/drawable/circle_accent_alpha_20.xml
app/src/main/res/drawable/ic_add_rounded.xml
app/src/main/res/layout/item_add_card.xml
app/src/main/res/values-de/strings_i18n.xml
app/src/main/res/values-es/strings_i18n.xml
app/src/main/res/values-fr/strings_i18n.xml
app/src/main/res/values-ja/strings_i18n.xml
app/src/main/res/values/strings_i18n.xml

New card CTA
🆕 copy
- Added `New_payment_method` string and set it as the text in `ic_add_card.xml`
- Added `circle_accent_alpha_20.xml` `Drawable`
- Added cute `ic_add_rounded.xml` `Drawable`
| After 🦋 | a11y | Before 🐛 |
| --- | --- |--- |
| ![screenshot-2020-04-08_164832](https://user-images.githubusercontent.com/1289295/78832693-b02ef700-79b9-11ea-9c21-63f2dfc1e048.png) |![screenshot-2020-04-08_165150](https://user-images.githubusercontent.com/1289295/78832697-b0c78d80-79b9-11ea-8eeb-0224dadec349.png) | ![screenshot-2020-04-08_135848](https://user-images.githubusercontent.com/1289295/78831442-a6a48f80-79b7-11ea-9298-5750ad0a22e0.png) |
Pledge 
[NT-1125]
[NT-1125]: https://kickstarter.atlassian.net/browse/NT-1125

[➕] NT-1125 New card CTA

---

app/src/main/java/com/kickstarter/models/StoredCard.kt
app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
app/src/main/java/com/kickstarter/ui/viewholders/RewardCardSelectedViewHolder.kt
app/src/main/java/com/kickstarter/ui/viewholders/RewardCardUnselectedViewHolder.kt
app/src/main/res/layout/reward_card_details.xml
app/src/main/res/values/strings.xml

Updating copy of payment methods' last four digits.
🆕 copy
Updating payment methods' last four digits copy.
- Added template string `payment_method_last_four`
- Used in `BackingFragment`, `RewardCardSelectedViewHolder`, and `RewardCardUnselectedViewHolder`
- Updated `StoredCard.DATE_FORMAT` because I noticed a bug where the dates were displaying strangely
| View/Manage pledge screen | Pledge screen | Bug 🐞 | 
| ![screenshot-2020-04-08_135848](https://user-images.githubusercontent.com/1289295/78823992-a0a8b180-79ab-11ea-9a0b-1bef0bbc1987.png) | ![screenshot-2020-04-08_135859](https://user-images.githubusercontent.com/1289295/78823993-a1414800-79ab-11ea-8849-187d4dce61b2.png) | ![screenshot-2020-04-08_135622](https://user-images.githubusercontent.com/1289295/78823988-a0a8 …

[💳] NT-1123 Last four digits copy

---

app/src/main/res/drawable/white_gradient.xml
app/src/main/res/layout/item_update_card.xml

- Gradient border
- Maxlines to 6
- more margin
- Match figma Design: https://www.figma.com/file/hLN2KNtHj692pwnhK7M3Ei/Updates?node-id=63%3A4
[Project Update cards truncation polish](https://kickstarter.atlassian.net/browse/NT-1075)

NT-1075: Project Update cards truncation polish

---

app/src/main/java/com/kickstarter/ApplicationModule.java
app/src/main/java/com/kickstarter/libs/ExperimentsClientType.kt
app/src/main/java/com/kickstarter/libs/Koala.java
app/src/main/java/com/kickstarter/libs/KoalaTrackingClient.java
app/src/main/java/com/kickstarter/libs/LakeTrackingClient.kt
app/src/main/java/com/kickstarter/libs/OptimizelyExperimentsClient.kt
app/src/main/java/com/kickstarter/libs/TrackingClient.kt
app/src/main/java/com/kickstarter/libs/TrackingClientType.java
app/src/main/java/com/kickstarter/libs/models/OptimizelyEnvironment.kt
app/src/main/java/com/kickstarter/libs/utils/ExperimentUtils.kt
app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
app/src/main/java/com/kickstarter/mock/MockExperimentsClientType.kt
app/src/test/java/com/kickstarter/KSRobolectricTestCase.java
app/src/test/java/com/kickstarter/libs/KoalaTest.kt
app/src/test/java/com/kickstarter/libs/LakeTest.kt
app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
app/src/test/java/com/kickstarter/libs/utils/ExperimentUtilsTest.kt

Reverts kickstarter/android-oss#846 so I can fix the commit message for prosperity

Revert "[💥] NT-1177 Adding Optimizely property group (to Project Page Pledge Button Clicked event)"

---

app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt

The `Either` import was missing in `ProjectViewModelTest`
I tried to rebase and remain unsuccessful.
`import com.kickstarter.libs.*`
The tests are PASSING ✅

[🐜] Fixes imports in ProjectViewModelTest so the tests can build!

---

app/src/main/java/com/kickstarter/libs/Koala.java
app/src/main/java/com/kickstarter/libs/LakeEvent.kt
app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
script/style/checkstyle.xml

Hit that red button and you will have a new Event launched
Take a loo into your logcat: 
Take a look into your logcat 
[Manager Pledge Button](https://kickstarter.atlassian.net/browse/NT-1147)

NT-1147: Manage Pledge Button Clicked Event

---

app/src/main/java/com/kickstarter/libs/utils/DiscoveryUtils.java
app/src/main/java/com/kickstarter/services/DiscoveryParams.java
app/src/main/java/com/kickstarter/ui/adapters/DiscoveryPagerAdapter.java
app/src/main/java/com/kickstarter/ui/viewholders/ProjectCardViewHolder.java
app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
app/src/main/java/com/kickstarter/viewmodels/ProjectCardHolderViewModel.java
app/src/main/res/layout/project_tags.xml
app/src/test/java/com/kickstarter/viewmodels/ProjectCardHolderViewModelTest.java

Displaying project location tags in Discovery Project cards when viewing projects sorted by distance.
It'll be used in the Lights On™ project
- Added `DISTANCE` sort
- Added `defaultSorts` array for Discovery
- Added output `locationContainerIsGone` that emits a `Boolean` determining if the project location tag should be shown
- Added output `locationName` that emits the ``displayableName` of the project's `Location`
- Added tests for each
- Made root container a `ConstraintLayout`
- Added `location_container`
You cannot see it yet.
It shouldn't be visible at all yet because we currently don't sort by distance anywhere.
[NT-1233]
[NT-1233]: https://kickstarter.atlassian.net/browse/NT-1233

NT-1233 Showing location in project cards

---

app/src/main/graphql/schema.json

Updating the graphQL schema
So we have access to the latest schema
`apollo-codegen introspect-schema config/schema.graphql`
N/A
N/A
N/A

Updating graphQL schema

---

app/src/test/java/com/kickstarter/viewmodels/CancelPledgeViewModelTest.kt

- Testing currency in user's locale
N/A
N/A
N/A

Broken currency tests: CancelPledgeViewModelTest

---

app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt

- Testing currency in user's locale
N/A
N/A
N/A

Broken currency tests: ProjectViewModelTest

---

app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
app/src/test/java/com/kickstarter/viewmodels/ShippingRuleViewHolderViewModelTest.kt

- Testing currency in user's locale
N/A
N/A
N/A

Broken currency tests: RewardViewHolderViewModelTest

---

app/src/test/java/com/kickstarter/viewmodels/ShippingRuleViewHolderViewModelTest.kt

- Testing currency in user's locale
N/A
N/A
N/A

Broken currency tests: ShippingRuleViewHolderViewModelTest

---

app/src/main/java/com/kickstarter/viewmodels/ProjectCardHolderViewModel.java
app/src/test/java/com/kickstarter/viewmodels/ProjectCardHolderViewModelTest.java

Show the location tag just for projects with tagID = LightsOn
|  |  |
- Hit the Lights On banner and check the collection of projects loading in there is showing the location tag on the project card
- No tag location in any other part check Magic or Popular tabs
[Location tag on Lights On project card](https://kickstarter.atlassian.net/browse/NT-1233)

NT-1233: Show location tag for Lights On project card

---

app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
app/src/main/res/drawable/divider_dark_grey_300_horizontal.xml
app/src/main/res/layout/fragment_pledge.xml
app/src/main/res/layout/fragment_pledge_section_reward_summary.xml
app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt

- Header for no reward
On left figma design, on right simulator
|  |  |
[Header UI for no reward](https://kickstarter.atlassian.net/browse/NT-1328)

[NT-1328] - Header UI for no reward

---

app/src/main/java/com/kickstarter/viewmodels/ExpandableHeaderViewHolderViewModel.kt
app/src/main/res/layout/fragment_pledge_section_header_item.xml
app/src/main/res/layout/fragment_pledge_section_header_reward_sumary.xml

-Some ghost when the title of the reward needs to jump to second line, but just by few letters, it was hiding those few letters from the title
Establish margins on textViews when using width = 0dp and constraints Start/End on the textView or else those margins won't be counted in the space the textView is occupying 
| 
|
|  |  |
[Expandable Header UI](https://kickstarter.atlassian.net/browse/NT-1326)

NT-1326: Reward Title going two lines

---

app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
app/src/main/res/layout/fragment_backing_section_delivery_date_reminder.xml
app/src/main/res/layout/fragment_backing_section_reward_delivery.xml
app/src/main/res/values/strings_i18n.xml

Manage Pledge UI changes
Clean up UI to closer match Figma designs
Make sure text colors match by using correct colors in spans, fix font sizing and string references.
, external resources?
https://kickstarter.atlassian.net/secure/RapidBoard.jspa?rapidView=9&modal=detail&selectedIssue=NT-1171
https://kickstarter.atlassian.net/secure/RapidBoard.jspa?rapidView=9&modal=detail&selectedIssue=NT-1171

NT-1171(Fix): Manage Pledge UI fixes

---

app/src/main/res/drawable/rect_coral_alpha_6.xml
app/src/main/res/layout/item_add_on_pledge.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml

Create UI part of the addOns card. Logic, CTA, and stepper will be handled in upcoming PRs
Add ons work a bit differently from rewards, so it made sense to create a new layout, and logic that will live in a new viewholder.
Create layout XML file that will be inflated via a RecyclerView adapter
https://kickstarter.atlassian.net/secure/RapidBoard.jspa?rapidView=9&modal=detail&selectedIssue=NT-1385

NT-1385: Create backing add on layout

---

app/src/main/java/com/kickstarter/services/KSApolloClient.kt

Fix for a crash 
- unwrapping object
- safe casting 
[NT-1448:Crash on tapping "Manage" on Activity Errored Pledge alert](https://kickstarter.atlassian.net/browse/NT-1448)

NT-1448:Crash on tapping "Manage" on Activity Errored Pledge alert

---

app/src/main/graphql/fragments.graphql
app/src/main/java/com/kickstarter/services/KSApolloClient.kt
app/src/main/java/com/kickstarter/ui/adapters/BackingAddOnsAdapter.kt
app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
app/src/main/java/com/kickstarter/ui/viewholders/BackingAddOnViewHolder.kt
app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
app/src/main/res/color/soft_grey_enabled_drak_gray_disabled.xml
app/src/main/res/drawable/border_rounded_soft_grey_300.xml
app/src/main/res/drawable/border_rounded_solid_black.xml
app/src/main/res/layout/fragment_backing_addons.xml
app/src/main/res/layout/item_add_on_pledge.xml
app/src/main/res/layout/stepper_add_on.xml
app/src/test/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModelTest.kt
app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt

- Added UI for selection into the Add-On Card View
- UI on layout/item_add_on_pledge.xml
- Bussiness logic on com.kickstarter.viewmodels.BackingAddOnViewHolderViewModel
- Find a project with add-ons
- Select a reward containing add-ons
[Figma Designs](https://www.figma.com/file/Mgu86KSC8hksuVvD2c2288/Add-Ons%3A-Delivery?node-id=1063%3A108)
[NT-1386](https://kickstarter.atlassian.net/browse/NT-1386)

NT-1386: Stepper UI on Add-On card

---

app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
app/src/main/res/layout/fragment_backing_section_delivery_date_reminder.xml
app/src/main/res/layout/fragment_backing_section_reward_delivery.xml
app/src/main/res/values-de/strings_i18n.xml
app/src/main/res/values-es/strings_i18n.xml
app/src/main/res/values-fr/strings_i18n.xml
app/src/main/res/values-ja/strings_i18n.xml
app/src/main/res/values/strings_i18n.xml

Design polish changes to manage pledge screen
To closer match mocks
XML layout changes, Fragment changes
https://kickstarter.atlassian.net/secure/RapidBoard.jspa?rapidView=9&selectedIssue=NT-1381

Design polish changes to manage pledge screen

---

app/src/main/java/com/kickstarter/ui/viewholders/BackingAddOnViewHolder.kt
app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt

Remove animation for transition between add button and stepper
[Stepper UI + functionality ](https://kickstarter.atlassian.net/browse/NT-1386)

NT-1386:Rejected fix

---

app/src/main/java/com/kickstarter/libs/utils/RewardViewUtils.kt
app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
app/src/main/java/com/kickstarter/mock/factories/RewardFactory.java
app/src/main/java/com/kickstarter/services/KSApolloClient.kt
app/src/main/java/com/kickstarter/ui/viewholders/RewardViewHolder.kt
app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
app/src/main/res/drawable/ic_container.xml
app/src/main/res/layout/item_reward.xml
app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt

- Added new UI for the selected Reward on the choose another reward flow
- already checked by @colleenmacd 
|  |  |
[Add the "You Backed" tag to previously selected reward](https://kickstarter.atlassian.net/browse/NT-1445)

NT-1445: Selected Reward Tag 

---

app/src/main/java/com/kickstarter/libs/utils/RewardViewUtils.kt
app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
app/src/main/java/com/kickstarter/mock/factories/RewardFactory.java
app/src/main/java/com/kickstarter/services/KSApolloClient.kt
app/src/main/java/com/kickstarter/ui/viewholders/RewardViewHolder.kt
app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.java
app/src/main/res/drawable/ic_container.xml
app/src/main/res/layout/item_reward.xml
app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt

A pledge with add-ons can be updated or changed the payment method
|  |  |
[Update pledge with Add-ons](https://kickstarter.atlassian.net/browse/NT-1462)

NT-1462:Update pledge flow

---

app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt

- When no changes in your previously selected addOns continue button disabled
- Before the validation was not being triggered when backed reward is digital. Fixed that
- If same addOns selected and no updates, but new item is selected button should be enabled
|  |  |
- pledge to a digital reward with add ons
- change reward and select same reward
- check in addOns fragment button is disabled until update preSelected addOns or added new one.
[NT-1390](https://kickstarter.atlassian.net/browse/NT-1390?focusedCommentId=17873)

NT-1390: Disabled button first load changing reward with addOns

---

app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt

- Change to a reward with different ID, ignore the previously selected addOns, and load the available ones for that project
- Load the addOns from the backing object just if the selected reward is the same as the previously backed reward.
|  |  |
- Choose another reward different from what you previously selected
- The AddOns screen should load as new pledge one 
[NT-1549](https://kickstarter.atlassian.net/browse/NT-1549)

NT-1549 : Choose another reward flow

---

app/src/main/java/com/kickstarter/libs/models/Country.kt

Update the country project file in android with new supported countries Poland, Greece and Slovenia. 
Expanding kickstarter backing to more countries.
Created new instances of each country with their country code, currency code, currency symbol, max pledge amount, minimum pledge amount, and if they have a trailing code. 
N/A - not sure how to test this part of the project in the UI. 
[NT-1528](https://kickstarter.atlassian.net/secure/RapidBoard.jspa?rapidView=9&projectKey=NT&modal=detail&selectedIssue=NT-1528&assignee=5efe5a70e0043f0bacaf7706&assignee=5eda9c57222d4d0b8296577e)

NT-1528: Android Update Project File to include New Countries

---

app/build.gradle
app/src/main/java/com/kickstarter/ui/viewholders/RewardViewHolder.kt
app/src/main/res/layout-land/project_media_header.xml
app/src/main/res/layout/activity_survey_view.xml
app/src/main/res/layout/creator_avatar_verified.xml
app/src/main/res/layout/dashboard_referrer_breakdown_layout.xml
app/src/main/res/layout/discovery_drawer_logged_in_view.xml
app/src/main/res/layout/discovery_drawer_logged_out_view.xml
app/src/main/res/layout/form_new_card.xml
app/src/main/res/layout/fragment_backing_section_bonus.xml
app/src/main/res/layout/fragment_pledge_section_accountability.xml
app/src/main/res/layout/fragment_pledge_section_bonus_support.xml
app/src/main/res/layout/fragment_pledge_section_editable_shipping.xml
app/src/main/res/layout/fragment_pledge_section_pledge_amount.xml
app/src/main/res/layout/fragment_pledge_section_shipping.xml
app/src/main/res/layout/fragment_pledge_section_summary_bonus.xml
app/src/main/res/layout/fragment_pledge_section_summary_shipping.xml
app/src/main/res/layout/item_add_card.xml
app/src/main/res/layout/item_errored_backing.xml
app/src/main/res/layout/item_reward_selected_card.xml
app/src/main/res/layout/item_update_card.xml
app/src/main/res/layout/project_creator_info.xml
app/src/main/res/layout/project_metadata_view.xml
app/src/main/res/layout/toast_error.xml

- Fix linter errors for task `:app:lintExternalRelease`

[No-Jira]:Fix linter error

---

app/build.gradle
app/src/main/java/com/kickstarter/KSApplication.java
app/src/main/java/com/kickstarter/ui/adapters/KSListAdapter.kt
app/src/test/java/com/kickstarter/TestKSApplication.java
build.gradle
gradle/wrapper/gradle-wrapper.properties

- Updated kotlin version 
- Do not instantiate firebase dependencies on tests 
|  |  |
**You need in your environment a Gradle version 6.+**
**You need in your environment the JDK version  1.8.+**
Execute on you environment the next scripts: 
- ` bundle exec fastlane external` -> this creates and publish to firebase an external release
- ` bundle exec fastlane internal` -> this creates and publish to firebase an internal release
- `./bin/milkrun update-strings ` -> -> this fetch the new translations and updates all the languages string files
[NT-1467](https://kickstarter.atlassian.net/browse/NT-1467)

NT-1467: Kotlin 1.4.20

---

app/src/main/res/layout/dashboard_referrer_breakdown_layout.xml
app/src/main/res/layout/item_update_card.xml

- Fix color for the Updates page on project
- Fix color on the creator dashboard for the graph
** - Updates screen**
** - Creator Dashboard**
|  |  |
- Open a project an open the updates screen 
- Open the creator dashboard
[NT-1684](https://kickstarter.atlassian.net/browse/NT-1684)

NT-1684:Fix colors

---

app/build.gradle
app/src/main/java/com/kickstarter/services/LakeWorker.kt
app/src/main/java/com/kickstarter/services/interceptors/GraphQLInterceptor.kt

- Update Networking libraries
- Log in in the app (V1) 
- load projects (V1)
- select a project and back it with addOns (GraphQL)
- Check older backed project (GraphQL)
|  |  |
- Perform some of the basic features within the app
** Test V1 (OkHTTP + Retrofit) **
- Log in in the APP
- Lad projects
- Select and project
** Test GraphQL (OkHTTP) **
- Back a project with addons if you find one 
- Look at one previously backed project 
[NT-715](https://kickstarter.atlassian.net/browse/NT-715)

NT-715: Update OkHTTP & Retrofit libraries

---

app/src/main/java/com/kickstarter/libs/utils/extensions/StringExt.kt
app/src/test/java/com/kickstarter/libs/utils/extensions/StringExtKtTest.kt

Created the `StringExt` file as well as the test suite. These methods will replace the ones used from `StringUtils.java` A subsequent pull request will address updating the these methods throughout the codebase. 
An ongoing effort to migrate our codebase to Kotlin and address technical debt.
N/A, these additions in the PR are isolated and not reflected in the app in the UI or functionality. 
[Migrate StringUtils.java to kotlin extension](https://kickstarter.atlassian.net/browse/NT-1700)

NT-1700 Create StringExt.kt and Test Suite

---

app/build.gradle
app/src/main/res/layout/activity_editorial.xml
app/src/main/res/layout/activity_new_card.xml
app/src/main/res/layout/backing_layout.xml
app/src/main/res/layout/fragment_pledge_section_bonus_support.xml
app/src/main/res/layout/fragment_pledge_section_pledge_amount.xml
app/src/main/res/layout/item_add_on_pledge.xml
app/src/main/res/layout/pledge_container.xml

Update androidx dependencies
- Adopted version 1.1.1 for preference with the kotlin build -> 
` implementation 'androidx.preference:preference:1.1.0' -> implementation 'androidx.preference:preference-ktx:1.1.1'`
- Adopted appcompat 1.3.0: <fragment> xml declaration has been replaced by <androidx.fragment.app.FragmentContainerView>
` 'androidx.appcompat:appcompat:1.1.0-rc01' -> 'androidx.appcompat:appcompat:1.3.0-alpha02'`
- We will not adopt for now FragmentFactory 
- Navigate projects
- Pledge to a project 
- Take a look to one of you baked projects
- Add a new payment method
- Use it to pledge to a project
[Update androidx dependencies](https://kickstarter.atlassian.net/browse/NT-1714)

NT-1714: AndroidX dependencies [🛠]

---

app/src/main/java/com/kickstarter/libs/utils/EventContext.kt
app/src/main/java/com/kickstarter/libs/utils/EventName.kt

Added enum classes that represent the Event Names and Event Contexts for phase 1 of segment integration.
This is the new taxonomy that will be sent to segment. 
Created enum classes to hold these values:
Event Names:
- "CTA Clicked"
- "Page Viewed"
Event Context:
- "add_ons_continue"
- "pledge_initiate"
- "pledge_submit"
- "reward_continue"
No change to anything user facing. Once we start implementing these events, we can use the segment dashboard to confirm they are firing correctly. 
[NT-1762: Create Phase 1 "Back a Project" EventNames and EventContext Constants](https://kickstarter.atlassian.net/browse/NT-1762)

NT-1762: Create Phase 1 "Back a Project" EventNames and EventContext Constants

---

app/src/main/java/com/kickstarter/libs/TrackingClient.kt
app/src/main/java/com/kickstarter/libs/TrackingClientType.kt
app/src/main/java/com/kickstarter/libs/utils/extensions/ConfigExtension.kt
app/src/test/java/com/kickstarter/libs/MockTrackingClient.java

- Added feature flag for segment
- Backend PR done for adding the feature flag, take a look here -> https://github.com/kickstarter/kickstarter/pull/21150
|  |  |
- You should see all events we send manually to segment being send if you have the feature flag on
- You should see that no event of the ones send manually to segment being send if you have the feature flag off
[NT-1759](https://kickstarter.atlassian.net/browse/NT-1759)

NT-1759: Feature Flag for Segment

---

app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
app/src/main/java/com/kickstarter/libs/utils/EventKeys.kt
app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt

I reorganized and renamed some of the enums we are using for segment to be more clear. 
As I am adding more keys and values, it was becoming clear that I had put a few things in the wrong place. This will set us up to be better organized as we are moving forward. 
All segment work should be the same as before, just updated the imports. 
N/A

Reorganized key and value enums for segment.events

---

app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java

- Added a track event for Discovery clicks events that fire when the filters are tapped in the discovery overlay.
- Created a new function to our `AnalyticsEvents` class that handles sending the event name and properties to the client.
- Added this function to the `DiscoveryViewHolder` that fires when any of the filters in the overlay menu is tapped. 
Examples of what fires these events: 
- Open the app
- Tap the overflow menu button (hamburger button) in the top left corner of the screen
- Tap on "Recommended", "Projects we love", "Saved", "Back by people you follow"
- Both Segment (CTA Clicked) and DataLake (Filter Clicked) should appear in the segment dashboard. Each filter CTA should have it's own event, with "context_cta" = "discovery_filter", and …

EP-239: Create event for Discover filters CTA

---

app/src/main/java/com/kickstarter/libs/qualifiers/KoalaEndpoint.kt
app/src/main/java/com/kickstarter/libs/qualifiers/KoalaRetrofit.kt
app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
app/src/main/java/com/kickstarter/ui/views/KSWebView.kt
app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
app/src/test/java/com/kickstarter/libs/SegmentTest.kt

- created user property `user_is_admin`
- created project property `project_has_add_ons`
- deleted no longer necessary Koala files
|  |  |
- Log In with an admin user
- See a project page to a project with addons ie: [Ares Expedition - The Terraforming Mars Card Game](https://staging.kickstarter.com/projects/strongholdgames/ares-expedition-the-terraforming-mars-card-game?ref=android_project_share)
[EP-163](https://kickstarter.atlassian.net/browse/EP-163)

EP-163: Create new properties

---

app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
app/src/main/java/com/kickstarter/viewmodels/ActivityFeedViewModel.java
app/src/test/java/com/kickstarter/viewmodels/ActivityFeedViewModelTest.java

Added track event for "discover projects" button clicks in the activity screen
- Create a new method that submits CTA click event to segment
- Called method from ActivityFeedViewModel class for every click on "Discover Projects" button
| --- | --- |
|  |  |
- Navigate to the Activity Screen. 
- Click "Discover Projects" button. You should the event registered on segment dashboard
https://kickstarter.atlassian.net/browse/EP-237

EP-237: CTA Clicked (discover)

---

app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/LoginViewModelTest.kt

Android: CTA Clicked (log_in_submit)
Segment Implementation
- Created method ``` trackLogInButtonCtaClicked ``` in ``` AnalyticEvents ```
```
/*
* Sends data to the client when the login button is clicked.
*/
fun trackLogInButtonCtaClicked() {
val props: HashMap<String, Any> = hashMapOf(CONTEXT_PAGE.contextName to LOGIN.contextName)
props[CONTEXT_CTA.contextName] = LOGIN_SUBMIT.contextName
client.track(CTA_CLICKED.eventName, props)
}
```
- Called method from ``` LoginViewModel ``` on ``` Log in ``` button clicked
``` 
logInButtonClicked
.subscribe{ this.lake.trackLogInButtonCtaClicked() }
```
| --- | --- |
|  |  |
- On the login screen, fill in the required fields
- Click on the ``` Log in ``` button
You should the new event registered in …

EP-276: CTA Clicked (log_in_submit)

---

.circleci/config.yml
app/quality.gradle
lib/milkrun/checkstyle.rb

- Kotlin linter to follow the kotlin language style conventions
- Less time spend on reviewing PR's as the code style is automatically checked by the linter
- Have consistency across files in code style
- Integrated linter  see 👀  [ktLint rules](https://ktlint.github.io/#rules)
- gradle task to launch the linter: `ktlint`
- gradle task to perform the fix commant the ktlinter provide us: `ktlintFormat` this task will try to fix the errors automatically ⚠️ **_some of the rules as the wild-card one are mandatory to fix by hand_**
- gradle task to assert the generated report on `ktlint` task contains any error `ktlintHasErrors` ⚠️  **_for now this task is disabled until we fix all the currently exiting linter errors._**
- **LOCAL** gradle task to launch the linter: `ktlint`
- **LOCAL** gradle …

NT-1633:Kotlin linter

---

app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
app/src/main/java/com/kickstarter/viewmodels/LoginToutViewModel.java
app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.java

Register SignIn or Sign Up events:
- Log In or Sign Up Button Clicked,
- Facebook Log In or Sign Up Button Clicked
Segment Implementation
- Created method ```  trackLoginOrSignUpCtaClicked  ```
``` 
fun trackLoginOrSignUpCtaClicked(type: String?, page: String) {
val props: HashMap<String, Any> = hashMapOf(CONTEXT_CTA.contextName to LOGIN_OR_SIGN_UP.contextName)
props[CONTEXT_PAGE.contextName] = page
type?.let { props[CONTEXT_TYPE.contextName] = it }
client.track(CTA_CLICKED.eventName, props)
}
```
- Called method from ``` DiscoveryFragmentViewModel ``` and ``` LoginToutViewModel ``` respectively
```
this.discoveryOnboardingLoginToutClick
.subscribe(v -> {
this.lake.trackLogInSignUpButtonClicked();
this.lake.trackLoginOrSignUpCtaClicked(null, …
```

EP-273: Android: CTA Clicked (log_in_or_sign_up)

---

NOTICE

update notice file and remove butter knife  and replacing it with view binding
Keep notice file updated

Update notice file replace butter-knife with view-binding

---

app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
app/src/main/java/com/kickstarter/libs/utils/EventName.kt
app/src/main/java/com/kickstarter/ui/activities/VideoActivity.kt
app/src/main/java/com/kickstarter/viewmodels/VideoViewModel.kt
app/src/test/java/com/kickstarter/libs/SegmentTest.kt
app/src/test/java/com/kickstarter/viewmodels/VideoViewModelTest.java

add Video Playback Completed segment event
A user clicks finished viewing video event or press back
Add Event Handler in Video ViewModel
Add test
open Project and click the video Play button and press back
https://kickstarter.atlassian.net/browse/EP-263

EP-263: Android: Video Playback Completed

---

app/src/main/java/com/kickstarter/ui/activities/HelpActivity.kt

- Contextual right menu on SignUp/Log In screen was crashing
| NOW 🦋 |
https://user-images.githubusercontent.com/4083656/113042936-9ea5a880-9150-11eb-82a1-51f77b4c1915.mp4
| --- | --- |
|  |  |
- Load the app, press Sign Up or Log In button
- Hit the top right contextual menu, try load all the options within that menu
[NT-1811](https://kickstarter.atlassian.net/browse/NT-1811)

NT-1811: Fixes for Regression 2.13.0

---

app/build.gradle
app/src/main/java/com/kickstarter/ApplicationModule.java
build.gradle

- Added `appboy-segment` dependency in order to complete the Side-By-Side integration, with this dependency added and configured on the segment client, we should be able to flow data from Segment to Braze.
- Some configuration has been done on Segment Dashboard to add braze dependency
- Some configuration has been done on Braze Dashboard to hold the data regarding our Segment implementation
- Updated firebase related dependencies as is mandatory for the next braze SDK integration
[Side-by-side integration](https://segment.com/docs/connections/destinations/catalog/braze/#android)
|  |  |
[NT-1827](https://kickstarter.atlassian.net/browse/NT-1827)

NT-1827: Side-by-side integration Segment-Braze

---

app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.java
app/src/test/java/com/kickstarter/libs/SegmentTest.kt
app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.java

Send `CTA Clicked (project)`AUser taps on a project in the recommendations list on the thanks page.
Segment integration/QA Feedback
https://user-images.githubusercontent.com/1075310/115852805-c4109400-a428-11eb-946a-1523ac365e25.mp4
https://kickstarter.atlassian.net/browse/EP-417

EP-417:Android: CTA Clicked (project)

---

README.md

Add codecov badge in the readme for github
to show the codecov badge
https://kickstarter.atlassian.net/browse/NT-1819

NT-1819:Android CodeCov Integration "Adding badge"

---

README.md

[No-jira]: Added ktlint badge to readme

---

app/src/main/res/layout/activity_newsletter.xml

- move up newsletters row
|  |  |
- Settings -> newsletters check that screen looks like the screenshoot
[NT-1860](https://kickstarter.atlassian.net/browse/NT-1860)

NT-1860: Move up newsletter row

---

app/src/main/java/com/kickstarter/ui/adapters/CommentsAdapter.kt

Remove a section from the comment adapter
Crashing in case opening comment list
| --- | --- |
|  |  |
open project comments without logging in 
https://kickstarter.atlassian.net/browse/NT-1907

NT-1907:UI for Comment Card

---

app/src/main/graphql/project.graphql
app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
app/src/main/java/com/kickstarter/services/ApolloClientType.kt
app/src/main/java/com/kickstarter/services/KSApolloClient.kt
app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt

Add Page Count to Root Comments Query
The query requires the  ``` first ``` param to have a valid hasNextPage and hasPreviousPage  in the pageInfo object.  This is necessary for effective pagination.
Not passing the ``` first ``` param, assuming the default; ```hasNextPage``` and ```hasPreviousPage```  in the ```pageInfo``` object will always be ```false```
- Added page ``` limit ``` to query 
```
query GetProjectComments($slug: String!, $limit: Int!, $cursor: String)
...
```
- Refactored ``` ApolloClientType ``` set a default page limit to 25
``` fun getProjectComments(slug: String, cursor: String?, limit: Int = 25): Observable<CommentEnvelope> ```
| --- | --- |
|  |  |
- Add this code snippet to ``` CommentsViewModel ``` …

added page count to comments query

---

app/src/main/java/com/kickstarter/libs/utils/ApplicationLifecycleUtil.java
app/src/main/java/com/kickstarter/services/interceptors/ApiRequestInterceptor.kt

When the applications resumes, it refreshes the config file and checks if there is a 401 (Unauthorized). A 401 is given when the auth token passed is no longer valid. The application then forces a logout and displays the discovery activity. We've noticed however that when the user is logged in however the access token is null, the app will not be able to load authenticated endpoints such as Activity and Backed projects. 
In order to prevent this case, an additional check is made when the user is refreshed. When a null access token is passed to the config endpoint, it does not return a 401. This is because the endpoint is does not require the user to be logged in. Logged out users can refresh their config file. If the user is logged in and the access token is null, the app will also force …

[NT-1808, NT1837] Blank Screens for Activity and Backed Projects

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/kickstarter/ui/IntentKey.java
app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
app/src/main/res/layout/activity_thread_layout.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/test/java/com/kickstarter/viewmodels/ThreadViewModelTest.kt

- New screen for the `Thread view`
https://user-images.githubusercontent.com/4083656/119744242-6f55a400-be40-11eb-8d6b-79b1c88fa71e.mp4
|  |  |
- Hit the reply button in a comment
[NT-1956](https://kickstarter.atlassian.net/browse/NT-1956)

NT-1956: Thread view and navigation

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

- Updated gradle plugin
- Maintenance 
- Support new android studio versions
- the project builds properly on your environment
- execute on your environment succesfully the script for getting new translations : `./bin/milkrun update-strings`

[NO JIRA]: Updated gradle plugin

---

fastlane/Appfile
fastlane/Fastfile
lib/milkrun/version_code.rb

- The Release process now is able to generate on the Google Play Store a draft release 
- Service account generated on Google Play Console 
- "GOOGLE_PLAY_SERVICE_ACCOUNT_KEY" is an environment key on the private CI environment
- see https://docs.fastlane.tools/actions/upload_to_play_store/
- Private CI environment workflow and google play console with the new created draft: 
- Test version for which the draft was generated
|  |  |
- When we cut the release branch, the signed APK is now uploaded to the google play store as well as a draft release

NT-1992: Automatic release process step 3

---

app/src/main/java/com/kickstarter/libs/loadmore/PaginatedViewModelOutput.kt
app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
app/src/main/java/com/kickstarter/ui/adapters/CommentsAdapter.kt
app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt

open kickstarter comments link when it clicked from deleted comment
Show the comment was deleted 
1- fix insert comment
2- handle on onCommentGuideLinesClicked
Open deleted comment for project
https://user-images.githubusercontent.com/1075310/121095588-df750a00-c7f0-11eb-8fb4-6d5d5be280af.mp4
https://kickstarter.atlassian.net/browse/NT-1962

NT-1962:UX – Show removed comments && NT-2024 && NT-2025

---

app/src/main/java/com/kickstarter/ui/viewholders/CommentCardViewHolder.kt
app/src/main/java/com/kickstarter/ui/views/CommentCard.kt
app/src/main/res/values/styles.xml

The Flagged comment message wasn't showing after translated
The value changed in the translation file
set the new value in viewHolder 
| Before 🐛 |
| After 🦋 |
Check comments in that project "shenmue-3" scroll till found comments deleted has replies
https://kickstarter.atlassian.net/browse/NT-1962

NT-1962:UX – Show removed comments

---

app/src/test/java/com/kickstarter/viewmodels/CommentsViewHolderViewModelTest.kt
app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt

- No changes on the code, just added a few more unit tests 
[NT-2055](https://kickstarter.atlassian.net/browse/NT-2055)

NT-2055: Added more Unit tests 

---

app/src/main/java/com/kickstarter/ui/viewholders/PaginationErrorViewHolder.kt
app/src/main/java/com/kickstarter/ui/viewholders/RepliesStatusCellViewHolder.kt
app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
app/src/main/res/layout/item_error_pagination.xml
app/src/main/res/layout/item_show_more_replies.xml

Icon alignment follows the design – both for errors when loading more root comments and more replies
To match Figma design
separate button and icon
https://user-images.githubusercontent.com/1075310/127037518-33ed4a98-6dd3-4863-b4ea-99eb868a3c0f.mp4
Test both for Initial /Pagination errors when loading more root comments and more replies
https://kickstarter.atlassian.net/browse/NT-2133

NT-2133:UI – Misaligned icon on error messages

---

app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt

Solve issue when pressing back icon  with text in the composer to show a dialog in comment activity
https://user-images.githubusercontent.com/1075310/127163775-5562c2a9-c084-4bcf-a1bf-d73117bea659.mp4
Press back icon and hardware back key when there is unposted text in the composer 
https://kickstarter.atlassian.net/browse/NT-2003

NT-2003:UX – Show pending comment dialog

---

app/src/main/java/com/kickstarter/ui/viewholders/BackingAddOnViewHolder.kt
app/src/main/res/layout/item_add_on_pledge.xml

remove static UI , and check for components name 
there was an issue showing a fixed number for all projects add-on
Open production project and compare with ios 
https://www.kickstarter.com/projects/strangewise/fearsome-weirdos-harvest-of-horrors
https://kickstarter.atlassian.net/browse/NT-2145

Fix limit and left

---

app/src/main/AndroidManifest.xml

Fix the crash for Open Creator Bio crashes the app
Added to the android manifest  file 
https://user-images.githubusercontent.com/1075310/130122968-19cff49a-653a-4903-820a-c5bc1319cf0e.mp4
1. checkout latest master branch
2. Go to any project
3. Hit the creator view, it will crash 
https://kickstarter.atlassian.net/browse/NT-2192

NT-2192:Open Creator Bio crashes the app

---

app/src/main/graphql/fragments.graphql
app/src/main/graphql/project.graphql
app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
app/src/main/java/com/kickstarter/models/Category.java
app/src/main/java/com/kickstarter/models/Project.java
app/src/main/java/com/kickstarter/services/ApolloClientType.kt
app/src/main/java/com/kickstarter/services/KSApolloClient.kt
app/src/main/java/com/kickstarter/ui/intentmappers/ProjectIntentMapper.java
app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt

- Fetch information for Project instead of V1 from GraphQL
- Modify the Project data model to work with both V1 and graphQL
- Preparing ground for future work
- Added new query and fragments for project
- Added new method to the ApolloClient 
- Added transformers for project and the other subtypes needed.
|  |  |
We have not plugged in yet the actual network call, is there is details to iron out as you can see on the screenshots, but for testing it on you environment go to ``ProjectViewModel.kt`` and substitute lines 345 and 346 like this: 
```
.map {
ProjectIntentMapper.projectFromIntent(it)?.slug() ?: ""
}
.switchMap {
this.apolloClient.getProject(it)
```
[NTV-171](https://kickstarter.atlassian.net/browse/NTV-171)

NTV-171: Project query 

---

app/src/main/java/com/kickstarter/ui/fragments/CheckoutRiskMessageFragment.kt
app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
app/src/main/res/layout/fragment_checkout_risk_message.xml
app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt

Handle the understand button in the bottom sheet 
Check that pledge is done only in case the dialog is confirmed
Create delegate to handle button action 
Uploading device-2021-09-15-185841.mp4…
| --- | --- |
|  |  |
Pledge project 
Update Pledge or payment 
https://kickstarter.atlassian.net/browse/NTV-166

Ntv:166 confirm button functionality

---

app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
app/src/test/java/com/kickstarter/libs/SegmentTest.kt
app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt

Add a new event to the confirmation CTA,New event has context_cta=pledge_confirm
Pledge project and click confirm Button
https://kickstarter.atlassian.net/browse/NTV-170

NTV-170 :Segment Analytics Call

---

app/src/main/java/com/kickstarter/libs/utils/NumberUtils.java
app/src/main/java/com/kickstarter/libs/utils/extensions/StringExt.kt
app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
app/src/test/java/com/kickstarter/libs/utils/extensions/StringExtKtTest.kt

- Some backers were reporting invalid bonus amount when updating pledge or fixing pledge
- Bug unraveled finally, the only transformation we do to the bonus amount when moving from `manage your pledge` screen to `update your pledge` screen is a parsing from String to Double like so
`NumberUtils.parse(String, Locale)`, the issue lays here, every language uses different characters for decimal symbols and the character for thousands. 
- Some countries will do `0,99` and others `0.99` 
Reason why we have in mind the Locale when parsing. Well now, not all the languages are listed as Default Locale like is the case for Spanish or Polish, take a look here to see the available list for Java -> 
[Locale.java](https://github.com/frohoff/jdk8u-jdk/blob/da0da73ab82ed714dc5be94acd2f0d00fbdfe2e9/src/sha …

NTV-189: Wrong bonus update pledge

---

app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.kt

Steps to reproduce
1- Open https://www.kickstarter.com/discover/advanced?category_id=1 or https://www.kickstarter.com/discover/categories/art with the app
2- Change sorting
**BEFORE**
💥
**NOW**
🆗 
https://user-images.githubusercontent.com/4083656/134723680-ba30cd79-99b2-48b1-bec0-2123e224da0f.mp4
|  |  |
[NTV-220](https://kickstarter.atlassian.net/browse/NTV-220)

NTV-220: Crash after opening deep link and change Sort

---

app/src/main/graphql/fragments.graphql
app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
app/src/main/java/com/kickstarter/models/Project.java
app/src/main/java/com/kickstarter/services/KSApolloClient.kt
app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt

This person is a collaborator and they have commenting permissions. They're able to post comments on a desktop but are unable to comment while using the mobile app.
Use the `can_comment` flag `graph-ql` for` the project so allowed users can add comment 
Uploading device-2021-10-29-201101.mp4…
Open project as `collaborator `, ``creator`,`backers` and normal user
https://kickstarter.atlassian.net/browse/NTV-215

NTV-215:project collaborator can't comment on project in mobile

---

app/src/main/res/layout/fragment_frequently_asked_question.xml
app/src/main/res/layout/fragment_project_environmental_commitments.xml
app/src/main/res/layout/fragment_project_risks.xml

Fix the padding for risk fragments and remove extra padding  from the other fragments 
https://user-images.githubusercontent.com/1075310/139677407-b387476f-a466-441c-ac73-f5ccdd1b6daf.mp4
Open the project and check padding between title and text below 
https://kickstarter.atlassian.net/browse/NTV-247

NTV-247 : Add to navigation and implement UI

---

app/build.gradle
app/src/main/java/com/kickstarter/libs/utils/ApplicationLifecycleUtil.java

- Update Facebook SDK version
https://user-images.githubusercontent.com/4083656/140422215-4304d4a5-ade8-4068-8207-d5c0424b1e22.mp4
|  |  |
- Log in with Facebook 
[NTV-279](https://kickstarter.atlassian.net/browse/NTV-279)

NTV-279: Update Facebook SKD Version

---

app/src/main/java/com/kickstarter/libs/htmlparser/HTMLModels.kt
app/src/main/java/com/kickstarter/libs/htmlparser/HTMLParser.kt
app/src/main/java/com/kickstarter/ui/adapters/projectcampaign/ViewElementAdapter.kt
app/src/main/java/com/kickstarter/ui/viewholders/projectcampaign/ExternalViewViewHolder.kt
app/src/main/res/layout/view_element_external_source_from_html.xml

Add web view to the external links
External media is displayed and playable
Add a webview 
Inject the HTML coming from the parser
https://user-images.githubusercontent.com/1075310/140425059-75b5d634-8dec-4eb9-9f81-d2bacb0022ba.mp4
Open Artsy project 
https://kickstarter.atlassian.net/browse/NTV-266

NTV-266 :UI – Add External element (Youtube, Spotify, Soundcloud...)

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/kickstarter/libs/htmlparser/ElementExt.kt
app/src/main/java/com/kickstarter/ui/adapters/projectcampaign/ViewElementAdapter.kt
app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectCampaignFragment.kt
app/src/main/java/com/kickstarter/ui/viewholders/projectcampaign/ExternalViewViewHolder.kt
app/src/main/java/com/kickstarter/ui/views/WebChromeVideoFullScreenClient.kt

allow viewing a Youtube video in full screen.
Create WebChromeVideoFullScreenClient 
https://user-images.githubusercontent.com/1075310/142672292-af37ff3b-958d-48d2-9413-055729f0e4bd.mp4
Open the "Artsy" project check the `ExternalViewViewHolder ` for youtube video in full screen
https://kickstarter.atlassian.net/browse/NTV-291

NTV-291 :How to support Youtube in full screen

---

app/src/main/java/com/kickstarter/ui/fragments/projectpage/FrequentlyAskedQuestionFragment.kt
app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectEnvironmentalCommitmentsFragment.kt
app/src/main/res/layout/fragment_frequently_asked_question.xml

Fix the styling for the Ask a question button!
Fix nested scroll effect for recycler view
https://kickstarter.slack.com/archives/CG55BBBBL/p1637693032010500
https://user-images.githubusercontent.com/1075310/143097176-f3306081-cb7f-43e0-99f6-a8bb8ee40bf8.mp4
Check FQA and  different scrollable areas "The LMNL Tent System by Diamond Brand"
Check to ask question button style
https://kickstarter.atlassian.net/browse/NTV-261

NTV-261 :Fetch and apply new translations

---

app/build.gradle

- Update perimeterX dependency
[NTV-300](https://kickstarter.atlassian.net/browse/NTV-300)

NTV-300: Update perimeter-x dependency

---

app/src/test/java/com/kickstarter/libs/utils/extensions/ProjectExtTest.kt

No-jira: Removed flaky test

---

app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
app/src/main/res/layout/activity_project_page.xml

- After rotating a few times the layout got broken
- Collapse the toolbar in case when orientation is landscape
https://user-images.githubusercontent.com/4083656/145084833-6a9db4a1-9de1-4b81-ba32-31e3bbd18d28.mp4
|  |  |
- Open a project, rotate the screen several times, having active several tabs

no-jira: orientation changes issue

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/kickstarter/libs/htmlparser/HTMLModels.kt
app/src/main/java/com/kickstarter/libs/htmlparser/HTMLParser.kt
app/src/main/java/com/kickstarter/libs/utils/extensions/IntentExt.kt
app/src/main/java/com/kickstarter/ui/IntentKey.java
app/src/main/java/com/kickstarter/ui/activities/VideoActivity.kt
app/src/main/java/com/kickstarter/ui/adapters/projectcampaign/ViewElementAdapter.kt
app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectCampaignFragment.kt
app/src/main/java/com/kickstarter/ui/viewholders/projectcampaign/VideoElementViewHolder.kt
app/src/main/java/com/kickstarter/ui/views/WebChromeVideoFullScreenClient.kt
app/src/main/java/com/kickstarter/viewmodels/VideoViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectCampaignViewModel.kt

Implement Fullscreen for Kickstarter Video
Removed flag from Manifest 
Reflector the video activity  to open recycler view videos
send the video closed position to list 
https://user-images.githubusercontent.com/1075310/146211278-01aa0374-622a-4583-bc81-ceda4f05bbb0.mp4
Open project with Kickstarter video "Hiplok"

[no-jira]: Add fullscreen support for Kickstarter video

---

app/src/main/res/layout/fragment_project_campaign.xml
app/src/main/res/layout/view_element_external_source_from_html.xml
app/src/main/res/layout/view_element_header.xml
app/src/main/res/layout/view_element_image_from_html.xml
app/src/main/res/layout/view_element_text_from_html.xml
app/src/main/res/layout/view_element_video_from_html.xml

Left margins are inconsistent across different elements.
Remove margins from elements and add to Recyler-view
https://user-images.githubusercontent.com/1075310/146405752-0af759c0-74be-41bd-b5d8-f957e19b7543.mp4
Margins across different elements in the Story tab match the design on Figma
https://kickstarter.atlassian.net/browse/NTV-303

NTV-303  Fix margins

---

app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
app/src/test/java/com/kickstarter/libs/SegmentTest.kt

Having the project URL flowing through Segment e
Check project properties 
https://kickstarter.atlassian.net/browse/NTV-351

NTV-351  Segment – Add project_url to properties

---

app/src/main/assets/json/server-config.json
app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
app/src/main/res/layout/activity_project_page.xml
app/src/main/res/layout/fragment_frequently_asked_question.xml
app/src/main/res/layout/fragment_project_environmental_commitments.xml
app/src/main/res/values-de/strings_i18n.xml
app/src/main/res/values-es/strings_i18n.xml
app/src/main/res/values-fr/strings_i18n.xml
app/src/main/res/values-ja/strings_i18n.xml
app/src/main/res/values/strings_i18n.xml

solve Two copy formatting errors in Paulo's screenshots in #releases. Section titles for Environmental commitments and Frequently asked questions appear in Title Casing
Copy formatting for `Environmental commitments` and `Frequently asked questions `
Open the project overview
https://kickstarter.atlassian.net/browse/NTV-327

NTV-327: Copy formatting Errors

---

app/src/main/java/com/kickstarter/services/KSApolloClient.kt
app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
app/src/test/java/com/kickstarter/services/GraphQLTransformersTest.kt

- Renamed function
- Added test
- run the tests, no user facing changes

[No-jira]: Added test for GraphQLTransformers

---

app/src/main/graphql/project.graphql
app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
app/src/main/java/com/kickstarter/services/ApolloClientType.kt
app/src/main/java/com/kickstarter/services/KSApolloClient.kt
app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/ProjectPageViewModelTest.kt

Migrate SaveProject call to GraphQL
Replace API call with GraqhQL
https://user-images.githubusercontent.com/1075310/150851670-0c8f3d63-0ff8-4c22-9bc4-5f094a918d89.mp4
Save the project by clicking the heart icon with the Login and Log-out user 
https://kickstarter.atlassian.net/browse/NTV-321

NTV-321 : SaveProject call from V1 to GraphQL

---

app/src/main/java/com/kickstarter/ApplicationModule.java

Fix Optimizely loading file error 
update deprecated method 
set polling time interval to 15 minutes
https://user-images.githubusercontent.com/1075310/151416745-38ecd02d-3629-464d-b027-4603d8fcf787.mp4
open app several times 
https://kickstarter.atlassian.net/browse/NTV-308

NTV-308:Fix Optimizely Non-fatal issue

---

app/src/main/java/com/kickstarter/ui/viewholders/ProjectCardViewHolder.kt

- Fixing Friends avatar issue 
the issue in view holder
|  |  |
- Check the backed project friends avatar

Fix friend avatar issue

---

app/src/main/java/com/kickstarter/ui/viewholders/projectcampaign/ImageElementViewHolder.kt
app/src/main/java/com/kickstarter/ui/views/ImageWithCaptionView.kt

- The image can be clickable if there is an url
https://user-images.githubusercontent.com/4083656/153513942-38f3ec8d-38b8-4218-9996-5a7fe36ca9cf.mp4
|  |  |
- Example project – [Mina the Hollower](https://www.kickstarter.com/projects/yachtclubgames/mina-the-hollower) 
Check the links to Discord, Twitter, and Steam
[NTV-397](https://kickstarter.atlassian.net/browse/NTV-397)

NTV-397:  Clickable images on campaign

---

app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
app/src/test/java/com/kickstarter/viewmodels/ProjectPageViewModelTest.kt

The error is indicating that we are attempting to create comments with an invalid commentable type. Looking at some instances of the error, it looks like we are setting the commentable to the parent comment when it should be an instance of a Project, ProjectPreview, Post, etc.
1. Increase delay to let project loaded for deep link
2. wait for the commendable id loading 
Run  for project reply 
`adb shell am start -a android.intent.action.VIEW     -c android.intent.category.BROWSABLE     -d "https://staging.kickstarter.com/projects/kucaklajn/lets-renovate-the-house-of-klajn-hall/comments?comment=Q29tbWVudC0zNTU0NTAxNw=="`
Run  for update reply 
` adb shell am start -a android.intent.action.VIEW     -c android.intent.category.BROWSABLE     -d …

NTV-399  Reply comments created with invalid commentable

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/kickstarter/viewmodels/DeepLinkViewModel.kt

Seeing some potential issues with Deep Linking
https://user-images.githubusercontent.com/1075310/157887551-f69740f7-09a7-4c3f-ba41-3d7ed54a18a0.mp4
open the Link `https://staging.kickstarter.com/projects/craightonberman/pinch-a-gourmet-salt-and-pepper-set?ref=learn`
in the browser and click the open button, it should open directly in the app.
https://kickstarter.atlassian.net/browse/NTV-422

NTV-422 DeepLinks bug while QA

---

app/src/main/graphql/fragments.graphql
app/src/main/graphql/schema.json
app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt

- Added new feature flag key tied to [CA Local Tax Pickup]( https://kickstarter.atlassian.net/browse/PAY-1309)
- Updated GraphQL Schema.json as new location field has beed added to the reward model
- Upcoming user facing changes will placed behind that feature flag
- Needed to update the Schema for being able to query new data added.
|  |  |
- Load some project with addons, and pledge to it. No difference should be appreciated.
[PAY-1524](https://kickstarter.atlassian.net/browse/PAY-1524)

PAY-1524: Added new feature flag + updated Schema.json

---

app/src/main/graphql/schema.json

- Updated schema.json due to the addition of new queries to GrahpQL

[No-jira]: Update schema.json

---

app/build.gradle

- Update PerimeterX version
[NTV-537](https://kickstarter.atlassian.net/browse/NTV-537)

NTV-537: Update perimeterX version

---

app/src/main/java/com/kickstarter/viewmodels/SurveyHolderViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/SurveyResponseViewModel.kt

- Fix for two crashes
- Solving this two crashes
|  |  |
- Use production environment
- Log in using therealnative account with facebook
- Hit on left menu "Activity" -> it was crashing before
- Load a Survey -> it was crashing before
[NTV-588](https://kickstarter.atlassian.net/browse/NTV-588)

NTV-588: Fix for two crashes

---

app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/TextViewElementShotTest.kt
app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt

Added a new feature flag tied to the 
[Remove Facebook Login](https://kickstarter.atlassian.net/browse/WEB-633)
deprecatete facebook login
[WEB-678](https://kickstarter.atlassian.net/browse/WEB-678)[Android] Create feature flag for Facebook login deprecation.

WEB-678:[Android] Create feature flag for Facebook login deprecation.

---

app/src/main/java/com/kickstarter/libs/ActivityRequestCodes.kt
app/src/main/java/com/kickstarter/libs/utils/extensions/IntentExt.kt
app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
app/src/main/java/com/kickstarter/ui/activities/ResetPasswordActivity.kt
app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
app/src/test/java/com/kickstarter/libs/utils/extensions/IntentExtTest.kt
app/src/test/java/com/kickstarter/viewmodels/LoginViewModelTest.kt

Forget Password screen back few times
Refactor code  to user on activity result to replace open new activity with back 
https://user-images.githubusercontent.com/1075310/183660035-bfffff52-22ad-447e-a02f-869c37687bf8.mp4
test Forget password and click back action 
https://kickstarter.atlassian.net/browse/WEB-688

WEB-688 :[Android ]Forget Password screen back few times

---

app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt

Fix BackingFragment crash 
[
Trending crash
](https://console.firebase.google.com/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/3884ba2f53a99393a47b3049f4e3147e?time=last-seven-days&sessionEventKey=62F0C72202FB00013D44E41CE5E4816E_1707955772361315800)
https://console.firebase.google.com/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/3884ba2f53a99393a47b3049f4e3147e?time=last-seven-days&sessionEventKey=62F0C72202FB00013D44E41CE5E4816E_170795577236131580
Checking setPledgeStatusText for backing fragement

[no-jira]: Fix the null pointer exception for BackingFragment

---

app/build.gradle
app/src/main/java/com/kickstarter/libs/braze/BrazeClient.kt
app/src/test/java/com/kickstarter/libs/InAppCustomListenerHandlerTest.kt
build.gradle

- Upgrade braze-segment side-by-side integration from version 11.0.1 to version 12.0.0, this appboy version contains internally brazeSDK 21.0.0, here the changelog https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md#2100
- Required some firebase +gradle upgrades as well 
Android 13
- PushNotification targeting API 33
https://user-images.githubusercontent.com/4083656/185180273-f01d20f9-1da9-48e2-b114-345c2e7e80fa.mp4
- In-appMessage targeting API 33
https://user-images.githubusercontent.com/4083656/185180359-8707308d-4f1a-4ba1-9269-a52ae083cb7a.mp4
- Displayed error when push notifications have been denied
|  |  |
- With your Device using Android 13 run this branch using the internalRelease build variant, set the environment to production and log in. Go to braze_staging …

NTV-597: Appboy 12.0.0

---

app/build.gradle
app/src/main/java/com/kickstarter/libs/braze/BrazeClient.kt

- Upgrade Braze to the latest version
- Android 13
- Follow the changelog https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md#2100
- Push notifications
https://user-images.githubusercontent.com/4083656/185445304-586d7f91-e0a2-458d-aa75-d61759ba1bca.mp4
- InAppMessage
https://user-images.githubusercontent.com/4083656/185445329-0a441427-fdfc-4460-a047-66110bd0ea94.mp4
|  |  |
- As in previous tickets, build this branch using the internalBuild variant, log in production environment, go to braze dashboard, and use the test tool to sent pushnotifications + inappmesages. If your user id is not added to the internal testers group you can target your specific user_ id.
- Do the same for a device with Android 13 and a lower API. …

NTV-594: Appboy 13.0.0

---

app/build.gradle
app/src/main/java/com/kickstarter/libs/htmlparser/ElementExt.kt
app/src/main/java/com/kickstarter/libs/perimeterx/PerimeterXClient.kt
app/src/main/java/com/kickstarter/libs/rx/operators/ApiErrorOperator.kt
app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
app/src/main/java/com/kickstarter/ui/views/CommentCard.kt
app/src/main/java/com/kickstarter/viewmodels/MessagesViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentLegacyViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
build.gradle

- Latest kotlin version, the only impactful change has been around when statements, now the `else` branch is mandatory even when all the use cases for an ENUM have been covered.
- Browse a few projects
- Pledge to some projects
- View your messages
- View your pledge from a message
- Comment on a project
[NTV-598](https://kickstarter.atlassian.net/browse/NTV-598)

NTV-598: kotlin 1.7.10

---

.circleci/config.yml
app/build.gradle
build.gradle

- Updating stripe version, they fixed a bug on the PaymentSheet when jumping from the top textfield to the next line. 
|  |  |
- Add a new paymentMethod on user settings
- Delete a payment method on user settings

PAY-1931: Update stripe SDK

---

app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt
app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectOverviewViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
app/src/main/res/layout/fragment_project_overview.xml
app/src/main/res/layout/project_creator_info.xml
app/src/test/java/com/kickstarter/viewmodels/ProjectOverviewViewModelTest.kt
app/src/test/java/com/kickstarter/viewmodels/ProjectPageViewModelTest.kt

Deleted feature flag for Android Story tab
Open project and check Campaign has been removed and story tab is added 
https://kickstarter.atlassian.net/browse/WEB-786

WEB-786  : [Android] Deleted feature flag for Android Story tab

---

app/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties

- #allwaysKeepUpdating gradle + kotlin version
- The firebase stuff is updated due to: 
- You can build and run the app
[NTV-628](https://kickstarter.atlassian.net/browse/NTV-628)

NTV-628: Android Studio Dolphin

---

.circleci/config.yml

Bring back jacoco android report and codcov
Jococo stoped test covrage report generation 
run jacoco vs debug build not release

Update Config file

---

app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt
app/src/main/java/com/kickstarter/viewmodels/AddOnViewHolderViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentLegacyViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/AddOnViewHolderViewModelTest.kt
app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentLegacyViewModelTest.kt
app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt

Remove the feature flag related code, updated tests acordingly
- No user changes 
[PAY-1526](https://kickstarter.atlassian.net/browse/PAY-1526)

PAY-1526: Removed feature flag for Local pickup

---

app/src/main/graphql/fragments.graphql
app/src/main/graphql/project.graphql
app/src/main/graphql/schema.json
app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
app/src/main/java/com/kickstarter/models/Update.kt
app/src/main/java/com/kickstarter/services/ApolloClientType.kt
app/src/main/java/com/kickstarter/services/KSApolloClient.kt
app/src/main/java/com/kickstarter/services/apiresponses/updatesresponse/UpdatesGraphQlEnvelope.kt
app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
app/src/main/java/com/kickstarter/ui/activities/ProjectUpdatesActivity.kt
app/src/main/java/com/kickstarter/viewmodels/ProjectUpdatesViewModel.kt
app/src/main/res/layout/activity_updates.xml
app/src/test/java/com/kickstarter/services/GraphQLTransformersTest.kt
app/src/test/java/com/kickstarter/services/apiresponses/UpdatesGraphQlEnvelopeTest.kt
app/src/test/java/com/kickstarter/viewmodels/ProjectUpdatesViewModelTest.kt

Migrate fetch Updates Service from V1 to graphQl
Fix pagination error
1. Create a transform to update Envelope
2. Show loading with scrolling
https://user-images.githubusercontent.com/1075310/207705578-c2df92f2-b105-45cf-8184-f5e2dabbbf0a.mp4
Open projects updates check no changes and paginations works 
[https://www.kickstarter.com/projects/restorationgames/return-to-dark-tower?ref=android_project_share](https://www.kickstarter.com/projects/restorationgames/return-to-dark-tower?ref=android_project_share)
https://kickstarter.atlassian.net/browse/WEB-845

WEB-845 : [Android] Migrate Updates Service from V1 to graphQl

---

app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt

Feature flag for consent management on android
We will be gating changes related to consent management behind a feature flag. 
[WEB-856: Create feature flag for consent management](https://kickstarter.atlassian.net/browse/WEB-856)

WEB-856: Create feature flag for consent management

---

.circleci/config.yml

Temporary removal as we figure out the jacoco Out of memory issue

Temporary skipping code coverage step

---

app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt
app/src/main/java/com/kickstarter/ui/activities/compose/ReportProjectScreen.kt
app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectOverviewViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/ProjectCardHolderViewModelTest.java
app/src/test/java/com/kickstarter/viewmodels/ProjectOverviewViewModelTest.kt
app/src/test/java/com/kickstarter/viewmodels/SearchViewModelTest.java
app/src/test/java/com/kickstarter/viewmodels/ThanksCategoryHolderViewModelTest.java
app/src/test/java/com/kickstarter/viewmodels/VideoViewModelTest.java

UGC will be release without a feature flag, as we cannot access optimizely feature flags at the moment
|  |  |
[NTV-650](https://kickstarter.atlassian.net/browse/NTV-650)
[NTV-650]: https://kickstarter.atlassian.net/browse/NTV-650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NTV-650: Remove feature flag

---

app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt
app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectOverviewViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/ProjectOverviewViewModelTest.kt
gradle.properties

- Optimizely is back, so we can release behind a feature flag
[NTV-652](https://kickstarter.atlassian.net/browse/NTV-652)
[NTV-652]: https://kickstarter.atlassian.net/browse/NTV-652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NTV-652: Feature flag added again.

---

app/src/main/java/com/kickstarter/ui/activities/compose/ReportProjectScreen.kt

- added clickAction to arrow icon
https://user-images.githubusercontent.com/4083656/217378922-388ec0d4-ddd5-417d-9f72-2966a0df27bf.mp4
| --- | --- |
|  |  |
- Click on the arrow icon
[NTV-653](https://kickstarter.atlassian.net/browse/NTV-653)
[NTV-653]: https://kickstarter.atlassian.net/browse/NTV-653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NTV-643: click action for the arrow icon

---

.circleci/config.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties
jacoco.gradle

- Brought back code coverage , upgraded gradle version
- Run locally 
[NTV-654](https://kickstarter.atlassian.net/browse/NTV-654)
[NTV-654]: https://kickstarter.atlassian.net/browse/NTV-654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

NTV-654: gradle version + code coverage

---

app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt
app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.kt
app/src/test/java/com/kickstarter/viewmodels/SearchViewModelTest.kt

Feature flag for the pre-launch page on android
We will be gating changes related to the pre-launch page behind a feature flag. 
Test with `ANDROID_PRE_LAUNCH_SCREEN` feature flag enabled for device id  app navigation to the new screen otherwise the app opens the browser for the project 
https://staging.kickstarter.com/projects/midronome/midronome-midi-synchronization-reimagined?ref=discovery
https://kickstarter.atlassian.net/browse/WEB-755

WEB-974   [Android] Feature Flag for Prelaunch page

---

app/build.gradle
app/src/main/java/com/kickstarter/libs/utils/ConversionsApiEventName.kt
app/src/main/java/com/kickstarter/ui/activities/compose/PreLaunchProjectPageScreen.kt
app/src/main/java/com/kickstarter/ui/compose/KSTextCompose.kt
app/src/test/java/com/kickstarter/KSRobolectricTestCase.kt
app/src/test/java/com/kickstarter/ui/activities/compose/PreLaunchProjectPageScreenTest.kt

Increase test coverage by creating a Prelaunch screen test for jetpack compose 
Increase test coverage

[no-jira]: Add test case for jetpack compose Prelaunch screen 

---

app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectExt.kt
app/src/main/res/values/strings.xml
app/src/test/java/com/kickstarter/viewmodels/ProjectCardHolderViewModelTest.kt

Showing Coming soon badge for saved project
Change order in metadata
https://user-images.githubusercontent.com/1075310/228647316-87ad1810-6e0d-4aa6-ad98-3496259bc4e7.mp4
Opened pre-launched projects check badge coming soon
Form technology ->wearables
From saved

[no-jira]: Fix issue for Showing Coming soon badge for saved projecta

---

app/src/main/java/com/kickstarter/viewmodels/projectpage/PrelaunchProjectViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/PrelaunchProjectViewModelTest.kt

[New crash](https://console.firebase.google.com/u/1/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/6ed1ae6d3df725fb4bd8714bfb1aae91) appearing in Android 3.10.0
The crash takes place in PreLaunchProjectActivity
We need to show Retry layout in case of error
Add a test case as the issue is not reproducible
https://kickstarter.atlassian.net/browse/MBL-717

MBL-717: Handle Crash In PreLaunchProjectPageActivity

---

app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.kt
app/src/main/java/com/kickstarter/viewmodels/SettingsViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/SettingsViewModelTest.kt

Updating the settings viewmodel, activity, and tests to use RXJava 2
Stuffs out of date!
Changed the code to use the new standards
No visual changes
Go to the settings page (only visible while logged in) and click all the things (not play store review will not work due to dev package name)
[MBL-826](https://kickstarter.atlassian.net/browse/MBL-826)
[MBL-826]: https://kickstarter.atlassian.net/browse/MBL-826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-826] Update settings viewmodel, activity, and tests to RX2

---

app/quality.gradle
app/src/internal/java/com/kickstarter/ui/activities/PlaygroundActivity.kt
app/src/main/java/com/kickstarter/ui/viewholders/BackingAddOnViewHolder.kt
app/src/main/java/com/kickstarter/ui/views/AddOnCard.kt
app/src/main/java/com/kickstarter/ui/views/Stepper.kt
app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModelTest.kt

- One more migration
|  |  |
- The stepper on the addon card works as usual
- The addOnd card shows information as usual
[MBL-743](https://kickstarter.atlassian.net/browse/MBL-743)
[MBL-739]: https://kickstarter.atlassian.net/browse/MBL-739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MBL-743]: https://kickstarter.atlassian.net/browse/MBL-743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MBL-743: BackingAddOnViewHolder-ViewModel-ViewModelTest migrated to RXJ2 

---

app/src/main/java/com/kickstarter/models/ProjectFaq.kt
app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
app/src/main/java/com/kickstarter/ui/adapters/KSAdapter.java
app/src/main/java/com/kickstarter/ui/adapters/KSListAdapter.kt
app/src/main/java/com/kickstarter/ui/viewholders/FrequentlyAskedQuestionsViewHolder.kt
app/src/main/java/com/kickstarter/viewmodels/FrequentlyAskedQuestionsViewHolderViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/FrequentlyAskedQuestionsViewHolderViewModelTest.kt

Migration to rxjava 2.2 and jetpacks viewmodel
- Find a project with FAQ questions (I used "Campster 2 the portable chair for everyone everywhere")
- Make sure you can view the FAQ tab, that there are no crashes, formatting is okay, scrolling works, etc.
- 
[MBL-766: FrequentlyAskedQuestionsViewHolderViewModel.kt to Jetpack ViewModel and RxJava2.2](https://kickstarter.atlassian.net/browse/MBL-766)

MBL-766: FrequentlyAskedQuestionsViewHolderViewModel.kt to Jetpack ViewModel and RxJava2.2

---

app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt

Some changes for the login viewmodel to hopefully address some recent crashes
Crashes are happening on login viewmodel involving null
Removed all them nulls
Go to the login screen and try logging in
[MBL-872](https://kickstarter.atlassian.net/browse/MBL-872?atlOrigin=eyJpIjoiZmNkNWM3NDA3YmE3NDBkOTkwNjQ3OTI5Yzg4NWQ0ODIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
[MBL-872]: https://kickstarter.atlassian.net/browse/MBL-872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-872] Changes for loging viewmodel

---

app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
app/src/main/java/com/kickstarter/ui/activities/compose/ChangePasswordScreen.kt
app/src/main/java/com/kickstarter/viewmodels/ChangePasswordViewModel.kt

Fix a visual issue with the horizontal loading bar in the change password scren, fix bug with error text reappearing
Visual bugs
Set widt to max width, reset error value after its used up
No ticket

fix visuals for compose version of change password, fix issue with error

---

.circleci/config.yml
app/build.gradle
build.gradle

- Upgraded the orb and machine executor image, take a look [here ](https://circleci.com/developer/machine/image/android#image-name) to check what is available on the new machine.
- Upgraded kotlin version + compose compiler + compose dependencies according to this [compatibility table](https://developer.android.com/jetpack/androidx/releases/compose-kotlin)
Always up to date!
|  |  |
- run the app, it should build as usual without any issue
[MBL-874](https://kickstarter.atlassian.net/browse/MBL-874)
[MBL-874]: https://kickstarter.atlassian.net/browse/MBL-874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MBL-874: Upgrades in preparation for API 34

---

app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt

Makes it so there is not a loop when an error comes in
Efficiency
Make it so if the error is empty (which happens when reset)
No visual changes
No ticket

[No Ticket] Fix loop of error handler

---

app/src/main/assets/json/server-config.json
app/src/main/res/values-de/strings_i18n.xml
app/src/main/res/values-es/strings_i18n.xml
app/src/main/res/values-fr/strings_i18n.xml
app/src/main/res/values-ja/strings_i18n.xml

[No-jira]: Translated strings

---

app/src/main/java/com/kickstarter/libs/featureflag/FeatureFlagClient.kt

- New feature flag
- Added feature flags for the 3 project, external, internal and debug
|  |  |
- Nothig to QA yet.
[MBL-896](https://kickstarter.atlassian.net/browse/MBL-896)
[MBL-896]: https://kickstarter.atlassian.net/browse/MBL-896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MBL-896: Added feature flag for new "Use of AI" tab

---

app/src/internal/java/com/kickstarter/ui/activities/DesignSystemActivity.kt
app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AiDisclosureScreen.kt
app/src/main/java/com/kickstarter/ui/compose/designsystem/KSClickableTexts.kt
app/src/main/res/values/strings.xml
app/src/test/java/com/kickstarter/ui/activities/compose/AiDisclosureScreenTest.kt

Updating some string names to be more permanent
old string names had fpo

[NoTicket] updated string names for translations

---

app/src/main/java/com/kickstarter/ui/activities/compose/login/LoginToutScreen.kt
app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AiDisclosureScreen.kt
app/src/main/java/com/kickstarter/ui/compose/designsystem/KSButtons.kt
app/src/main/java/com/kickstarter/ui/toolbars/compose/ToolBar.kt
app/src/test/java/com/kickstarter/ui/activities/compose/AiDisclosureScreenTest.kt
app/src/test/java/com/kickstarter/ui/activities/compose/LoginToutScreenTest.kt

Added tests to logintout screen
Added more spacing at bottom of use of ai tab for scrolling, moved padding to spacer for better scrolling visuals
Tests are good, visual changes were nice to have
[MBL-945](https://kickstarter.atlassian.net/browse/MBL-945)
[MBL-945]: https://kickstarter.atlassian.net/browse/MBL-945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-945] Add tests to logintout screen, minor visual adjustment for use of ai tab

---

Gemfile.lock
app/src/main/assets/json/server-config.json

Updates to our gemfile.lock and config.json from server need to be added
Downloaded changes from server
no user-facing changes

[no-jira] Download gemfile.lock and config.json from server

---

app/src/main/graphql/schema.json

Download graphql schema changes, updated android app
no user facing changes
Everything should work as normal

[no-jira] Download graphql schema

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
app/src/main/java/com/kickstarter/ui/activities/compose/login/KSLoginDropdownMenu.kt
app/src/main/java/com/kickstarter/ui/activities/compose/login/LoginScreen.kt
app/src/main/java/com/kickstarter/ui/compose/designsystem/KSAlerts.kt
app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
app/src/test/java/com/kickstarter/ui/activities/compose/LoginScreenTest.kt
app/src/test/java/com/kickstarter/viewmodels/LoginViewModelTest.kt

Convert the login screen to compose
Dark mode eventually and design system
Brainpower!
make sure login still works as normal, forgot password dialog still works, etc
[MBL-961](https://kickstarter.atlassian.net/browse/MBL-961)
[MBL-961]: https://kickstarter.atlassian.net/browse/MBL-961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Convert Login to Compose

---

app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectOverviewViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/ProjectOverviewViewModelTest.kt

Migration, take a look at the [engineering plan](https://kickstarter.atlassian.net/wiki/spaces/NT/pages/2350317579/ViewModel+Tech+Debt+Epic) if any doubt 
- No visible user changes
|  |  |
- Load the project page for several projects, as backer, logged out, as creator.
[MBL-788](https://kickstarter.atlassian.net/browse/MBL-788)
[MBL-788]: https://kickstarter.atlassian.net/browse/MBL-788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MBL-788: ProjectOverviewViewModel to JetpackViewModel and compose

---

app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectEnvironmentalCommitmentsFragment.kt
app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectEnvironmentalCommitmentsViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/ProjectEnvironmentalCommitmentsViewModelTest.kt

Migration, take a look at the [engineering plan](https://kickstarter.atlassian.net/wiki/spaces/NT/pages/2350317579/ViewModel+Tech+Debt+Epic) if any doubt 
- No visible user changes
|  |  |
- Load the project page for several projects with Environmental commitment tab, not all projects have that tab available.
[MBL-788](https://kickstarter.atlassian.net/browse/MBL-787)
[MBL-788]: https://kickstarter.atlassian.net/browse/MBL-788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MBL-787: EnvironmentalCommitments to JetpackViewModel and RXJava2

---

app/src/main/java/com/kickstarter/ui/compose/designsystem/KSDimensions.kt
app/src/main/java/com/kickstarter/ui/viewholders/compose/search/FeaturedSearchViewHolder.kt
app/src/main/java/com/kickstarter/ui/viewholders/compose/search/ProjectSearchViewholder.kt

Adding in compose views for the search project cards
A step towards full conversion of the search page
🧠  POWER
Not necessary yet
[MBL-979](https://kickstarter.atlassian.net/browse/MBL-979)
[MBL-979]: https://kickstarter.atlassian.net/browse/MBL-979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-979] add the project cards for the search page

---

app/src/main/java/com/kickstarter/ui/activities/CreatorBioActivity.kt
app/src/main/java/com/kickstarter/viewmodels/CreatorBioViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/CreatorBioViewModelTest.kt

Migration, take a look at the [engineering plan](https://kickstarter.atlassian.net/wiki/spaces/NT/pages/2350317579/ViewModel+Tech+Debt+Epic) if any doubt 
- Back navigation has been improved.
|  |  |
- Load the project page, click on the creator information, the CreatorBio page will be displayed. Try with logged in user, and logged out, on the header a button to message the creator when logged in is available, not visible otherwise.
[MBL-752](https://kickstarter.atlassian.net/browse/MBL-752)
[MBL-752]: https://kickstarter.atlassian.net/browse/MBL-752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MBL-752: CreatorBioActivity to JetpackViewModel and RXJava2

---

app/src/main/java/com/kickstarter/ui/activities/HelpActivity.kt
app/src/main/java/com/kickstarter/viewmodels/HelpViewModel.kt

Remove the helpviewmodel as it did nothing
Confirm help activity still works
[MBL-769](https://kickstarter.atlassian.net/browse/MBL-769)
[MBL-769]: https://kickstarter.atlassian.net/browse/MBL-769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-769] Remove HelpViewModel

---

app/src/main/java/com/kickstarter/ui/activities/HelpSettingsActivity.kt
app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
app/src/main/java/com/kickstarter/ui/activities/ResetPasswordActivity.kt
app/src/main/java/com/kickstarter/ui/activities/SetPasswordActivity.kt
app/src/main/java/com/kickstarter/ui/activities/SignupActivity.kt
app/src/main/java/com/kickstarter/ui/activities/TwoFactorActivity.kt
app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt

There is an issue with the privacy policy page on the login flow, so we need to update it to load in a chrome tab which currently works
Legal issues with not showing privacy policy im sure
Adjust the activity extension to use the chrome tabs
In every login page (logintout, sign up, log in, two factor) make sure all legal pages can load correctly
[MBL-1012](https://kickstarter.atlassian.net/browse/MBL-1012)
[MBL-1012]: https://kickstarter.atlassian.net/browse/MBL-1012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-1012] Update legal pages in login to load in Chrome tabs

---

app/src/main/java/com/kickstarter/ui/viewholders/PaymentMethodsViewHolder.kt
app/src/main/java/com/kickstarter/viewmodels/PaymentMethodsViewHolderViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/PaymentMethodsViewHolderViewModelTest.kt

Convert more stuff to rx2
We are converting ALL THE THINGS
Make sure the places the payment methods viewholders are still work as expected
[MBL-784](https://kickstarter.atlassian.net/browse/MBL-784)
[MBL-784]: https://kickstarter.atlassian.net/browse/MBL-784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-784] Convert Paymentmethodsviewholderviewmodel to rx2

---

app/src/main/java/com/kickstarter/KSApplication.java

One of our top crashes:
https://console.firebase.google.com/u/0/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/647dca91175ed9021cfb0b50ee03760b?time=last-seven-days&types=crash&versions=3.15.0%20(2014150884)&sessionEventKey=6531C2D102A7000151E69C5E77F41EB6_1870269481912293087
has to do with undeliverable exceptions.  This is being caused by a thread or call being canceled with no handler.  This codes addes a handler that will take and handle/record the UnderliverableException.
Gotta get that crash rate down
[More in-depth discussion of the change or implementation.](https://stackoverflow.com/questions/66576755/io-reactivex-exceptions-undeliverableexception-the-exception-could-not-be-delive#:~:text=You%20should%20add,RxJavaPlugins.setErrorHandler …

[NoTicket] add uncaught UndeliverableException handler

---

app/src/main/java/com/kickstarter/services/ConnectivityReceiver.kt

- Prevent crash
|  |  |
- Cannot reproduce, but put the app in background change your connectivity from wify to cellular to airplane ... come back to the app 
[MBL-1034](https://kickstarter.atlassian.net/browse/MBL-1034)
[MBL-1034]: https://kickstarter.atlassian.net/browse/MBL-1034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MBL-1034: Fresh Crash on Android 3.16.0:ConnectivityReceiver.unregister

---

app/src/main/java/com/kickstarter/ui/viewholders/RewardViewHolder.kt
app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt

Update RewardViewHolderVIewmodel to RX2 and removal of unused code
Updating all those thigns
🧠 
Make sure the rewards are presented as expected on various projects:
- Ones with limited shipping
- Ones with limited rewards
- One that youve backed
[MBL-796](https://kickstarter.atlassian.net/browse/MBL-796)
[MBL-796]: https://kickstarter.atlassian.net/browse/MBL-796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-796] Update RewardViewHolderVIewmodel to RX2

---

app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
app/src/main/java/com/kickstarter/ui/activities/MessageCreatorActivity.kt
app/src/main/java/com/kickstarter/viewmodels/MessageCreatorViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/MessageCreatorViewModelTest.kt

- Migration, take a look at the [engineering plan](https://kickstarter.atlassian.net/wiki/spaces/NT/pages/2350317579/ViewModel+Tech+Debt+Epic) if any doubt 
- Improved back navigation
- Added connectivity check
https://github.com/kickstarter/android-oss/assets/4083656/b7ba67f1-c796-4b0a-ba71-bd90b29898b6
| --- | --- |
|  |  |
- Message a creator
[MBL-805](https://kickstarter.atlassian.net/browse/MBL-816)
[MBL-805]: https://kickstarter.atlassian.net/browse/MBL-805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MBL-816: MessageCreator Screen

---

app/src/main/java/com/kickstarter/ui/viewholders/RewardCardSelectedViewHolder.kt
app/src/main/java/com/kickstarter/ui/viewholders/RewardCardUnselectedViewHolder.kt
app/src/main/java/com/kickstarter/viewmodels/BaseRewardCardViewHolderViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/RewardCardSelectedViewHolderViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/RewardCardUnselectedViewHolderViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/RewardCardSelectedViewHolderViewModelTest.kt
app/src/test/java/com/kickstarter/viewmodels/RewardCardUnselectedViewHolderViewModelTest.kt

Update some more viewholder viewmodels to rx2
We are updating everything to rx2 to assist with further updates
🧠 
Make sure the rewards card viewholders work and function as they used to
[MBL-793](https://kickstarter.atlassian.net/browse/MBL-793)
[MBL-794](https://kickstarter.atlassian.net/browse/MBL-794)
[MBL-793]: https://kickstarter.atlassian.net/browse/MBL-793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MBL-794]: https://kickstarter.atlassian.net/browse/MBL-794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-793/794] Update CardViewHolder ViewModels to RX2

---

app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
app/src/main/java/com/kickstarter/ui/fragments/CancelPledgeFragment.kt
app/src/main/java/com/kickstarter/viewmodels/CancelPledgeViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/CancelPledgeViewModelTest.kt

- Migration RXJava2 + ViewModel, take a look at the [engineering plan](https://kickstarter.atlassian.net/wiki/spaces/NT/pages/2350317579/ViewModel+Tech+Debt+Epic) if any doubt 
| --- | --- |
|  |  |
- Pledge to a project, then cancel, then pledge again, then cancel.
[MBL-746](https://kickstarter.atlassian.net/browse/MBL-746)
[MBL-746]: https://kickstarter.atlassian.net/browse/MBL-746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MBL-746: CancelPledge Screen

---

app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
app/src/main/java/com/kickstarter/ui/activities/BackingActivity.kt
app/src/main/java/com/kickstarter/viewmodels/BackingViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/BackingViewModelTest.kt

- Migration RXJava2 + ViewModel, take a look at the [engineering plan](https://kickstarter.atlassian.net/wiki/spaces/NT/pages/2350317579/ViewModel+Tech+Debt+Epic) if any doubt 
- Added connectivity check
- Improved back navigation
| --- | --- |
|  |  |
- Go to your messages -> open a message from creator of a project you backed -> hit "view your pledge" button
[MBL-744](https://kickstarter.atlassian.net/browse/MBL-744)
[MBL-744]: https://kickstarter.atlassian.net/browse/MBL-744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MBL-744: BackingActivity to RXJava2 + ViewModel

---

app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
app/src/main/java/com/kickstarter/ui/activities/EditorialActivity.kt
app/src/main/java/com/kickstarter/viewmodels/EditorialViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/EditorialViewModelTest.kt

RX2 electric boogaloo
Refactoring is kinda sick
🧠 s
Make sure the editorial view works as expected
[MBL-762](https://kickstarter.atlassian.net/browse/MBL-762)
[MBL-762]: https://kickstarter.atlassian.net/browse/MBL-762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-762] Update EditorialViewModel and activity to rx2

---

app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleFriendFollowViewHolder.kt
app/src/main/java/com/kickstarter/viewmodels/ActivitySampleFriendFollowViewHolderViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/ActivitySampleFriendFollowViewHolderViewModelTest.kt

Quite the mouthful for its being updated to rx2
Refactoring is based
🧠 
[MBL-740](https://kickstarter.atlassian.net/browse/MBL-740)
[MBL-740]: https://kickstarter.atlassian.net/browse/MBL-740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-740] Update ActivitySampleFriendFollowViewHolderVIewModel to rx2

---

app/src/main/java/com/kickstarter/ui/viewholders/EditorialViewHolder.kt
app/src/main/java/com/kickstarter/viewmodels/EditorialViewHolderViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/EditorialViewHolderViewModelTest.kt

Update more things to RX2
Refactoring!
🧠 s
[MBL-761](https://kickstarter.atlassian.net/browse/MBL-761)
[MBL-761]: https://kickstarter.atlassian.net/browse/MBL-761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-761] Update Editorialviewholder to rx2

---

app/src/main/java/com/kickstarter/viewmodels/BaseRewardCardViewHolderViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/BaseRewardCardViewHolderViewModelTest.kt

Update base rewards card view model to rxjava 2
no user-facing changes
Go to a backed project, manage pledge, and then change card screen. 
[MBL-745: BaseRewardCardViewHolderViewModel.kt to Jetpack ViewModel and RxJava2.2](https://kickstarter.atlassian.net/browse/MBL-745)

MBL-745: BaseRewardCardViewHolderViewModel.kt to Jetpack ViewModel and RxJava2.2

---

app/src/main/java/com/kickstarter/ui/viewholders/UpdateCardViewHolder.kt
app/src/main/java/com/kickstarter/viewmodels/UpdateCardViewHolderViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/UpdateCardViewHolderViewModelTest.kt

Update the viewholder and its viewmodel to rx2
Refactoring is cool
🧠 
Make sure the update card view is shown corretly in the update card screen
[MBL-804](https://kickstarter.atlassian.net/browse/MBL-804)
[MBL-804]: https://kickstarter.atlassian.net/browse/MBL-804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-804] Update UpdateCardViewholder to RX2

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/kickstarter/libs/utils/extensions/UriExt.kt
app/src/main/java/com/kickstarter/ui/activities/DeepLinkActivity.kt
app/src/main/java/com/kickstarter/viewmodels/DeepLinkViewModel.kt
app/src/test/java/com/kickstarter/services/UriExtTest.kt
app/src/test/java/com/kickstarter/viewmodels/DeepLinkViewModelTest.kt

- Marketing emails use several domains, those URL's perform a redirection to a project page URL
- Added deeplink from the maon page Open button 
- SplashScreen presented as UI for `DeepLinkActivity`, before it was a transparent activity giving 0 user feedback.
ℹ️  Screenshot with the Main Page open button URL
ℹ️  Screenshot analyzing URL from an Marketing Email
- Deeplinks are one of the top baker pain points
- For the email redirection, perform a network call, on the response check the redirection has happen and make sure the final url is a Project URL
- For the Main Page deeplink, recognize the host domain plus the specific query params, in order to not cause conflicts with any other existing deeplink 
https://github.com/kickstarter/android-oss/assets/4083656/88bad1a2-22be-489a-8899-dbc3 …

MBL-1054: Marketing emails deeplinks

---

app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/ThreadViewModelTest.kt

Update thread viewmodel and associated files to RX2
Refactoring is getting close to done!
🧠 
Make sure threads work as expected
[MBL-803](https://kickstarter.atlassian.net/browse/MBL-803)
[MBL-803]: https://kickstarter.atlassian.net/browse/MBL-803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-803] Update ThreadViewModel and files to RX2

---

app/quality.gradle
app/src/main/java/com/kickstarter/ui/viewholders/ExpandableHeaderViewHolder.kt
app/src/main/java/com/kickstarter/viewmodels/ExpandableHeaderViewHolderViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/ExpandableHeaderViewHolderViewModelTest.kt

Update expandable header view model to rxjava 2
no user-facing changes
Test going through the pledging flow and backing a project
[MBL-765: ExpandableHeaderViewHolderViewModel.kt to Jetpack ViewModel and RxJava2.2](https://kickstarter.atlassian.net/browse/MBL-765)

MBL-765: ExpandableHeaderViewHolderViewModel.kt to Jetpack ViewModel and RxJava2.2

---

app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt

A crash came up with this viewmodel:
https://console.firebase.google.com/u/0/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/efe8a43e0b95638aae8bfefd3099ce72?time=last-seven-days&versions=3.17.0%20(2014150890)&types=crash&sessionEventKey=6570B56D01E3000150EE85831ED32812_1887987293388166730
So this is to make more null safetey and fix the refactoring of this class
Crashes are bad
Add more null filtering before mapping in some places and add better subscribe handling
Go to a project and confirm all rewards are being displayed
[MBL-1087](https://kickstarter.atlassian.net/browse/MBL-1087)
[MBL-1087]: https://kickstarter.atlassian.net/browse/MBL-1087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-1087] update viewmodel with more null filtering and adjusting subscribing

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

[Mo-jira]: Android Studio Hedgehog

---

app/src/main/graphql/schema.json

[No-jira]: Updated graphql schema

---

app/src/main/AndroidManifest.xml

Android known vulnerability that was solved for Android 10 and upper, but  present vulnerability for lower versions. Take a look here https://developer.android.com/privacy-and-security/risks/strandhogg and here https://medium.com/mobile-app-development-publication/the-risk-of-android-strandhogg-security-issue-and-how-it-can-be-mitigated-80d2ddb4af06 for more context 
A malicious application can set the taskAffinity of one of its activities to match the packageName of a target application. This can then be coupled with intent hijacking so that the next time the target application is launched by the user, the malicious application is also launched and displayed on top of the target application.
The Task Affinity vulnerability can then be used to hijack legitimate user actions.
The user …

MBL-1126: Task Affinity Vulnerability

---

app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt

Crash found on errored backings network response: https://console.firebase.google.com/u/1/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/32db9d35aff8d53ec0d5dccf77db8ae0?time=last-seven-days&types=crash&sessionEventKey=65C3E311034600017E2F037064923C72_1911400123071008652
Cleaned up the rx chain where the crash was happening. 
Hard to QA this issue, but make sure the happy path is working -> when you have an errored pledge, observe no crashes. 
[MBL-1190: KSApolloClientV2 ErroredBackings Crash](https://kickstarter.atlassian.net/browse/MBL-1190)

MBL-1190: KSApolloClientV2 ErroredBackings Crash

---

app/src/main/java/com/kickstarter/ui/activities/MessagesActivity.kt
app/src/main/java/com/kickstarter/viewmodels/MessagesViewModel.kt
app/src/main/res/layout/messages_layout.xml
app/src/test/java/com/kickstarter/viewmodels/MessagesViewModelTest.kt

In Messages view, allow user to click on project name to navigate to project page
We received a feature request on Android (from app store reviews) about wanting to be able to click on the KSR campaign from Messages. 
Added a test too
The touch target size is shown in blue:
Go to your messages. Click on a message. Click on the project name to navigate to the project page.
https://kickstarter.atlassian.net/browse/MBL-1071

MBL-1071 Add link to Kickstarter campaign from messages

---

app/src/main/graphql/checkout.graphql
app/src/main/graphql/schema.json

[no-jira]: Updated schema.json

---

app/src/main/java/com/kickstarter/libs/KSCurrency.kt

No JIRA ticket for this specifically, just wanted to clean up some repeated comments as I was doing the currency conversion spike 
N/A
N/A
N/A
N/A
https://kickstarter.atlassian.net/browse/MBL-1185

Remove repeated comments in KSCurrency.kt

---

app/src/main/graphql/schema.json

A description of the change.
| --- | --- |
|  |  |
https://kickstarter.atlassian.net/browse/MBL-1235

MBL-1235 Update schema.json with CreateAttributionEvent mutation

---

app/src/main/java/com/kickstarter/ui/compose/designsystem/KSBadges.kt
app/src/main/java/com/kickstarter/ui/compose/designsystem/KSButtons.kt

Design is working on a new app specific color scheme:
https://www.figma.com/file/g7zQWR0x9gZp7LSNomRBZu/Mobile-Design-System-Updates?type=design&node-id=3964-2214&mode=design&t=6wcg7YTv6J2CEQL2-0
The colors we were using for compose were more of a guess than anything for dark mode, this makes them closer to what should be used.
More  of these changes will be coming

[No Ticket] Adjust some colors to be closer to new design color schemes

---

.circleci/config.yml

Remove tag in CircleCI config
CircleCI changes documented [here](https://discuss.circleci.com/t/android-image-deprecations-and-eol-for-2024/50180)
N/A
N/A
| --- | --- |
|  |  |
N/A
N/A

remove android tag

---

app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectExt.kt
app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/ProjectPageViewModelTest.kt

- Feature flag in place for Late pledges
- UI shown/hidden for late pledges
- Video showing with the feature flag on, a pledge on the `crowdfunding` checkout flow, then search for the project enabled lated pledges and start late pledges flow.
https://github.com/kickstarter/android-oss/assets/4083656/d83ed4b7-f9f7-47df-8bcc-e73e17579e9e
|  |  |
- Follow same steps as the Video above
[MBL-1291](https://kickstarter.atlassian.net/browse/MBL-1291)
[MBL-1291]: https://kickstarter.atlassian.net/browse/MBL-1291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MBL-1291: Feature Flag for latePledges

---

app/src/test/java/com/kickstarter/viewmodels/RewardsSelectionViewModelTest.kt

Add unit tests for rewards selection viewmodel
Testing is good and we want them
[MBL-1294](https://kickstarter.atlassian.net/browse/MBL-1294)
[MBL-1294]: https://kickstarter.atlassian.net/browse/MBL-1294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-1294] Add unit tests for rewards selection viewmodel

---

app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
app/src/main/java/com/kickstarter/ui/adapters/ThanksAdapter.java
app/src/main/java/com/kickstarter/ui/adapters/data/ThanksData.kt
app/src/main/java/com/kickstarter/ui/viewholders/ThanksShareViewHolder.kt
app/src/main/java/com/kickstarter/viewmodels/ThanksShareHolderViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/projectpage/CheckoutFlowViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/projectpage/LatePledgeCheckoutViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/projectpage/RewardsSelectionViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/ThanksShareHolderViewModelTest.kt
app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.kt

Thanks page now launches when late pledge is successful
We need a thanks page to show checkout completed to users
coding magic
Back a post campaign project and make sure the copy on the thanks screen indicates the name of the project, the cost of the pledge, and the user email
[MBL-1287: Updating thanks page](https://kickstarter.atlassian.net/browse/MBL-1287)

MBL-1287: Updating thanks page

---

app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ProjectPledgeButtonAndFragmentContainer.kt

Added functionality to the links being clicked in the checkout page of late page checkout
Those are legal links and are needed
Added some on click stuff
Uploading screen-20240402-170810.mp4…
Go to the checkout page in the late pledge checkout and confirm all links are clickable (privacy policy, terms, cookies, and accountability links)
[MBL-1319](https://kickstarter.atlassian.net/browse/MBL-1319)
[MBL-1319]: https://kickstarter.atlassian.net/browse/MBL-1319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-1319] Add links functionality for checkout page

---

app/src/main/java/com/kickstarter/viewmodels/OAuthViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/OAuthViewModelTest.kt

- Fix for the crash: https://console.firebase.google.com/u/1/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/3b9941d98771e2a016b219a7dd41b388?time=last-seven-days&types=crash&sessionEventKey=660C7DFB01DA0001314F1C3951CCE116_1931836576860752820
- Never spiked, but owr policy is to try to fix new crashes before following release 
- Was completely unable to reproduce, but by locking at the logs, seems for some reason some users are trying to go over the step after the redirection took place, without first creating a codeVerifier.
- Added more security around the step after the redirection, it requires proper: schema, host, code and codeVerifier.
- codeVerifier is now nullable instead of lateinit.
|  |  |
- Logout and log in …

MBL-1286: Avoided lateinit error for after OAuth redirection step.

---

app/src/main/java/com/kickstarter/ui/viewholders/ThanksShareViewHolder.kt

Copy needs to be changed but we do not have the translations for the new string, so just using a blank for now
🦔  gotta go fast
Instructions for anyone to be able to QA this work.Back a late pledge project and confirm text is blank
[MBL-1353](https://kickstarter.atlassian.net/browse/MBL-1353)
[MBL-1353]: https://kickstarter.atlassian.net/browse/MBL-1353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-1353] Update copy to be blank for late pledges

---

app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt

Same changes as what was made for release-3.20.0
Need the changes everywhere
Cherry picked the commit onto a new branch pointed to master

[BUGFIX] Fix add-ons for master branch

---

app/src/main/java/com/kickstarter/viewmodels/projectpage/RewardsSelectionViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/RewardsSelectionViewModelTest.kt

Delivery date was not appearing on confirm details screen
late pledge polish
Make sure estimated delivery date appears on pledge with shippable reward. make sure estimated delivery does not show on a pledge with digital reward
[MBL-1341: Missing delivery date](https://kickstarter.atlassian.net/browse/MBL-1341)

MBL-1341: Missing delivery date

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

New android studio version, new gradle wrapper version

No-jira: Gradle wrapper version upgrade

---

app/src/test/java/com/kickstarter/viewmodels/LatePledgeCheckoutViewModelTest.kt

All networking was covered for error states already, so took the chance to add a few tests :
- More tests always welcome!
- nothing to qa just tests
|  |  |
- nothing to qa just tests 
[MBL-1306](https://kickstarter.atlassian.net/browse/MBL-1306)
[MBL-1306]: https://kickstarter.atlassian.net/browse/MBL-1306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MBL-1306: Added tests

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

- Updated wrapper after android studio new version available

[no-jira]: updated wrapper

---

app/src/main/java/com/kickstarter/libs/featureflag/FeatureFlagClient.kt

Feature flag for pledged projects overview. 
added flag to our feature flag client, as well as remote config. On for internal debug and release, off for external release (prod)
no user facing changes. 
[MBL-1486: Create pledged projects overview feature flag](https://kickstarter.atlassian.net/browse/MBL-1486)

MBL-1486: Create pledged projects overview feature flag

---

app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PPOCardView.kt

Create the UI in compose for the confirm address card
This is the part of the PPO card UI that allows user to edit or confirm their address
Use the design preview in AS and compare against figma: https://www.figma.com/design/r0WKSECmMTCJTSKQskt2SQ/Backed-Projects-Dashboard?node-id=969-15965&t=W82xcgx7xa2fJhqY-0
https://kickstarter.atlassian.net/browse/MBL-1469

MBL-1469 PPO confirm address card

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PPOCardView.kt
app/src/test/java/com/kickstarter/ui/activities/compose/PPOCardViewKtTest.kt

UI tests for the new PPO cards
| --- | --- |
|  |  |
https://kickstarter.atlassian.net/browse/MBL-1527

Compose UI tests for MBL-1468 MBL-1471 MBL-1470 MBL-1469

---

app/src/test/java/com/kickstarter/viewmodels/LatePledgeCheckoutViewModelTests.kt

Added tests for the checkout viewmodel for late pledges
Testing is cool!
[MBL-1297](https://kickstarter.atlassian.net/browse/MBL-1297)
[MBL-1297]: https://kickstarter.atlassian.net/browse/MBL-1297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-1297] Create viewmodel tests for late pledge checkout

---

app/src/main/java/com/kickstarter/ui/activities/ProfileActivity.kt
app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
app/src/main/java/com/kickstarter/viewmodels/ProfileViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/ProfileViewModelTest.kt

Remove RX1 and replace it with RX2 in profile activity/viewmodel
RX1 is old and busted, we need the new hotness
Confirm profile activity still works as normal
[MBL-821](https://kickstarter.atlassian.net/browse/MBL-821)
[MBL-821]: https://kickstarter.atlassian.net/browse/MBL-821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-821] Upgrade profile activity to RX2

---

app/src/main/java/com/kickstarter/ui/viewholders/SurveyViewHolder.kt
app/src/main/java/com/kickstarter/viewmodels/SurveyHolderViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/SurveyHolderViewModelTest.kt

Update the SurveyViewHolder Viewmodel to RX2
We need to get rid of RX1
🧠 
Make sure the viewholder in the activity page works as expected
[MBL-800](https://kickstarter.atlassian.net/browse/MBL-800)
[MBL-800]: https://kickstarter.atlassian.net/browse/MBL-800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MBL-800] Update survey viewholder viewmodel to RX2

---

app/src/main/graphql/fragments.graphql
app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/projectpage/RewardsSelectionViewModel.kt
app/src/main/java/com/kickstarter/viewmodels/usecases/GetShippingRulesUseCase.kt
app/src/test/java/com/kickstarter/viewmodels/RewardsFragmentViewModelTest.kt

New checkout screen using late pledges UI + entirely new VM
⚠️ Some UI small pieces will come
⚠️ Still work in progress more PR's will come with bunch of testing for the new VM!
- Modify my current selection of Shipping location/Bonus/AddOns or payment method
https://github.com/user-attachments/assets/942bf183-f90f-4592-9271-c58e63fe1c92
- Select other reward
https://github.com/user-attachments/assets/e3d4cf6d-0ce2-4bc7-ac42-e0782eb917fd
|  |  |
- Use any project in staging that is still in campaign and not completed, [here one example](https://staging.kickstarter.com/projects/1521513553/a-really-cool-proj?ref=nav_search&result=project&term=a%20really%20cool%20proj)
[MBL-1573](https://kickstarter.atlassian.net/browse/MBL-1573)
[MBL-1573]: …

MBL-1573: Checkout Screen (Change Reward flow for crowdfund) 

---

app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
app/src/main/java/com/kickstarter/ui/fragments/CrowdfundCheckoutFragment.kt

Steps to Reproduce the crash:
- Remove all saved payment methods/new user
- Select stripe link
- Cancel Stripe link flow
Firebase links: 
- https://console.firebase.google.com/u/1/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/0c1bdd8a1a2f371e3ba43087d96c3f78
- https://console.firebase.google.com/u/1/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/edb7989d61828a6bb9e6f3418539caf9
| Before 🐛 | 
https://github.com/user-attachments/assets/dde9336d-26c9-488a-a72f-6087226c2249
| After 🦋 |
https://github.com/user-attachments/assets/fb29ae9f-d4f5-448f-a2e6-dd644a8896ec
| --- | --- |
|  |  |
[MBL-1737](https://kickstarter.atlassian.net/browse/MBL-1737) …

MBL-1737: When user has no saved cards and stripe link fails or is canceled there is a crash

---

.circleci/config.yml
app/build.gradle
app/src/main/java/com/kickstarter/libs/loadmore/ApolloPaginateV2.kt
app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
app/src/test/java/com/kickstarter/viewmodels/ThreadViewModelTest.kt
build.gradle
gradle/wrapper/gradle-wrapper.properties

Fix CircleCI Pipeline to work with SDK 35(ANDROID 15
CircleCI pipeline broke after using an Android Image that has SDK 35
- Make some changes in CircleCI configuration to make it use JVM 17 on the build
- updated some dependencies
- fix tests

MLB-1740: Fix Circle CI Pipeline to work with sdk 35 (Android 15)

---

app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
app/src/main/res/layout/activity_project_page.xml
app/src/main/res/layout/pledge_container.xml

Fix 'Back this project' component on Project activity due a UI bug
This was before the fix 
Changed the method to obtain status bar height

MBL-1825 Fix 'Back this project' component on Project activity (UI)

---

app/src/main/java/com/kickstarter/libs/featureflag/FeatureFlagClient.kt

Added a feature flag for Plot
To have a feature flag to show or not the PLOT changes on the project
Created the flag on Firebase remote config and added to the enum on the project

MBL-1806 Feature flag PLOT

---

app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewActivity.kt

[Crash happening on PPO related to lateinit variable](https://console.firebase.google.com/u/1/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/c72cd5414e911422bd9f159519b7cf28?time=last-seven-days&types=crash&sessionEventKey=674FFAFD01810001333F7E8A935BF5BC_2022890279315480636)
This is caused by the PPO activity being destroyed when the 3DS challenge opens. Upon returning to the PPO screen, the lateinit variable stripe is called in an activity result callback, but it is no longer initialized at this point, and it causes a crash. The PPO activity being destroyed is dependent on the users device and phone memory, so it won’t happen to everyone, but it can happen. 
We are forced to use the deprecated onActivityResult callback because of Stripe. To …

MBL-1921: Crash from lateinit variable stripe uninitialized on activity result callback in PledgedProjectsOverviewActivity

---

app/src/main/java/com/kickstarter/libs/utils/ProjectViewUtils.kt
app/src/main/java/com/kickstarter/libs/utils/extensions/StringExt.kt
app/src/main/java/com/kickstarter/ui/views/compose/checkout/PaymentSchedule.kt
app/src/test/java/com/kickstarter/libs/utils/extensions/StringExtKtTest.kt
app/src/test/java/com/kickstarter/ui/activities/compose/PaymentScheduleTest.kt

Designs
- In compose using `buildAnnotatedString` to join substrings styled with `withStyle`
- `fontSize = typography.title3.fontSize * 0.6f` to make the leading and trail substrings smaller but relative
- `baselineShift = BaselineShift(0.25f)` will align on top the 3 substrings
https://github.com/user-attachments/assets/8f90cd49-e7f5-41af-a02e-50bdb9163b74
- Compose preview
|  |  |
- Load manage pledge screen on a pledge made with plot enabled, here two project available to tests with PLOT:
- https://staging.kickstarter.com/projects/deepmagic/tales-of-the-valiant-game-masters-guide-5e
- https://staging.kickstarter.com/projects/1768690592/dubstep-raspberry-pi-album
[MBL-1992](https://kickstarter.atlassian.net/browse/MBL-1992)
[MBL-1992]: …

MBL-1992: Currency format for PaymentIncrement

---

app/src/main/graphql/schema.graphqls

Update `schema.graphqls`
Schema changes
`downloadApolloSchema`
N/A
Build the app
[\[MBL-2267\] Update GraphQL schema and fix schema changes - Jira](https://kickstarter.atlassian.net/browse/MBL-2267)

MBL-2267: Update GraphQL Schema

---

app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt

Pass a Project's Backing to CreatorBioActivity
Users can access `MessagesActivity` from `CreatorBioActivity` to chat with a Creator. If a user is backing that Creator's Project, the `Backing` object is required to both load the conversation and allow that user to view their Pledge from that same screen. Without the Backing data, accessing `MessagesActivity` via `CreatorBioActivity` results in an infinite loading state.
Previously, a Project's Backing (if one existed) was "reduced" out of `Project` when navigating to `CreatorBioActivity`. Now, the `Backing` is re-included in the `Project` for this particular navigation, as opposed to being re-included more generally within `Project.reduceProjectPayload()`.
https://github.com/user-attachments/assets/9778a6cf-39fb-490c-9a7b-814e22a53fc2 …

MBL-2323: Pass a Project's Backing to CreatorBioActivity

---

app/src/main/java/com/kickstarter/models/Order.kt
app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt

Users with an order could not load project page
Order id was incorrectly parsed as a Long instead of a String
| --- | --- |
| ![Screenshot_20250410_094049](https://github.com/user-attachments/assets/88baa510-53c6-4d40-8ea5-c631ea2391d5) | ![Screenshot_20250411_093347](https://github.com/user-attachments/assets/8d679c29-0676-4487-b2c0-fb9391adabf9) |
Obtain a user that has gone through PM checkout. View the project page of that PM project.
Users in test state can be found here: https://kickstarter.atlassian.net/browse/MBL-2313
https://kickstarter.atlassian.net/browse/MBL-2321

MBL-2321 Fix bug that caused project page to infinite load for PM backers

---

app/src/main/java/com/kickstarter/ui/activities/compose/OnboardingFlowScreen.kt

Unable to repro this crash https://console.firebase.google.com/u/0/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/a34175e57d4cd343ec43f9d330ccada0?time=last-seven-days&versions=3.34.0%20(2014150947)&types=crash&sessionEventKey=689B754B01B4000107E77DCB074AE4DB_2116221379110272843 where the value of currentPages somehow got to 5, but refactoring some logic on the onboarding screen to be more robust.
May or may not fix the crash.
| --- | --- |
|  |  |
https://kickstarter.atlassian.net/browse/MBL-2724

MBL-2724 Filter list of onboarding pages upfront
