kickstarter/android-oss

- app/src/main/java/com/kickstarter/libs/ApiPaginator.java
- app/src/main/java/com/kickstarter/viewmodels/CommentFeedViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/ResetPasswordViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/SignupViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/TwoFactorViewModel.java
- Just Fix to use `doAfterTerminate` instead of `finallyDo` since `finallyDo` is deprecated already.
> Fix to use doAfterTerminate instead of finallyDo.

- app/src/main/java/com/kickstarter/libs/KSCurrency.java
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectViewHolder.java
- app/src/main/java/com/kickstarter/viewmodels/RewardViewModel.java
- app/src/test/java/com/kickstarter/KSCurrencyTest.java
- app/src/test/java/com/kickstarter/viewmodels/RewardViewModelTest.java
Rounded our USD conversion text up so we avoid showing `$0` amounts in rewards.
We want to be sure to only round `UP` for currency in the reward conversion, since generally in other use cases we want the currency to be rounded down.
> Round reward conversion label up

- Makefile
This should suppress the error emitted when attempting to clone the private, non-OSS repo, hopefully reducing the number of false positives reported.
> Suppress secrets error

- app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
- app/src/main/java/com/kickstarter/ui/adapters/DiscoveryPagerAdapter.java
- app/src/main/java/com/kickstarter/ui/fragments/DiscoveryFragment.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/outputs/DiscoveryFragmentViewModelInputs.java
- app/src/main/java/com/kickstarter/viewmodels/outputs/DiscoveryViewModelOutputs.java
- app/src/test/java/com/kickstarter/factories/CategoryFactory.java
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
This is some much needed infrastructural cleanup in our `DiscoveryViewModel` and `DiscoveryFragmentViewModel`. It paves a clearer route for tackling our blank sorts Discovery bug, trust me.
The main change is passing `rootCategories` as an `output` from `DiscoveryActivity` to the `DiscoveryFragment` via an `input`, rather than calling `fetchCategories` again in the fragment.
We need the categories in the fragment for our `DiscoveryUtils.fillRootCategoryForFeaturedProjects` function:
```java
/**
* Given a list of projects and root categories this will determine if the first project is featured
* and is in need of its root category. If that is the case we will find its root and fill in that
* data and return a new list of projects.
*/
```
Before: 4 fetch categories requests on app startup …
> Pass categories from DiscoveryActivity to Fragment

- app/build.gradle
- app/src/main/java/com/kickstarter/libs/Either.kt
- app/src/test/java/com/kickstarter/libs/EitherTest.kt
Say hello to our first Kotlin class. 🤸‍♂️ 
I ran into this 🤔 💭 moment when setting up our code for native comment support on project updates: since we have comments for *either* projects or updates, and Swift in fact handles this with [its own `Either` type](https://github.com/kickstarter/Kickstarter-Prelude/blob/master/Prelude/Either.swift), 💡, add one to android. Maybe even add it in Kotlin.
Things to note:
* [`companion object`](https://kotlinlang.org/docs/reference/object-declarations.html#companion-objects) allows for us to access `left` and `right` as static methods, while keeping our private constructor
* this ensures that `Either` objects cannot be created with both values, i.e. 
```kotlin
new Either<Int, String>(1, "don't do this!")
```
* **[EDIT]** Using [sealed …
> 🎉 Add Either class, in Kotlin

- app/src/main/java/com/kickstarter/services/DiscoveryParams.java
- app/src/test/java/com/kickstarter/services/DiscoveryParamsTest.java
Lil bit of cleanup. Historically `/recommended` was used for staff picks. The endpoint still returns staff picks, but we use `recommended` as a query param now for recommended projects.
> Remove `recommended` from custom uri scope

- app/src/main/java/com/kickstarter/libs/utils/DiscoveryDrawerUtils.java
hey hi what up
This adds `backed(-1)` to the recommendations discovery params.
We filter user's backed projects from recommendations on web, and we also filter them in the native Thanks activity. Filtering them here will homogenize the backer experience across our platforms and stop people from asking jeff what's up with that rec engine.
The Thanks activity also filters backings from staff picks, so that's a possibility here.
> Filter backings from recommended projects

- app/src/main/java/com/kickstarter/ui/activities/ProjectUpdatesActivity.java
- app/src/main/java/com/kickstarter/ui/activities/UpdateActivity.java
- app/src/main/java/com/kickstarter/ui/activities/WebViewActivity.java
Found a bug in the latest internal build where tapping on `Updates -> Update -> Nav back -> Nav back` (or `Updates -> Comments -> Nav back -> Nav back`) results in a navigation loop. 
This is because any of our WebView activities with `RequestHandler`s handle the requests, but still store said requests in the webview's history. 
This is a gnarlier bug that I'm going to leave out of this next build, meaning that our webviews for updates will continue to function as they do now on production (jank) (sryverysry)
> Remove back logic from Update activities

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/KoalaEvent.java
- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.java
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.java
More project view model modernization / cleanup:
* Removed our weird ` private final BehaviorSubject<Project> project = BehaviorSubject.create();` that was neither an input nor an output
* Made all outputs `Observable`s
* Added `currentProject` logic (I think back then we just didn't use `Observable.merge(...)` yet) to distinguish from `initialProject` logic as the project changes on login / starring
* Updated 🐨 events
* Renamed outputs to be more explicit. A lot of noise is from this, sry not sry
> Refactor Project VM

- app/src/main/java/com/kickstarter/ui/activities/SignupActivity.java
- build.gradle
Some signup errors aren't really errors (tho their http status code is 4xx), such as when we ask the user to verify their email. This will come up more often with guest checkout stuff.
So, let's just not show the "Sign up error" title in the dialog, and just show the message that the server provided us.
> Not all signup errors are created equal.

- app/src/main/res/layout/activity_feed_layout.xml
- app/src/main/res/layout/discovery_layout.xml
- app/src/main/res/layout/login_tout_layout.xml
- app/src/main/res/layout/search_layout.xml
- app/src/main/res/layout/two_factor_layout.xml
A few of the layout files have an incorrect path for `tools:context`. Fix them, to keep Android Studio happy.
> fix path for tools:context

- app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
- app/src/main/java/com/kickstarter/ui/adapters/DiscoveryPagerAdapter.java
- app/src/main/java/com/kickstarter/ui/fragments/DiscoveryFragment.java
It all began in #79 when @coryroy discovered that the upgraded linter no longer allowed us to use `getFragments()` from `FragmentManager`. This fix removes our usage of `getFragments()` from our `DiscoveryPagerAdapter`, a method we relied on to get references to our fragments safely for our sort pages.
The plan is to merge this in first, then we can go ahead with merging in #79 to get us onto the latest greatest Android Studio and gradle. 
Turns out that `FragmentManager` always had an annotation to restrict its `getFragments()` usage, but since the method was still public our linter previously allowed it:
```java
@RestrictTo(LIBRARY_GROUP)
public abstract List<Fragment> getFragments();
```
We know the `FragmentPagerAdapter` is finicky with keeping its references to instantiated fragments …
> Remove getFragments() usage

- app/build.gradle
Hooray let's get on the latest (stable) Kotlin! Kotlin files are still slim, so no breaking changes.
https://blog.jetbrains.com/kotlin/2017/04/kotlin-1-1-2-is-out/
If Android Studio isn't or hasn't been prompting you already to upgrade your plugin, go to `Tools > Kotlin > Configure Kotlin Plugin Updates` and check for updates.
> Bump Kotlin version

- app/src/main/java/com/kickstarter/libs/Config.java
- app/src/main/java/com/kickstarter/libs/CurrentUser.java
- app/src/main/java/com/kickstarter/libs/FeatureKey.java
- app/src/main/java/com/kickstarter/ui/activities/ProfileActivity.java
- app/src/main/java/com/kickstarter/viewmodels/ProfileViewModel.java
- app/src/main/res/layout/profile_toolbar.xml
- app/src/test/java/com/kickstarter/factories/ConfigFactory.java
- app/src/test/java/com/kickstarter/viewmodels/ProfileViewModelTest.java
1. Added `features` to our config model so we can start tapping into our feature flags to use them! Config is already a part of our `environment` so this was a breeze.
2. Implemented flag for messages in our `ProfileViewModel`.
3. Modernized `ProfileViewModelTest` and added additional tests.
> Add feature flags to config, implement for messages

- app/src/main/java/com/kickstarter/viewmodels/ProfileViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/ProfileViewModelTest.java
We don't pull in disabled feature flags so only show if present and true
> Adjust feature flag logic

- app/src/main/java/com/kickstarter/services/DiscoveryParams.java
- app/src/test/java/com/kickstarter/libs/utils/DiscoveryParamsUtilsTest.java
When performing searches it seemed weird that the top project had nothing to do with the search term
Change the criteria for showing the POTD to not include search
> Don't put the POTD at the top of search pages

- app/src/test/java/com/kickstarter/libs/utils/DiscoveryParamsUtilsTest.java
- script/style/checkstyle.xml
Our checkstyle rules currently disallows static import of functions unless their package is specifically allowed. We only wanna statically import things that enhance the expressiveness of Java, such as being able to do `observable.filter(isEmpty)` instead of `observable.filter(StringUtils::isEmpty)`.
I propose to add the assert helpers `org.junit.Assert.*` to this list so that we can write tests like:
```java
assertEquals(thingA, thingB);
```
instead of 
```java
Assert.assertEquals(thingA, thingB);
```
Note that we haven't run into this in the vast majority of our tests because we have historically inherited from `TestCase`, which has static assert methods and we can use them without saying `TestCase.assert` cause we are in a subclass. However, current JUnit best practices dictate that …
> Allow static imports of assert functions.

- app/src/main/res/layout/project_search_result_view.xml
- app/src/main/res/values/dimens.xml
Slipped my 👀 that we want our project names to not have bottom gravity, and that our image size should be 80x45dp as per Maggie's mocks
before & after on a 19 moto:
on a 22 nexus 6:
Takeaways? Make sure to take a few mins to do the visual QA on older devices!!!!! And ~ one day ~ may we will have screenshot tests to catch this for us.
> Search result view tweaking

- app/src/test/java/com/kickstarter/viewmodels/ProjectCardholderViewModelTest.java
We have a date rounding error right now that is quite similar to some stuff we saw in iOS until we took control of the co-effect of using dates. This is a fix for now, and we'll look into a proper way of adding date constructors to the environment v soon!
> Add one second to fix rounding error

- app/build.gradle
- build.gradle
Bumping Android Studio to 2.3.3. Release notes here:
https://developer.android.com/studio/releases/index.html
Subsequently upgrading our Kotlin plugin to match our AS version.
> Upgrade AS to 2.3.3

- app/src/main/java/com/kickstarter/services/DiscoveryParams.java
- app/src/test/java/com/kickstarter/services/DiscoveryParamsTest.java
we are currently showing the featured project for a parent category as the first project in all of it's child, more narrow categories.  This has been determined to be a bad discovery experience!  sad!
small little fix to check if the category has no parent so we don't grab the featured project from api.  should there be a test for this? maybe! I'll try to figure that out.
cc @ktman 👋
> Dont show featured projects in subcategories

- app/src/main/java/com/kickstarter/ui/activities/ProjectUpdatesActivity.java
- app/src/main/java/com/kickstarter/ui/activities/UpdateActivity.java
scrolling to the second page of project updates is currently broken - we make a request for the second page, but we don't actually end up showing new data.
I'm mostly just following the pattern that we use in the [checkout activity](https://github.com/kickstarter/android-oss/blob/master/app/src/main/java/com/kickstarter/ui/activities/CheckoutActivity.java#L190), but I think what's happening is we get multiple values emitted from [this merge](https://github.com/kickstarter/android-oss/blob/master/app/src/main/java/com/kickstarter/viewmodels/ProjectUpdatesViewModel.java#L70) in our ProjectUpdatesViewModel, so we don't actually load the data that is returned in the first emission.
> Fix project updates pagination

- app/src/main/java/com/kickstarter/libs/Config.java
- app/src/main/java/com/kickstarter/viewmodels/ActivityFeedViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/ProfileViewModel.java
We have a bunch of crashes since our 1.4.5 release that I thought I had fixed via using:
* `coalesce` to coalesce `config.features().get` with `false` in case a config had not been refreshed properly
* [A default Builder value for features to avoid using Nullable](https://github.com/kickstarter/android-oss/blob/master/app/src/main/java/com/kickstarter/libs/Config.java#L55)
But after some debugging it turns out that the default AutoParcel initialization isn't doing what we expected, i.e. if `features` is null for a non refreshed config we see the crashes in our feature flagged places. This is a hotfix for now so we can move on with making external builds, but for future notice we need to upgrade our AutoParcel to AutoValue.
> Mark features as nullable

- app/src/main/java/com/kickstarter/ui/activities/MessageThreadsActivity.java
- app/src/main/java/com/kickstarter/ui/activities/MessagesActivity.java
- app/src/main/java/com/kickstarter/ui/adapters/MessagesAdapter.java
- app/src/main/java/com/kickstarter/viewmodels/MessageThreadsViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/MessagesViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/MessageThreadsViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/MessagesViewModelTest.java
1. Fixed a bug in which `backingOrThread.compose(takeWhen(messageSent))` would reload an array of `messages` again in the RecyclerView, rather than just the new message sent
2. Fixed the UI of the `unreadMessageCountTextView` so that the text view is only bold and green when there are new messages
> [Messages] Patches 

- app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardViewModelTest.java
build is failing on circle on a test that [compares times](https://github.com/kickstarter/android-oss/blob/master/app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardViewModelTest.java#L110).  I'm hoping this will fix it by not hardcoding the value that we expect to come back from the view model.
> Naive fix for timing in test

- app/src/main/java/com/kickstarter/services/ApiClient.java
- app/src/main/java/com/kickstarter/services/ApiClientType.java
- app/src/main/java/com/kickstarter/services/apiresponses/MessageThreadEnvelope.java
- app/src/main/java/com/kickstarter/ui/activities/MessagesActivity.java
- app/src/main/java/com/kickstarter/ui/data/LoginReason.java
- app/src/main/java/com/kickstarter/ui/data/MessageSubject.kt
- app/src/main/java/com/kickstarter/viewmodels/MessagesViewModel.java
- app/src/main/res/layout/message_threads_layout.xml
- app/src/main/res/layout/messages_layout.xml
- app/src/test/java/com/kickstarter/services/MockApiClient.java
- app/src/test/java/com/kickstarter/viewmodels/MessagesViewModelTest.java
* Preserve toolbar expanded state on rotation, done by setting the id of its CoordinatorLayout
* Open keyboard when there are no messages in a thread
* Add `MessageSubject` & refactor MessagesVM to use it! (this VM is where most of the surgery is done)
* Previously, I was sending messages to a Backing thread as a backer and thus received 422s, since backers should be sending to a Project thread. The overall flow of our messages via message subjects is
```
MessageSubject.Backing : creator -> backer
MessageSubject.Project : backer / user -> creator
MessageSubject.MessageThread : user to a message thread, navigated from Inbox
```
I missed this logic the first time through because in Swift, we have a `MessagesViewModel` as well as a `MessageDialogViewModel` since our editor for writing …
> [Messages] More bugfixes

- app/src/main/java/com/kickstarter/ui/activities/MessageThreadsActivity.java
- app/src/main/java/com/kickstarter/viewmodels/MessageThreadsViewModel.java
- app/src/main/res/layout/message_threads_layout.xml
Implemented swipe refresh layout for messages. Held off on this for a bit cause there was a bug with threads not loading initially, but after looking at our `ActivityFeedViewModel` and other swipe refresh layout turns out that
1. `paginator` related data with the swipe refresher need to be `BehaviorSubject`s (something to do with `ApiPaginator` using PublishSubjects...)
2. we need to manually ping `this.refresh()` initially to kick off the paginator's `startOverWith`
> [Messages] Swipe refresh layout

- app/src/main/java/com/kickstarter/ui/adapters/MessageThreadsAdapter.java
- app/src/main/java/com/kickstarter/viewmodels/MessageThreadHolderViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/MessageThreadsViewModel.java
- app/src/main/res/layout/messages_layout.xml
- app/src/test/java/com/kickstarter/viewmodels/MessageThreadsViewModelTest.java
There was a lil bug with rendering the correct `unread` state for messages on resume.
Turns out since we weren't passing down the correctly refreshed `List<MessageThread>` data from the parent `MessageThreadsViewModel` to its `MessageThreadHolderViewModel`s, so despite caching, the previous value would be fed through again on rotation and recycling (i.e. `onResume`). Wahoo!
> [Messages] Render unread state correctly on refresh

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kickstarter/libs/RefTag.java
- app/src/main/java/com/kickstarter/ui/activities/BackingActivity.java
- app/src/main/java/com/kickstarter/ui/activities/MessagesActivity.java
- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.java
- app/src/main/java/com/kickstarter/ui/viewholders/RewardViewHolder.java
- app/src/main/java/com/kickstarter/viewmodels/BackingViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/MessagesViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.java
- app/src/main/res/layout/backing_layout.xml
- app/src/main/res/layout/backing_toolbar.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/com/kickstarter/viewmodels/BackingViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/MessagesViewModelTest.java
Project context banner should drill into the project from the backing screen if we're coming from messages. Else we just navigate back (to the project page) if coming from the project. 
Bonus renaming of `ViewPledge__` to `Backing__` to align with our Swift code, .:. making it easier to find / make more sense etc etc
[Trello bug report](https://trello.com/c/H92wWu1u/727-p3-android-messages-project-name-banner-on-pledge-info-screen)
> [Messages] Fix project context banner

- app/src/main/java/com/kickstarter/viewmodels/MessageThreadsViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/MessageThreadsViewModelTest.java
Fixing a bug that caused the Message Threads RecyclerView to jump around.
I was using 
```java
Observable.merge(this.onResume, this.refresh)
``` 
as the `startOverWith` signal for both refreshing the `currentUser` as well as fetching new message threads. 
Since the message threads are populated in the recycler view we don't want to refresh the threads each time we hit `onResume`, as it causes the threads to re-populate and lose the previous position.
The solution is to use the `merge` above to refresh the current user, then listen to the user's `unreadMessagesCount` and to refresh the RV data only when there are actually new unreads.
[Refresh Trello Card](https://trello.com/c/w0hEVdWN/726-p2-android-messages-pagination-quirk-1)
Bonus: I'm pretty sure this also fixes [this second …
> [Messages] Pagination refactor

- app/src/main/java/com/kickstarter/viewmodels/MessagesViewModel.java
- app/src/main/res/layout/message_reply_layout.xml
- app/src/main/res/layout/message_view.xml
- app/src/main/res/layout/messages_backing_info_view.xml
- app/src/main/res/layout/messages_layout.xml
- app/src/test/java/com/kickstarter/viewmodels/MessagesViewModelTest.java
Feedback from our QA session, fixed
1. Hide backing info banner if no backing [card](https://trello.com/c/oYTOEtzX/738-p2-view-pledge-cta-shows-in-thread-view-even-if-you-arent-a-backer)
2. Rend sent message to a new message thread [card](https://trello.com/c/G1jTflJY/737-p2-if-you-send-a-new-message-to-a-thread-from-your-backing-info-message-content-doesnt-show-in-the-screen-youre-on)
3. Let reply expand to >1 line [card](https://trello.com/c/5PWLTfJY/736-when-message-goes-onto-2nd-line-see-last-line-of-text-and-only-bottom-of-characters-on-line-above)
> [Messages] QA round dos

- app/src/main/java/com/kickstarter/ui/activities/MessagesActivity.java
Got [this crash in HockeyApp](https://rink.hockeyapp.net/manage/apps/239008/app_versions/81/crash_reasons/178790844?type=crashes) and while I'm not able to re-pro the bug, my hunch is that setting 2 offset listeners on the same `AppBarLayout` in `MessagesActivity` is causing a rendering race condition.
For this instance, in which we do want the toolbar fade effect that `ToolbarUtils` provides us, but also additional logic from listening to the offset changes, let's consolidate the listeners for peace of mind.
> Consolidate toolbar offsetlisteners

- app/src/main/java/com/kickstarter/libs/FeatureKey.java
- app/src/main/java/com/kickstarter/viewmodels/BackingViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/BackingViewModelTest.java
Finishing what I started in #140, since we also show a `Message creator` button in our Backing info view, which would be nice to release since it's ya know already there
Refresher: we still do need to hide the button if we're navigating to the view from Messages, to avoid a weird loop of Backing -> Messages -> Backing -> Messages
> Remove flag from backing screen

- app/src/test/java/com/kickstarter/KSRobolectricTestCase.java
- app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardHeaderHolderViewModelTest.java
joda time has [a method to freeze time in it's current state](http://www.joda.org/joda-time/apidocs/org/joda/time/DateTimeUtils.html#setCurrentMillisFixed-long-).  Maybe this will solve our flaky timing test? Maybe there is a better place to do this like in setup/teardown blocks, but we only need it for one test right now.
anyway, here's a dance about millys
> Use setCurrentMillisFixed for timing test????

- app/src/internal/res/layout/internal_tools_button_view.xml
- app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/ChildFilterViewHolder.java
- app/src/main/res/drawable-v21/click_indicator_dark_masked.xml
- app/src/main/res/drawable-v21/woohoo_vector.xml
- app/src/main/res/drawable/button_white_border_dark_gray.xml
- app/src/main/res/drawable/button_white_border_gray_500.xml
- app/src/main/res/layout-land/discovery_onboarding_view.xml
- app/src/main/res/layout-land/login_tout_layout.xml
- app/src/main/res/layout/activity_feed_layout.xml
- app/src/main/res/layout/black_spinner_item.xml
- app/src/main/res/layout/discovery_drawer_logged_in_view.xml
- app/src/main/res/layout/discovery_drawer_logged_out_view.xml
- app/src/main/res/layout/login_layout.xml
- app/src/main/res/layout/login_tout_layout.xml
- app/src/main/res/layout/profile_layout.xml
- app/src/main/res/layout/profile_toolbar.xml
- app/src/main/res/layout/project_context_view.xml
- app/src/main/res/layout/project_creator_info.xml
- app/src/main/res/layout/project_layout.xml
- app/src/main/res/layout/project_toolbar.xml
- app/src/main/res/layout/two_factor_layout.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
* `black` -> `ksr_soft_black`
* Make base toolbar background `white`
* Make backgrounds `white` where appropriate
* Deprecate `light_gray` in favor of `ksr_grey_200`
A lil unity and cleanliness // alignment with fresher designs.
Before / after:
> Update some base colors

- app/src/main/java/com/kickstarter/ui/activities/SurveyResponseActivity.java
- app/src/main/java/com/kickstarter/viewmodels/SurveyResponseViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/SurveyResponseViewModelTest.java
Previous `handleProjectUriRequest(...)` logic in the SurveyResponseActivity was duplicating `startProjectActivity` logic and completing the request handling prematurely (i.e. tap project header -> go back -> tap project header again -> nothing happens). 
The [change made here](https://github.com/kickstarter/native-secrets/pull/14) fixes the bug, in conjunction with returning `false` in `handleProjectUriRequest` so that we continue to handle project uris. Other changes include code cleanup.
> Fix survey project request bug

- app/src/main/java/com/kickstarter/ui/activities/CreatorDashboardActivity.java
- app/src/main/java/com/kickstarter/ui/adapters/CreatorDashboardBottomSheetAdapter.java
- app/src/main/java/com/kickstarter/ui/fragments/CreatorDashboardFragment.java
- app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardBottomSheetViewHolder.java
- app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardBottomSheetHolderViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardViewModel.java
- app/src/main/res/layout/creator_dashboard_project_switcher_view.xml
- app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardViewModelTest.java
hello, attaching an onclick and updating the fragment when the project switcher is clicked.  here's a look:
> attach new fragment when project switcher is clicked in dashboard

- app/src/main/java/com/kickstarter/services/KSUri.java
- app/src/main/java/com/kickstarter/ui/activities/CheckoutActivity.java
- app/src/test/java/com/kickstarter/services/KSUriTest.java
Client fix for https://trello.com/c/wAraEE4s/3647-guest-pledging-showing-and-sometimes-404ing-in-android-checkout-webviews
The new guest checkout flow redirected users to a new URL when they tried to pledge while not logged in. We were listening for `/signup`, and the new URI is `/checkouts/:checkout_id/guest/new`. Instead of showing the login tout in the app, we were displaying the web signup/guest checkout form.
Will also have a server side change that fixes things for older clients.
> Fix logged out users not going to tout in pledge flow

- app/src/main/res/layout/help_layout.xml
This task (#64) remove **<View..>** because it was used just for add a background. Now, this background is set in the enclosing RelativeLayout.
> Remove view from help-layout

- script/bootstrap
This change addresses #7 #28 #30. I believe many Windows users are using [Bash on Ubuntu for Windows](https://msdn.microsoft.com/en-gb/commandline/wsl/about) or a POSIX-compliant shell to run the bootstrap script. The `function` keyword is not defined on POSIX. This change improves portability and should not break the bash shell on OSX. I am able to build and run the Kickstarter app successfully on Windows.
http://unix.stackexchange.com/questions/73750/difference-between-function-foo-and-foo
> Use POSIX syntax in bootstrap script

- app/src/main/java/com/kickstarter/ui/activities/ActivityFeedActivity.java
- app/src/main/java/com/kickstarter/viewmodels/ActivityFeedViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/ActivityFeedViewModelTest.java
Fixing [this bug](https://trello.com/c/LTdz1Af6/186-zd-android-error-when-accessing-comments-on-an-update) of web comments loading rather than native app comments when accessing updates from the activity feed.
When implementing `UpdatesActivity` for native updates, I forgot to refactor the `ActivityFeedActivity`--we were still launching a `WebViewActivity` with an updates url rather than the proper `UpdateActivity` with a project and update.
> Patch activity feed update comments

- app/build.gradle
- app/src/main/res/layout/message_view.xml
Enabling web links in messages. I went with `web` but the other options are `all, email, phone, map`.
Links in messages should be clickable ヽ(。_°)ノ
> messaging links

- app/src/main/java/com/kickstarter/libs/PushNotifications.java
- app/src/main/java/com/kickstarter/ui/fragments/DiscoveryFragment.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/UpdateViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/outputs/DiscoveryFragmentViewModelOutputs.java
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/UpdateViewModelTest.java
In #167 we refactored the activity feed to patch its Update logic to use the appropriate `UpdateActivity.class` with `Project` and `Update` extras rather than the legacy `WebViewActivity.class` with a `Url`. 
Well...turns out there were a couple more spots we needed to change: the push notification, and the activity sample from the discovery feed. This PR:
* Refactors PushNotifications and DiscoveryFragment to open the appropriate `UpdateActivity` with proper data
* Refactors `UpdateViewModel` to accept either a Project or its Param 
* Renames an output to align with modern styles
A takeaway from this is to audit more thoroughly when implementing new features that replace "temporary" placeholder features.
> Refactor all Update activity helpers

- app/src/main/java/com/kickstarter/libs/qualifiers/AccessTokenPreference.java
- app/src/main/java/com/kickstarter/libs/qualifiers/ActivitySamplePreference.java
- app/src/main/java/com/kickstarter/libs/qualifiers/ApiEndpointPreference.java
- app/src/main/java/com/kickstarter/libs/qualifiers/ApiRetrofit.java
- app/src/main/java/com/kickstarter/libs/qualifiers/AppRatingPreference.java
- app/src/main/java/com/kickstarter/libs/qualifiers/ApplicationContext.java
- app/src/main/java/com/kickstarter/libs/qualifiers/ConfigPreference.java
- app/src/main/java/com/kickstarter/libs/qualifiers/GamesNewsletterPreference.java
- app/src/main/java/com/kickstarter/libs/qualifiers/PackageNameString.java
- app/src/main/java/com/kickstarter/libs/qualifiers/UserPreference.java
- app/src/main/java/com/kickstarter/libs/qualifiers/WebEndpoint.java
- app/src/main/java/com/kickstarter/libs/qualifiers/WebRetrofit.java
`@Qualifier` itself is annotated with `@Retention(RUNTIME)`.
> Remove @Retention from custom Dagger qualifiers

- app/src/main/java/com/kickstarter/ui/toolbars/AlphaBehavior.java
- app/src/main/res/drawable/click_indicator_light.xml
- app/src/main/res/layout/discovery_layout.xml
- app/src/main/res/layout/discovery_toolbar.xml
Started with discovery as a first pass since it's most visible. `AppBarLayout` no longer has elevation, now has a divider whose alpha is based on how much the user has scrolled. The toolbar is only expanded when at the top of the list.
For fun, I got rid of the awkward selected state in the toolbar on pre 21 devices.
> toolbar refresh

- app/src/main/java/com/kickstarter/services/KSUri.java
- app/src/test/java/com/kickstarter/services/KSUriTest.java
This PR adds two helper methods, `isWebViewUri` and `isKSGraphQLUri` to determine whether the URI of a HTTP request is for a WebView i.e. a GET request to get the contents of a WebView. Here, we define a WebView URI as one that is a Kickstarter URI, but not to our GraphQL endpoint.
> Create `isWebViewUri` helper to allow GraphQL reqs via Webviews

- app/src/main/java/com/kickstarter/models/User.java
- app/src/main/java/com/kickstarter/services/gcm/RegisterService.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
- app/src/test/java/com/kickstarter/factories/UserFactory.java
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
Adds `memberProjectsCount` to the `User` object so we show creator dashboard icon for collaborators, not just creators.
Fixes error when registering push token (can't call first() on an `Empty`).
Tests!
> creator tools collaborator access

- app/src/main/res/layout-land/project_media_header.xml
- app/src/main/res/layout/activity_project_state_changed_positive_view.xml
- app/src/main/res/layout/dashboard_funding_view.xml
- app/src/main/res/layout/dashboard_referrer_breakdown_layout.xml
- app/src/main/res/layout/dashboard_referrer_stats_row_view.xml
- app/src/main/res/layout/dashboard_referrer_stats_view.xml
- app/src/main/res/layout/dashboard_reward_stats_row_view.xml
- app/src/main/res/layout/dashboard_reward_stats_view.xml
- app/src/main/res/layout/profile_layout.xml
- app/src/main/res/layout/project_main_layout.xml
- app/src/main/res/layout/search_popular_title_view.xml
- app/src/main/res/values/styles.xml
Went through v1 of creator tools with @dannyalright:
-UI changes (spacing and text size)
-added a new style, `Title2Medium`
> creator tools design sweep

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/KoalaEvent.java
- app/src/main/java/com/kickstarter/ui/activities/CreatorDashboardActivity.java
- app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardBottomSheetViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardHeaderViewHolder.java
- app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardFragmentViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardHeaderHolderViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/MessageThreadsViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardFragmentViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardHeaderHolderViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardViewModelTest.java
Creator tools tracking/instrumentation!
-refactoring `CreatorDashboardViewModel` and tests
-added ref tag for messages
-added events for `Viewed Project Dashboard`, `Opened Project Switcher` and `Switched Projects`
> Creator tools tracking

- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.java
Updating how we share projects because Samsung ruins everything.
We've gotten some Android feedback about users not being able to choose a different app to share projects. On Samsung devices, once you share a project via say Facebook, you get defaulted to sharing via Facebook and you have to reset app defaults to reset it. We should be using this way to share anyway, not sure why the project screen was different. 
Here are the docs on it: https://developer.android.com/training/sharing/send.html
> project share intent

- app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardViewModel.java
Crash be gone. 
No longer crashing if you somehow access the dashboard but you're not a member of any projects by making sure the first project isn't null. Iconic.
> creator dashboard crash

- app/src/main/java/com/kickstarter/services/apiresponses/ProjectStatsEnvelope.java
The server will now only be returning `["kickstarter", "custom", "external"]` as referral types so we don't need to check for campaign and domain. Check out this PR https://github.com/kickstarter/kickstarter/pull/9962 for reference. 
@Scollaco @cdolm92 it's not necessary for iOS to make this change but it affected my chart work in the #221 PR (basically I have no corresponding colors for `["campaign", "domain"]` so I removed them).
> ReferrerType update

- app/src/main/java/com/kickstarter/libs/ReferrerType.kt
- app/src/main/java/com/kickstarter/services/apiresponses/ProjectStatsEnvelope.java
- app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardReferrerBreakdownViewHolder.java
- app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardReferrerBreakdownHolderViewModel.java
- app/src/main/res/layout/creator_dashboard_layout.xml
- app/src/main/res/layout/creator_dashboard_recycler_layout.xml
- app/src/main/res/layout/dashboard_referrer_breakdown_layout.xml
- app/src/main/res/layout/dashboard_referrer_stats_view.xml
- app/src/main/res/layout/dashboard_reward_stats_view.xml
- app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardReferrerBreakdownHolderViewModelTest.java
Changing internal to kickstarter for consistency.
Adding empty state for breakdown with tests.
Adding a progress bar for the dashboard because on a bad connection, you're just looking at a white screen with a back arrow.
> creator tools breakdown empty view

- app/src/main/java/com/kickstarter/libs/CurrentUser.java
- app/src/main/java/com/kickstarter/libs/utils/ApplicationLifecycleUtil.java
- app/src/main/java/com/kickstarter/libs/utils/UserUtils.java
- app/src/main/java/com/kickstarter/services/apiresponses/ProjectStatsEnvelope.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
- app/src/test/java/com/kickstarter/libs/utils/UserUtilsTest.java
Refreshing the user on app resumes.
We are running into a bug where creators won't see the button to the dashboard because their user object is stale. `memberProjectsCount` on the `User` object was previously unused so for all users it's 0 until they are refreshed. Previously, we only refreshed when they logged in or out or they viewed settings, messages or profile. 
This happens in the `onActivityResumed`(when the app is foregrounded) method of `ApplicationLifecycleUtil` where we are currently tracking app opens and refreshing the config. We have the access token (a nullable string) and the user observable. I make the token an observable by calling `.just`. Then, I use `zipWith` to combine them in a pair/tuple (You don’t want to subscribe to the current user observable because it would …
> refresh-user

- app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardReferrerBreakdownViewHolder.java
Checking if external stats are to the left of the breakdown view,  :sparkles: including padding :sparkles: so it doesn't get clipped
> creator-tools-clipped-text

- app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardHeaderHolderViewModel.java
- app/src/test/java/com/kickstarter/factories/UserFactory.java
- app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardHeaderHolderViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
Collaborators were not seeing the "Select another project" button because we were checking `created_projects_count` and not `member_projects_count`.
Did an audit of where `User.creator` is used so we don't miss any collaborators.
Added a helper User that is a collaborator and not a creator.
As a collaborator of 2 projects and no created projects, I see the "Select another project" button.
> creator-tools-collab-bug

- app/src/main/java/com/kickstarter/libs/utils/ApplicationLifecycleUtil.java
one line fix for crashing when opening the app with no service
`Transformers.neverError()` 🙃
> refresh user crash

- app/src/main/java/com/kickstarter/libs/FeatureKey.java
- app/src/main/java/com/kickstarter/services/apiresponses/ProjectStatsEnvelope.java
- app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardReferrerBreakdownViewHolder.java
- app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardReferrerBreakdownHolderViewModel.java
- app/src/main/res/layout/dashboard_referrer_breakdown_layout.xml
- app/src/test/java/com/kickstarter/factories/ProjectStatsEnvelopeFactory.java
- app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardReferrerBreakdownHolderViewModelTest.java
The chart is back!
( •\_•\)
( •\_•\)>⌐■-■
(⌐■_■) 
Removed feature flag for breakdown chart.
Added new model and factory for ReferralAggregates.
Chart now displays accurate data based on aggregates and total pledged amount. Yay percentages 
SO MANY TESTS!
LOOK AT HER
> return of the referrer breakdown chart!

- app/src/main/assets/json/server-config.json
- app/src/main/java/com/kickstarter/ui/activities/SignupActivity.java
- app/src/main/java/com/kickstarter/viewmodels/SignupViewModel.java
- app/src/main/res/layout/signup_form_view.xml
- app/src/main/res/values-de/strings_i18n.xml
- app/src/main/res/values-es/strings_i18n.xml
- app/src/main/res/values-fr/strings_i18n.xml
- app/src/main/res/values-ja/strings_i18n.xml
- app/src/main/res/values/strings_i18n.xml
- app/src/test/java/com/kickstarter/viewmodels/SignupViewModelTest.java
Updating sign up name copy and updating strings.
@miki-nakata
> name copy update

- app/build.gradle
> Remove espresso

- app/src/main/java/com/kickstarter/ui/adapters/DiscoveryPagerAdapter.java
- app/src/main/java/com/kickstarter/ui/fragments/DiscoveryFragment.java
We have a few `NullPointerException`s because we attempt to access the `ViewModel` after the fragment is detached.
Now we check if the `ViewModel` is `null`.
https://rink.hockeyapp.net/manage/apps/239014/app_versions/51/crash_reasons/215537957?type=overview
> [bug] NPE in DiscoveryFragment

- app/src/main/res/layout/settings_layout.xml
Refactoring the settings screen XML in preparation for GDPR changes that will be coming 🔜
1. ⌘⌥L to reformat the code (alphabetizes properties)
2. Removing manually drawn dividers. 
Manually drawing dividers in a [LinearLayout](https://developer.android.com/reference/android/widget/LinearLayout) is redundant because it's supported by adding `showDividers` with values `"beginning"|"end"|"middle"|"none"` for positioning and providing a divider drawable by using `divider`.
(I don't think these heights should be hardcoded either. If the text gets really long, or the font size changes, it could get cut off. But I'll hold off for now.)
> [refactor] settings layout, no more manual dividers!

- app/src/main/java/com/kickstarter/libs/utils/DiscoveryDrawerUtils.java
- app/src/main/java/com/kickstarter/models/User.java
- app/src/test/java/com/kickstarter/factories/UserFactory.java
- app/src/test/java/com/kickstarter/libs/utils/DiscoverDrawerUtilsTests.java
Hiding recommendations when user has setting off.
> [GDPR] Hiding recommendations

- app/src/main/assets/json/server-config.json
- app/src/main/res/layout-land/login_tout_layout.xml
- app/src/main/res/layout/facebook_confirmation_layout.xml
- app/src/main/res/layout/login_tout_layout.xml
- app/src/main/res/layout/signup_form_view.xml
- app/src/main/res/values-de/strings_i18n.xml
- app/src/main/res/values-es/strings_i18n.xml
- app/src/main/res/values-fr/strings_i18n.xml
- app/src/main/res/values-it/strings_i18n.xml
- app/src/main/res/values-ja/strings_i18n.xml
- app/src/main/res/values/strings_i18n.xml
Updating the strings from the server.
Removing Facebook copy.
Updating the disclaimer.
|￣￣￣￣￣￣|
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;G&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;D&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;P&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;R&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
| ＿＿＿＿＿__| 
(\ _ /)  || 
(•ㅅ•) || 
/ 　 づ 
cc @dannyalright @nnekab
> Login Tout & Sign Up, GDPR style

- app/src/main/java/com/kickstarter/libs/utils/Secrets.java.example
- app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.java
- app/src/main/res/layout/settings_layout.xml
Linking externally to data export feature.
GDPR is still coming for my neck
> v1 of data export

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kickstarter/libs/utils/Secrets.java.example
- app/src/main/java/com/kickstarter/ui/activities/HelpActivity.java
- app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.java
- app/src/main/java/com/kickstarter/ui/views/LoginPopupMenu.java
- app/src/main/res/menu/login_help_menu.xml
Updating help center link!
It follows the same pattern as our other help links.
@walterbm said so
> Updating help center link

- app/src/main/java/com/kickstarter/services/ApiClient.java
- app/src/main/java/com/kickstarter/services/apirequests/SettingsBody.java
- app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.java
- app/src/main/java/com/kickstarter/viewmodels/SettingsViewModel.java
- app/src/main/res/layout/settings_layout.xml
- app/src/test/java/com/kickstarter/viewmodels/SettingsViewModelTest.java
Users should be able to toggle whether or not they can be following or `social` via settings. This change also updates whether the `Backed by people you follow` section is visible in the drawer.
This is a destructive change so we need to confirm they definitely want to do this.
G
D
P
R
The `optIntoFollowing` input determines whether user has checked the switch on or off. The `optOutOfFollowing` input determines whether user has confirmed turning Following off.
When `optIntoFollowing` is `true`, we just turn Following on.
When `optIntoFollowing` is `false`, we show the confirmation dialog. This dialog is not cancelable, I ~~expect~~ demand, they make a choice!
When `optOutOfFollowing` is `true`, that's a confirmation, we turn Following off.
When `optOutOfFollowing` is `false`, we change …
> Toggling following in settings

- Makefile
- app/build.gradle
- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
TLS 1.0 and 1.1 is no longer supported on our image host starting 5/18/18.  https://blog.imgix.com/2018/05/18/tls-deprecation.html
Android versions 19 and below don't have TLS 1.2 enabled by default :neutral_face: So videos and images are currently broken for all users on 19 and below 😢 
This change uses Google Play Services to patch Android's security provider, it's lit 👏 
Shout out to this StackOverflow answer: https://stackoverflow.com/questions/29916962/javax-net-ssl-sslhandshakeexception-javax-net-ssl-sslprotocolexception-ssl-han/36892715#36892715
I'm removing the work Lisa did to enable TLS on 19 > devices because it was only on Retrofit, we have external dependencies that make network calls including Picasso (I think uses Okhttp) and ExoPlayer. This needs to be a global change.
> fixing broken videos and images on 19 and below

- app/src/main/assets/json/server-config.json
- app/src/main/java/com/kickstarter/models/User.java
- app/src/main/java/com/kickstarter/services/ApiClient.java
- app/src/main/java/com/kickstarter/services/apirequests/SettingsBody.java
- app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.java
- app/src/main/java/com/kickstarter/viewmodels/SettingsViewModel.java
- app/src/main/res/layout/settings_layout.xml
- app/src/main/res/values-de/strings_i18n.xml
- app/src/main/res/values-es/strings_i18n.xml
- app/src/main/res/values-fr/strings_i18n.xml
- app/src/main/res/values-ja/strings_i18n.xml
- app/src/main/res/values/strings_i18n.xml
- app/src/test/java/com/kickstarter/viewmodels/SettingsViewModelTest.java
- Due to GDPR we needed to add the ability for users to make their profile private from the mobile app.
- Refactored the `settings_layout.xml` to bring parody to the iOS settings screen.
- Added methods to `SettingsActivity`, `SettingsViewModel`, `User`, `ApiClient`, and `SettingsBody`.
> RC- [Feature] - Privacy Policy Toggle and Info Dialog

- app/src/main/res/layout-land/login_tout_layout.xml
- app/src/main/res/layout/facebook_confirmation_layout.xml
- app/src/main/res/layout/login_tout_layout.xml
Facebook copy has been updated.
The disclaimer was removed from the Facebook confirmation screen and updated copy was added under the facebook button of the login tout screen. I adjusted some margin so all the copy fits vertically on smaller devices.
Refactored the layouts for ✨ 
ya tu sabe....GDPR
cc @nnekab
> Updated Facebook copy

- lib/milkrun/build.rb
Apparently~, the output folders for releases changed. This update fixes that so milkrun can successfully find the built apk.
> Updating milkrun

- app/build.gradle
- build.gradle
I couldn't run my tests because the imports didn't resolve. So I moved the Fabric imports to `app/build.gradle`.
The `Fabric` and `Crashlytic` imports weren't resolving.
[Per the docs](https://fabric.io/kits/android/crashlytics/install)
They also recommend using the latest version number and not `+` so I changed that too.
> Fixing broken `Crashlytics` and `Fabric` imports

- app/src/main/java/com/kickstarter/services/KSUri.java
- app/src/main/java/com/kickstarter/viewmodels/DeepLinkViewModel.java
- app/src/test/java/com/kickstarter/services/KSUriTest.java
- app/src/test/java/com/kickstarter/viewmodels/DeepLinkViewModelTest.java
No longer showing a blank project page when a user navigates to a project preview. Instead, taking the user to their external browser.
Checking if the URL looks like a project but contains the param `token` 🦆 
WITH TESTS
cc @roblum @willmanduffy thanks for your help!
> No longer consuming project preview links

- .circleci/config.yml
- Makefile
- app/build.gradle
- fastlane/Fastfile
@Rcureton and I did a fire collabo on this!
I added some helper methods in our Makefile: `sync_oss_to_private` and `sync_private_to_oss` to keep the heads up to date.
The `update_strings` lane in the Fastfile, pulls down the latest config and strings and pushes to the current branch.
The version codes are now automatically incremented in `build.gradle`.
**Android CI process:**
We now have a workflow called `build_and_test` that includes 4 jobs: `build`, `test`, `create_alpha` and `alpha`.
`build`- makes sure the app can still build. Its main task is running `assembleExternalPre21Release`.
`test`- runs lint, checkstyle and unit tests. It's main tasks are: `checkstyle`, `lintExternalPre21Release` and `testExternalPre21Release`. Its dependent on the `build` job passing.
`create_alpha`- runs …
> Android automatic alpha builds

- app/src/main/java/com/kickstarter/ui/activities/PrivacyActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/PrivacyViewModel.kt
- app/src/main/res/layout/activity_privacy.xml
- app/src/test/java/com/kickstarter/viewmodels/PrivacyViewModelTest.kt
- Added logic to hide privacy rows when the user is a creator.
- Added ViewModelTest functions to test if the privacy row is hidden.
- Creators can't have private profiles.
> [Enhancement] - Removed privacy feature for creators

- app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
- app/src/main/java/com/kickstarter/ui/adapters/DiscoveryPagerAdapter.java
- app/src/main/java/com/kickstarter/ui/fragments/DiscoveryFragment.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
Smooth scrolling to the top of the Disco fragment when a tab is reselected.
Added a `TabSelectedListener` to the `TabLayout` and  `onTabReselected`, letting the `DiscoveryPagerAdapter` know the current fragment needs to scroll to the top.
> ENHANCE ✨Smooth scrolling to the top of the disco fragment when reselecting a tab.

- app/build.gradle
- app/src/main/graphql/userprivacy.graphql
- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/libs/graphql/EmailAdapter.kt
- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/services/ApolloClientType.kt
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/ui/activities/TestApolloActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/TestApolloViewModel.kt
- app/src/main/res/layout/activity_test_apollo.xml
Added a POC for custom scalars.
Added adapter for Email custom scalar.
In the `TestApolloActivity`, logged in users can now update their email addresses.
Added `Email`, defined as a `java.lang.String` to `customTypeMapping` in `build.gradle`.
Added adapter for encoding and decoding `Email` in `EmailAdapter`. Should we do some validation here? It happens server side.
Added mutation for `UpdateUserEmail` that takes in `email` and `current_password`.
Updated `TestApolloActivity` to actually make this call.
Shouts to @orionmcc for support!
> [POC] Mutations? ✅ Custom scalar support? ✅

- app/src/main/res/layout/search_toolbar.xml
Updating search query length to 60 chars per front end.
Made the search EditText height conform to minimum accessible touch target size of `48dp`.
Made the search EditText take up the width between back button and clear icon.
@mcstew pointed out the 25 char limit. it's downright restrictive!
> ENHANCE 📈Updating search query length to 60 chars per front end.

- app/src/main/res/layout/discovery_drawer_logged_in_view.xml
- app/src/main/res/layout/discovery_layout.xml
Finally had time to address https://github.com/kickstarter/android-oss/issues/230 🤓 Now the drawer won't get cut off for devices with cutouts.
It was actually pretty straight-forward (as straight-forward as Android can be 😛)
The default value of `fitsSystemWindows` is `true` so we don't need it in the `DrawerLayout` but for `NavigationView` we do, so it draws below the status bar.
There's an option in Developer Settings to simulate a cutout. That's how I tested this out!
> [bug] Fixing the drawer getting cut off and reformatting.

- app/src/main/res/layout/discovery_drawer_logged_out_view.xml
- app/src/main/res/values-v21/dimens.xml
- app/src/main/res/values/dimens.xml
Finishing what I started in #347:
Removing margin top from drawer logged out view and deleting unused dimensions.
> [bug] Fixing the drawer getting cut off and reformatting pt 2

- lib/milkrun/server_config_refresher.rb
Per the wiki, we can update strings locally by running `bin/milkrun update-strings --local`.
But we haven't updated the endpoint since it changed.
> Local endpoint for updating strings.

- app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
The `clearPages` output `Emits a list of pages that should be cleared of all their content.` which translates to all of the pages but the current one. Since we got rid of the last sort, our indices went from [0,1,2,3,4] to [0,1,2,3]. Doing `this.vm.inputs.discoveryPagerAdapterSetPrimaryPage(null, 4)` is an illegal condition since position 4 doesn't exist and it will never get "cleared" because it doesn't actually exist.
> Fixes DiscoveryViewModelTest.testClearingPages

- app/src/main/java/com/kickstarter/libs/utils/DiscoveryUtils.java
- app/src/main/java/com/kickstarter/services/DiscoveryParams.java
- app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
- app/src/main/res/layout/discovery_layout.xml
- app/src/test/java/com/kickstarter/services/DiscoveryParamsTest.java
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
- Removed the most funded from sort options.
- Design sign off from @dannyalright
> [Enhancement] - removed most funded and fixed the tabs style

- app/src/main/assets/json/server-config.json
- app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/ChangePasswordViewModel.kt
- app/src/main/res/drawable/icon__check_gray.xml
- app/src/main/res/drawable/save.xml
- app/src/main/res/values-de/strings_i18n.xml
- app/src/main/res/values-es/strings_i18n.xml
- app/src/main/res/values-fr/strings_i18n.xml
- app/src/main/res/values-ja/strings_i18n.xml
- app/src/main/res/values/strings_i18n.xml
- app/src/test/java/com/kickstarter/viewmodels/ChangePasswordViewModelTest.kt
Updated strings for change password warning copy.
Fixed bug where confirm and new password were swapped.
Fixed save disabled icon color.
Changed logic for showing warning.
Updated tests.
> Change password warning copy

- app/src/main/res/layout/settings_layout.xml
Hiding the "Edit Profile" row.
Adding a `@null` content description for the profile image. We should never be ignoring these.
> 🔜 Hiding profile row in preparation for 1.10.0 release

- app/src/main/res/layout/discovery_layout.xml
- app/src/main/res/layout/discovery_toolbar.xml
Quick returning the entire Discovery CollapsingToolbarLayout on scroll and stubbornly bringing back the elevation.
Removing the divider line with AlphaBehavior because it's no longer visually relevant when the Appbar is collapsed.
> [Enhance] Quick return Discovery CollapsingToolbarLayout

- app/src/main/java/com/kickstarter/ui/activities/PaymentMethodsSettingsActivity.kt
- app/src/main/java/com/kickstarter/ui/adapters/KSListAdapter.kt
- app/src/main/java/com/kickstarter/ui/adapters/PaymentMethodsAdapter.kt
- app/src/main/java/com/kickstarter/viewmodels/PaymentMethodsViewModel.kt
-Leveraged the new `ListAdapter` class that handles list changes more responsibly 😛 
-When a user adds or deletes a card, we now get these awesome animations for free.
Shoutout to @CDRussell for a great blog post about it: https://medium.com/@trionkidnapper/recyclerview-more-animations-with-less-code-using-support-library-listadapter-62e65126acdb
-I didn't want to change `KSAdapter` because 16 classes extend it and that's not what this feature is about. Maybe for an Investment Day™, I could refactor all of them.
-So! I made a new class called `KSListAdapter` that extends `ListAdapter`. It still can handle sections and uses our existing `KSViewHolder` pattern ٩( ᐛ )و
> [(∩｀-´)⊃━☆ﾟ.*･｡ﾟ] Payment methods recycler animations

- app/src/main/res/layout/discovery_layout.xml
- fixed bug in discovery layout by wrapping the toolbar and tabs in a linear layout
- The toolbar wasn't responding to clicks due to the `CollapsingToolbarLayout` not having one direct child.
- Galaxy S7 (Aaliyah 7.0)
- Galaxy S3 (Enya 4.4.2)
- HTC One (Cher 4.4.2)
> [Bug Fix] - fixed bug in discovery layout Toolbar

- app/src/main/java/com/kickstarter/ui/activities/PaymentMethodsSettingsActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/PaymentMethodsViewModel.kt
- app/src/main/res/layout/activity_settings_payment_methods.xml
- app/src/test/java/com/kickstarter/viewmodels/PaymentMethodsViewModelTest.kt
I noticed in @dannyalright's [designs](https://app.goabstract.com/projects/ff85f7f0-23b6-11e8-9c12-3d345000cd85/branches/master/commits/efe3a35bdf1ea1c406cd89069504b6686da04da5/files/DD4807BD-4D34-43F3-853E-4765774306D1/layers/0EBFCADE-A8F6-4C2C-8910-2FEDDB76810B?mode=build&selected=4278085803-8C454A8A-61FB-4846-A935-201E6DA09C78) there's a really cute divider on the payment methods screen.
Also fixed the height of the button.
With tests 👾
> [✨] Payment methods divider

- app/src/main/graphql/userprivacy.graphql
- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/ui/activities/AccountActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/AccountViewModel.kt
- app/src/main/res/layout/activity_account.xml
- app/src/test/java/com/kickstarter/viewmodels/AccountViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ChangeEmailViewModelTest.kt
This is another fire collabo between @Rcureton and I.
Users who have logged in with Facebook™ don't have a password. The change email and change password features require a current password. This PR hides those rows from users who don't have a password.
When `user.hasPassword` is false, hide the change email and change password rows.
> [👩🏾‍💻👨🏿‍💻] Hiding change password and change email

- app/src/main/res/layout/activity_account.xml
- Fixed the Spinner layout dimens to final specs with @dannyalright. 
- Removed `marginTop` from the spinner and gave it `marginBottom`.
[Settings Currency UI slightly off from designs](https://trello.com/c/YzUczdZy/1107-settings-currency-ui-slightly-off-from-designs)
> [UI-Fix] - Settings Currency UI slightly off from designs

- app/src/main/res/layout/settings_layout.xml
- Fixed the `Rate us` container dimens to final specs with @dannyalright. 
- gave it `grid_12` `marginBottom`.
[Settings bottom padding missing](https://trello.com/c/BpDfHKNH/1110-settings-bottom-padding-missing)
> [UI-Fix] - Settings bottom padding missing

- app/src/internal/res/layout/internal_tools_button_view.xml
- app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.kt
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectNotificationViewHolder.java
- app/src/main/res/layout/activity_account.xml
- app/src/main/res/layout/activity_newsletter.xml
- app/src/main/res/layout/activity_privacy.xml
- app/src/main/res/layout/project_notification_settings_layout.xml
- app/src/main/res/layout/project_notification_view.xml
- app/src/main/res/values/styles.xml
**Touch target size:**
-Drawer buttons
**Fixed large text cut off:**
-Privacy rows
-Newsletters rows
**Voice over:**
-Added accessibility label for the undeliverable warning icon
-Added copy for version
**UX:**
Project notifications - (Went off the rails because Danny is busy 😅)removed divider, allowed multiline text and fixed bug with delayed switches.
Before vs After
|￣￣￣￣￣￣ |
|&nbsp;   &nbsp;   say NO to&nbsp;   &nbsp;  |
|&nbsp;&nbsp;  hardcoded&nbsp;&nbsp;  |
|&nbsp;   &nbsp;  &nbsp;   heights&nbsp;   &nbsp;  &nbsp;   |
| ＿＿＿＿＿__|
(\ __/) ||
(•ㅅ•) ||
/ 　 づ
Hardcoding a height causes text to be cut off
> Settings a11y

- app/src/main/java/com/kickstarter/viewmodels/AccountViewModel.kt
I was testing this [PR](https://github.com/kickstarter/kickstarter/pull/13556#pullrequestreview-182861708) and got my user in a weird state where the chosen currency was returned as null. This causes a crash.
Filtering the result of `UpdateUserCurrency` mutation because the value it returns is optional.
> [bug?] Filtering null currencies because it causes a crash on Account screen.

- app/src/main/java/com/kickstarter/libs/utils/ProjectUtils.java
- app/src/main/java/com/kickstarter/ui/adapters/ThanksAdapter.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
- app/src/test/java/com/kickstarter/libs/utils/ProjectUtilsTest.java
Showing categories on thanks page.
Moved `combineProjectsAndParams` to `ProjectUtils` because it is now used in 2 places: Discovery and Thanks.
Added a test.
Very Popular™ non-fatal that I missed because I usually look at crashes here: https://fabric.io/kickstarter2/android/apps/com.kickstarter.kickstarter/issues/5c00af84f8b88c2963f42498?time=last-seven-days
> Showing categories on thanks page

- app/src/main/java/com/kickstarter/extensions/SnackbarExt.kt
- app/src/main/res/drawable/bg_snackbar_confirmation.xml
- app/src/main/res/drawable/bg_snackbar_error.xml
- app/src/main/res/drawable/bg_snackbar_heads_up.xml
- app/src/main/res/drawable/bg_snackbar_network_error.xml
Removing rounded corners and margin from Snackbars because they were all forced to the bottom in API 28.
[Update Snackbar Styles](https://trello.com/c/ZgWvg0ok/1151-update-snackbar-styles)
> [UI] Snackbar style update

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kickstarter/ui/activities/VideoActivity.java
- app/src/main/res/values/styles.xml
- fastlane/report.xml
- So with the adoption of `Android 8` we can't change the orientation for an `Activity` that has a translucent background according to several [stackoverflow](https://stackoverflow.com/a/50832408) posts. The crash was occurring in the `VideoActivity` where the screen changes from `portrait` to `landscape` and since our overall theme had the `<item name="android:windowIsTranslucent">true</item>` it was crashing on Samsung devices and some other devices running `Android 8`. So to fix this issue I removed the `<item name="android:windowIsTranslucent">true</item>` from the main parent theme and created a style for the activities in `Settings` where we're using this attribute to remove the black background during activity transitions. 
- `ChangePassword`,`ChangeEmail`, `Notifications`, …
> [Bug Fix] - Android 8 + Samsung orientation theme fix

- .circleci/config.yml
We're targeting API 28, our Docker image needs those libraries.
> [⚙️] Docker image update for CI

- app/src/main/java/com/kickstarter/libs/KoalaTrackingClient.java
- app/src/test/java/com/kickstarter/KSRobolectricTestCase.java
- app/src/test/java/com/kickstarter/ShadowAndroidXMultiDex.kt
- app/src/test/java/com/kickstarter/libs/KoalaTest.kt
- app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
Sending koala timestamp in seconds vs millis. Updated tests. Changed Roboloectric MultiDex shadows to support AndroidX.
The Android app is currently in the future and we need to bring it back to the present. Our timestamps are expected in seconds vs millis.
Nothing to see here!
Thank you @abelsonlive for helping me out and knowing where to look 💡
> [🐛] Koala timestamps

- lib/milkrun/i18n_string_resources.rb
Like the title - we only want to download localizations for the locales that we currently support in the app.
When new languages are supported on the web these locales are automatically returned in the config. We don't yet want to have these strings downloaded locally until we know we're supporting them in the app so this just allows us to filter based on what we know we support.
Thanks @pcreux for the Ruby tips.
https://trello.com/c/WqK6zXfF/655-filter-for-supported-languages
> Ensure that only supported locales are downloaded from the config

- app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
Another one bites the dust!
`Transformers.pipeErrorsTo` is deprecated. Instead, we should use `Observable.materialize` and handle the error state and the values state.
Removing pipeErrorsTo from LoginViewModel and refactoring.
Log in screen successfully:
> [🚮] Removing deprecated calls to pipeErrorsTo in Log In

- app/src/main/java/com/kickstarter/viewmodels/ResetPasswordViewModel.kt
`Transformers.pipeErrorsTo` is deprecated. Instead, we should use `Observable.materialize` and handle the error state and the values state.
Removed deprecated call and changed file spacing for 2 to 4.
Reset password screen successfully:
> [🚮] Removing deprecated calls to pipeErrorsTo in Reset Password

- app/src/main/java/com/kickstarter/ui/activities/NotificationsActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/NotificationsViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/NotificationsViewModelTest.kt
`Transformers.pipeErrorsTo` is deprecated. Instead, we should use `Observable.materialize` and handle the error state and the values state.
Removing `pipeErrorsTo` from `NotificationsViewModel`. Also displaying when there's an error (added a test). Cleaning up huge `onCreate` in `NotificationsActivity`.
Notification screen successfully:
> [🚮] Removing deprecated calls to pipeErrorsTo in Notifications

- app/src/main/assets/json/server-config.json
- app/src/main/java/com/kickstarter/models/User.java
- app/src/main/java/com/kickstarter/services/ApiClient.java
- app/src/main/java/com/kickstarter/services/apirequests/SettingsBody.java
- app/src/main/java/com/kickstarter/ui/activities/NotificationsActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/NotificationsViewModel.kt
- app/src/main/res/layout/activity_notifications.xml
- app/src/main/res/values-de/strings_i18n.xml
- app/src/main/res/values-es/strings_i18n.xml
- app/src/main/res/values-fr/strings_i18n.xml
- app/src/main/res/values-ja/strings_i18n.xml
- app/src/main/res/values/strings_i18n.xml
- app/src/test/java/com/kickstarter/viewmodels/NotificationsViewModelTest.kt
- Updated the `NotificationsActivity` to use the new strings for the creators digest.
- Removed the `mail_icon` and `notifyOfPostLikes` email from the `SettingsBody` and `User` models
- Updated strings from `milkrun`
[Pledge Activity Digest](https://trello.com/c/L2keALkt/1166-pledge-activity-digest)
> [Enhancement] - Pledge Activity Digest

- app/src/main/java/com/kickstarter/ui/toolbars/KSToolbar.java
In the first pass https://github.com/kickstarter/android-oss/pull/334, I made the toolbar the accent color when we were not hitting prod.
In the second pass https://github.com/kickstarter/android-oss/pull/344, I made the toolbar `ksr_dark_grey_400` because you couldn't see buttons that also were the accent color. 
In this third (and hopefully final) pass, I'm showing a cobalt stripe on toolbar when we're not hitting prod.
It's super helpful for us to know when we're not hitting the production server but it's visually distracting to change the whole toolbar's background. This is a good compromise.
> Staging toolbar part 2

- app/src/main/java/com/kickstarter/libs/rx/transformers/Transformers.java
- app/src/main/java/com/kickstarter/ui/activities/ProjectNotificationSettingsActivity.java
- app/src/main/java/com/kickstarter/viewmodels/ProjectNotificationSettingsViewModel.java
- app/src/test/java/com/kickstarter/libs/rx/transformers/NeverErrorTransformerTest.java
- app/src/test/java/com/kickstarter/viewmodels/ProjectNotificationSettingsViewModelTest.kt
`pipeErrorsTo` has been deprecated since April 2016 with no helpful explanation why.
This is the final PR to wrap up the official deprecation of `pipeErrorsTo` (#445, #447, #448, #449, #450)     
`ProjectNotificationSettingsViewModel` did not have any tests so I added some 👍 
Showing a `Snackbar` when there is an error instead of a `Toast`.
[Trello](https://trello.com/c/s2jv9eth/189-removing-deprecated-transformerspipeerrorsto-calls)
> Removing pipeErrorsTo

- app/src/main/java/com/kickstarter/ui/viewholders/PaymentMethodsViewHolder.kt
- app/src/main/res/layout/activity_account.xml
- app/src/main/res/layout/item_payment_method.xml
Making payment methods visible, typo fix and pushing delete icon in card row to the end of the layout.
Visually confirm the same start and end padding for card rows.
[Trello](https://trello.com/c/xHWVc2aY/1178-settings-v3-sweep)
> Payment methods padding

- app/src/main/java/com/kickstarter/ui/activities/NotificationsActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/NotificationsViewModel.kt
- Paired with @eoji on fixing the delay in the `NotificationsActivity` it was due the emissions of the `userInput` and `userOutput` being in separate observables. 
> Upon deselecting 'Project activity' if I have 'Daily summary' as my chosen value, the spinner will first change from 'Daily summary' to 'Twice a day summary', then close. If I re-enable 'Project activity', it will start from 'Twice a day summary'.
- It should now just collapse the spinner without changing the values.
> [Bug] fixed the delay in the pledge activity digest spinner

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kickstarter/ui/activities/AccountActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ChangeEmailActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/CreatePasswordActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
- app/src/main/java/com/kickstarter/ui/activities/EditProfileActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/HelpSettingsActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/NewsletterActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/NotificationsActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/PaymentMethodsSettingsActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/PrivacyActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ProjectNotificationSettingsActivity.java
- app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.kt
- app/src/main/res/values/styles.xml
Created standard style `SettingsActivity` for settings transitions  so we don't need to override `exitTransition` everywhere.
Removed Discovery -> Settings transition.
[Trello](https://trello.com/c/xHWVc2aY/1178-settings-v3-sweep)
**From Discovery** 
**Top Level Settings**
**Account & Payment methods**
(change email is omitted from gif on purpose)
**Notifications**
> Settings transitions

- app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
I was going to open another PR but then I noticed, if you're logged in, looking at a category in Discovery and you leave that screen, Discovery shows the default params (recommended if you’re opted in or all projects). This PR fixes the bug that causes Discovery to show default params every time `currentUser` emits. We really only care if the user changes (shoutout to my friend `changedUser` https://github.com/kickstarter/android-oss/pull/224). 
In Discovery, view a category or top filter that's not your default. Trigger a user refresh; you can open up settings or open up a different app. When you return, you should see the category/top filter you previously chose.
> Discovery user refresh bug 🐜

- app/src/main/java/com/kickstarter/ui/toolbars/DiscoveryToolbar.java
- app/src/main/res/drawable/ic_menu.xml
- app/src/main/res/layout/discovery_toolbar.xml
- rounded menu icon with content description 
- updated title click indicator to match the buttons 
Turn on TalkBack, and select the menu icon, it should say "User menu button -- double tap to activate"
[Trello](https://trello.com/c/WKp0lN4a/374-add-accessibility-labels-on-nav-bar-icons)
> Discovery Toolbar content description

- app/src/internal/java/com/kickstarter/ui/activities/InternalToolsActivity.java
- app/src/internal/res/layout/internal_tools_layout.xml
- app/src/main/java/com/kickstarter/libs/utils/Secrets.java.example
- Due to the Trello board being full and unmonitored also a HackerOne issue which was flagged to @peat , we agreed to remove this functionality since it isn't used frequently.
- Removed the submit feedback button along with the logic to send the email
[Bug Trello Account Strings in Android](https://trello.com/c/wyVZaZqN/1228-bug-trello-account-strings-in-android)
> [Bug]- Removed Trello Email for Internal Tools

- app/src/main/res/layout/discovery_drawer_logged_in_view.xml
- changed the container attribute from background to foreground so the ripple stays within the view.
- Log into the app `->` open the drawer `->` long press the profile row.
[Ripple of profile section in logged in drawer layout goes outside of the bounds of the view.](https://trello.com/c/yYvRnJsn/1256-ripple-of-profile-section-in-logged-in-drawer-layout-goes-outside-of-the-bounds-of-the-view)
> [UI Fix] - Ripple of profile section in logged in drawer layout goes outside of the bounds of the view.

- app/src/main/res/layout/checkout_layout.xml
In this huge PR #427, I added TWO (?!?!) `WalletFragment`s.
I got rid of the second one 🙏 
I inspected the layout 😭 
I initially thought it was in the toolbar but really it was floating on top ༼ ༎ຶ ෴ ༎ຶ༽ We got around this with the first fragment by setting its height and width to `0dp`.
Try to pledge to a project! 
The screen should no longer show that ghost button.
[Trello Story](https://trello.com/c/RLNU1cIC/202-buy-with-android-pay)
(These are Stripe test cards)
> Fixing bug with android pay button

- app/src/main/java/com/kickstarter/services/DiscoveryParams.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
Fixing bug with default params not getting selected.
The activity shouldn't determine the sort, the DiscoveryFragment should.
Fixed it by updating `DiscoveryParams.getDefaultParams` to not set the sort.
Updated (more like reverted 😛) the tests.
<details><summary>Logged out user sees `All Projects` highlighted in the drawer on app open.</summary>
<p>
</p>
</details>
<details><summary>Logged in, opted out of recommendations user sees `All Projects` highlighted in the drawer on app open.</summary>
<p>
</p>
</details>
<details><summary>Logged in, opted in to recommendations user sees `Recommended for you` highlighted in the drawer on app open.</summary>
<p>
</p>
</details>
[Trello Story](https://trello.com/c/ZJZEaes2/1315-initial-drawer-params-are-not-selected-when-the-app-is-first-opened)
I …
> [🐞] Default drawer params bug

- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/ui/viewholders/HorizontalRewardViewHolder.kt
- app/src/main/java/com/kickstarter/ui/views/BottomCropImageView.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/res/layout/fragment_pledge.xml
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Showing actual mini reward in `PledgeFragment` with tests.
`BottomCropImageView` now prioritizes scale of the width.
With the `Horizontal rewards` (to be renamed) internal flag enabled, select a reward.
[Trello Story](https://trello.com/c/TP3fSgRb/1344-open-pledgefragment-when-reward-is-clicked)
> Reward animation

- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/main/res/layout/project_layout.xml
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
I noticed an unsightly bug when the keyboard is dismissed while the `RewardsFragment` is up caused by the evil and deceptive `ConstraintLayout`. For example, this can happen when you quick reply to a notification.
Confirm the `RewardsFragment` reward cards are always full height.
issa bug i found
| --- | --- |
| ![bug](https://user-images.githubusercontent.com/1289295/56834952-e58e1380-6840-11e9-86c3-7fa1d985d921.gif) | ![fix](https://user-images.githubusercontent.com/1289295/56834953-e58e1380-6840-11e9-8018-e0fa715de8d7.gif) |
> [🐞] Fixes bug with rewards container getting resized 

- app/src/main/java/com/kickstarter/libs/RecyclerViewPaginator.java
Ignoring all `RecyclerView` scroll events when `Secrets.IS_OSS` is `true` because there's no pagination because it doesn't actually hit the server.
Build the OSS app without the secrets.
Run it and scroll to the bottom of Discovery.
Figured it out when this issue was opened #521 
Thanks @sbenitez10!
> [🐜] OSS pagination bug

- app/src/main/res/drawable/white_gradient_background.xml
- app/src/main/res/layout/item_reward.xml
- Added a fade effect on the bottom of long Reward Cards.
https://trello.com/c/Z1jiiSsK/1355-add-fade-out-effect-to-the-bottom-scrollable-reward-items
| Before | After |
| --- | --- | 
| <img src="https://user-images.githubusercontent.com/3709676/57088758-f6230b80-6cd0-11e9-95f1-fe9736bf1a8a.png" > | <img src="https://user-images.githubusercontent.com/3709676/57088792-03d89100-6cd1-11e9-8762-17759a31a24f.png"> |
> Reward bottom gradient

- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/res/drawable/ic_expand.xml
- app/src/main/res/layout/fragment_pledge.xml
Showing the little expand icon on the top right of the mini reward.
Added a click listener at the request of @nnekab and @Rcureton. The icon is 24 x 24, which is too small for a tappable container so I put it in a `FrameLayout` that's the proper size.
[Trello Story](https://trello.com/c/kpcmzWpD/1364-add-expand-icon-to-min-reward-after-transition-animation)
> Expand icon

- app/src/main/java/com/kickstarter/libs/utils/ViewUtils.java
- app/src/main/java/com/kickstarter/mock/factories/RewardFactory.java
- app/src/main/java/com/kickstarter/ui/adapters/HorizontalRewardsAdapter.kt
- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/ui/viewholders/HorizontalNoRewardViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/HorizontalRewardViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/HorizontalNoRewardViewHolderViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/HorizontalRewardViewHolderViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/res/layout/fragment_pledge.xml
- app/src/main/res/layout/item_no_reward.xml
- app/src/test/java/com/kickstarter/viewmodels/HorizontalNoRewardViewHolderViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Selecting a no reward reward takes user to `PledgeFragment`.
Delivery info is hidden.
Tests.
Back a project with no reward and verify the Pledge screen is shown and the estimated delivery is gone.
We discussed but where's the card? I don't know 👀
> No reward -> PledgeFragment

- app/src/main/res/drawable/button_reward_pledge.xml
- app/src/main/res/values/colors.xml
- Fixed the opacity for the reward disabled state.
> fixed the opacity in the disabled reward state

- app/src/main/java/com/kickstarter/libs/KSCurrency.java
- app/src/main/java/com/kickstarter/libs/utils/StringUtils.java
- app/src/main/java/com/kickstarter/libs/utils/ViewUtils.java
- app/src/main/java/com/kickstarter/mock/factories/ShippingRuleFactory.kt
- app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardHeaderViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardReferrerBreakdownViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardReferrerStatsRowViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardRewardStatsRowViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectStateChangedPositiveViewHolder.java
- app/src/main/java/com/kickstarter/viewmodels/BackingViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/HorizontalRewardViewHolderViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectHolderViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/RewardViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/ShippingRuleViewHolderViewModel.kt
- app/src/test/java/com/kickstarter/KSCurrencyTest.java
- app/src/test/java/com/kickstarter/libs/rx/operators/ApiErrorOperatorTest.java
- app/src/test/java/com/kickstarter/libs/utils/StringUtilsTest.java
- app/src/test/java/com/kickstarter/viewmodels/HorizontalRewardViewHolderViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/ShippingRuleViewHolderViewModelTest.kt
My fourth and hopefully final refactor of `KSCurrency`.
- Added `KSCurrency.currencyNeedsCode` to determine if a country's currency requires the country code and KSCurrency.getCurrencySymbol to return currency symbols for a country. These are helper methods to do the spanned currencies. Currently only shown in the `PledgeFragment`.
- By default, we round `DOWN`, so I created `KSCurrency.format` that only takes in a value and project.
- If we're rounding `DOWN`, we floor the number, or else we just leave it as is.
- There shouldn't be any platform dependent code in unit tests so `KSCurrency` never returns a `SpannableString`.
- Updated `KSCurrencyTest` to show how rounding works and added tests for `formatWithUserPreference` with new precision option.
- Added `StringUtils.trim` to remove …
> [🔢] Currency refactor 2

- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/res/layout/fragment_pledge.xml
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
- Hides Delivery Info with rewards has no shipping rules.
- Hides Shipping Rules section when user selects `No Reward`.
- Fixes a bug that didn't hide the `+` icon of the shipping amount when shipping rules were being loaded.
[Hide Delivery Info if no shipping rules](https://trello.com/c/d96vOW9E/1398-hide-delivery-info-when-user-selects-reward-with-no-shipping-rules)
| No Reward | No Shipping Rules |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/3709676/59118513-60594c80-891e-11e9-91b7-a72eea64d194.png"> | <img src="https://user-images.githubusercontent.com/3709676/59118541-71a25900-891e-11e9-919d-5d0021c29e74.png">
| Shipping Rules |
| <img src="https://user-images.githubusercontent.com/3709676/59118571-7f57de80-891e-11e9-9fd3-98c4b6aba00d.png"> |
> No reward shipping rules hidden

- app/src/main/java/com/kickstarter/libs/utils/IntegerUtils.java
- app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/LoggedInViewHolder.kt
- app/src/test/java/com/kickstarter/libs/utils/IntegerUtilsTest.java
- Fixed a crash that happens at app start when I'm logged in with a mocked user account. 
The `unreadMessagesCount` and `unseenActivityCount` are null because of how the mock user object is created with minimum fields. Since they are nullable fields anyway, I made the caller code perform null-check.
1. Log in with a mock account with the `IS_OSS` build.
2. Close the app and reopen.
3. Crashes as soon as the app launches.
> Fix NPE at app start with mock users

- app/src/main/java/com/kickstarter/libs/utils/ViewUtils.java
- app/src/main/java/com/kickstarter/ui/viewholders/HorizontalRewardViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/HorizontalRewardViewHolderViewModel.kt
- app/src/main/res/layout/item_reward.xml
- app/src/test/java/com/kickstarter/viewmodels/HorizontalRewardViewHolderViewModelTest.kt
Rewards should only show the minimum amount with the mini currency code if it requires the country code.
- Added `ViewUtils.styleCurrency` that takes in a boolean to determine the style of shrunken currency code. 
-  If we're just not centering it, we shrink the currency code to 70% (currency code is `17sp`  and the amount is `24sp`).
- Added `minimumAmountTitle` output for styled reward minimum.
- Added separate output for showing the unavailable button `limitReachedButtonTextIsVisible`.
- `HorizontalRewardViewHolderViewModel` is written in Kotlin so it can make use of the implicit parameter `it`.
- Tests.
| Currency with country code | Currency without|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/1289295/59227518-880d1680-8ba3-11e9-9247-93d885c27dd4.png" …
> Reward minimum span

- app/src/main/graphql/checkout.graphql
- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/libs/utils/ViewUtils.java
- app/src/main/java/com/kickstarter/mock/factories/RewardFactory.java
- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/models/Reward.java
- app/src/main/java/com/kickstarter/services/ApolloClientType.kt
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/ui/adapters/RewardCardAdapter.kt
- app/src/main/java/com/kickstarter/ui/data/CardState.kt
- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/ui/viewholders/RewardLoadingCardViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/RewardPledgeCardViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/BaseRewardCardViewHolderViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardLoadingCardViewHolderViewModel.kt
- app/src/main/res/layout/fragment_pledge.xml
- app/src/main/res/layout/item_reward_loading_card.xml
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardCardViewHolderViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardLoadingCardViewHolderViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardPledgeCardViewHolderViewModelTest.kt
Pledging with a `StoredCard`:
- Added mutation for `nativeCheckout`. 
- It's kind of funky because `projectId` and `rewardId` are relay IDs while `locationId` and `paymentSourceId` are just strings.
- It returns `Checkout.State` and I consider the call to have been successful if `state == VERIFYING`.
- We needed a 5th loading state `RewardLoadingCardViewHolder` for the stored cards in the `PledgeFragment.` Instead of `showPledgeCard` returning `Pair<Int, Boolean>`, I created an enum `CardState` and that has 3 values: `SELECT`, `PLEDGE`, `LOADING`. 
- So the normal state is `SELECT`. If a user clicks `"Select"`, its new state will be `PLEDGE` and when they click `"Pledge"`, it'll be `LOADING`. If the pledge call is successful, the state doesn't really matter because we're going to destroy …
> Literally native checkout 🙃

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kickstarter/KSApplication.java
- app/src/main/java/com/kickstarter/libs/utils/ApplicationLifecycleUtil.java
- app/src/main/java/com/kickstarter/libs/utils/TransitionUtils.java
- app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.java
- app/src/main/java/com/kickstarter/ui/fragments/DiscoveryFragment.java
- app/src/main/java/com/kickstarter/viewmodels/LoginToutViewModel.java
- app/src/main/res/anim/fade_in.xml
- app/src/main/res/values/strings_config.xml
- app/src/test/java/com/kickstarter/TestKSApplication.java
- app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.java
- Updated Facebook SDK to the dynamic version, per their recommendation https://developers.facebook.com/docs/android/getting-started/
- `LoginToutViewModelTest` only had tests for clicking log in and sign up so I added 2 more for Facebook success and errors but the VM needs some refactoring and more tests.
- The `fade_out` animation used to take .5 seconds, that's a long time. It's now .2 seconds.
- Using fade in/out transition in `LoginToutActivity`.
- Log in or sign up with Facebook.
[Trello Story](https://trello.com/c/uGFzObNM/1406-update-facebook-sdk)
This is what users who have already logged in with Facebook and have the Facebook app installed see:
I don't love it but it's basically what we already have now.
> ⬆️Facebook SDK

- app/src/main/java/com/kickstarter/libs/utils/ProjectUtils.java
- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/main/res/color/button_manage_pledge.xml
- app/src/main/res/layout/project_layout.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/com/kickstarter/libs/utils/ProjectUtilsTest.java
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
- Shows the manage pledge container on the project page when user taps to see a `backed` and `live` project.
I go to profile and select a backed and live project:
```
You're a backer!
$5 • Snicky Snack 
```
```
You're a backer!
$5
```
[Manage my pledge (project state)](https://trello.com/c/ejojWhwB/1279-manage-my-pledge-project-state)
| With Reward | No Reward |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/3709676/59518897-b08f5c00-8e94-11e9-9537-e432e53ab5a4.png"> | <img src="https://user-images.githubusercontent.com/3709676/59518925-bc7b1e00-8e94-11e9-96b6-360c7d40fc72.png"> |
> Manage my pledge (project state)

- app/src/main/java/com/kickstarter/mock/factories/BackingFactory.java
- app/src/main/java/com/kickstarter/viewmodels/BackingViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/BackingViewModelTest.java
Loading view your pledge from reward and hiding mark as received from creators.
In #159, we added the ability for creators to view a backer's pledge but we open the `BackingActivity` from several places in the app:
1. Creator dashboard mailbox
2. Normal mailbox
3. Clicking the project action button on the project page
4. Clicking your pledged reward on the project page
So the screen was blank in scenario 4. This became more apparent when native checkout work started. The `BackingViewModel` will default to showing the backer as the current user if no backer is supplied.
Then in #234, we added a toggle for users to mark their rewards as received. But creators should not see this section when viewing a backer's pledge.  
Refactored the tests because they never tested for when a backer was …
> [🐞] View pledge bug

- app/src/main/AndroidManifest.xml
API 26 wanted `iconRound` and we weren't giving it. Now we are. 
Load this branch on a device or emulator running API 26.
None! Quick fix.
| --- | --- |
| ![Before](https://user-images.githubusercontent.com/3104761/60028785-f525af00-966d-11e9-88ab-1caf5445e7e5.png) | ![After](https://user-images.githubusercontent.com/3104761/60028893-256d4d80-966e-11e9-88a9-74fd114ab677.png) |
> Added round icon support

- app/src/main/java/com/kickstarter/libs/KSCurrency.java
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/KSCurrencyTest.java
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
- Changes the format of pledge amount on the `ProjectPage`
- We now show decimals if the pledge amount is not a whole number and the backing is `No Reward`.
- On the `KSCurrency` class, the `format(initialValue: project: excludeCurrencyCode: roundingMode:)` function was tweaked to only add roundingMode to the `numberOptions` variable if the roundingMode not `UNNECESSARY`.
- Some tests were included in order to insure the changes mentioned above didn't break anything.
[Manage Pledge - Pledge amount format](https://trello.com/c/Zrlmfb0t/1428-manage-pledge-pledge-amount-format
| No Reward - Number w/ decimals | No Reward - Whole Number | Reward |
| <img src="https://user-images.githubusercontent.com/3709676/59876534-e7241580-9371-11e9-87c6-76c2a84a77cc.png"> | <img …
> Added decimals for NoReward pledges on project page

- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/res/layout/fragment_pledge.xml
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Pledge screen UI and tests for managing currently pledged reward.
The first step in cancel pledge work.
- Reorganized `PledgeFragmentViewModel` with commented sections since it's getting Hectic ™
- Added 4 new outputs: `cancelPledgeButtonIsGone`, `changePaymentMethodButtonIsGone`, `totalContainerIsGone` and `updatePledgeButtonIsGone`.
- `Update pledge` and `Change payment method` buttons are disabled for now.
| After 🦋 |
| --- |
| <img src=https://user-images.githubusercontent.com/1289295/60631451-74815400-9dcd-11e9-972f-a944f58ef26d.png width=330/> | 
On a live project you've backed, open the rewards sheet and click `Manage your pledge`.
[Trello Story](https://trello.com/c/qY7q7T9B/1435-user-can-cancel-pledge)
> Manage your pledge, pledged reward UI

- app/src/main/java/com/kickstarter/libs/utils/RewardUtils.java
- app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
- app/src/main/java/com/kickstarter/mock/factories/RewardFactory.java
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/test/java/com/kickstarter/libs/utils/RewardUtilsTest.java
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Stepping by project country minimums and setting max based on country.
So we step by sensible amounts in countries with a lower exchange rate.
- By pulling the `country` from the project's currency.
| After 🦋 |
| --- |
| ![device-2019-07-03-205616 2019-07-03 20_56_57](https://user-images.githubusercontent.com/1289295/60632719-2d975c80-9dd5-11e9-9871-a9375fe04c67.gif) |
Try to back any project, the step amount should be the project's country's `minPledge` amount.
https://github.com/kickstarter/android-oss/blob/master/app/src/main/java/com/kickstarter/libs/models/Country.kt
[Trello Story](https://trello.com/c/p316VtXB/1444-stepping-by-min-pledge-amount)
> Proper stepping!

- app/src/main/java/com/kickstarter/libs/utils/ProjectViewUtils.kt
- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/main/res/layout/activity_project.xml
- app/src/main/res/layout/fragment_pledge.xml
- app/src/main/res/layout/fragment_rewards.xml
- app/src/test/java/com/kickstarter/libs/utils/ProjectViewUtilsTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Displaying the proper title in the toolbar of the Rewards sheet and fixed the bug with the background color of the toolbar.
So users have context about why they're in the rewards sheet. And to match the designs!
- Added `ProjectViewUtils. rewardsToolbarTitle` to determine what the title text should be and tests.
- Added `rewardsToolbarTitle` output to `ProjectViewModel` and tests.
- Added padding to the top of `RewardsFragment` and `PledgeFragment` so the transparent `rewards_toolbar` could inherit their respective background colors.
| Unbacked Live project | Backed Live Project |
| --- | --- |
| ![screenshot-2019-07-16_150551](https://user-images.githubusercontent.com/1289295/61327919-00d94100-a7e8-11e9-8039-968021735623.png) | ![screenshot-2019-07-16_150528](https://user-images.githubuse …
> Reward sheet titles

- app/build.gradle
Updating out of date dependencies that don't require refactoring.
It is ideal for dependencies to be up to date 🙂 These don't require any code changes. I have a list of dependencies that have breaking changes.
Updated out of date dependencies:
- Jetpack libraries
- Exoplayer
- Firebase
- Firebase messaging
- Jsoup
- Phoenix
- Play Services
- Material components
- Test libraries
Nothing to visually see. App should behave the same, IF NOT BETTER.
Regression testing.
👀
> Dependency sweep

- Gemfile.lock
Bumping `mini_magick` library to resolve security vulnerability.
TO BE SECURE
4.5.1 -> >= 4.9.4
> 🔒Updating mini_magick vulnerability

- app/src/main/res/color/button_pledge_live.xml
- app/src/main/res/values/colors.xml
Changed the name of a particular shade of green.
This particular shade of green, #57bfa4, is used as the disabled green button fill. I changed the name from `green_alpha_66` to `green_200` because:
- The hex colour does not have any transparency and therefore shouldn't be part of the `_alpha` list
- The `_200` prefix makes it easier to systematically (all platforms) change values and assume usages
- I decided with @cdolm92's help to name this shade `green_200` on iOS, so figured it's nice to have the same on Android for the above reason
Changed the variable name in colors.xml and updated its one usage reference.
See the file changes. Pretty straightforward.
> Green naming change

- Gemfile.lock
Bumping mini_magick library to resolve security vulnerability. This is a followup to #568 because it's in 2 places.
TO BE SECURE
4.5.1 -> >= 4.9.4
> [🔒] Updating mini magick gem

- app/src/main/java/com/kickstarter/services/apiresponses/MessageThreadEnvelope.java
- app/src/main/java/com/kickstarter/viewmodels/BackingViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/MessagesViewModel.java
- app/src/main/res/layout/backing_layout.xml
- app/src/test/java/com/kickstarter/viewmodels/BackingViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/MessagesViewModelTest.java
- This PR fixes the bug where the `Mark as received` switch was not visible when backers clicked the `View pledge` button (vs clicking the reward).
- Removing the `View Pledge` button in the `View pledge` screen when the user came from the creator bio.
- Fixes unsightly(!) overscroll in the `View pledge` screen.
- Fixes the crash when backers who try to start a message thread with the creator crashed when they clicked `View Pledge`.
BUGS
- Previously~ I foolishly assumed that we'd only supply the `backer` to the `intent` to start the `BackingActivity` when a creator was viewing a backer's pledge not a backer viewing their own pledge... so now I'm just checking if the current user's `id` is the same as the backer's.
- Friendly reminder: If you're going to nest scrolling views, they need to …
> [🐜🕷] Mark as received bug, View pledge bug

- app/src/main/res/layout/messages_backing_info_view.xml
Set the maximum width of the _View pledge_ button to 50%.
Messages in German (and perhaps other languages) causes the _View pledge_ button to clash with the pledge information text ([image](https://p14.zdusercontent.com/attachment/7902/yiFgNiaV5IeTlSsUYeBmYLsgx?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..9I8RHPyZJWfkmAT1j3tUXg.N078VVb84C2Rv6V7Z55NxiTKgUrsjRXQ7oIs4uAOv0bifs0i1J1i8TRQV7t2j_ZLKZMFpvfM1nqsBe8eOal7ZcbcqHqSgNa3q4y-jnklgqr_djiSdnE76t_H0C7Z3ZPbl53b4iqI0Q-7VMnz8oSqDFgfQjY2ll4vjjftGYf6U-j_1RcKuXwCoZ2zmKk8sx8XJWnK3yRd9ZbRqQii7EmBGc6JcAh95ajfcgbN3oyJAgcl7ycWARgMp6jja-y4fILltET1irjUwsV3alq0cN67jQ.V-Hi7e7E6aTgBqQ46a2myA)). This is because we didn't set a limit to the size of the button.
The button will now ellipsise instead of pushing the other content to a smidge, until the …
> Set maximum width on button

- app/src/main/java/com/kickstarter/ui/views/KSWebView.kt
Fixes crashes from non-null params in `KSWebView.loadUrl` and `evaluateJavascript`.
So it doesn't crash.
`?`
I can't repro but here are the crashes:
https://fabric.io/kickstarter2/android/apps/com.kickstarter.kickstarter/issues/9fb2fab0b01904ebae74231a7277cc1b?time=last-seven-days
https://fabric.io/kickstarter2/android/apps/com.kickstarter.kickstarter/issues/574e904766c2d3c39b206c70a72fad46?time=last-seven-days
Not sure. I can't repro so...just QA that webviews continue to not crash 👀 
https://dripsprint.atlassian.net/browse/NT-67
> Webview nullable

- app/build.gradle
- app/src/main/java/com/kickstarter/ui/viewholders/NativeCheckoutRewardViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/NativeCheckoutRewardViewHolderViewModel.kt
- app/src/main/res/drawable/divider_grid_1.xml
- app/src/main/res/layout/item_reward.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/com/kickstarter/viewmodels/NativeCheckoutRewardViewHolderViewModelTest.kt
Displaying shipping restrictions.
So users know where a reward can be shipped.
- Added `FlexboxLayout` so the limits section wraps if necessary.
- Added a style `RewardPill`  for reward pills since it's used in 3 places.
- Tests.
| Ended Project 👻 | Live Project 🐥 | Flexing 💪🏾 |
| ![screenshot-2019-08-06_145311](https://user-images.githubusercontent.com/1289295/62568004-58eceb80-b85a-11e9-8952-78b902707e81.png) | ![screenshot-2019-08-06_145311](https://user-images.githubusercontent.com/1289295/62567799-f72c8180-b859-11e9-86c7-4179362fd39f.png) | ![screenshot-2019-08-06_145405](https://user-images.githubusercontent.com/1289295/62567876-1a573100-b85a-11e9-8f9e-c431beef2ab5.png) |
👻 Ended projects don't show any limits because you can't pledge to it so they're irrelevant. …
> [📦] Native checkout shipping summaries

- app/src/main/java/com/kickstarter/viewmodels/NativeCheckoutRewardViewHolderViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/NativeCheckoutRewardViewHolderViewModelTest.kt
Unbacked no reward title is now `Pledge without a reward`
👀
Updated string to `Pledge without a reward` and updated tests.
| --- | --- |
| ![screenshot-2019-08-08_111010](https://user-images.githubusercontent.com/1289295/62714767-2f080600-b9cd-11e9-9002-6d99cee380ea.png) | ![screenshot-2019-08-08_111043](https://user-images.githubusercontent.com/1289295/62714768-2f080600-b9cd-11e9-9c76-45537f72daea.png) |
1️⃣ When the user **hasn't** backed `no reward`, the title should be `Pledge without a reward`
2️⃣ When the user **has** backed `no reward`, the title should be `Thank you for supporting this project.`
https://dripsprint.atlassian.net/browse/NT-44
> [📄] No reward title copy

- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/ui/data/PledgeData.kt
- app/src/main/java/com/kickstarter/ui/data/PledgeReason.kt
- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
- app/src/main/res/layout/activity_project.xml
- app/src/main/res/layout/fragment_backing.xml
- app/src/main/res/menu/manage_pledge.xml
- app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardsFragmentViewModelTest.kt
Showing an interstitial screen with menu options when the pledge sheet is expanded and the user has backed the project.
MANAGE UR PLEDGE
- `ProjectActivity` displays `BackingFragment` as the primary screen when the pledge sheet is opened.
- When it's visible, an options menu is present in the rewards toolbar.
- The menu has options for `Update pledge`, `Change payment method`, `View rewards`, `Cancel pledge` and `Contact creator`
- Added `PledgeReason` that will be used to configure `PledgeFragment` UI
- `PledgeData.screenLocation` is now optional.
- `PledgeFragment` hides mini reward if no `ScreenLocation`.
- Renamed `RewardFragment` to `RewardsFragment`.
- Renamed `RewardFragmentViewModel` to `RewardsFragmentViewModel`.
- Testz
| Menu❓  | Update pledge | Change payment method |
| --- | …
> [🆕] Manage pledge menu

- app/src/main/java/com/kickstarter/mock/factories/LocationFactory.java
- app/src/main/java/com/kickstarter/models/Location.java
- app/src/main/java/com/kickstarter/ui/fragments/NewCardFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardCardViewHolderViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardCardViewHolderViewModelTest.kt
Added `expandedCountry` to the `Location` model.
So we can tell users why a credit card isn't allowed.
- Alphabetized `Location` model (after `id`).
- Added `expandedCountry` to the `Location` model.
- Updated `NewCardFragment` and `RewardCardViewHolderViewModel` to use value.
- Tests.
| --- | --- |
| ![screenshot-2019-08-05_113355](https://user-images.githubusercontent.com/1289295/63118664-4d8d7480-bf6c-11e9-8e38-c77e5fc02b8e.png) | ![screenshot-2019-08-15_144836](https://user-images.githubusercontent.com/1289295/63118568-20d95d00-bf6c-11e9-8882-6634cd8ff911.png) |
| --- | --- |
|  ![screenshot-2019-08-06_120413](https://user-images.githubusercontent.com/1289295/63118614-38b0e100-bf6c-11e9-9d97-75d8fb4eab1f.png) | …
> [🆕] Adding expandedCountry to location model

- app/src/main/graphql/checkout.graphql
- app/src/main/graphql/schema.json
- app/src/main/java/com/kickstarter/extensions/ActivityExt.kt
- app/src/main/java/com/kickstarter/extensions/SnackbarExt.kt
- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/services/ApolloClientType.kt
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/res/layout/fragment_pledge.xml
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Updating create backing mutation.
It was renamed on the backend...
Updated schema.
`nativeCheckout` is now `createBacking`.
Moved Snackbar extension to `SnackbarExt.kt`.
Properly showing pledge errors.
| After 🦋 |
| --- |
| ![device-2019-08-16-112011 2019-08-16 11_20_51](https://user-images.githubusercontent.com/1289295/63178395-f3e28400-c017-11e9-9660-bbc5a0a26829.gif) |
Right now this mutation is broken in master but works in the native HQ. https://github.com/kickstarter/kickstarter/pull/16898#pullrequestreview-275942393
You can switch to the native HQ by opening the drawer -> Clicking `Internal tools` -> Clicking `Hivequeen` and entering `native` in the dialog. 
Back a project.
This is a refactor of already done work due to a rename. Not sure what epic it should belong to.
> [🔁] Native checkout, take 2

- app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
- app/src/main/java/com/kickstarter/models/Project.java
- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Prelaunch projects open in the browser 🌍 
So users are taken to the prelaunch webpage when it's #activated.
- One does not simply _open a URL in the browser_, especially if that link is identical to a deep link it supports because then it just creates a very sad feedback loop. So, I had to use the same logic in the `DeepLinkActivity`; by creating an `Intent` chooser to present the user with options to open the link, not including the app they're already in!
- When the API returns a project where `prelaunchActivated` is `true`, the project opens in the browser.
- When the API returns a project where `prelaunchActivated` is `false`, the project opens natively.
- Tests ❤️ 
| Pretend this project is prelaunchActivated~ | 
| --- |
| ![device-2019-08-12-145520 2019-08-12 …
> [🔜] Prelaunch project MVP

- app/src/main/java/com/kickstarter/mock/factories/LocationFactory.java
- app/src/main/java/com/kickstarter/mock/factories/ShippingRulesEnvelopeFactory.kt
- app/src/main/java/com/kickstarter/ui/ArgumentsKey.java
- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/ui/data/PledgeReason.kt
- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
- app/src/main/res/layout/fragment_pledge.xml
- app/src/main/res/layout/fragment_pledge_section_pledge_amount.xml
- app/src/main/res/layout/fragment_pledge_section_shipping.xml
- app/src/main/res/layout/fragment_pledge_section_summary_pledge.xml
- app/src/main/res/layout/fragment_pledge_section_summary_shipping.xml
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardsFragmentViewModelTest.kt
Displaying the proper UI in the Pledge screen when managing your pledge.
The Designs Changed™: An Autobiography  
`PledgeFragment` now requires a `PledgeReason` to be instantiated. It uses that to configure the UI.
Added `LocationFactory.nigeria` to test the shipping summary output.
Moved stepper and shipping labels out of root pledge XML so they could easily be hidden.
Added layouts for pledge and shipping summaries.
Tests....so many tests.
| Unbacked project | Updating payment method  |
| --- | --- |
| ![screenshot-2019-08-20_184045](https://user-images.githubusercontent.com/1289295/63389540-0e9b5c80-c37a-11e9-9463-7513a975af31.png) | ![screenshot-2019-08-22_145918](https://user-images.githubusercontent.com/1289295/63542066-73c38f00-c4ed-11e9-8205-96657d1e3b0b.png) |
| Updating pledge | …
> [🔁] Revert manage pledge

- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/ui/fragments/CancelPledgeFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/CancelPledgeViewModel.kt
- app/src/main/res/layout/fragment_cancel_pledge.xml
- app/src/test/java/com/kickstarter/viewmodels/CancelPledgeViewModelTest.kt
Implementation of the cancel pledge redesign.
Redesign™
- Changed background color to `ksr_grey_300`.
- Removed toolbar.
- The pledge amount and project name are now **bold**.
- There were some `BehaviorSubject`s that should've been `PublishSubject`s, you know how it goes.
- It now animates horizontally, instead of vertically.
| After 🦋 | Before 🐛| 
| --- | --- |
| ![screenshot-2019-08-21_114404](https://user-images.githubusercontent.com/1289295/63448067-2e2e9580-c40b-11e9-93fa-eade249b2685.png) | ![screenshot-2019-07-12_153909](https://user-images.githubusercontent.com/1289295/63448124-51594500-c40b-11e9-97f4-54af41d940f3.png) |
| ![device-2019-08-21-114534 2019-08-21 11_46_02](https://user-images.githubusercontent.com/1289295/63448156-6209bb00-c40b-11e9-9c6c-0a40af68c3b8.gif) | …
> [🔁] Cancel Pledge redesign

- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/services/interceptors/GraphQLInterceptor.kt
Sending client id with custom header on graphql requests
2 B SECURE
Added `clientId` to `GraphQLInterceptor` constructor.
Sending with every graphQL request with as `"X-KICKSTARTER-CLIENT"` header.
Nothing 2 c here.
👀 if you're on a debug build, this will be in the logz
https://dripsprint.atlassian.net/browse/NT-87
> [🔒] Sending client id with custom header on graphql requests

- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Previously we showed the total amount pledged if you backed no reward and the reward minimum if you backed an actual reward. This PR makes it so we always show the total pledge amount in the pledge summary of a backed live project.
So the amount is unambiguous. 
Removed special logic for no reward and updated tests.
| Reward minimum | Total amount pledged (includes shipping) 🆕 |
| --- | --- |
| ![screenshot-2019-08-29_134909](https://user-images.githubusercontent.com/1289295/63963857-e4295d80-ca63-11e9-9481-4b8f91fb5cb2.png) | ![screenshot-2019-08-28_193405](https://user-images.githubusercontent.com/1289295/63899419-d83d8d00-c9ca-11e9-9016-b8386301c8de.png) |
Back a project! Or view a backed live project (check your profile!). 
The backing summary in the collapsed pledge sheet should show …
> [💰] Always showing the total pledge amount in the pledge summary

- app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
Hiding the rewards count footer in landscape.
It's cramped in here.
We have this handy method `ViewUtils.isLandscape`. Did all the work for me 😛 
| Portrait 🤲🏾 | Landscape 👐🏾 |
| --- | --- |
| ![screenshot-2019-09-06_134105](https://user-images.githubusercontent.com/1289295/64449084-2af30500-d0ad-11e9-8c98-05a190630cd1.png) | ![screenshot-2019-09-06_134110](https://user-images.githubusercontent.com/1289295/64449085-2af30500-d0ad-11e9-9342-3a34cdd62fcf.png) |
In a Native Checkout Enabled™ project, open the rewards sheet, rotate. 🎩The count is gone. 
https://dripsprint.atlassian.net/browse/NT-249
> [🙈] hiding the rewards count in landscape

- app/src/main/java/com/kickstarter/libs/utils/RewardViewUtils.kt
- app/src/main/java/com/kickstarter/ui/viewholders/NativeCheckoutRewardViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/NativeCheckoutRewardViewHolderViewModel.kt
- app/src/main/res/color/button_pledge_ended.xml
- app/src/main/res/color/button_pledge_live.xml
- app/src/main/res/color/button_pledge_manage.xml
- app/src/main/res/layout/item_reward.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/com/kickstarter/libs/utils/RewardViewUtilsTest.kt
- app/src/test/java/com/kickstarter/viewmodels/NativeCheckoutRewardViewHolderViewModelTest.kt
Backed reward button CTA is now `Selected`.
Unbacked rewards (of a backed project) button CTA is `Select` instead of `Select this instead`.
Backed reward buttons are disabled (because you can't reselect them, ya know).
The disabled background for all reward buttons is `ksr_grey_500` with default Material disabled text color.
Removed check denoting selected reward.
Becauseeeeee opening the rewards sheet no longer takes users directly to the carousel so the colors no longer apply and `Select this instead` copy was awkward.
LOVE TO DELETE CODE.
- Removed `RewardViewUtils.checkBackgroundDrawable` and `RewardViewUtils.pledgeButtonColor`.
- Updated `RewardViewUtils.pledgeButtonText` to 
- backed reward -> `Selected`
- available, unbacked reward -> `Select`
- unavailable reward -> `No longer …
> [🔙] Reward buttons, take 2

- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/res/layout/fragment_pledge.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Reversing the reward card animation when the user hits back when viewing the Pledge screen.
It looks more better*
- `ProjectActivity.handleNativeCheckoutBackPress` will tell the `PledgeFragment` to reverse the reward animation if it's at the top of the back stack and the card is present.
- The background of the `PledgeFragment` now fades in and out.
- `startPledgeAnimatorSet` no longer takes in a `ScreenLocation` because it can pull it from the `Arguments`.
- Not emitting `PledgeFragmentViewModel.ViewModel.arguments()` until `onGlobalLayout` emits to remove some jank by delaying UI work until the view is laid out.
- Fetching a user's stored cards properly waits until the total has successfully emitted.
- All of the tests in `PledgeFragmentViewModelTest` assert that `animateRewardCard` …
> [🔙] Reversing reward animation on back press

- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
Hitting back in the Project screen crashes! 
I played myself by trying to write prettier code.
Moved the check inline so it's guarded by the `backStackIsNotEmpty` boolean.
> [💥] Back button bug

- app/src/main/java/com/kickstarter/models/Backing.java
- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
Using `backing.locationName` to display in View/Manage pledge screen.
So users know what shipping location they chose.
- Added `locationName` to `Backing` model.
- Updated test.
| After 🦋 |
| --- |
| <img src=https://user-images.githubusercontent.com/1289295/64562251-968dda00-d31a-11e9-8a47-c93a65d467c4.png width=330/> | 
🌍Back a project with shipping, the View/Manage pledge screen should display the location.
NT-281
> [🗺] NT-281 Consuming backing.locationName

- app/src/main/java/com/kickstarter/libs/utils/ProjectUtils.java
- app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
- app/src/main/java/com/kickstarter/models/Project.java
Disabling stored cards based on `project.availableCardTypes`.
So users can't pledge with an unsupported card.*
*Please note that this doesn't stop them from adding an unsupported card (if we change which cards we support) because the types from the API are not the same as the types from Stripe or Google Pay.
- Added `availableCardTypes` to `Project` model.
- Updated `ProjectUtils.acceptedCardType` to use `availableCardTypes`.
- Updated `ProjectFactory` so the tests pass.
Looks the same
| Disabled cards  |
| --- |
| <img src=https://user-images.githubusercontent.com/1289295/64807196-b6174380-d562-11e9-8c19-536a9e6613bd.png width=330/> | 
Cards that are not available for the project should have the unavailable button style and helper copy as seen in Abstract.
[NT-246]
[NT-246]: …
> [💳] NT-246 Disabling stored cards based on project.availableCardTypes

- .circleci/config.yml
- app/build.gradle
Continuing my streak 🚀 our compile and target SDKs are now `29` to support Android Q https://developer.android.com/about/versions/10/migration
ALWAYS B UPGRADING
- Updated `compileSdkVersion` and `targetSdkVersion` from `28` to `29`
- Updated build tools from `28.0.3` to `29.0.2`
- Changed CircleCI Docker image from `circleci/android:api-28-alpha` to `circleci/android:api-29`
- I also took the liberty of increasing the CircleCI gradle JVM from .5GBs to 2GB. Did it make things go faster? Not really!
Nothing to see but another one of my fire upgrades
🤔 
[NT-336]
[NT-336]: https://dripsprint.atlassian.net/browse/NT-336
> [𝐐] NT-336 Targeting SDK 29

- app/src/main/java/com/kickstarter/libs/utils/UrlUtils.kt
- app/src/main/java/com/kickstarter/ui/activities/DeepLinkActivity.java
- app/src/main/java/com/kickstarter/ui/activities/HelpSettingsActivity.kt
- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/test/java/com/kickstarter/libs/utils/UrlUtilsTest.kt
First step in full ref tag support!
There's not much Android happening here, just BUSINESS!
So we can track users' comings and goings.
- Renamed `UrlUtils. buildUrl` to `UrlUtils.appendPath` for clarity.
- Added `UrlUtils. appendQueryParameter ` as a helper method to add a query param to a URL.
- Added `UrlUtils. appendRefTag ` as a helper method to add a ref tag to a URL.
- Added `UrlUtils. refTag ` as a helper method to get a ref tag from a URL.
- Beautiful tests.
Nothing 2 c
Nothing to QA
[NT-338]
[NT-338]: https://dripsprint.atlassian.net/browse/NT-338
> [🏷] Adding helper methods for setting/getting ref tags from URLs

- app/src/main/java/com/kickstarter/libs/RefTag.java
- app/src/main/java/com/kickstarter/viewmodels/DeepLinkViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/DeepLinkViewModelTest.java
Setting a ref tag on project page deep links if they did not initially have one.
┏┓
┃┃╱╲ In this
┃╱╱╲╲ house
╱╱╭╮╲╲ we
▔▏┗┛▕▔ 
╱▔▔▔▔▔▔▔▔▔▔╲
&nbsp;&nbsp;&nbsp;__Attribute our referrers__
╱╱┏┳┓╭╮┏┳┓ ╲╲
▔▏┗┻┛┃┃┗┻┛▕▔
- If a project link doesn't have a ref tag, we add the `android_deep_link` ref tag.
- Tests.
This is a Behind the Scenes™ PR.
KTK? 👀 
[NT-343]
[NT-343]: https://dripsprint.atlassian.net/browse/NT-343
> [🏷] NT-343 Adding default ref tag to project deep links that don't have one

- app/src/main/java/com/kickstarter/libs/RefTag.java
- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Adding a ref tag when sharing a project.
So we know if users navigated to the project page via a link shared from the Android app!
- Added `RefTag.projectShare` which has a value of `android_project_share`.
- The `showShareSheet` output in ProjectViewModel is now a `Pair<String, String>` representing the project's name and the share URL instead of just the project so we can properly test that the tag is set!
- Tests!
| --- | --- |
| Don't Go Without Me by Rosemary Valero-O'Connell, via @Kickstarter https://kickstarter.com/projects/shortbox/dont-go-without-me-by-rosemary-valero-oconnell | Don't Go Without Me by Rosemary Valero-O'Connell, via @Kickstarter https://kickstarter.com/projects/shortbox/dont-go-without-me-by-rosemary-valero-oconnell?ref=android_project_share …
> [🔗] NT-337 Adding ref tag when sharing projects

- app/src/main/java/com/kickstarter/libs/RefTag.java
- app/src/main/java/com/kickstarter/ui/activities/UpdateActivity.java
- app/src/main/java/com/kickstarter/viewmodels/UpdateViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/UpdateViewModelTest.java
Adding a ref tag when sharing an update.
So we know if users navigated to an update page via a link shared from the Android app!
- Added `RefTag.updateShare` which has a value of `android_update_share`.
- The `startShareIntent` output in `UpdateViewModel` now outputs a pair of an update and the share url string.
- Updated intent share style in `UpdateActivity`.
- Tests.
| --- | --- |
| Update #31: A calm before the storm: daily unlock! WIPs! https://www.kickstarter.com/projects/1492106834/aeon-trespass-odyssey/posts/2635180 | Update #31: A calm before the storm: daily unlock! WIPs! https://www.kickstarter.com/projects/1492106834/aeon-trespass-odyssey/posts/2635180?ref=android_update_share |
| <img src=https://user-images.githubusercontent.com/1289295/65721280-bc83e00 …
> [🔗] NT-342 Adding ref tag when sharing updates

- .gitignore
Updating `gitignore` in prep for prerelease
Because we're not ready for the script to be committed yet!
> 🔜Pre-release prep!

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/KoalaEvent.java
- app/src/main/java/com/kickstarter/viewmodels/CancelPledgeViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/CancelPledgeViewModelTest.kt
Adding tracking events for canceling a pledge.
TRACKING
- Added `CANCEL_PLEDGE_BUTTON_CLICKED`  to `KoalaEvent`.
- Tracking `Cancel Pledge Button Clicked` when a user confirms their pledge cancellation.
- Tests.
nothing 2 c
check ur local LogCat
On debug builds, we log the Koala events and their properties.
Canceling a pledge should fire the `Cancel Pledge Button Clicked` event with default project properties.
[NT-397]
[NT-397]: https://dripsprint.atlassian.net/browse/NT-397
> [🛤] NT-397 Checkout tracking events for canceling a pledge

- app/src/main/java/com/kickstarter/libs/utils/ProjectViewUtils.kt
- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/res/layout/fragment_pledge.xml
- app/src/main/res/layout/fragment_pledge_section_payment.xml
- app/src/main/res/layout/fragment_pledge_section_pledge_amount.xml
- app/src/main/res/layout/fragment_pledge_section_shipping.xml
- app/src/main/res/layout/fragment_pledge_section_summary_pledge.xml
- app/src/main/res/layout/fragment_pledge_section_summary_shipping.xml
- app/src/main/res/layout/fragment_pledge_section_total.xml
- app/src/main/res/layout/item_reward.xml
- app/src/main/res/values-de/strings_i18n.xml
- app/src/main/res/values-es/strings_i18n.xml
- app/src/main/res/values-fr/strings_i18n.xml
- app/src/main/res/values-ja/strings_i18n.xml
- app/src/main/res/values/strings_i18n.xml
- app/src/test/java/com/kickstarter/libs/utils/ProjectViewUtilsTest.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Improving a11y on Pledge screen.
It's non-negotiable.
- Pledge screen is now fully traversable.
- The screen starts with the mini reward focused so users can jump back to rewards list.
- Currency that can't be edited (shipping, total, pledge summary, shipping summary) now read as one element.
- `pledgeSummaryAmount`, `shippingAmount`, `shippingSummaryAmount`, and `totalAmount` outputs in the `PledgeFragmentViewModel` are now `CharSequence`s instead of `String`s.
- Removed currency symbol `TextView`s in shipping section `fragment_pledge_section_shipping.xml`, pledge summary section `fragment_pledge_section_summary_pledge.xml`, shipping summary section `fragment_pledge_section_summary_shipping.xml`, and total section `fragment_pledge_section_total.xml`
- `ProjectViewUtils. …
> [💳] NT-416 Improved a11y in Pledge screen

- app/src/main/java/com/kickstarter/models/StoredCard.kt
- app/src/main/java/com/kickstarter/ui/viewholders/PaymentMethodsViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/RewardCardViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/RewardLoadingCardViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/RewardPledgeCardViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/BaseRewardCardViewHolderViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/PaymentMethodsViewHolderViewModel.kt
- app/src/main/res/layout/item_payment_method.xml
- app/src/main/res/layout/item_reward_loading_card.xml
- app/src/main/res/layout/item_reward_pledge_card.xml
- app/src/test/java/com/kickstarter/viewmodels/PaymentMethodsViewHolderViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardCardViewHolderViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardLoadingCardViewHolderViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardPledgeCardViewHolderViewModelTest.kt
Supporting visual and mobility impaired users in stored cards.
SUPPORT ALL THE USERS
- Added `StoredCard.issuer` to return card brand for a11y descriptors (from Stripe).
- Added issuer content description in payment methods list and in checkout.
- Added more padding around cancel card button (when you've selected a card).
- Added content description for loading card.
- Tests.
Nothing 2 c
Turn on TalkBack™ and focus on the stored cards in Settings -> Account -> Payment Methods. 
Turn on TalkBack™ and focus on the stored cards when pledging to a project. 
[NT-414]
[NT-414]: https://dripsprint.atlassian.net/browse/NT-414
> [💳] NT-414 Improved a11y support for stored cards

- app/src/main/java/com/kickstarter/ui/fragments/NewCardFragment.kt
Fixes NPE when unsuccessfully saving a card in settings.
Ideally...we would not crash.
- `new_card_root` is `null` when the `NewCardFragment` is not shown modally.
Stripe will still crash if you attempt to save a card without a network connection so I'm not sure how to test.
[NT-225]
[NT-225]: https://dripsprint.atlassian.net/browse/NT-225
> [🐛] NPE when saving card unsuccessfully in settings

- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
Fixes bug where rewards were hidden the first time a user try to view rewards of a backed project
Issa bug fix
**What's my problem this time?**
Okay so, first I noticed a crash due to an `IllegalStateException` when starting the `ThanksActivity` after a pledge was successfully created. I was attempting to commit a `FragmentTransaction` (to show the `RewardsFragment` and hide the `BackingFragment`) after the `onPause` lifecycle method of the `ProjectActivity` was called. You can't do that because it causes state loss.
**First attempt**
I stopped committing a `FragmentTransaction` and just toggled the visibility of the `RewardsFragment` and the `BackingFragment`. That is all good and fine except if you're viewing a backed project, the `RewardsFragment` would initially be hidden.
**This PR, …
> [🐛] NT-455 Fixing bug when viewing rewards of a backed project.

- app/src/main/java/com/kickstarter/libs/Either.kt
- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/main/res/layout/fragment_backing.xml
- app/src/main/res/values/apple_pay_strings.xml
- app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
Adds content description for payment method in view/manage pledge.
So the user knows what their payment method is.
- Added proper `equals` method to `Either` class. It compares the `left` and `right` values.
- Added `cardIssuer` output to `BackingFragmentViewModel`. It's an `Either<String, Int>` representing the card brand or the string resource of the description.
- Added Apple Pay content description string.
- The payment method section in the `BackingFragment` is now focusable so it reads all at once.
- Tests.
Turn on TalkBack and focus on a backing's payment method.
[NT-457]
[NT-457]: https://dripsprint.atlassian.net/browse/NT-457
> [💳] NT-457 A11y label for backing payment method

- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Hiding the pledge summary in the change payment method screen when a reward is not shippable.
The pledge amount is the same as the total.
- The `pledgeSummaryIsGone` output in the `PledgeFragmentViewModel` now uses the same logic as the `shippingSummaryIsGone` output. They're both hidden if the user is not updating their payment method OR the reward is not shippable.
| --- | --- |
| ![screenshot-2019-10-23_131024](https://user-images.githubusercontent.com/1289295/67419777-50739980-f59b-11e9-9399-e3e9b41711d7.png) | ![screenshot-2019-10-23_133328](https://user-images.githubusercontent.com/1289295/67419778-50739980-f59b-11e9-8edb-6b480bdba70e.png) |
Change the payment method of a reward without shipping.
[NT-442]
[NT-442]: …
> [🙈] NT-442 Pledge summary visibility in the pledge screen

- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
Hiding the pledge summary in the view/manage pledge screen when a backing doesn't have a location.
The pledge amount is the same as the total.
- Added `pledgeSummaryIsGone` output to the `BackingFragmentViewModel`. It  uses the same logic as the `shippingSummaryIsGone` output. They're both hidden if the backing does not have a `locationId`.
| --- | --- |
| ![screenshot-2019-10-23_140012](https://user-images.githubusercontent.com/1289295/67421247-1ce63e80-f59e-11e9-99b2-ca376baddb16.png) | ![screenshot-2019-10-23_135949](https://user-images.githubusercontent.com/1289295/67421245-1ce63e80-f59e-11e9-8084-e58b79c521d0.png) |
View a pledge with no shipping!
[NT-466]
[NT-466]: https://dripsprint.atlassian.net/browse/NT-466
> [🙈] NT-466 Pledge summary visibility in the view/manage pledge screen

- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Fixes bug where rotating didn't reveal the pledge deadline warning.
So users are warned, even when they rotate.
- Removing `.take(1)` fixes the bug.
- Updated tests. `totalAndDeadlineIsVisible` now emits every time `totalAndDeadline` emits.
Go to the pledge screen and rotate~
[NT-448]
[NT-448]: https://dripsprint.atlassian.net/browse/NT-448
> [🐜] NT-448 Pledge warning rotation bug

- app/src/main/res/values/styles.xml
Styling our native 3DS2 screens.
Consistency is 🔑 
- Synced with @colleenmacd on recommendations and overrode [`Stripe3DS2Theme`](https://github.com/stripe/stripe-android/blob/master/example/res/values/themes.xml#L26) and `Stripe3DS2Button` styles.
You can't take screenshots of these screens!
Back a project (on the native HQ) with one of these [cards](https://stripe.com/docs/mobile/android/authentication#testing). 
[NT-487]
[NT-487]: https://dripsprint.atlassian.net/browse/NT-487
> [🎨] NT-487 Customizing 3DS2 style

- app/src/main/java/com/kickstarter/viewmodels/NativeCheckoutRewardViewHolderViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/NativeCheckoutRewardViewHolderViewModelTest.kt
Hiding the `Select` button when a creator views the rewards of their own project.
Because they can't back their own project.
- The `buttonIsGone` output of `NativeCheckoutRewardViewHolderViewModel` now checks if the current user is the current project's creator and returns `true` if they are.
- Split all the `buttonUIOutput` test cases into their own tests.
- Added tests for making sure the button is gone when the current user is the current project's creator.
| Logged  in 🦋 | Logged out 🐛 |
| --- | --- |
| ![device-2019-11-01-151731 2019-11-01 15_20_09](https://user-images.githubusercontent.com/1289295/68050253-2157d900-fcbb-11e9-912c-c39000f7ac68.gif) | ![device-2019-11-01-151640 2019-11-01 15_20_20](https://user-images.githubusercontent.com/1289295/68050252-2157d900-fcbb-11e9-8d65-ef9da …
> [⛔️] NT-509 Hiding reward CTA for creators on their own project

- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/main/res/drawable/ic_action_icon__arrow_left.xml
- app/src/main/res/drawable/ic_arrow_back.xml
- app/src/main/res/drawable/ic_arrow_down.xml
- app/src/main/res/layout/creator_dashboard_toolbar.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Reverting #558 logic for how the navigation icon in the pledge toolbar works and updating icon drawable based on fragment back stack count.
Everyone clicks the down icon thinking it'll take them back and it doesn't. GIVE THE PEOPLE WHAT THEY WANT
- Added `ic_arrow_back.xml`. We now use this rounded style everywhere. Deleted `ic_action_icon__arrow_left.xml`. 
- Updated `ic_arrow_down.xml` color to `ksr_soft_black`.
- Renamed `ProjectViewModel` input `collapsePledgeSheet ` to `pledgeToolbarNavigationClicked`.
- Added `pledgeToolbarNavigationIcon` output to `ProjectViewModel`. It emits the down icon drawable when the back stack is empty and the back icon when it's not.
- Added `goBack ` output to `ProjectViewModel`. It emits when the pledge toolbar navigation icon is clicked and there are …
> [🔙] NT-479 Pledge toolbar navigation

- app/src/main/java/com/kickstarter/mock/factories/AvatarFactory.java
- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/main/res/layout/fragment_backing.xml
- app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
Added current user's name and avatar to view/manage pledge
The first step in a sticky new feature.
- Added `backerAvatar` output to `BackingFragmentViewModel`. It emits the current user's backing medium avatar.
- Added `backerName` output to `BackingFragmentViewModel`. It emits the current user's name.
- Alphabetized subscribed outputs in `BackingFragment`.
- Tests
| --- | --- |
| ![screenshot-2019-11-06_162136](https://user-images.githubusercontent.com/1289295/68338954-99564280-00b1-11ea-93d0-bd13155ae9e9.png) | ![screenshot-2019-11-06_162151](https://user-images.githubusercontent.com/1289295/68339238-2d280e80-00b2-11ea-8956-a7cb5948e30c.png) |
View your pledge.
[NT-536]
[NT-536]: https://dripsprint.atlassian.net/browse/NT-536
> [📛] NT-536 Added current user's name and avatar to view/manage pledge

- app/src/main/res/layout/fragment_backing_section_summary_total.xml
- app/src/main/res/layout/fragment_pledge_section_pledge_amount.xml
- app/src/main/res/layout/fragment_pledge_section_shipping.xml
- app/src/main/res/layout/fragment_pledge_section_summary_pledge.xml
- app/src/main/res/layout/fragment_pledge_section_summary_shipping.xml
- app/src/main/res/layout/fragment_pledge_section_total.xml
- app/src/main/res/values/styles.xml
Updating text colors for currency in the backing and pledge fragments.
🎨 
- We now have 3 styles for pledge currency.
- `PledgeCurrency` `ksr_soft_black`
- `PledgeCurrencySecondary` `ksr_dark_grey_500`
- `PledgeCurrencyInput` `ksr_green_500`
| After pledge screen 🦋| Before pledge screen 🐛 |
| --- | --- |
| ![screenshot-2019-11-06_170457](https://user-images.githubusercontent.com/1289295/68342292-48961800-00b8-11ea-86eb-ed247bead5ca.png) | ![screenshot-2019-11-06_170955](https://user-images.githubusercontent.com/1289295/68342293-48961800-00b8-11ea-86fe-942f1499afe5.png) |
| After view/manage screen 🦋| Before view/mange screen 🐛 |
| ![screenshot-2019-11-06_171126](https://user-images.githubusercontent.com/1289295/68342394-7b401080-00b8-11ea-9b2a-600a0ec9d197.png) | …
> [🎨] NT-473 Pledge currency text styles

- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/main/res/layout/fragment_backing.xml
- app/src/main/res/layout/pledge_container.xml
- app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Adds pull to refresh support in view/manage pledge screen.
So users can get their latest backing.
- `ProjectActivity` now implements `BackingFragment.BackingDelegate`.
- `ProjectViewModel` refreshes current project when `Input.refreshProject` is called.
- Tests
- Added `SwipeRefresherLayout` to `BackingFragment`'s `NestedScrollView`.
- Added `BackingDelegate` that's used to notify when we need to refresh the project (when the user swipes to refresh).
- When the project is refreshed, we hide the `SwipeRefresherLayout` progress.
- Tests
| After 🦋 |
| --- |
| <img src=https://user-images.githubusercontent.com/1289295/68717636-509cfe80-0575-11ea-8183-10f7707ffa39.gif width=330/> | 
View a pledge. Pull to refresh.
[NT-566]
[NT-566]: https://dripsprint.atlassian.net/browse/NT-566
> [👆🏾] NT-566 Pull to refresh support in View/Manage pledge

- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/main/res/menu/manage_pledge_preauth.xml
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Showing a special menu when users are managing their preauth pledge.
Users can't make any changes to their pledge while it's being verified. 
- Created a new menu with an option to only contact the creator `manage_pledge_preauth.xml`.
- `ProjectViewModel.Outputs.managePledgeMenu` now emits `manage_pledge_preauth.xml` when a backed `Project` is _live_ and the status of the `Backing` is `preauth`.
- Added a test and renamed original test.
🔜 
[NT-567]
[NT-567]: https://dripsprint.atlassian.net/browse/NT-567
> [🆕] NT-567 Special manage pledge menu for backings in preauth state

- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
Hiding payment method section in BackingFragment when it's `null`.
Canceled projects return `null` for `project.backing.paymentMethod`.
- If the `paymentType` is not `ANDROID_PAY`, `APPLE_PAY`, or `CREDIT_CARD`, `BackingFragmentViewModel.output.paymentMethodIsGone` emits `true`.
| After 🦋 |
| --- |
| <img src=https://user-images.githubusercontent.com/1289295/68880811-f7021480-06d9-11ea-9f05-ea655f191db6.png width=330/> |
View the pledge of a canceled project.
🔜
> [😴] Hiding payment method in BackingFragment when it's null

- app/src/main/java/com/kickstarter/ApplicationModule.java
Adding headers to distinguish graphQL requests coming from Android
So the backend doesn't ignore our RefTags
- Added a [`KSRequestInterceptor`](https://github.com/kickstarter/android-oss/blob/master/app/src/main/java/com/kickstarter/services/interceptors/KSRequestInterceptor.java) to the ` in `ApplicationModule.provideApolloClient`.
Nothing to see
@walterbm and I paired on this by adding some logs in the native HQ
🔜
> [📱] Adding KSRequestInterceptor to graphQL client

- app/signing.gradle.example
- script/bootstrap
Fixes documentation with signing.gradle credentials.
Recently @Scollaco tried to build an external release and was unsuccessful because the documentation was outdated! Now that the instructions are up to date, future generations will know how to cut an external release!
> [👷🏾‍♀️] Fixes documentation with signing.gradle credentials

- app/build.gradle
- app/src/internal/java/com/kickstarter/ui/activities/FeatureFlagsActivity.kt
- app/src/internal/res/layout/activity_feature_flags.xml
- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/libs/Environment.java
- app/src/main/java/com/kickstarter/libs/FeatureKey.java
- app/src/main/java/com/kickstarter/libs/qualifiers/GoRewardlessPreference.kt
- app/src/main/java/com/kickstarter/ui/SharedPreferenceKey.java
- app/src/main/res/values/strings.xml
Scaffolding for go rewardless feature flag
Go rewardless prompt coming soon 🚀 
- Added `androidx.preference:preference:1.1.0` lib because  [`PreferenceManager.getDefaultSharedPreferences`](https://developer.android.com/reference/android/preference/PreferenceManager.html#getDefaultSharedPreferences(android.content.Context)) is deprecated. It's been superseded by [`PreferenceManager.getDefaultSharedPreferences`](https://developer.android.com/reference/androidx/preference/PreferenceManager.html#getDefaultSharedPreferences(android.content.Context))
- Added `FeatureKey.ANDROID_GO_REWARDLESS` with the value `android_go_rewardless` from https://github.com/kickstarter/kickstarter/pull/18139 (hasn't yet been deployed)
- Added `goRewardlessPreference` field to `Environment`.
- Added …
> [👷🏾‍♀️] NT-584 Go rewardless feature flag support

- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/main/res/layout/activity_project.xml
- app/src/main/res/layout/pledge_container.xml
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Pull to refresh bug.
TIL (it was yesterday) that calling `ApiClient.fetchProject(final @NonNull Project project)` emits the initial project first... this meant that doing PTR would sometimes flicker in the view/manage pledge screen.
- Now calling `ApiClient.fetchProject(final @NonNull String slug)` instead of `ApiClient.fetchProject(final @NonNull Project project)` to refresh project.
- Refreshing the project now hides the pledge action button (so the user won't see the `ProgressBar` and the action button at the same time).
- The non native checkout `ProgressBar` initially starts as `GONE`.
- Pull to refresh times out after 10 seconds if it fails so the user can retry.
- The retry button was blocked from being clicked so it not lives on top of the pledge fragments.
- Updated tests.
| …
> [🐞] NT-566 Refreshing project page bug

- app/src/main/java/com/kickstarter/ui/viewholders/NativeCheckoutRewardViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/NativeCheckoutRewardViewHolderViewModel.kt
- app/src/main/res/drawable/bg_go_rewardless.xml
- app/src/main/res/layout/item_reward.xml
- app/src/test/java/com/kickstarter/viewmodels/NativeCheckoutRewardViewHolderViewModelTest.kt
Go rewardless carousel treatment
So users are ENCOURAGED to go rewardless.
- Added `background` output to `NativeCheckoutRewardViewHolderViewModel` that emits a `Int` representing the background of the reward contents. [`0`](https://developer.android.com/reference/android/view/View#setBackgroundResource(int)) is how you clear the background.
- Added `bg_go_rewardless` as the special go rewardless background `Drawable`.
- Added special go rewardless copy when a user is viewing `No reward` and they haven't backed `No reward`.
- Decreased the size of the gradient behind the `Select` button for readability.
- Tests
| Enabled ✔️  | Disabled ✖️  |
| --- | --- |
| ![screenshot-2019-11-25_171021](https://user-images.githubusercontent.com/1289295/69582430-9a8ad900-0fa6-11ea-9986-5716b3fde1a6.png) …
> [✨] NT-587 Go rewardless carousel treatment

- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/KoalaEvent.java
- app/src/main/java/com/kickstarter/libs/KoalaTrackingClient.java
- app/src/main/java/com/kickstarter/libs/RefTag.java
- app/src/main/java/com/kickstarter/libs/TrackingClientType.java
- app/src/main/java/com/kickstarter/libs/utils/ConfigUtils.kt
- app/src/main/java/com/kickstarter/libs/utils/DiscoveryParamsUtils.java
- app/src/main/java/com/kickstarter/mock/factories/ConfigFactory.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
- app/src/test/java/com/kickstarter/KSRobolectricTestCase.java
- app/src/test/java/com/kickstarter/libs/KoalaTest.kt
- app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
- app/src/test/java/com/kickstarter/libs/utils/ConfigUtilsTest.kt
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
^
Metricz
- Now sending `enabled_feature_flags` array. It only sends events that are enabled and start with `android_`.
- `Koala` now takes in a `CurrentConfigType` so we can extract the currently enabled features.
- Added `ConfigUtils.enabledFeatureFlags ` that returns enabled android features.
- Added event when clicking Editorial tout `Editorial Card Clicked` with additional `ref_tag` property.
- Added support for `RefTag`s from `Editorial`s or `DiscoveryParams` that contain a `tag_id`.
- Tests (there's already a test for extracting a `RefTag` from an `Intent`).
- `GooglePlayServicesUtil.isGooglePlayServicesAvailable` is deprecated but then I also realized `isGooglePlayServicesAvailable` was returning `unavailable` instead of `available`.
Tail your user's events in ktk …
> [🛤] NT-622 Go rewardless tracking

- app/src/main/java/com/kickstarter/services/KoalaBackgroundService.kt
- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
Adding some bumpers in the Project page.
So we don't crash!
- Added tracking breadcrumbs to Crashlytics in `KoalaBackgroundService`
- Since `FragmentManager.findFragmentById` returns nullable `Fragment`s, safely unwrapping `BackingFragment` and `RewardsFragment`.
Check out these sweet breadcrumbs https://fabric.io/kickstarter2/android/apps/com.kickstarter.kickstarter.internal.debug/issues/60f1455fd23c9568a2e1edd61e889530/sessions/5DDDB6990210000116C5F000C2B933B0_DNE_0_v2?
I can't replicate these crashes IRL so smash the crash button in Internal Tools and check out the tracking breadcrumbs.
[NT-625]
[NT-625]: https://dripsprint.atlassian.net/browse/NT-625
> [💥] NT-625 No Crash Zone™ 

- app/build.gradle
- build.gradle
Silencing gradle warnings by updating fabric gradle tools and google services.
The APIs were obsolete and throwing warnings.
- Bumped `io.fabric.tools:gradle` from `1.25.4` to `1.30.0`
- Bumped `com.google.gms:google-services` from `4.3.0` to `4.3.3`
N/A
> [👷🏾‍♀️] Updating fabric gradle tools and google services to silence obsolete 

- app/src/main/java/com/kickstarter/ui/fragments/DiscoveryFragment.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
- app/src/main/res/layout/fragment_discovery.xml
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
Removing secondary `ProgressBar` in Discovery because it shows up randomly.
No ProgressBar, no problems.
- Removed the second `ProgressBar` in the `DiscoveryFragment`. (We already have a `ProgressBar` on this screen via pull to refresh.) After the `onStop` lifecycle method is called, it becomes visible so when you return to the screen, it looks like something is happening; surprise, nothing is happening. You can click behind it and it goes away if you pull to refresh but it's visually disturbing.
- Fixed another bug where `isFetchingProjects` never emitted if the project list was empty.
- Removed tests.
| --- | --- |
| ![device-2019-12-03-180746 2019-12-03 18_11_33](https://user-images.githubusercontent.com/1289295/70097865-68a5f200-15f8-11ea-866b-dde91ccf15b2.gif) …
> [🐞] NT-661 Removing secondary ProgressBar in Discovery

- app/src/main/java/com/kickstarter/services/DiscoveryParams.java
Fixes bug where the incorrect projects for a collection were shown.
Go rewardless was showing the wrong projects.
- V1 disco always returns something even if you send it garbo like `tad_id`. Fixed the typo as `tag_id`.
- Also fixed some copy pasta when merging params.
The projects shown in the Go Rewardless editorial should be the same as those shown here: https://www.kickstarter.com/discover/tags/back-it-because-you-believe-in-it?ref=believe-in-it
[NT-689]
[NT-689]: https://dripsprint.atlassian.net/browse/NT-689
> [🐛] NT-689 Fetching projects by "tag_id" and not "tad_id"

- app/src/main/java/com/kickstarter/libs/FeatureKey.java
- app/src/test/java/com/kickstarter/libs/utils/ConfigUtilsTest.kt
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
Updating key for go rewardless flag.
`android_go_rewardless` has been deprecated due to #693 in favor of `android_go_rewardless_2` https://github.com/kickstarter/kickstarter/pull/18369
- Updated value of `FeatureKey.ANDROID_GO_REWARDLESS` to `android_go_rewardless_2`.
- Updated broken tests. 
Go rewardless is only enabled on external builds that have `android_go_rewardless_2` enabled.
[NT-691]
[NT-691]: https://dripsprint.atlassian.net/browse/NT-691
> [🏴] NT-691 Go rewardless flag, take 2

- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/libs/utils/WebUtils.kt
- app/src/main/java/com/kickstarter/services/interceptors/GraphQLInterceptor.kt
- app/src/main/java/com/kickstarter/services/interceptors/WebRequestInterceptor.java
- app/src/main/java/com/kickstarter/ui/activities/VideoActivity.java
- app/src/test/java/com/kickstarter/libs/utils/WebUtilsTest.kt
Sending custom User Agent header with graphQL requests.
Android pledges currently have a `null` backing `Channel`. The UA is used to determine the pledge came from a `phone`.
- Created `WebUtils.userAgent` and tests.
- Adds `User-Agent` header to `GraphQLInterceptor`,
View your logs in a debug build or verify that backings created from the app have the channel `phone`.
[NT-690]
[NT-690]: https://dripsprint.atlassian.net/browse/NT-690
> [📱] NT-690 Sending custom User Agent header with graphQL requests

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kickstarter/ApplicationGraph.java
- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/libs/ActivityViewModel.java
- app/src/main/java/com/kickstarter/libs/Environment.java
- app/src/main/java/com/kickstarter/libs/FragmentViewModel.java
- app/src/main/java/com/kickstarter/libs/KoalaTrackingClient.java
- app/src/main/java/com/kickstarter/libs/LakeTrackingClient.kt
- app/src/main/java/com/kickstarter/libs/TrackingClient.kt
- app/src/main/java/com/kickstarter/libs/TrackingClientType.java
- app/src/main/java/com/kickstarter/libs/qualifiers/KoalaTracker.kt
- app/src/main/java/com/kickstarter/libs/qualifiers/LakeEndpoint.kt
- app/src/main/java/com/kickstarter/libs/qualifiers/LakeRetrofit.kt
- app/src/main/java/com/kickstarter/libs/qualifiers/LakeTracker.kt
- app/src/main/java/com/kickstarter/libs/utils/ApplicationLifecycleUtil.java
- app/src/main/java/com/kickstarter/libs/utils/Secrets.java.example
- app/src/main/java/com/kickstarter/services/LakeBackgroundService.kt
- app/src/main/java/com/kickstarter/services/LakeService.kt
- app/src/main/java/com/kickstarter/ui/IntentKey.java
- app/src/main/java/com/kickstarter/ui/views/AppRatingDialog.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
- app/src/test/java/com/kickstarter/KSRobolectricTestCase.java
- app/src/test/java/com/kickstarter/libs/KoalaTest.kt
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
- app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
Added additional tracking client to send events to the Data Lake™ 
We're cleaning up our event tracking.
- Abstracted reusable parts `KoalaTrackingClient` to `TrackingClient` so now `KoalaTrackingClient` is an extension of a `TrackingClient`.
- Added `LakeTrackingClient` which is an extension of a `TrackingClient` to the `Environment`.
- Added `LakeBackgroundService` to handle background task of sending tracking event requests.
- Added `LakeService` as API interface. It currently only sends a `PUT` request to the `record` endpoint with a `"Content-Type: application/json"` header.
- Added `@LakeEndpoint`, `@LakeRetrofit`, `@LakeTracker`, and `@KoalaTracker` qualifiers so our dependency injection can differentiate between clients.
- Added fake values for `Secrets.LakeEndpoint.Staging` and …
> [💧] NT-653 Set up additional tracking client to hit the Data Lake™ 

- app/src/main/java/com/kickstarter/libs/KoalaTrackingClient.java
- app/src/main/java/com/kickstarter/libs/LakeTrackingClient.kt
- app/src/main/java/com/kickstarter/libs/TrackingClient.kt
- app/src/main/java/com/kickstarter/libs/TrackingClientType.java
- app/src/main/java/com/kickstarter/services/KoalaBackgroundService.kt
- app/src/main/java/com/kickstarter/services/LakeBackgroundService.kt
Extracting shared parts of `LakeTrackingClient` and `KoalaTrackingClient` and moving to `TrackingClient`.
Refactor of #692 per @Scollaco's recommendation.
- Created abstract methods in `TrackingClient` for `backgroundServiceClass`, `eventKey`,  `eventNameKey`, `tag`, that are used in the now `final` `track` method.
Nothing 2 c
N/A
https://github.com/kickstarter/android-oss/pull/692#discussion_r355698774
> [🔄] Refactor of TrackingClient

- app/src/main/java/com/kickstarter/ui/activities/SurveyResponseActivity.java
- app/src/main/java/com/kickstarter/viewmodels/SurveyResponseViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/SurveyResponseViewModelTest.java
Handling users clicking on project links in the webviews.
So we can stop crashing.
- In #157, we attempted to fix the redirect bug after a successful survey submission that took users to the project page. That fix assumed that [`Request.tag`](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-request/tag/) would never be `null`. Around December 10, 2019, it started returning `null`. This PR checks if the tag is `null`.
- Previously, we returned `false` in `SurveyResponseActivity.handleProjectUriRequest` which means that we didn't handle the project page URL but since now we do, we return `true` so that the user isn't in an endless loop and the app doesn't crash.
| --- | --- |
| 💥 | ![device-2019-12-17-174027 2019-12-17 …
> [😕] NT-713 Handling null request tags in survey webview and tests

- app/src/main/java/com/kickstarter/libs/Config.java
- app/src/main/java/com/kickstarter/libs/TrackingClient.kt
- app/src/main/java/com/kickstarter/libs/TrackingClientType.java
- app/src/main/java/com/kickstarter/libs/utils/ConfigUtils.kt
- app/src/main/java/com/kickstarter/mock/factories/ConfigFactory.java
- app/src/test/java/com/kickstarter/libs/KoalaTest.kt
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
- app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
- app/src/test/java/com/kickstarter/libs/utils/ConfigUtilsTest.kt
Adding "Session Properties" tracking group.
The first step of many for new tracking events.
- Added `abExperiments` property to `Config` model
- Added `ConfigUtils.currentVariants` to return a `JSONArray` of current experiments
- Added new session properties to `TrackingClientType`
- Implemented new session property values in `TrackingClient`
- Testzzzzz
Nothing 2 c here
All events sent to the Lake 💧 should have these properties. This is a WIP so I'm on hitting staging.
> [🛁] Adding new tracking session properties

- app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
- app/src/test/java/com/kickstarter/libs/KoalaTest.kt
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
Adding "Discover Properties" tracking group.
The next next step of many for new tracking events 😛
- Added new discover properties to TrackingClientType.
- Implemented new discover property values in TrackingClient.
- Testz
nothing 2 c
All discovery events sent to the Lake 💧 should have these properties. This is a WIP so I'm only hitting staging.
> [🛁] Adding new tracking discover properties

- app/src/main/java/com/kickstarter/libs/TrackingClient.kt
- app/src/main/java/com/kickstarter/libs/TrackingClientType.java
- app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
- app/src/main/java/com/kickstarter/models/User.java
- app/src/test/java/com/kickstarter/libs/KoalaTest.kt
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
- app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
Adding "User Properties" tracking group.
The next step of many for new tracking events 😛 
- Added `facebookConnected` and `isAdmin` fields to `User` model.
- Added new user properties to `TrackingClientType`.
- Implemented new user property values in `TrackingClient`.
- Testz
Nothing 2 C
All logged in user events sent to the Lake 💧 should have these properties. This is a WIP so I'm only hitting staging.
> [🛁] Adding new tracking user properties 

- app/src/main/java/com/kickstarter/libs/TrackingClientType.java
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
Adding timestamps to Lake events.
It's the only `Context` property that's ready to go 😢 
Added `context_timestamp` to Lake default properties.
nothing 2 c
All Lake events will have the `context_timestamp` property.
[NT-654]: https://kickstarter.atlassian.net/browse/NT-654
> [⏱] Adding timestamps to Lake events

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
Adding `Explore Page Viewed` event.
- Added `Discover a Project` region to `Koala`
- Added `LakeEvent` file and `EXPLORE_PAGE_VIEWED` `const`
- Calling `koala.trackExplorePageViewed` when user views a Discovery page (but not for pagination)
- Updating `LakeTest` to test `koala.trackExplorePageViewed` instead of `koala.trackDiscovery`
- Added Lake tests in `DiscoveryFragmentViewModelTest`
[NT-654]: https://kickstarter.atlassian.net/browse/NT-654
> [🔍] NT-654 Adding Explore Page Viewed event

- app/src/main/java/com/kickstarter/libs/TrackingClientType.java
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
Adds missing `session_os` property
It's a must have!
Added `os` to `sessionProperties`.
Nothing 2 c
All Lake events should have the `session_os` prop.
Part of NT-654
> [😅] Adds missing session_os property

- app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
Fixes crash when clicking a project update.
Crashes are bad.
When a project update is clicked in the Activity feed is clicked, `Koala.trackViewedUpdate` is called with `activity.project` which is a minified `Project` so `project.category.parent` can return `null` despite being a subcategory.
| --- | --- |
| 💥 | ![device-2020-01-10-173403 2020-01-10 17_34_51](https://user-images.githubusercontent.com/1289295/72191224-8de40800-33cf-11ea-8b58-f6da82a73fa9.gif) |
Click a project update.
Bug fix for #705
> [💥] Fixes crash when clicking a project update

- app/src/main/java/com/kickstarter/libs/utils/ApplicationUtils.java
- app/src/main/java/com/kickstarter/ui/activities/DeepLinkActivity.java
- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/UpdateActivity.java
- app/src/main/java/com/kickstarter/viewmodels/DeepLinkViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/UpdateViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/DeepLinkViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/UpdateViewModelTest.java
Fixes bug where clicking a project URL in an update takes users to the current project instead of the one they clicked.
issa bug
- Added `ApplicationUtils.openUrlExternally` because we do this behavior in 3 places: 
1. `DeepLinkActivity`
2. `ProjectActivity`
3. `UpdateActivity`
- `DeepLinkViewModel` output `startBrowser` now emits a `String` instead of a list of `Intent`s.
- `UpdateViewModel` now supports clicking project links.
- If the project is live, it'll open natively.
- If the project is a preview or in  prelaunch, it'll open in the browser.
- I also a noticed a bug with prelaunch projects not opening sometimes. I fixed it by making the `ProjectViewModel.prelaunchUrl` output a `BehaviorSubject`.
- Updated `DeepLinkViewModelTest` and `UpdateViewModelTest`
| Pre launch project After …
> [🕷] NT-786 Fixes bug with clicking project URLs from an update

- app/src/main/java/com/kickstarter/ui/fragments/CancelPledgeFragment.kt
There's a NPE when users click the cancel pledge button. [Firebase](https://console.firebase.google.com/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/d3541be652f49610888ff3b55c1ebca8?time=last-ninety-days&sessionId=5E1C70CF00790001715905AAD3FB7807_DNE_2_v2)
So it doesn't crash.
- Added static import for `observeForUI`
- All view operations unwrap for null safety
nothing 2 c
Not sure how to repro -> not sure how to QA
[NT-726]
[NT-726]: https://kickstarter.atlassian.net/browse/NT-726
> [🤕] NT-726 Cancel pledge NPE

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
Adding `Hamburger Menu Clicked` event.
- Added `LakeEvent.HAMBURGER_MENU_CLICKED` `const`
- Calling `lake.trackHamburgerMenuClicked ` when user clicks the menu icon or slides the drawer open
- Added Lake tests in `DiscoveryFragmentViewModelTest.testDrawerData`
[NT-811]
[NT-811]: https://kickstarter.atlassian.net/browse/NT-811
> [🍔] NT-811 Added Hamburger Menu Clicked event

- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/libs/Environment.java
- app/src/main/java/com/kickstarter/libs/qualifiers/FirstSessionPreference.kt
- app/src/main/java/com/kickstarter/models/QualtricsIntercept.kt
- app/src/main/java/com/kickstarter/models/User.java
- app/src/main/java/com/kickstarter/ui/SharedPreferenceKey.java
- app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
- app/src/test/java/com/kickstarter/models/QualtricsInterceptTest.kt
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
Additional Qualtrics properties. 
😢
- Added `first_session` `SharedPreference` that's passed through to Qualtrics as `first_app_session`.
- Added `{interceptID}_impression_count` property to Qualtrics.
- Added `logged_in` and `user_uid` as embedded data in the survey url.
- Added tests for survey url, impression count and first session. 
Nothing 2 c
@jamielynnroth this can't be verified until we update the intercept logic 🙏 
[NT-790]
[NT-790]: https://kickstarter.atlassian.net/browse/NT-790
> [🆕] NT-790 Additional Qualtrics properties

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
Adding `Explore Sort Clicked` event.
- Added `LakeEvent.EXPLORE_SORT_CLICKED` `const`
- Added input `sortClicked` that takes in the position of the selected sort to `DiscoveryViewModel`
- Calling `lake.trackExploreSortClicked ` when user clicks on a sort tab
- Updated Lake tests in `DiscoveryViewModelTest.testUpdateInterfaceElementsWithParams`
[NT-812]
[NT-812]: https://kickstarter.atlassian.net/browse/NT-812
> [🔍] NT-812 Added Explore Sort Clicked event

- app/src/main/java/com/kickstarter/ui/activities/CheckoutActivity.java
- app/src/main/java/com/kickstarter/ui/activities/ProjectUpdatesActivity.java
- app/src/main/java/com/kickstarter/ui/activities/UpdateActivity.java
- app/src/main/java/com/kickstarter/ui/views/KSWebView.kt
Trying to catch some errors in the [`ProjectUpdatesActivity`](https://console.firebase.google.com/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/f7165a53c873de79256d56f51d77232e?time=last-ninety-days&sessionId=5E1C919D03D100011C2C293B8ED36190_DNE_0_v2) and [`UpdateActivity`](https://console.firebase.google.com/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/996998e6f710ab9964d1faaf2bde6daf?time=last-ninety-days&sessionId=5E1C92F500E10001199439C4FF808AF6_DNE_0_v2) in my pokeball.
we h8 bugz
Get in losers, we're fixing bugs. [mean girls reference](https://knowyourmeme.com/memes/get-in-loser-were-going-shopping)
OKAY SO, if you Read The Error Message™: 
```Attempt to read from field …
```
> [💦] NT-725 Cleaning up some context leaks

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/SearchViewModelTest.java
Adding `Search Button Clicked` event.
- Added `LakeEvent.SEARCH_BUTTON_CLICKED ` `const`
- Calling `lake.trackSearchButtonClicked ` when user clicks the search menu icon
- Added Lake tests in `SearchViewModelTest.testSearchProjectsWhenEnterSearchTerm` and `SearchViewModelTest.testSearchPagination`
[NT-818]
[NT-818]: https://kickstarter.atlassian.net/browse/NT-818
> [🕵🏾‍♀️] NT-818 Search Button Clicked event

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
Adding `Filter Clicked` event.
- Added `LakeEvent.FILTER_CLICKED ` `const`
- Calling `lake.trackFilterClicked ` when user clicks a Discovery filter in the drawer
- Updated Lake tests in `DiscoveryViewModelTest.testDrawerData` and `DiscoveryViewModelTest.testUpdateInterfaceElementsWithParams `
- Fixed bug with `Explore Sort Clicked` being called with previous sort value
[NT-817]
[NT-817]: https://kickstarter.atlassian.net/browse/NT-817
> [🔍] NT-817 Filter Clicked event

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/viewmodels/ActivityFeedViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/ActivityFeedViewModelTest.java
Adding `Activity Feed Viewed` event.
- Added `LakeEvent.ACTVITIY_FEED_VIEWED ` `const`
- Calling `lake.trackActivityFeedViewed ` when user views the Activity feed 
- Added Lake tests in `ActivityFeedViewModelTest.testActivitiesEmit `
[NT-816]
[NT-816]: https://kickstarter.atlassian.net/browse/NT-816
> [⚡️] NT-816 Activity Feed Viewed event

- app/src/main/res/layout/qualtrics_prompt.xml
Changing background color of Qualtrics prompt to `ksr_grey_300` #F0F0F0
So it's more distinct in Disco.
- Added `cardbackgroundColor` attribute to prompt `CardView`
| --- | --- |
| <img src=https://user-images.githubusercontent.com/1289295/72851581-096c7180-3c7a-11ea-88af-e3591039358b.png width=330/> | ![screenshot-2020-01-10_120245](https://user-images.githubusercontent.com/1289295/72851611-14270680-3c7a-11ea-9175-cd3547a88ffa.png) |
👀 View the prompt! (If you've dismissed it more than 3 times already, clear your data to reset the count)
[NT-792]
[NT-792]: https://kickstarter.atlassian.net/browse/NT-792
> [🎨] NT-792 Updating Qualtrics prompt background color

- app/src/main/java/com/kickstarter/libs/LakeTrackingClient.kt
Updating "partition-key" value in Data Lake events
To help with session tracking.
- When user is logged **in** the value of `partition-key` is `user.id`.
- When user is logged **out** the value of `partition-key` is `deviceDistinctId` that returns a non-null `String`.
No visuals~
tail your device's events in `ktk`
[NT-813]
[NT-813]: https://kickstarter.atlassian.net/browse/NT-813
> [ℹ️] NT-813 Updating "partition-key" value in Data Lake events

- app/src/main/java/com/kickstarter/services/LakeBackgroundService.kt
- app/src/main/java/com/kickstarter/services/LakeService.kt
Sending the client ID as a query param of requests to the Lake endpoint.
SECURITY
- Injected the `clientId` into `LakeBackgroundService` and passed it into `LakeService.track` that's annotated as a `Query` named `"client_id"`
An extremely redacted request log:
We don't currently test our network clients but I believe there is a ticket in the backlog.
Please check your friendly Logcat 🐱 on a debug build of the app for the Lake requests. The URL should contain a `client_id` query param. 
[NT-693]
[NT-693]: https://kickstarter.atlassian.net/browse/NT-693
> [🔒] NT-693 Adding client_id param to Lake requests

- app/src/main/java/com/kickstarter/libs/TrackingClientType.java
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
what it says on the tin
issa bug
- `TrackingClientType.sessionProperties` now sends `session_user_is_logged_in` instead of `session_user_logged_in`
- Updated `LakeTest`
[NT-826]
[NT-826]: https://kickstarter.atlassian.net/browse/NT-826
> [🕷] NT-826 Renaming session_user_logged_in property to session_user_is_logged_in

- app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
- app/src/test/java/com/kickstarter/libs/KoalaTest.kt
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
Removing volatile user tracking properties
The values Can Change™ 
- Removing volatile user attributes:
`backed_projects_count`
`facebook_account`
`is_admin`
`launched_projects_count`
`watched_projects_count`
- Updated `KoalaTest` and `LakeTest`.
Nothing visual
- ktk the staging lake
- check the Logcat in Android Studio
- Look at the dev project in Amplitude
[NT-831]
[NT-831]: https://kickstarter.atlassian.net/browse/NT-831
> [🚮] NT-831 Removing volatile user tracking properties

- app/src/main/java/com/kickstarter/libs/utils/DiscoveryUtils.java
- app/src/main/java/com/kickstarter/services/DiscoveryParams.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/EditorialViewModel.kt
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/EditorialViewModelTest.kt
Actually using magic sort as the default in Discovery
In https://github.com/kickstarter/android-oss/pull/240 I thought I was just making a copy change but I think we actually wanted to start sorting by `"magic"` 🙂 
I'm considering this both a bug and a feature!
- Renamed `DiscoveryParams.Sort.HOME` to `DiscoveryParams.Sort.MAGIC`
- `DiscoveryParams.Sort.toString` returns `"magic"` for `MAGIC`
- `DiscoveryParams.Sort.fromString` returns `MAGIC` for `"magic"`
Check your friendly LogCat.
`ktk` your user. `discover_sort` should now be `magic`
[NT-825]
[NT-825]: https://kickstarter.atlassian.net/browse/NT-825
> [🎩] NT-825 Changing home sort to magic but for real this time

- app/src/main/java/com/kickstarter/ApplicationModule.java
Hitting prod data Lake when hitting prod API.
We're prepping for 2.2.0 release and need to start hitting prod Data Lake so events get sent to the right Amplitude project.
- Removed comment and now return `Secrets.LakeEndpoint.PRODUCTION` if the API endpoint is production in `ApplicationModule.provideLakeEndpoint`
Nothing 2 c
Tail the prod data lake!
[NT-815]
[NT-815]: https://kickstarter.atlassian.net/browse/NT-815
> [💧] NT-815 Hitting prod data Lake in prod

- app/src/main/java/com/kickstarter/libs/TrackingClientType.java
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
Removing platform prepend from `session_os_version` tracking property.
It's not needed.
Removed `"Android"` prepend
no visual changes
[NT-850]
[NT-850]: https://kickstarter.atlassian.net/browse/NT-850
> [🔢] NT-850 session_os_version tracking property should only contain numbers.

- app/src/main/java/com/kickstarter/libs/TrackingClientType.java
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
Adds `session_client_platform` to session properties.
It's needed.
Added `session_client_platform` to session properties and updated test
no visual changes
[NT-851]
[NT-851]: https://kickstarter.atlassian.net/browse/NT-851
> [🛤] NT-851 Add session_client_platform to session properties

- app/src/main/graphql/checkout.graphql
- app/src/main/java/com/kickstarter/mock/factories/CheckoutFactory.kt
- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/models/Checkout.kt
- app/src/main/java/com/kickstarter/services/ApolloClientType.kt
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Adding `id` field to `Checkout` model
It will be used in the `Back a project` tracking events.
- Added `checkout.id` field to `CreateBacking` and `UpdateBacking` mutations.
- Added `id` field to `Checkout` model.
- `ApolloClientType.createBacking` and `updateBacking` now return a `Checkout`.
- Created `CheckoutFactory` to easily return mock `Checkout` objects for tests.
- Updated `PledgeFragmentViewModel` and `PledgeFragmentViewModelTest`.
Under the hood changes only.
Backing or updating a pledge should behave the same.
[NT-849]
[NT-849]: https://kickstarter.atlassian.net/browse/NT-849
> [ℹ️] NT-849 Adding id field to checkout model

- app/src/internal/java/com/kickstarter/ui/activities/InternalToolsActivity.java
- app/src/internal/res/layout/internal_tools_layout.xml
- app/src/internal/res/values/styles.xml
- app/src/main/res/values/strings.xml
Adding device identifier to `InternalToolsActivity`
When #731 is merged, it would be nice to know the device's distinct ID for Optimizely.
- Added a row to the `InternalToolsActivity` for the device identifier.
- Changed the row margins from `grid_3_half` to `grid_1` and the top padding from `activity_vertical_margin` to `grid_1` to condense the screen.
| --- | --- |
| ![screenshot-2020-02-12_104155](https://user-images.githubusercontent.com/1289295/74350949-74462f80-4d84-11ea-94a3-c244e6b5407e.png) | ![screenshot-2020-02-12_104206](https://user-images.githubusercontent.com/1289295/74350953-74462f80-4d84-11ea-9896-d9ababdc2e15.png) |
Take a peek at the Internal Tools.
[NT-840]
[NT-840]: https://kickstarter.atlassian.net/browse/NT-840
> [ℹ️] NT-840 Adding device identifier to InternalToolsActivity

- app/src/main/java/com/kickstarter/ui/viewholders/NativeCheckoutRewardViewHolder.kt
- app/src/main/res/layout/fragment_backing.xml
Reverting hiding reward IA in view/manage pledge screen. It will now display the backers count and estimated delivery.
They were hidden in #613 but they're back now.
- Added start and end margin to `BackingFragment` root view.
- Removed special `inset` behavior for `NativeCheckoutRewardCardViewHolder` except for `Select` button
| --- | --- |
| ![Screenshot_1581524534](https://user-images.githubusercontent.com/1289295/74354905-0bfa4c80-4d8a-11ea-808d-3007d034b509.png) | ![Screenshot_20200212-112328](https://user-images.githubusercontent.com/1289295/74354987-2f24fc00-4d8a-11ea-9246-69bff2207949.png) |
View or manage your pledge.
NT-805
> [ℹ️] NT-805 BackingFragment reward card IA

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Adding `Checkout Payment Page Viewed` event.
We have new Back a Project events.
- Added `LakeEvent.CHECKOUT_PAYMENT_PAGE_VIEWED` with value `"Project Page Pledge Button Clicked"`
- Added `KoalaUtils.pledgeDataProperties` since we also pass the same data for the `Select Reward Button Clicked` event
- Added `Koala.trackCheckoutPaymentPageViewed`
- Tracking when a user views the pledge screen of an unbacked project
- Updated tests in `PledgeFragmentViewModelTest`
[NT-846]
[NT-846]: https://kickstarter.atlassian.net/browse/NT-846
> [💳] NT-846 Checkout Payment Page Viewed event

- app/src/main/res/layout/fragment_backing.xml
Adding some bottom margin to the reward card of view/manage pledge screen.
So the divider has room to breathe.
`item_reward` now has `grid_4` bottom margin
| --- | --- |
| ![screenshot-2020-02-13_135643](https://user-images.githubusercontent.com/1289295/74468332-ae88fd00-4e68-11ea-9a2b-bd7d88f78f76.png) | ![screenshot-2020-02-13_134548](https://user-images.githubusercontent.com/1289295/74468330-adf06680-4e68-11ea-8fa6-e95d6b6cd652.png) |
Look at all that space.
[NT-805]
[NT-805]: https://kickstarter.atlassian.net/browse/NT-805
> [␠] NT-805 Missed bottom margin of reward in fragment_backing

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
- app/src/main/java/com/kickstarter/mock/factories/CheckoutDataFactory.kt
- app/src/main/java/com/kickstarter/ui/data/CheckoutData.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Adding `Pledge Submit Button Clicked` event.
We have new Back a Project events.
- Added `LakeEvent. PLEDGE_SUBMIT_BUTTON_CLICKED ` with value `"Pledge Submit Button Clicked"`
- Added `Koala. trackPledgeSubmitButtonClicked `
- Added `CheckoutData` and `CheckoutDataFactory `model to hold data needed for Checkout properties group
- Tracking when a user clicks the `"Pledge"` button in `PledgeFragmentViewModel`
- Added tests in `PledgeFragmentViewModelTest`
- Added `LakeTest` for checkout properties
- Fixed bug where `Project Page Pledge Button Clicked` event fired after user backed project because `take(1)` was used.
- Moved `reward_estimated_delivery_on` and `reward_title` to pledge property group.
- check the `Logcat` in Android …
> [🛍] NT-847 Pledge Submit Button Clicked event

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kickstarter/models/Project.java
- app/src/main/java/com/kickstarter/ui/activities/CampaignDetailsActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/CampaignDetailsViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/main/res/layout/activity_campaign_details.xml
- app/src/test/java/com/kickstarter/viewmodels/CampaignDetailsViewModelTest.kt
Added a new screen explicitly for the campaign details.
Prep for an experiment ⚗️
- Created new `CampaignDetailsActivity` to open campaign in webview. It has one output `url` that's the URL of the project's campaign.
- Now using `UrlUtils.appendPath` in Project url helper methods.
Tests.
Looks EYE dentical
| --- | --- |
| ![device-2020-02-14-180421 2020-02-14 18_06_38](https://user-images.githubusercontent.com/1289295/74575437-eff6d680-4f54-11ea-80dc-ad76ab4cfd10.gif) | ![device-2020-02-14-180421 2020-02-14 18_06_38](https://user-images.githubusercontent.com/1289295/74575437-eff6d680-4f54-11ea-80dc-ad76ab4cfd10.gif) |
Smash that read more button
[NT-875]
[NT-875]: https://kickstarter.atlassian.net/browse/NT-875
> [🕸] NT-875 Campaign details webview

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
- app/src/main/java/com/kickstarter/mock/factories/CheckoutDataFactory.kt
- app/src/main/java/com/kickstarter/ui/IntentKey.java
- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.java
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.java
Adding `Thanks Page Viewed` event.
We have new Back a Project events.
- Added `Koala.trackThanksPageViewed`
- Added `LakeEvent.THANKS_PAGE_VIEWED` with value `"Thanks Page Viewed"`
- `PledgeFragmentViewModel.Output.showPledgeSuccess` now emits a pair of `CheckoutData` and `PledgeData`
- `PledgeFragment.PledgeDelegate.pledgeSuccessfullyCreated` now takes in a pair of `CheckoutData` and `PledgeData`
- Added `IntentKey.CHECKOUT_DATA` and `PLEDGE_DATA`
- `ThanksActivity` is now started with `CheckoutData` and `PledgeData` to pass through to event
- Tracking `THANKS_PAGE_VIEWED` in `ThanksViewModel`
- Updated tests.
- Added tests in `ThanksViewModelTest`.
- Added test in `LakeEvent` for a successful checkout
- check the `Logcat` in …
> [🙏🏾] NT-848 Thanks Page Viewed event

- app/src/main/java/com/kickstarter/libs/ActivityRequestCodes.java
- app/src/main/java/com/kickstarter/ui/IntentKey.java
- app/src/main/java/com/kickstarter/ui/activities/CampaignDetailsActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/CampaignDetailsViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/main/res/layout/activity_campaign_details.xml
- app/src/test/java/com/kickstarter/viewmodels/CampaignDetailsViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Displaying native_project_page_campaign_details variants on live and not backed Campaign details screen.
🧬
- Added `ActivityRequestCodes.SHOW_REWARDS` when starting `CampaignDetailsActivity`
- Added `IntentKey.PROJECT_DATA` for passing `ProjectData` to started Activity
- `CampaignDetails`
- `CampaignDetailsActivity` is now started with `ProjectData`
- Added faux pledge container `campaign_details_pledge_container`
- `CampaignDetailsViewModel`
- Added `pledgeActionButtonClicked` input that is called when the user clicks the pledge action button.
- Added `goBackToProject` output that emits when we should dismiss this screen and show the rewards.
- Added `pledgeContainerIsVisible` output that emits a `Boolean` determining if the faux pledge container should be visible.
- Tests
- `Project`
- …
> [🧪] NT-888 Campaign details experiment on Campaign details page

- app/src/main/java/com/kickstarter/libs/OptimizelyEvent.kt
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectViewHolder.java
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Added Campaign Details Button Clicked Optimizely tracking event
So we can get those sweet funnel numbers.
- Created `OptimizelyEvent` file to hold event name constants.
- Added `OptimizelyEvent.CAMPAIGN_DETAILS_BUTTON_CLICKED` with value `"Campaign Details Button Clicked"`
- Added separate `ProjectViewHolder.Delegate` method `projectViewHolderBlurbVariantClicked` that is called when a user clicks the `Read more about the campaign` button.
- Tracking `CAMPAIGN_DETAILS_BUTTON_CLICKED` when `blurbVariantClicked` emits with a live, not backed project.
- Added tests to assert the webview is shown when `blurbVariantClicked` emits and `CAMPAIGN_DETAILS_BUTTON_CLICKED` is tracked for only live, not backed projects.
Take a look at the Android experiment results! I'm in `variant-2` …
> [🧪] NT-913 Campaign Details Button Clicked event

- app/src/main/java/com/kickstarter/services/interceptors/ApiRequestInterceptor.java
- app/src/main/java/com/kickstarter/services/interceptors/GraphQLInterceptor.kt
Adds the device identifier to our prepared request headers for requests to v1 endpoints and GraphQL queries/mutations.
In order to properly attribute our _Completed Checkout_ server-side events to Optimizely experimental variants, we need to send the `device_distinct_id` to the server so that Optimizely tracking calls can be made using the `device_distinct_id` instead of the user's ID.
Added a header, `Kickstarter-Android-App-UUID` which will be set using the [`FirebaseInstanceId`](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId) to `ApiRequestInterceptor` for all v1 requests and `GraphQLInterceptor` for all graphQL requests.
I learned~ that OkHttp (our networking library) doesn't print headers for intercepted GET requests. But it does for …
> [👤] NT-914 Adding distinct ID header to v1 and graphQL requests 

- app/src/main/java/com/kickstarter/libs/OptimizelyEvent.kt
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectViewHolder.java
- app/src/main/java/com/kickstarter/viewmodels/CampaignDetailsViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/CampaignDetailsViewModelTest.kt
Added `Campaign Details Pledge Button Clicked` event for Optimizely and fixed bug with campaign details opening twice.
So we can get those sweet funnel numbers.
- Added `OptimizelyEvent.CAMPAIGN_DETAILS_PLEDGE_BUTTON_CLICKED` with value `"Campaign Details Pledge Button Clicked"`
- Tracking `CAMPAIGN_DETAILS_PLEDGE_BUTTON_CLICKED` when `Back this project` button is clicked in `CampaignDetailsActivity`.
- Added tests to assert `CAMPAIGN_DETAILS_PLEDGE_BUTTON_CLICKED` is tracked when the button is clicked.
- Forgot to remove click listener from `read_more` in #755 when I gave the blurb variant its own click listener
Check your local logs!
[NT-916]
[NT-916]: https://kickstarter.atlassian.net/browse/NT-916
> [🦟] NT-916 Campaign Details Pledge Button Clicked event 

- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Added Project Page Pledge Button Clicked tracking event to Optimizely
So we can get those sweet funnel numbers.
- Tracking `PROJECT_PAGE_PLEDGE_BUTTON_CLICKED` when user clicks on the `Back this project` button and its variants (`View the reward`, `See the rewards`).
- Added tests in `ProjectViewModel` to ensure it's being tracked on for live, not backed projects 
Check those sweet logs.
[NT-915]
[NT-915]: https://kickstarter.atlassian.net/browse/NT-915
> [🧪] NT-915 Adding Project Page Pledge Button Clicked event to Optimizely

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
**Note:** This won't pass lint checks because `Koala.java` is too long. Please take a look at #759 first!
Adding `Log In or Signup Button Clicked` event.
- Added `LakeEvent.LOG_IN_OR_SIGNUP_BUTTON_CLICKED ` with value `"Log In or Signup Button Clicked"`
- Added `Koala.trackLogInSignUpButtonClicked`
- Tracking when a not logged in user clicks the tout button in `DiscoveryFragmentViewModel`
- Added separate test for `showLoginTest` in `DiscoveryFragmentViewModelTest`
[NT-917]
[NT-917]: https://kickstarter.atlassian.net/browse/NT-917
> [🛤] NT-917 Log In or Signup Button Clicked event

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/viewmodels/LoginToutViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.java
**Note:** This won't pass lint checks because `Koala.java` is too long. Please take a look at #759 first!
Adding `Log In or Sign Up Page Viewed` event.
- Added `LakeEvent.LOG_IN_OR_SIGN_UP_PAGE_VIEWED` with value `"Log In or Sign Up Page Viewed"`
- Added `Koala.trackLogInSignUpPageViewed` to track when a user lands on the login tout screen.
- Tracking `LOG_IN_OR_SIGN_UP_PAGE_VIEWED` in `LoginToutViewModel`
- There were no tracking tests in `LoginToutViewModelTest` so I added tests for the Data Lake.
[NT-918]
[NT-918]: https://kickstarter.atlassian.net/browse/NT-918
> [🛤] NT-918 Log In or Sign Up Page Viewed events

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/viewmodels/LoginToutViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.java
Adding `Facebook Log In or Signup Button Clicked` event.
- Added `LakeEvent.FACEBOOK_LOG_IN_OR_SIGNUP_BUTTON_CLICKED ` with value `"Facebook Log In or Signup Button Clicked"`
- Added `Koala.trackFacebookLogInSignUpButtonClicked `
- Tracking when a not logged in user clicks the Facebook sign in button in `LoginToutViewModel`
- Updated tests `DiscoveryFragmentViewModelTest`
[NT-919]
> [🛤] NT-919 Facebook Log In or Signup Button Clicked event

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/viewmodels/LoginToutViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.java
Adding `Sign Up Button Clicked` event.
- Added `LakeEvent.SIGN_UP_BUTTON_CLICKED` with value `"Sign Up Button Clicked"`
- Added `Koala.trackSignUpButtonClicked` to track when a user clicks on the sign up button in the `LoginToutActivity`.
- Tracking `SIGN_UP_BUTTON_CLICKED` in `LoginToutViewModel` when user clicks the sign up button
- Added test in `LoginToutViewModelTest`
[NT-921]
[NT-921]: https://kickstarter.atlassian.net/browse/NT-921
> [🛤] NT-921 Sign Up Button Clicked event

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/viewmodels/SignupViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/SignupViewModelTest.java
Adding `Sign Up Submit Button Clicked` event.
- Added `LakeEvent.SIGN_UP_SUBMIT_BUTTON_CLICKED` with value `"Sign Up Submit Button Clicked"`
- Added `Koala.trackLogInSubmitButtonClicked` to track when a user clicks the sign up button in the `SignupActivity`
- Tracking `SIGN_UP_SUBMIT_BUTTON_CLICKED` in `SignupViewModel` when user clicks the log in button
- Added test in `SignupViewModelTest`
[NT-923]
[NT-923]: https://kickstarter.atlassian.net/browse/NT-923
> [🛤] NT-923 Sign Up Submit Button Clicked event

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/viewmodels/ResetPasswordViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ResetPasswordViewModelTest.kt
Adding `Forgot Password Page Viewed` event.
- Added `LakeEvent.FORGOT_PASSWORD_PAGE_VIEWED` with value `"Forgot Password Page Viewed"`
- Added `Koala.trackForgotPasswordPageViewed` to track when a user views the `ResetPasswordActivity`
- Tracking `FORGOT_PASSWORD_PAGE_VIEWED` in `SignupViewModel` when user clicks the reset password button
- Added test in `ResetPasswordViewModelTest`
[NT-924]
[NT-924]: https://kickstarter.atlassian.net/browse/NT-924
> [🛤] NT-924 Forgot Password Page Viewed event

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/viewmodels/TwoFactorViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/TwoFactorViewModelTest.java
Adding `Two-Factor Confirmation Viewed` event.
- Added `LakeEvent.TWO_FACTOR_CONFIRMATION_VIEWED` with value `"Two-Factor Confirmation Viewed"`
- Added `Koala.trackTwoFactorConfirmationViewed` to track when a user views the `TwoFactorActivity`
- Tracking `TWO_FACTOR_CONFIRMATION_VIEWED` in `TwoFactorViewModel` when user views the 2FA screen
- Added tests in `TwoFactorViewModelTest`
[NT-925]
[NT-925]: https://kickstarter.atlassian.net/browse/NT-925
> [🛤] NT-925 Two-Factor Confirmation Viewed event

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/libs/KoalaTest.kt
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
Adding `context_pledge_flow` to `Project Page Viewed` and `Project Page Pledge Button Clicked` events
This value is expected for Back a Project events despite its potential to be `null`.
- `Koala. trackProjectShow` now takes in a `ProjectData` object instead of a separate `Project` and `RefTag`s
- `Koala. trackProjectPageViewed` and `trackProjectPagePledgeButtonClicked` now takes in `ProjectData` and `PledgeFlowContext instead of a separate `Project` and `RefTag`s
- Added helper method `ProjectViewModel.pledgeFlowContext` to derive the `PledgeFlowContext` from a `Project` and `User`
- Added helper method `ProjectViewModel.storeCurrentCookieRefTag` to ensure the `ProjectData` has the correct `cookieRefTag`.
The tests for `Project` properties broke because of DST. The `ProjectFactory` now …
> [⏱] NT-951 Adding context_pledge_flow to Project Page Viewed and Project Page Pledge Button Clicked events

- app/src/main/res/layout/item_update_card.xml
Updates design polish.
So we can LOOK GREAT.
- Body text color is styled as `BodyPrimary`.
- Likes and comments text are styled as `BodySecondary`.
- Displaying likes and comments in backers only updates.
- Backers only `TextView` has `grid_9` margin on top and bottom.
| --- | --- |
| ![screenshot-2020-03-03_111353](https://user-images.githubusercontent.com/1289295/75795273-17fd7c80-5d40-11ea-86ca-0daad38416e3.png) | ![screenshot-2020-03-03_111014](https://user-images.githubusercontent.com/1289295/75794957-93126300-5d3f-11ea-9d6d-fbcd7a3f36ad.png) |
Take a look!
[NT-958]
[NT-958]: https://kickstarter.atlassian.net/browse/NT-958
> [✨] NT-958 Updates design polish

- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/libs/ExperimentsClientType.kt
- app/src/main/java/com/kickstarter/libs/OptimizelyExperimentsClient.kt
- app/src/main/java/com/kickstarter/libs/utils/ExperimentUtils.kt
- app/src/main/java/com/kickstarter/mock/MockExperimentsClientType.kt
- app/src/test/java/com/kickstarter/libs/utils/ExperimentUtilsTest.kt
Adding `distinct_id` user attribute to Optimizely in non production environments.
So we can filter events by distinct ID for non production environments for testing purposes.
Adding `distinct_id` user attribute to Optimizely:
- `ExperimentUtils.attributes` now also takes in an `ApiEndpoint`. When we're not on `PRODUCTION`, we send the `distinct_id` property.
- `ExperimentsClientType.attributes` now takes in an `ApiEndpoint`.
- `OptimizelyExperimentsClient` constructor now takes in an `ApiEndpoint`.
- `MockExperimentsClientType` constructor now takes in an `ApiEndpoint`.
- Added secondary helper constructors for `MockExperimentsClientType`.
- Added tests in `ExperimentUtilsTest` for production and non production environments.
No visuals~
Activate™ an experiment in a non production …
> [🧫] NT-959 Adding `distinct_id` user attribute to Optimizely in non prod environments

- app/src/main/java/com/kickstarter/models/Project.java
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectViewHolder.java
- app/src/main/java/com/kickstarter/viewmodels/ProjectHolderViewModel.java
- app/src/main/res/layout/project_creator_info.xml
- app/src/test/java/com/kickstarter/viewmodels/ProjectHolderViewModelTest.java
Disabling project updates container in Project page when there are no updates.
If there are no updates, there's nothing 2 c.
- Disabling updates row in ProjectViewHolder when a project doesn't have any updates.
- Added helper method `hasUpdates` to `Project` model.
- Added output `updatesContainerIsEnabled` to `ProjectHolderViewModel` that emits a `Boolean` determining if the updates row should be enabled
- Cleaned up unnecessary dividers and strange padding in `project_creator_info`
- Tests for `updatesContainerIsEnabled`
| --- | --- |
| ![screenshot-2020-03-02_113711](https://user-images.githubusercontent.com/1289295/75696921-5597d200-5c7a-11ea-83c5-6073d3f7c346.png) | ![screenshot-2020-03-02_113415](https://user-images.githubusercontent.com/1289295/75696919-54ff3b …
> [0️⃣] NT-949 Disabling updates row when there are no updates 

- app/src/main/java/com/kickstarter/ui/activities/ProjectUpdatesActivity.java
- app/src/main/java/com/kickstarter/viewmodels/ProjectUpdatesViewModel.java
- app/src/main/res/layout/activity_account.xml
- app/src/main/res/layout/activity_change_email.xml
- app/src/main/res/layout/activity_change_password.xml
- app/src/main/res/layout/activity_create_password.xml
- app/src/main/res/layout/activity_message_creator.xml
- app/src/main/res/layout/activity_project.xml
- app/src/main/res/layout/activity_settings_payment_methods.xml
- app/src/main/res/layout/activity_updates.xml
- app/src/main/res/layout/form_new_card.xml
- app/src/main/res/values/dimens.xml
- app/src/test/java/com/kickstarter/viewmodels/ProjectUpdatesViewModelTest.java
Added a horizontal progress bar to the project updates list.
So the user has some indication something is happening when they get to the updates screen.
- Added output `horizontalProgressBarIsGone` to `ProjectUpdatesViewModel`
- Added `updates_progress_bar` to `activity_project_updates`
- Tests for `horizontalProgressBarIsGone`
| After 🦋 |
| --- |
| ![device-2020-03-02-123102 2020-03-02 12_31_40](https://user-images.githubusercontent.com/1289295/75701433-c7bfe500-5c81-11ea-84c7-5714168d5125.gif) |
View those sweet updates.
[NT-952]
[NT-952]: https://kickstarter.atlassian.net/browse/NT-952
> [⏳] NT-952 Project updates progress bar

- app/src/main/graphql/project.graphql
- app/src/main/java/com/kickstarter/mock/factories/CreatorDetailsFactory.kt
- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/models/CreatorDetails.kt
- app/src/main/java/com/kickstarter/services/ApolloClientType.kt
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectHolderViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/ProjectHolderViewModelTest.java
Adding `ProjectCreatorDetails` query and corresponding outputs in `ProjectHolderViewModel`.
Laying the foundation for the `native_project_page_conversion_creator_details` experiment.
- Added `project.graphql` with `ProjectCreatorDetails` query.
- Added `creatorDetails` call to `ApolloClientType` interface and implemented in subtypes that returns a `CreatorDetails` object.
- And `creatorBackedProjectsCount` and `creatorLaunchedProjectsCount` outputs to `ProjectHolderViewModel`.
- Added `CreatorDetailsFactory` for tests.
- Added tests to `ProjectHolderViewModelTest`.
Nothing 2 c
Does the code look legit?
[NT-929]
[NT-929]: https://kickstarter.atlassian.net/browse/NT-929
> [🔢] NT-929 Adding ProjectCreatorDetails query

- app/src/main/res/drawable/circle_blue_white_stroke.xml
- app/src/main/res/drawable/circle_grey_500.xml
- app/src/main/res/drawable/rect_grey_500_loading.xml
- app/src/main/res/layout-land/project_media_header.xml
- app/src/main/res/layout/creator_avatar_verified.xml
- app/src/main/res/layout/loading_placeholder_creator_info.xml
- app/src/main/res/layout/loading_placeholder_footnote.xml
- app/src/main/res/layout/project_main_layout.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles.xml
The UI changes for the `native_project_page_conversion_creator details` experiment.
I'm splitting up NT-934 so the PR isn't so big!
- Added `circle_blue_white_stroke.xml` `Drawable` for the verified icon background.
- Added `circle_grey_500.xml` `Drawable` for the loading placeholder of the avatar.
- Added `rect_grey_500_loading.xml` `Drawable` for the loading placeholder of the creator details text.
- Added `creator_avatar_verified.xml` container for the verified creator avatar.
- Added `loading_placeholder_creator_info.xml` for the loading state of the creator details.
- Added variant and loading layout to `project_media_header.xml` in landscape and `project_main_layout.xml` in portrait.
- Added `project_avatar_check_width` and `project_avatar_check_height` with value of `13dp` for the …
> [🎨] NT-986 Adding XML only changes for creator details experiment

- app/src/main/java/com/kickstarter/ApplicationModule.java
Decreasing Optimizely event dispatch interval from 10 seconds to 2 seconds.
We are playing telephone with Optimizely events coming from both the client and the backend and there is a race condition if a user completes a checkout on the backend before the client side events.
~`60L`~ `2L`
There are no visual changes!
Smash that pledge button.
[NT-985]
[NT-985]: https://kickstarter.atlassian.net/browse/NT-985
> [🔮] NT-985 Decreasing Optimizely event dispatch interval

- app/src/main/java/com/kickstarter/libs/utils/ProjectViewUtils.kt
- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectViewHolder.java
- app/src/main/java/com/kickstarter/viewmodels/ProjectHolderViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/main/res/layout-land/project_main_layout.xml
- app/src/main/res/layout/activity_project.xml
- app/src/test/java/com/kickstarter/viewmodels/ProjectHolderViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Removing native checkout feature flag support from the Project page
Tech debt.
- Removed `backProjectButtonClicked`, `managePledgeButtonClicked`, `viewPledgeButtonClicked` inputs.
- Removed `horizontalProgressBarIsGone`, `pledgeContainerIsGone`, `projectActionButtonContainerIsGone`, `startBackingActivity`, `startCheckoutActivity`, `startManagePledgeActivity` and outputs.
- Cleaned up tests.
- Removed `project_action_buttons` container.
- Removed `project_action_buttons` container.
- Removed `projectActionButtonContainerIsGone` output.
- Cleaned up tests.
- Removed `setActionButton` since it's no longer used.
Native checkout only.
Check out, natively.
[NT-965]
[NT-965]: https://kickstarter.atlassian.net/browse/NT-965
> [␡] NT-965 Removing native checkout feature flag support from the Project page

- app/src/main/java/com/kickstarter/ui/IntentKey.java
- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ThanksActivity.java
- app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.java
Removing native checkout feature flag support from the Thanks page
Tech debt.
- Removed `resumeDiscoveryActivity` output.
- Cleaned up tests.
- Removed `IntentKey.NATIVE_CHECKOUT_ENABLED` since it's no longer used.
Native checkout only.
Dismissing the Thanks page always goes back to the last screen, no longer to Discovery when Native checkout is disabled.
[NT-965]
[NT-965]: https://kickstarter.atlassian.net/browse/NT-965
> [␡] NT-965 Removing native checkout feature flag support from the Thanks page

- app/src/main/java/com/kickstarter/libs/ExperimentsClientType.kt
- app/src/main/java/com/kickstarter/libs/OptimizelyExperimentsClient.kt
- app/src/main/java/com/kickstarter/libs/utils/ExperimentUtils.kt
- app/src/main/java/com/kickstarter/mock/MockExperimentsClientType.kt
- app/src/main/java/com/kickstarter/viewmodels/CampaignDetailsViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectHolderViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/libs/utils/ExperimentUtilsTest.kt
- app/src/test/java/com/kickstarter/viewmodels/CampaignDetailsViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Adding `session_app_release_version` and `session_referrer_credit` attributes to Optimizely.
We may need to exclude some users from experiments by version. The `referrer_credit` was also in the sheet.
- Added `session_app_release_version` and `session_referrer_credit` attributes to Optimizely client.
- Added `ExperimentData` to wrap around `User` and `RefTag`s info.
- Updated tests.
- Alphabetized methods and attributes like I should have in the first place 😅 
No visuals~
You can see the properties if you filter the logs by `Optly`.
[NT-990]
[NT-990]: https://kickstarter.atlassian.net/browse/NT-990
> [🔮] NT-990 Adding additional Optimizely properties

- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Tracking `Campaign Details Button Clicked` in Optimizely when control blurb is clicked.
So we can get those sweet funnel numbers.
- Tracking `Campaign Details Button Clicked` in Optimizely when control blurb is clicked in `ProjectViewModel`.
- Added tests to assert `Campaign Details Button Clicked` is tracked when the button is clicked on live and not backed projects only.
Check your local logs!
Check your data dog logs!
[NT-989]
[NT-989]: https://kickstarter.atlassian.net/browse/NT-989
> [🛤] NT-989 Tracking `Campaign Details Button Clicked` for control variant

- app/src/internal/java/com/kickstarter/ui/activities/FeatureFlagsActivity.kt
- app/src/internal/res/layout/activity_feature_flags.xml
- app/src/internal/res/layout/item_feature_flag_override.xml
- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/libs/Environment.java
- app/src/main/java/com/kickstarter/libs/qualifiers/NativeCheckoutPreference.kt
- app/src/main/java/com/kickstarter/ui/SharedPreferenceKey.java
- app/src/main/java/com/kickstarter/viewmodels/ProjectHolderViewModel.java
- app/src/main/res/values/strings.xml
Removing native checkout feature flag support from internal tools
Maintaining.
- Removed native checkout feature flag override
- Removed override container
- Removed `Native_Checkout`
- Deleted `NativeCheckoutPreference`
- Removed `nativeCheckoutPreference`
- Removed `NATIVE_CHECKOUT`
- Removed unused `nativeCheckoutPreference`
- Removed `NativeCheckoutPreference` dependency injection
| --- | --- |
| ![screenshot-2020-03-16_165145](https://user-images.githubusercontent.com/1289295/76799538-1902c500-67a8-11ea-9a5d-4eabf59c6243.png) | ![screenshot-2020-03-16_165733](https://user-images.githubusercontent.com/1289295/76799539-1902c500-67a8-11ea-91f2-d07b33e639c6.png) |
^
[NT-965]
[NT-965]: https://kickstarter.atlassian.net/browse/NT-965
> [␡] NT-965 Removing native checkout feature flag support from internal tools

- app/src/main/java/com/kickstarter/ui/adapters/RewardsAdapter.kt
- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
- app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
- app/src/main/java/com/kickstarter/ui/viewholders/RewardViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
Renaming files that start with `NativeCheckoutReward` to just `Reward`.
Prefixing files with NativeCheckout is no longer necessary since there's only one way to pledge.
- Renamed `NativeCheckoutRewardsAdapter` to `RewardsAdapter`
- Remamed `NativeCheckoutRewardViewHolder` to `RewardViewHolder`
- Renamed `NativeCheckoutRewardViewHolderViewModel` to `RewardViewHolderViewModel`
- Renamed `NativeCheckoutRewardViewHolderViewModelTest` to `RewardViewHolderViewModelTest`
nothing 2 c
Do the tests pass?
[NT-968]
[NT-968]: https://kickstarter.atlassian.net/browse/NT-968
> [🆕] NT-968 Removing NativeCheckout prefix

- app/src/main/java/com/kickstarter/libs/FeatureKey.java
- app/src/test/java/com/kickstarter/libs/utils/ConfigUtilsTest.kt
Removed `FeatureKey.ANDROID_NATIVE_CHECKOUT`
Feature flag is over.
- Updated `ConfigUtilsTest` that used key.
N/A
N/A
[NT-965]
[NT-965]: https://kickstarter.atlassian.net/browse/NT-965
> [␡] NT-965 Removed `FeatureKey.ANDROID_NATIVE_CHECKOUT`

- app/src/main/java/com/kickstarter/libs/utils/BackingUtils.java
- app/src/main/java/com/kickstarter/libs/utils/ProjectViewUtils.kt
- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/main/res/color/button_pledge_error.xml
- app/src/main/res/layout/pledge_container.xml
- app/src/test/java/com/kickstarter/libs/utils/BackingUtilsTest.java
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
**Please note:** I am aware _errored_ is not a word but that's the word we're using in the app!
Displaying errored backing status in pledge container summary.
So users can know if their pledge was unsuccessfully collected when they're on the project page.
- Added helper `isErrored` that returns true when a backing's status is `"errored"`
- Added tests in `BackingUtilsTest`
- Added support for returning `R.color.button_pledge_error` in `pledgeActionButtonColor` when the Backing is errored.
- Added support for returning `R.string.Manage` in `pledgeActionButtonText` when the Backing is errored.
- Renamed output `backingDetails` to `backingDetailsSubtitle`.
- Added output `backingDetailsTitle` that returns a String resource ID for the title `TextView`.
- Added tests for errored backings in …
> [⛔️] NT-660 Displaying errored backing status in pledge container summary

- app/build.gradle
- app/src/main/graphql/activity.graphql
- app/src/main/graphql/schema.json
- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/libs/graphql/DateTimeAdapter.kt
- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/models/ErroredBacking.kt
- app/src/main/java/com/kickstarter/services/ApolloClientType.kt
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
**Please note:** This PR is _**BIG**_ because I updated the graphQL schema with the latest changes. You don't need to look at `schema.json`
Added network call to fetch errored backings via Apollo.
We're going to display them in app 🔜 
- Updated graphQL schema.
- Added `ErroredBackings` query
- Added `ErroredBacking` model
- Added `DateTimeAdapter` to deserialize `DateTime` objects from responses. Attached adapter in `provideApolloClient` injection method.
- Added `"ISO8601DateTime"` to `apollo.customTypeMapping` in `build.gradle`
- Added `erroredBackings` to that's implemented in `KSApolloClient` for real builds and `MockApolloClient` for tests
no visuals
How's the code look?
[NT-1048]
[NT-1048]: https://kickstarter.atlassian.net/browse/NT-1048
> [⛔️] NT-1048 Added graphQL call to get errored backings

- app/src/main/res/layout/item_header_errored_backings.xml
Added layout for errored backings header.
[We need it](https://www.figma.com/file/6GrAfzXmwgqdCaRGe1Ubyt/Checkout?node-id=1%3A13040)
- Added `item_header_errored_backings.xml`
Does it look legit? 🕵 
[NT-1049]
[NT-1049]: https://kickstarter.atlassian.net/browse/NT-1049
> [🎨] NT-1049 Added header layout for errored backings in Activity feed

- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/ui/data/PledgeReason.kt
- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Showing the pledge screen when users click the `Fix` button in the Backing screen
So users can fix their pledge 🔜 The actual fixin will be in NT-666 😈 
- Added new `PledgeReason` `FIX_PLEDGE`
- Added `BackingDelegate.showFixPaymentMethod`
- `BackingFragmentViewModel`
- Added input `fixPaymentMethodButtonClicked` and matching output `notifyDelegateToShowFixPledge`
- Tests
- Implements new `BackingDelegate.showFixPaymentMethod`
- `ProjectViewModel`
- Added input `fixPaymentMethodButtonClicked` that will cause `showUpdatePledge` to emit with `PledgeReason.FIX_PLEDGE`
- Tests
Smash that `Fix` button
[NT-1031]
[NT-1031]: https://kickstarter.atlassian.net/browse/NT-1031
> [⛔️] NT-1031 Navigating to pledge screen when users click "Fix"

- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/ui/activities/ActivityFeedActivity.java
- app/src/main/java/com/kickstarter/ui/adapters/ActivityFeedAdapter.java
- app/src/main/java/com/kickstarter/viewmodels/ActivityFeedViewModel.java
- app/src/test/java/com/kickstarter/ui/adapters/ActivityFeedAdapterTest.java
- app/src/test/java/com/kickstarter/viewmodels/ActivityFeedViewModelTest.java
Displaying errored backings in Activity feed. 
**Plz note:** I will automatically open the view pledge screen in a separate PR.
So users know they have pledges that have failed.
- Added `errorBackings` output that emits list of logged in user's errored backings
- Added `startFixPledge` output that emits when the `ProjectActivity` should be started.
- Tests
| Activity feed | Navigating to project page |
| --- | --- |
| <img src=https://user-images.githubusercontent.com/1289295/77952625-f7bad200-7299-11ea-920b-b43b531bee67.png width=330/> | ![device-2020-03-30-151745 2020-03-30 15_21_02](https://user-images.githubusercontent.com/1289295/77952713-14efa080-729a-11ea-83b7-ed7373bb6d4d.gif) |
View the Activity feed if you have an errored backing!
[NT-1051]
[NT-1051]: …
> [⛔️] NT-1051 Displaying errored backings in Activity feed

- app/src/main/java/com/kickstarter/libs/ExperimentsClientType.kt
- app/src/main/java/com/kickstarter/libs/OptimizelyEvent.kt
- app/src/main/java/com/kickstarter/libs/OptimizelyExperimentsClient.kt
- app/src/main/java/com/kickstarter/libs/utils/ExperimentUtils.kt
- app/src/main/java/com/kickstarter/mock/MockExperimentsClientType.kt
- app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.java
- app/src/test/java/com/kickstarter/libs/utils/ExperimentUtilsTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.java
Tracking `App Completed Checkout` event on the Thanks page
So we can track revenue from experiments!
- Added `ExperimentRevenueData` data class to hold models needed for checkout tags
- Added `checkoutTags` method to return map of checkout properties
- Added tests for `checkoutTags` for US and non US project
- Added `trackRevenue` method that takes in event key and `ExperimentRevenueData`
- Implemented in `OptimizelyExperimentsClient` and `MockExperimentsClientType`
- Added `tags` field to `OptimizelyEvent` to helper `ExperimentsEvent` class
- Added `APP_COMPLETED_CHECKOUT` with value `"App Completed Checkout"`
- Tracking `APP_COMPLETED_CHECKOUT` if `CheckoutData` and `PledgeData` are present
- Added tests for checking that `APP_COMPLETED_CHECKOUT` is tracked 
- …
> [🤑] NT-1024 App Completed Checkout event

- app/src/main/java/com/kickstarter/ui/IntentKey.java
- app/src/main/java/com/kickstarter/ui/activities/ActivityFeedActivity.java
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Displaying View pledge when clicking `Manage` of an errored backing in the Activity feed
Save a click
- Added `IntentKey.EXPAND_PLEDGE_SHEET` that is called when we want t…o show the pledge sheet expanded as soon as the `ProjectActivity` is started.
- Adding to `ProjectActivity` `Intent` in `ActivityFeedActivity.startFixPledge`
- `ProjectViewModel.expandPledgeSheet` emits when the `Intent` contains a `true` value for the `Extra` `EXPAND_PLEDGE_SHEET`
- Added tests for when `EXPAND_PLEDGE_SHEET` is `true`, `false`, or `null`
| --- | --- |
| ![device-2020-03-31-144931 2020-03-31 14_57_35](https://user-images.githubusercontent.com/1289295/78064750-33b86a80-7360-11ea-95fa-24f5ca05b0d7.gif) | ![device-2020-03-30-151745 2020-03-30 …
> [⛔️] NT-1057 Automatically expanding pledge sheet when fixing pledge

- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
**Please note:** The `Toolbar` does not live in the `PledgeFragment` and is not part of this ticket.
Pledge screen UI when fixing an errored backing's payment
So users **can only** change their payment method when fixing an errored backing.
- Adding support for `PledgeReason.FIX_PLEDGE` UI (it looks identical to updating your pledge).
- The pledge summary is **visible** if the pledge had shipping.
- The shipping summary is **visible** if the pledge had shipping.
- The total is **visible**
- The payment container is **visible**
- The pledge section is **hidden**
- The shipping section is **hidden**
- The update pledge button is **hidden**
- Tests
- The tests are almost identical to `PledgeReason.UPDATE_PAYMENT` but `"Update Payment Method Button Clicked"` is not tracked. There will be a …
> [⛔️] NT-1080 Pledge screen UI when fixing an errored backing's payment

- app/src/main/java/com/kickstarter/viewmodels/RewardCardViewHolderViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardCardViewHolderViewModelTest.kt
Enabling reselecting failed payment method
So users can retry their problematic card.
- Enabling reselecting failed payment method.
- Added helper methods for `buttonEnabled` and `buttonCTA` since the logic is more complex with the support of retrying errored payment methods.
- Tests
The problematic 0341 card can be reselected.
The tests are most helpful here.
NT-1079
> [💳] NT-1079  Enabling reselecting failed payment method

- app/src/main/java/com/kickstarter/ui/viewholders/RewardCardViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardCardViewHolderViewModel.kt
- app/src/main/res/layout/reward_card_details.xml
- app/src/test/java/com/kickstarter/viewmodels/RewardCardViewHolderViewModelTest.kt
Showing failed indicator icon on failed payment method
So users know what card was problematic.
- Added output `failedIndicatorIconIsVisible` that emits a `Boolean` that represents if the payment method was the errored payment method.
- Tests
- Added `ImageView` `failed_indicator_icon`
Take a look at your failed payment method 👀 
[NT-1078]
[NT-1078]: https://kickstarter.atlassian.net/browse/NT-1078
> [💳] NT-1078 Showing failed indicator icon on failed payment method

- app/src/main/java/com/kickstarter/libs/utils/Secrets.java.example
- app/src/main/java/com/kickstarter/services/KSUri.java
**Please note:** This PR depends on the updated secrets https://github.com/kickstarter/native-secrets/pull/68
Deleting Android Pay references.
Android Pay isn't supported in this app
- Removing placeholder `Secrets.RegExpPattern.ANDROID_PAY_1` and `Secrets.RegExpPattern.ANDROID_PAY_2`
- Removing `KSUri.isAndroidPayUri` since it's no longer used.
No visuals
Circle CI
[NT-1082]
[NT-1082]: https://kickstarter.atlassian.net/browse/NT-1082
> [🚮] NT-1082 Deleting Android Pay references

- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/res/layout/fragment_pledge_section_reward_summary.xml
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Updating no reward copy in Pledge screen
3rd time's the charm 😛 
- `rewardTitle` output now emits a `String` that is the reward's title if available or else the project name
- Added helper method `rewardTitle`
- Removed `setRewardTitle` method since it's no longer needed
- `reward_title` shows max `2` lines and ellipses at the `end` of the text
| After 🦋| After (but bigger) 🦋 | Before 🐛 |
| ![screenshot-2020-04-01_190928](https://user-images.githubusercontent.com/1289295/78194937-6dff3600-744c-11ea-8247-82e2f0c60132.png) | ![screenshot-2020-04-01_190918](https://user-images.githubusercontent.com/1289295/78194933-6cce0900-744c-11ea-9282-c40f4ef55685.png) | ![screenshot-2020-04-01_190209](https://user-images.githubusercontent.com/1289295/78194559-80c53b00- …
> [📄] NT-802 Updating no reward copy in Pledge screen

- app/src/main/java/com/kickstarter/ui/viewholders/ErroredBackingViewHolder.kt
- app/src/main/res/values-de/strings_i18n.xml
- app/src/main/res/values-es/strings_i18n.xml
- app/src/main/res/values-fr/strings_i18n.xml
- app/src/main/res/values-ja/strings_i18n.xml
- app/src/main/res/values/strings_i18n.xml
Added new copy for errored backings' final collection date.
This copy is better!
- Added (untranslated) `Fix_within_time_remaining` string resource
- Using `Fix_within_time_remaining` in `ErroredBackingViewHolder.kt`
| --- | --- |
| ![screenshot-2020-04-03_113203](https://user-images.githubusercontent.com/1289295/78379563-8da77300-75a0-11ea-9453-9b69193e999f.png) | ![screenshot-2020-03-30_120246](https://user-images.githubusercontent.com/1289295/78379519-7cf6fd00-75a0-11ea-8e8e-e70c1c9f9c15.png) |
^
[NT-1116]
[NT-1116]: https://kickstarter.atlassian.net/browse/NT-1116
> [⛔️] NT-1116 Errored backings deadline warning copy

- app/src/main/res/layout/item_errored_backing.xml
- app/src/main/res/values-de/strings_i18n.xml
- app/src/main/res/values-es/strings_i18n.xml
- app/src/main/res/values-fr/strings_i18n.xml
- app/src/main/res/values-ja/strings_i18n.xml
- app/src/main/res/values/strings_i18n.xml
Added new a11y copy for errored backings icon.
So that icon has some context for users who use TalkBack™.
- Added (untranslated) `Alert` string resource
- Using `Alert` for `contentDescription` of `ic_icon_alert`
Turn on TalkBack and navigate to the Activity feed with an errored backing.
[NT-1117]
[NT-1117]: https://kickstarter.atlassian.net/browse/NT-1117
> [🗣] NT-1117 Errored backings icon a11y

- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/ui/itemdecorations/RewardCardItemDecoration.kt
- app/src/main/res/layout/item_reward_add_card.xml
- app/src/main/res/layout/item_reward_credit_card.xml
- app/src/main/res/layout/item_reward_placeholder_card.xml
- app/src/main/res/values/dimens.xml
Payment methods in the Pledge screen are now displayed vertically
This is the first step in the payment methods redesign.
- `cards_recycler` orientation is now `VERTICAL`
- Removed `stored_card_width`. All cards are now full width.
- Removed special logic for stored cards margins
|  After 🦋 | Before 🐛 |
| --- | --- |
| ![screenshot-2020-04-03_142224](https://user-images.githubusercontent.com/1289295/78393008-1f21df80-75b7-11ea-9c49-7992e5da3508.png) | ![screenshot-2020-04-03_141451](https://user-images.githubusercontent.com/1289295/78393006-1e894900-75b7-11ea-8b1e-c5463fb15d1e.png) 
N/A
[NT-1120]
[NT-1120]: https://kickstarter.atlassian.net/browse/NT-1120
> [⬇] NT-1120 Vertical payment methods in Pledge screen

- app/src/main/java/com/kickstarter/ui/viewholders/RewardCardUnselectedViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardCardUnselectedViewHolderViewModel.kt
- app/src/main/res/layout/item_reward_unselected_card.xml
- app/src/main/res/values-de/strings_i18n.xml
- app/src/main/res/values-es/strings_i18n.xml
- app/src/main/res/values-fr/strings_i18n.xml
- app/src/main/res/values-ja/strings_i18n.xml
- app/src/main/res/values/strings_i18n.xml
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardCardUnselectedViewHolderViewModelTest.kt
Updating the copy for when a card is not allowed.
New copy party.
- Added `This_project_has_a_set_currency_that_cant_process_this_option` string and set it as the text for `card_not_allowed_warning`
- Removed `projectCountry` output because it's no longer needed
- Fixed bug where a card that is not allowed could be selected by default
- Added test for when the first card is not allowed
- Added test for when none of the cards are allowed
| After 🦋 | Before 🐛|
| --- | --- |
| ![screenshot-2020-04-08_154955](https://user-images.githubusercontent.com/1289295/78828777-3a279180-79b3-11ea-8661-056e3a517e81.png) | ![screenshot-2020-04-03_200313](https://user-images.githubusercontent.com/1289295/78828823-4dd2f800-79b3-11ea-9382-2ad9b966c70b.png) |
Try to pledge to a project with a card that's not …
> [💳] NT-1123 Card not allowed copy

- app/src/main/res/layout/fragment_pledge_section_footer.xml
Adding `Continue` and `ProgressBar` button in pledge screen footer.
So I can use them in future PRs and not have conflicts in this file.
- Added `pledge_footer_continue_button` button
- Added fake `pledge_footer_pledge_button_progress` button
Screenshots from XML previews in Android Studio
| Continue | Progress | Pledge |
| ![Screen Shot 2020-04-09 at 11 16 50 AM](https://user-images.githubusercontent.com/1289295/78911527-6a733c80-7a54-11ea-9413-a0a736a675b2.png) | ![Screen Shot 2020-04-09 at 11 17 26 AM](https://user-images.githubusercontent.com/1289295/78911528-6b0bd300-7a54-11ea-8911-a6ca634fb584.png) | ![Screen Shot 2020-04-09 at 11 18 11 AM](https://user-images.githubusercontent.com/1289295/78911529-6b0bd300-7a54-11ea-9e74-a364e7018cba.png) |
These buttons are …
> [🎨] NT-1111 Adding 2 buttons in the new pledge footer

- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/res/layout/fragment_pledge_section_footer.xml
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
**Note: ** Please review #830 first.
Displaying progress state when user clicks pledge button and request is in progress.
So users know when their pledge has been submitted.
- Added output `pledgeProgressIsGone` that emits a `Boolean` determining if the pledge `ProgressBar` should be visible.
- `pledgeProgressIsGone` has the same behavior as `updatePledgeProgressIsGone` because `updatePledgeProgressIsGone` will be removed when the `Update Pledge` button is removed
- Disabling the `Pledge` button when a pledge is being created.
- Tests...so many tests
Smash that pledge button.
[NT-1129]
[NT-1129]: https://kickstarter.atlassian.net/browse/NT-1129
> [🔌] NT-1129 Adding progress state for pledging

- app/src/main/res/layout/item_reward_selected_card.xml
- app/src/main/res/layout/item_reward_unselected_card.xml
- app/src/main/res/values-de/strings_i18n.xml
- app/src/main/res/values-es/strings_i18n.xml
- app/src/main/res/values-fr/strings_i18n.xml
- app/src/main/res/values-ja/strings_i18n.xml
- app/src/main/res/values/strings_i18n.xml
Payment methods a11y
So users who use voice assistance know which card is selected
- Added new strings `Selected_card` and `Select this card`
- Added content descriptions for select state icons in `item_reward_selected_card` and `item_reward_unselected_card`
| Selected ✅  | Unselected ☑️ |
| --- | --- |
| ![screenshot-2020-04-08_171301](https://user-images.githubusercontent.com/1289295/78834479-a0fd7880-79bc-11ea-829b-13d03831d3f4.png) | ![screenshot-2020-04-08_171310](https://user-images.githubusercontent.com/1289295/78834482-a2c73c00-79bc-11ea-86cb-688d5f049597.png) |
Turn on TalkBack 🗣 
[NT-1126]
[NT-1126]: https://kickstarter.atlassian.net/browse/NT-1126
> [🗣] NT-1126 Payment methods a11y

- app/src/main/java/com/kickstarter/services/TrackingWorker.kt
- build.gradle
Adding more info to TrackingWorker error logs.
Tracking failures are a big mystery! Hopefully with more info in the logs, we can get down to the bottom of it.
- Added the `response.message` and `runAttemptCount` to the error message that's logged when an event fails to track.
I had to add another repo for Apollo because it was causing the build to fail. More ammo for justification to get rid of it.
Logs only.
We will see these failures in the Firebase console 🚀 
[NT-1143]
[NT-1143]: https://kickstarter.atlassian.net/browse/NT-1143
> [ℹ️] NT-1143 Adding more info to TrackingWorker error logs

- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
Fixes bug where pledge button was still disabled after user added their first payment method.
So people can pledge after adding their first stored card!
- Instead of depending on `initialCardSelection` which won't emit if a user has no stored cards, using `selectedCardAndPosition` to determine if `pledgeButtonIsEnabled` should emit
- Added `distinctUntilChanged` to fix broken tests
Steps to repro:
- Have 0 saved payment methods
- Navigate to the pledge screen
- The pledge button should be disabled
- Added a payment method
- The pledge button should be enabled
[NT-1193]
[NT-1193]: https://kickstarter.atlassian.net/browse/NT-1193
> [🐛] NT-1193 Pledge button disabled bug

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/libs/OptimizelyEvent.kt
- app/src/main/java/com/kickstarter/viewmodels/CampaignDetailsViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/CampaignDetailsViewModelTest.kt
Moving `Campaign Details Pledge Button Clicked` from Optimizely to the Data Lake
We're moving Optimizely tracking events into the Data Lake.
- Added `trackCampaignDetailsPledgeButtonClicked` that tracks `Campaign Details Pledge Button Clicked` with Optimizely properties
- Added region for `native_project_page_campaign_details` experiment
- Added `CAMPAIGN_DETAILS_PLEDGE_BUTTON_CLICKED` const with value `Campaign Details Pledge Button Clicked`
- Removed `CAMPAIGN_DETAILS_PLEDGE_BUTTON_CLICKED`
- Tracking `pledgeButtonClicked` event with `lake` instead of `optimizely`
- Updated test
- Get into `variant-2` of the `native_project_page_campaign_details` experiment.
- Click the pledge button in the Campaign screen
- Check your local logcat
[NT-1190]
[NT-1190]: …
> [🔄] NT-1190 Moving Campaign Details Pledge Button Clicked event from Optimizely to Data 💧

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/libs/OptimizelyEvent.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Moving `Campaign Details Button Clicked` from Optimizely to the Data Lake
We're moving Optimizely tracking events into the Data Lake.
- Added `trackCampaignDetailsButtonClicked` that tracks `Campaign Details Button Clicked` with Optimizely properties
- Added `CAMPAIGN_DETAILS_BUTTON_CLICKED` const with value `Campaign Details Button Clicked`
- Removed `CAMPAIGN_DETAILS_BUTTON_CLICKED` and `native_project_page_campaign_details` region
- Tracking `blurbClicked` event with `lake` instead of `optimizely`
- Click the project blurb
- Check your local logcat
[NT-1191]
[NT-1191]: https://kickstarter.atlassian.net/browse/NT-1191
> [🔄] NT-1191 Moving Campaign Details Button Clicked event from Optimizely to Data 💧

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/libs/OptimizelyEvent.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Moving `Creator Details Button Clicked` from Optimizely to the Data Lake
We're moving Optimizely tracking events into the Data Lake.
- Added `trackCreatorDetailsClicked` that tracks `Creator Details Button Clicked` with Optimizely properties
- Added `experimentProperties` helper method since the 3 experiment tracking methods did the same thing
- Added `CREATOR_DETAILS_CLICKED` const with value `Campaign Details Button Clicked` in `native_project_page_conversion_creator_details` region
- Removed `CREATOR_DETAILS_CLICKED` and `native_project_page_conversion_creator_details` region
- Tracking `creatorInfoClicked` event with `lake` instead of `optimizely`
- Click the creator details
- Check your local logcat
[NT-1192]
[NT-1192]: …
> [🔄] NT-1192 Moving Creator Details Button Clicked event from Optimizely to Data 💧

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
No longer tracking `Project Page Pledge Button Clicked` in Optimizely
We're sending the Optimizely properties in the Data Lake call. This is the clean-up PR I mentioned in #846 
- Removed optimizely tracking call in `ProjectViewModel` when the project CTA button is clicked
- Only adding optimizely properties in `Koala.trackProjectPagePledgeButtonClicked` when the `PledgeFlowContext` is `NEW_PLEDGE`
Nothing 2 c.
Check the LogCat filtered for `Optly` to see no tracking happens when the project CTA buttton is clicked.
[NT-1195]
[NT-1195]: https://kickstarter.atlassian.net/browse/NT-1195
> [␡] NT-1195 No longer tracking Project Page Pledge Button Clicked in Optimizely

- app/src/main/java/com/kickstarter/models/User.java
- app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/LoggedInViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/ActivityFeedViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/LoggedInViewHolderViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ActivityFeedViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/LoggedInViewHolderViewModelTest.kt
Including `user.erroredBackingsCount` in drawer Activity count
So users know they should check their Activity feed if they have an errored backing
- Added `erroredBackingsCount` field
- Refreshing user on resumes/refreshes when `erroredBackingsCount` and `unseenActivityCount` is non zero
- Added a test
- Renamed `unseenActivityCount` to `activityCount` because it includes errored backings now
- Added tests for all the combinations of `erroredBackingsCount` and `unseenActivityCount`
| Still 🐛 | GIF 🦋 |
| --- | --- |
| <img src=https://user-images.githubusercontent.com/1289295/80258470-4e28ef80-8651-11ea-8786-bacbdaffd253.png width=330/> | ![device-2020-04-24-170400 2020-04-24 17_28_01](https://user-images.githubusercontent.com/1289295/80258463-4b2dff00-8651-11ea-84f8-6ec8c89c2a88.gif) | …
> [🔢] NT-1196 Including erroredBackingsCount in drawer Activity count

- app/src/main/java/com/kickstarter/libs/OptimizelyEvent.kt
- app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.java
Removed App Completed Checkout Optimizely event
The backend will be sending `Completed Checkout` events :pray: https://kickstarter.atlassian.net/wiki/spaces/NT/pages/126713858/Cut+Over+Strategy+for+Optimizely+Events
- Deleted this file since there are no more Optimizely events
- Removed Optimizely tracking call
- Updated test
N/A
Check the LogCat filtered for `Optly` to see no tracking happens when the thanks page is viewed.
[NT-1189]
[NT-1189]: https://kickstarter.atlassian.net/browse/NT-1189
> [␡] NT-1189 Removed App Completed Checkout Optimizely event

- app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/LoggedInViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/LoggedInViewHolderViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/LoggedInViewHolderViewModelTest.kt
The drawer Activity count is red when a user has errrored backings.
Calling more attention to the Activity row when there's an errored backing.
- Added output `activityCountTextColor` that emits the text color of the activity count. It's `ksr_red_400` when a user has errored backings and `text_primary` when they don't
- Added a test for both cases
| After 🦋 | Before 🐛 | 
| --- | --- |
| ![screenshot-2020-04-24_180921](https://user-images.githubusercontent.com/1289295/80260829-c47c2080-8656-11ea-8aaf-6519543501f4.png) | ![screenshot-2020-04-24_172756](https://user-images.githubusercontent.com/1289295/80260827-c3e38a00-8656-11ea-9198-b00e35b29cc2.png) |
Open your drawer with an errored backing!
[NT-1197]
[NT-1197]: https://kickstarter.atlassian.net/browse/NT-1197
> [🔴] NT-1197 Red drawer activity count text color when there are errored backings

- app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
- app/src/main/res/drawable/ic_menu_error_indicator.xml
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
Showing red indicator on drawer menu icon when a user has errored backings.
To let users know they have urgent matters in the drawer to attend to!
- Replaced output `showMenuIconWithIndicator` with `drawerMenuIcon` that emits the menu icon of the drawer with helper `currentDrawerMenuIcon` method. Emits
- `ic_menu_error_indicator` when a user has errored backings
- `ic_menu_indicator` when a user has unseen activity or unread messages
- `ic_menu` when a user is logged out or has no activity, messages or errored backings
- Removed `testShowMenuIconWithIndicator_whenUserHasUnreadMessagesOrUnseenActivity` because I think `testDrawerMenuIcon_afterLogInRefreshAndLogOut` handles that case
| Errored backings 🔴  | Unread message ✳️ |
| --- | --- |
| ![device-2020-04-24-183426 …
> [🔴] NT-1198 Red menu indicator for errored backings

- app/src/main/java/com/kickstarter/libs/ExperimentsClientType.kt
- app/src/main/java/com/kickstarter/libs/OptimizelyExperimentsClient.kt
- app/src/main/java/com/kickstarter/libs/utils/ExperimentUtils.kt
- app/src/main/java/com/kickstarter/mock/MockExperimentsClientType.kt
- app/src/test/java/com/kickstarter/KSRobolectricTestCase.java
- app/src/test/java/com/kickstarter/libs/utils/ExperimentUtilsTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.java
Removing unused Optimizely tracking calls
They're now being tracked in the Data Lake:
#850 
#852 
#853 
#855 
#856 
#858 
so we no longer need this code.
- Removed `checkoutTags`, `track` and `trackRevenue` methods since they're no longer used
- Removed in subclasses: ``MockExperimentsClientType` and `OptimizelyExperimentsClient`
- Removed `checkoutTags` method and tests since it's no longer used
- Removed `ExperimentRevenueData` since it's no longer used
- Removed `experimentsTest` field since we no longer track experiment events with the experiments client
- Removed usages in `ProjectViewModelTest` and `ThanksViewModelTest`
␡␡␡␡␡␡␡␡␡␡␡
N/A
[NT-1199]
[NT-1199]: https://kickstarter.atlassian.net/browse/NT-1199
> [␡] NT-1199 Removing unused Optimizely tracking calls

- app/src/main/java/com/kickstarter/ui/data/PledgeFlowContext.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Tracking `Pledge Submit Button Clicked` event for errored pledges
We have some events we want to track for the fix pledge flow.
- Added `FIX_ERRORED_PLEDGE` with tracking string `fix_errored_pledge`
- Tracking `Pledge Submit Button Clicked` when user is fixing their pledge
- Emitting `showUpdatePledge` with `PledgeFlowContext.FIX_ERRORED_PLEDGE` when a user is fixing their pledge
- Updated test
- Added a test for checkout properties when a user fixing their pledge
N/A
Check the LogCat for the `context_pledge_flow` property when fixing a pledge.
[NT-1149]
[NT-1149]: https://kickstarter.atlassian.net/browse/NT-1149
> [⛔️] NT-1149 Tracking Pledge Submit Button Clicked event for errored pledges

- app/src/internal/java/com/kickstarter/ui/views/DebugPushNotificationsView.java
- app/src/internal/res/layout/debug_push_notifications_layout.xml
- app/src/main/java/com/kickstarter/libs/PushNotifications.java
- app/src/main/java/com/kickstarter/services/apiresponses/PushNotificationEnvelope.java
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/main/res/values/strings.xml
Adds support for push notifications containing `ErroredPledge`
We will be turning on pushes for errored pledges.
- Added `ErroredPledge` model
- Added `erroredPledge` field
- Added new channel notification `CHANNEL_ERRORED_PLEDGES` with high priority
- Added a subscription for when the `PushNotificationEnvelope` contains an `ErroredPledge` object
- Created a helper method `projectIntent` to that returns an `Intent` for a `Project` so we can add more extras
- Fixed bug where the pledge sheet `ProgressBar` was still visible if the `ProjectActivity` was started with an `EXPAND_PLEDGE_SHEET` extra
- Added a button for triggering an `ErroredPledge` push that will take you to the Project page with the pledge sheet expanded
|  |  |
| --- | --- |
| <img …
> NT-658 ErroredPledge push notification

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
-  Added event for Fix pledge button inside View your pledge
New tracking events
When hitting that red button take a look into your logcat
[Fix pledge button clicked event](https://kickstarter.atlassian.net/browse/NT-1148)
> NT-1148: Fix pledge button clicked event

- app/src/main/java/com/kickstarter/services/KSUri.java
- app/src/main/java/com/kickstarter/ui/activities/DeepLinkActivity.java
- app/src/main/java/com/kickstarter/viewmodels/DeepLinkViewModel.java
- app/src/test/java/com/kickstarter/services/KSUriTest.java
- app/src/test/java/com/kickstarter/viewmodels/DeepLinkViewModelTest.java
Deep linking to project pledge URL.
Project URLs that end in `/pledge` will be used in errored pledge emails.
- Added `NATIVE_CHECKOUT_PATTERN` regex that matches pledge URLs
- Added `isCheckoutUri` method that returns if a URI matches that pattern
- Added test
- Added output `startProjectActivityForCheckout` that emits when we've deep linked with a pledge URL
- Added test cases that check this only emits for pledge URLs
- Added `projectIntent` since it's used in 2 places
Click a pledge URL (if you have deep links enabled)
[NT-1207]
[NT-1207]: https://kickstarter.atlassian.net/browse/NT-1207
> NT-1207 Deep linking to project pledge URL

- app/src/main/java/com/kickstarter/services/firebase/MessageService.java
Actually displaying errored pledge push notifications.
Because I missed it in #863 🥴 
Populating `PushNotificationEnvelope` with value of `"errored_pledge"` if it's in the data blob
**FYI** This is not the real copy~
👀 
[NT-658]
[NT-658]: https://kickstarter.atlassian.net/browse/NT-658
> NT-658 Errored pledge deserialization

- app/src/main/java/com/kickstarter/libs/ExperimentsClientType.kt
- app/src/main/java/com/kickstarter/libs/OptimizelyExperimentsClient.kt
- app/src/main/java/com/kickstarter/libs/TrackingClient.kt
- app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt
- app/src/main/java/com/kickstarter/mock/MockExperimentsClientType.kt
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
- app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
Adding support for consuming feature flags from Optimizely.
We're going to use feature flags from Optimizely.
- Added enum for optimizely feature flags
- Added `Key.LIGHTS_ON` with value `android_lights_on` from Optimizely
- Added 2 new abstract methods, `enabledFeatures` for tracking and `isFeaturedEnabled` for individual feature flag values
- Implemented in both subclasses, `OptimizelyExperimentsClient` and `MockExperimentsClientType`
- A tracking call can fire before Optimizely is initialized so `optimizelyClient` now returns an `OptimizelyClient?`
- `enabledFeatureFlags` now returns optimizely and config feature flags
- Updated `LakeTest` to assert that Optimizely flags are tracked
N/A
I plan to add displaying the features in the Internal Tools in the next PR!
[NT-1242]
[NT-1242]: …
> NT-1242 Support for Optimizely feature flags

- app/src/internal/java/com/kickstarter/ui/activities/FeatureFlagsActivity.kt
- app/src/internal/java/com/kickstarter/viewmodels/FeatureFlagsViewModel.kt
- app/src/internal/res/layout/activity_feature_flags.xml
- app/src/main/res/values/strings.xml
- app/src/testInternal/java/com/kickstarter/viewmodels/FeatureFlagsViewModelTest.kt
Displaying enabled Optimizely feature flags in Internal Tools
So users on an internal build can see if they're in an Optimizely feature. 
- Displaying `optimizelyFeatures` in new `optimizely_flags` `RecyclerView`
- Added output `optimizelyFeatures` that emits `OptimizelyExperimentsClient` enabled features
- Added test
| After 🦋 |
| --- | 
| <img src=https://user-images.githubusercontent.com/1289295/81017541-acfc1f00-8e30-11ea-9f5a-22bac218a3fd.png width=330/> |
N/A
[NT-1243]
[NT-1243]: https://kickstarter.atlassian.net/browse/NT-1243
> NT-1243 Displaying enabled Optimizely feature flags in Internal Tools

- app/src/main/java/com/kickstarter/viewmodels/EditorialViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/EditorialViewModelTest.kt
Sorting `LIGHTS_ON` projects by distance.
The closer the project, the better.
- Added helper method `discoveryParams`  
- Sorting by distance when viewing `Editorial.LIGHTS_ON`
- Added a nice test
Be in the `android_lights_on` feature.
Smash that Lights On card.
It doesn't actually sort but it's what lets the location tags show up!
[NT-1232]
[NT-1232]: https://kickstarter.atlassian.net/browse/NT-1232
> NT-1232 Sorting `LIGHTS_ON` projects by distance

- app/src/main/java/com/kickstarter/ui/viewholders/EditorialViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
- app/src/main/res/layout/activity_editorial.xml
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
- Just new styles
- Make sure data lake event is sent
--- Lake event---
---Design | Emulator-----
- Scroll on the Editorial page
- Try several devices
[NT-1230](https://kickstarter.atlassian.net/browse/NT-1230)
[Figma Design](https://www.figma.com/file/Xn3SO6HEQ5kmKo08RyvbLY/Lights-On?node-id=0%3A1)
> NT-1230: Style Lights On in Editorial view

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/KoalaEvent.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
Moving `Editorial Card Clicked` Event into Data Lake 
We used to track `Moving Editorial Card` with 🐨 
- Moved `trackEditorialCardClicked` into `Discover a Project` region
- `trackEditorialCardClicked` now takes in `DiscoveryParams` for `discover` properties and `Editorial` for `session_ref_tag` property
- Removed `EDITORIAL_CARD_CLICKED`
- Added `EDITORIAL_CARD_CLICKED`
Click the Lights On card if you're in the feature.
[NT-1246]
[NT-1246]: https://kickstarter.atlassian.net/browse/NT-1246
> NT-1246 Moving Editorial Card Clicked Event into Data Lake 

- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
Fixes bug caused by trying to create a `Spannable` from a null `String`
- since `pledgeStatusText` is nullable, we need to safely unwrap it before we try to use it. If it's `null`, we should clear the `backer_pledge_status` text.
N/A
I'm not able to repro but can see the crash [here](https://console.firebase.google.com/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/15f73366d66bd44e9aa9dff07a6f60bb?time=last-seven-days&sessionId=5EB5377803E30001381253B8967E8743_DNE_0_v2)
Need a bug ticket
> Backing status bug fix

- app/src/main/java/com/kickstarter/models/StoredCard.kt
Reverts `StoredCard.DATE_FORMAT` to fix crash on Marshmallow devices
`Y` is only supported on[ API 24 and above](https://developer.android.com/reference/java/text/SimpleDateFormat.html) 
- Date format is back to `yyyy`
N/A
View stored cards
Need a bug ticket
> StoredCard Marshmallow bug

- app/src/test/java/com/kickstarter/viewmodels/BackingViewModelTest.java
Fixes tests in `BackingViewModelTest` that assume the user is in the US
The tests should pass for all users wherever.
- instead of asserting the final currency value like `"$5"`, we assert the `formattedCurrency` value
N/A
N/A
N/A
> Broken currency tests: BackingViewModelTest

- app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
- Made helper method `expectedCurrency` that returns the localized currency
- Returning value of `DateTimeUtils. longDate` instead of date string
N/A
N/A
N/A
> Broken currency tests: BackingFragmentViewModelTest 

- app/src/main/java/com/kickstarter/mock/factories/RewardFactory.java
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
- Making tests assert values agnostic to user's locale for currency and timestamps
- Added `ESTIMATED_DELIVERY` constant to `RewardFactory`
N/A
N/A
N/A
> Broken currency tests: PledgeFragmentViewModelTest

- app/src/main/java/com/kickstarter/viewmodels/EditorialViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/EditorialViewModelTest.kt
Filter filter just by tagId: 557 -> Lights On in android , remove distance filtering
It seems the distance filtering is not working on the backend, for the MVP we just filter by tagId.
- Make sure to use staging and to have the device Id added to the android optimizely audience.
[NT-1232](https://kickstarter.atlassian.net/browse/NT-1232)
> NT-1232: Revert Distance sorting

- app/src/main/graphql/checkout.graphql
- app/src/main/graphql/fragments.graphql
- app/src/main/graphql/project.graphql
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
Refactor in queries Project.backing and Backing.backing to use fragments for each subtype 
Reusability - Readability - No code smells 
Creating separate fragments for each type and not attaching them to any high level query.
No UI chenges here 
- Check one of your backed projects, hit the manage pledge button, all data should remain the same as before
- Go to any message os your messages with a creator of a project you already backed, go to the thread view, hit the view pledge button, all data should remain as before.
- Log in as creator if you can, go to any message you have with a baker to one of your projects, hit the view pledge, you should see the pledge data as before.
> NT-1141: Refactor existing queries

- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
On the pledge screen, the pledge button was still active even if the user cleared their shipping selection, making it invalid.
Seems to be a possible cause for errors, if we're allowing users to make a pledge(spend money), without first confirming that a reward can even be shipped to their location.
I added an OnTextChangedListener to the shipping address AutoCompleteTextView. Each time the text is changed, I check if it's null, empty, or blank (only blank spaces). If so, I disable the pledge button. When the user selects a valid location from the shipping dropdown, I re-enable the pledge button.
I'm not 100% sure if this correct as I couldn't see where we were getting the shipping locations from. So, in the case that the user can select a location from the dropdown, and that location is …
> Disable pledge button if shipping selection is invalid

- app/src/main/java/com/kickstarter/libs/models/OptimizelyExperiment.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
Added a new experiment with several variants: 
Increase revenue from No reward options experiment
Control Variant
Variant 4 
- Log in on staging with a non-admin user
- make sure you have the deviceId added in the whitelist and in the android audiences
[Implement Variants](https://kickstarter.atlassian.net/browse/NT-1347)
> NT-1347: Suggested reward amount experiment for no reward

- app/src/main/java/com/kickstarter/ui/viewholders/RewardViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
Hide the minimum pledge amount from no-reward cards.
We want to run experiments with suggested minimum amounts for different audiences, and this change is needed in order to efficiently run that experient.
I created a new Observable in RewardViewModelViewhHolder that emits whether or not a reward item is of the "no-reward" type. If that value is true, and it's a no-reward, we hide the amount and conversion text fields.
Check to ensure that the $ amount indicator has been removed from the “Pledge without a reward” card in the Reward Carousel for the control as well as all experimental variants 
https://kickstarter.atlassian.net/secure/RapidBoard.jspa?rapidView=9&modal=detail&selectedIssue=NT-1346
> NT-1346: Hide minimum pledge amount for no reward card

- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/main/res/layout/fragment_pledge_section_summary_pledge.xml
This PR address the rejected items from the UAT checklist
https://kickstarter.atlassian.net/secure/RapidBoard.jspa?rapidView=9&modal=detail&selectedIssue=NT-1171
Make changes to the Manage Pledge view to reflect the addition of the bonus support field, and some new UI changes.
To begin adding support for backers who want to pledge a little extra to a project, and to make necessary UI changes that will be needed for add ons.
New UI changes that show bonus support, estimated delivery date and checkbox, and minor copy changes.
Users may view Add Ons they have backed on the web when viewing the View/Manage pledge screen 
In the list of numbers, a line called “Bonus” is added beneath shipping that denotes the amount of bonus support added by the backer
In the list of numbers, “Total amount” …
> NT-1171: (Fixed) Manage Pledge View Backing Info updates

- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
Show the status of a backing to a creator.
Creators will want to see the status of a pledge/backing, to have more context into the status of that pledge.
In PledgeFragmentViewModel, I check to see if the currently logged in user is a creator or not. Depending on the case, I fetch a different set of strings from our resource files.
The strings for creators show as follows: 
Canceled (by creator) - "You canceled this project, so the backer’s payment method was never charged."
Canceled (by backer) - “The backer canceled their pledge for this project.”
Collected - “We collected the backer’s pledge for this project.”
Dropped - “This pledge was dropped because of payment errors.”
Pledged - “If your project reaches its funding goal, the backer will be charged on November 5, 2019.”
Unsuccessful …
> NT-606: Update strings to reflect backer's state in creator view

- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
After PR conflicts merged& rebases, the total amount for the new summary header was lost
|  |  |
* Check the Two lines reward (easier to get one when using a low density device
* total amount in all the rewards in the expandable header
> NT-1326: (Fixed) Expandable Header UI

- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
* we weren't parsing the title from the graph request for the creator perspective
|  |  |
* Rewiew as creator
[Backing Fragment Add-ons UI](https://kickstarter.atlassian.net/browse/NT-1290)
> NT-1290: (Fixed) Manage Pledge Add ons UI - No title in reward from creator perspective

- app/src/main/java/com/kickstarter/libs/utils/RewardUtils.java
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/test/java/com/kickstarter/libs/utils/RewardUtilsTest.java
- Helper string must not be updated with the variant amount, meaning that, if we are running this experiment, even though the suggested amount has changed, the helper should remain with the control amount.
- Added helper method on RewardUtils to fetch the amount for each variant
Running experiments on the suggested amount for no rewards
The output for the amount in the string helper has been updated, in case is a regular reward, same as before. In case is a `No Reward` use the Control varian amount.
- On left image, a `No Reward` but with variant 4 active, so the amount should be `50`, but the helper remains the control variant
- On right image a regular reward, no behavior changes in there
|  |  |
* try at least two variants
* try a regular reward
[No reward …
> NT-1347:(Fixed) No reward amount experiment, helper string

- app/src/main/java/com/kickstarter/models/Reward.java
- app/src/main/java/com/kickstarter/ui/viewholders/RewardViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
- app/src/main/res/layout/item_reward.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
The reward carrousel now indicates in each reward if add-ons are available for that concrete reward
The backer needs to know before hand if the reward has Add-ons associated
- Added field "has_addons" to the Reward model to fetch that field from V1 API, optional because GraphQL reward model does not have that field.
| Emulator |
| [Figma Design](https://www.figma.com/file/Mgu86KSC8hksuVvD2c2288/Add-Ons%3A-Delivery?node-id=559%3A0) |
|  |  |
- Check in a project with Add-Ons if that tag is available for the reward that has Add-Ons
[Reward UI tag](https://kickstarter.atlassian.net/browse/NT-1402)
> [NT-1402]- Reward card UI tag

- app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
- app/src/main/java/com/kickstarter/ui/data/CheckoutData.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
Added new fields in already existing properties for bonus support `bonus_amount`, and `bonus_amount_usd`, the event is send when pledge button clicked.
Pledge to a Hong Kong project : 
- take a look into logcat and filter logs by `bonus_amount` once the project is being backed
[Event for bonus Support](https://kickstarter.atlassian.net/browse/NT-1392)
> [NT-1392] Event property for bonus support

- app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
- app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
- app/src/main/res/layout/fragment_backing_addons.xml
- app/src/main/res/layout/fragment_pledge_section_shipping.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/kickstarter/viewmodels/RewardsFragmentViewModelTest.kt
If a Reward has add-ons available when hitting continue show a new fragment, it will have for now just two string
- hitting a reward with add-ons will show a new screen
- hitting a reward without add-ons, or a no-reward will show the PledgeFragment.
[Add-ons screen](https://kickstarter.atlassian.net/browse/NT-1383)
> NT-1383: New add-ons screen

- app/src/main/java/com/kickstarter/ui/adapters/BackingAddOnsAdapter.kt
- app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
- app/src/main/java/com/kickstarter/ui/viewholders/BackingAddOnViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
- app/src/main/res/layout/fragment_backing_addons.xml
Structure for the Add-ons list ready. In next PR's we will add the add-ons query from Grapgh, Currently hardcoded 2 rewards as placeholder in order to facilitate the work in [Add-ons card UI: NT-1385](https://kickstarter.atlassian.net/browse/NT-1385)
Avoid conflicts and separate work for those working on the Add-on Card UI, and the Filtering by location/ fetching Add-ons work
[Add-ons list](https://kickstarter.atlassian.net/browse/NT-1384)
> NT-1384: Add-ons list

- app/src/main/graphql/fragments.graphql
- app/src/main/graphql/project.graphql
- app/src/main/graphql/schema.json
- app/src/main/java/com/kickstarter/mock/factories/RewardFactory.java
- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/models/Item.java
- app/src/main/java/com/kickstarter/models/Reward.java
- app/src/main/java/com/kickstarter/models/ShippingRule.kt
- app/src/main/java/com/kickstarter/services/ApolloClientType.kt
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/ui/adapters/BackingAddOnsAdapter.kt
- app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
- app/src/main/java/com/kickstarter/ui/viewholders/BackingAddOnViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
- app/src/main/res/layout/fragment_backing_addons.xml
- app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
- New query on project.graphql
- BackingAddonsFragmentViewModel now fecth all the available add-ons for a project
- BackingAddonsFragmentViewModel now fecth all the available shipping rules for the selected reward
- BackingAddonsFragmentViewModel now fecth the available shippingPreference
* No filtering yet just fetching data
- added two new optional fields into the Reward model
`@Nullable ShippingPreference shippingPreferenceType();`
`@Nullable List<ShippingRule> shippingRules();`
- new fragment for ShippingRules
-- Sending the shipping rules with the Reward model
[NT-1384](https://kickstarter.atlassian.net/browse/NT-1384)
> NT-1384- AddOns query

- app/src/main/java/com/kickstarter/libs/ExperimentsClientType.kt
- app/src/main/java/com/kickstarter/libs/OptimizelyEvent.kt
- app/src/main/java/com/kickstarter/libs/OptimizelyExperimentsClient.kt
- app/src/main/java/com/kickstarter/libs/utils/ExperimentUtils.kt
- app/src/main/java/com/kickstarter/mock/MockExperimentsClientType.kt
- app/src/main/java/com/kickstarter/viewmodels/CampaignDetailsViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/KSRobolectricTestCase.java
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
- app/src/test/java/com/kickstarter/viewmodels/CampaignDetailsViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Send events through the Optimizely SDK instead of just the Data Lake
Events passed to that data lake were not correctly forwarded to Optimizely.
Added the following events back to the app. Some events were not in the app originally
Events
- [Creator Details Button Clicked](https://github.com/kickstarter/android-oss/pull/855) 
- [Campaign Details Button Clicked](https://github.com/kickstarter/android-oss/pull/853)
- [Project Page Pledge Button Clicked](https://github.com/kickstarter/android-oss/pull/856)
- [Campaign Details Pledge Button Clicked](https://github.com/kickstarter/android-oss/pull/852)
- Project Page Viewed (Not originally added)
- Checkout Payment Page Viewed (Not originally added)
Run the app and ensure that the events are fired correctly …
> NT-1318: Add Optimizely SDK Events

- app/src/main/java/com/kickstarter/ui/activities/BackingActivity.java
- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingViewModel.java
When a creator goes to view details about a pledge to their project, the app was crashing on pull to refresh.
The current logic in BackingFragment expects the parent activity to call the appropriate delegate function when refresh is triggered. This is implemented correctly in ProjectActivity, where the BackingFragment is loaded from in the user-context of a backer. For creators, BackingFragment is loaded by BackingActivity, which did not properly implement these delegate functions, so we were crashing due to a ClassCastException. 
I implemented the BackingFragment.BackingDelegate interface in BackingActivity, and updated BackingViewModel to re-fetch the backing on pull to refresh, and then update the UI.
Hard to display this one, so no screenshots.
Log in as a creator, go to the Messages …
> NT-1411: Creator crash fixed

- app/src/main/java/com/kickstarter/ui/viewholders/BackingAddOnViewHolder.kt
Hide the divider when add on reward list is not visible
The divider separates sections, so having there when there is no section to separate from makes no sense.
When the reward items list gets hidden, also hide the divider by setting it's visibility to GONE.
> NT-1385: (Add on card UI) Hide add on divider

- app/src/main/java/com/kickstarter/ui/adapters/BackingAddOnsAdapter.kt
- app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
- app/src/main/java/com/kickstarter/ui/viewholders/BackingAddOnViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
- app/src/main/res/layout/item_add_on_pledge.xml
- app/src/test/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
- Display the shipping rule cost in each Add-on matching the selected shipping rule
- Fixed some translation strings
- Added new field shippingRule to the BackingAddonViewHolder
- Change the location, make sure the Add-on card reflects the shipping cost changing
> Selected Shipping Rule cost for Add-ons

- app/src/main/java/com/kickstarter/ui/adapters/ExpandableHeaderAdapter.kt
- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
Show a list of selected addOns in the expandable pledge header
Change the output `titleAndAmount` in PledgeFragmentViewModel to hold a list of items instead of just one item.
https://kickstarter.atlassian.net/secure/RapidBoard.jspa?rapidView=9&modal=detail&selectedIssue=NT-1421
> Show selected addOns in pledge header

- app/src/main/java/com/kickstarter/ui/data/PledgeData.kt
- app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
- app/src/main/java/com/kickstarter/ui/viewholders/BackingAddOnViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/main/res/layout/fragment_backing_addons.xml
- app/src/main/res/layout/fragment_backing_addons_section_footer.xml
- app/src/test/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.java
- CTA button to continue with our without Add-ons
- String informing amount of add-ons selected
- Backing with Add-ons from mobile app 
- ViewListener from each item in the RecyclerView informs the FragmentViewModel the amount selected for each row
- The Fragment ViewModel holds a structure containing the quantity per AddOnID selected
- The total amount selected gets updated everytime the stepper is pressed in any row
|  |  |
- Reach Pledge Screen with Add-ons
- Reach pledge Screen without Add-ons
- Reach pledge Screen without seeing BackingAddons screen
[Add-Ons cta button logic](https://kickstarter.atlassian.net/browse/NT-1388)
> NT-1388:cta-button-logic

- app/src/main/graphql/checkout.graphql
- app/src/main/graphql/fragments.graphql
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/services/mutations/UpdateBackingData.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
Update a pledge uses the UpdateCheckout Mutation, updated mutation for holding an array of reward ID's
|  |  |
- Update a pledge with add-ons
[Bug on Manage Screen with the shipping amount & bonus amount](https://kickstarter.atlassian.net/browse/NT-1463)
[Update a pledge with add-ons](https://kickstarter.atlassian.net/browse/NT-1462)
> NT- 1462&& NT-1463: UpdateBacking Mutation 

- app/src/main/graphql/checkout.graphql
- app/src/main/graphql/fragments.graphql
- app/src/main/graphql/schema.json
- app/src/main/java/com/kickstarter/libs/utils/RewardUtils.java
- app/src/main/java/com/kickstarter/mock/factories/RewardFactory.java
- app/src/main/java/com/kickstarter/mock/factories/ShippingRuleFactory.kt
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/services/mutations/CreateBackingData.kt
- app/src/main/java/com/kickstarter/services/mutations/UpdateBackingData.kt
- app/src/main/java/com/kickstarter/ui/data/PledgeData.kt
- app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.java
- app/src/main/res/layout/fragment_pledge.xml
- app/src/main/res/layout/fragment_pledge_section_editable_shipping.xml
- app/src/main/res/layout/fragment_pledge_section_shipping.xml
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.java
- Refactor PledgeFragment
- Updated schema.json
- New Checkout mutation
- For pledging to a Reward + AddOns we needed to update the current mutation to a new one
- Mutation now has a new field :  list of rewards 
- try a no reward
- try a no reward with experiment active
- try a no reward + bonus
- try a no reward with experiment active + bonus
- try a digital reward
- try a digital reward + bonus
- try a reward with shipping location
- try a reward with shipping location + bonus
- try a reward(digital) with addOn(digital)
- try a reward(with shipping) with addOn(with shipping)
- try a reward(with shipping) with addOns(with shipping + digital)
- try a reward(with shipping) with addOns(with shipping + shipping)
- try a reward(digital) with addOn(digital) + bonus
- try a reward(with …
> NT-1344: Updated checkout with new mutation 

- .circleci/config.yml
Exchange docker image
The previous one from CircleCI was updated to JDK 11 from JDK8 and was making our builds fail.
Thanks to @yatriks ⭐
> Exchange docker image

- app/src/main/java/com/kickstarter/libs/utils/RewardViewUtils.kt
- app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
- app/src/main/java/com/kickstarter/mock/factories/RewardFactory.java
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
- New logic for the CTA button string and when it should be activated.
|  |  |
- Change reward from one without Add-ons to another one without add-ons, no changes should be appreciated there on the button logic
- Change reward to the same reward with available add-ons, the button should be enabled
- Change reward to the same reward withOut available add-ons, the button should be disabled
[NT-1390: Previously selected reward logic](https://kickstarter.atlassian.net/browse/NT-1390)
> NT-1390: Previously selected reward logic

- app/src/main/res/layout/fragment_rewards.xml
- app/src/main/res/layout/pledge_container.xml
Update the background color of the toolbar in the pledge container view
When the user scrolls their add-ons, the toolbar is translucent
Open a project with add-ons and verify that the toolbar is no longer translucent
[NT-1464](https://kickstarter.atlassian.net/browse/NT-1464)
> NT-1464: Translucent Add-Ons Header Fix

- app/src/main/java/com/kickstarter/ui/activities/AccountActivity.kt
Fixed a crash when user's try to access their account.
In Firebase, we received crashes related to the ArrayAdapter. 
[Link to Crash](https://console.firebase.google.com/u/0/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/58ec151aaa1b8752aa817cdf9325fbb7?time=last-seven-days&sessionId=5F4E6DF500E8000157AD6BA2371B8A38_DNE_0_v2)
Instead of using the CurrencyCode enum that is generated by graphQL, we are going to use a list a supported enums so in the case where a new currency is added to the backend CurrencyCode we can still display the currencies without a crash.
The reason for the crash was do to a new currency that was added (PLN). The team updated the graphQL models and the next release was unable to handle the new currency. 
[Link to Currency …
> NT-1489: Fix Crash when a user views their Account

- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
Added a basic add-on if the backer pledge without a reward. 
The crash was due to the basic reward missing "id" and "minimum". Without this information the builder crashed.
In order to fix the issue the "id" and "minimum" was added to the reward object to correct pass a completed reward object.
Using the credentials for the creator account in the ticket below, navigate to the Dashboard, then messages and then select the first message. After that select the "view pledge" CTA
[NT-1411](https://kickstarter.atlassian.net/browse/NT-1411)
> NT-1411: Crash on Creator Pledge Screen

- app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/SearchViewModelTest.java
- When obtaining search results, we send some events alongside to the request for the results, in this PR those events have been scheduled in other thread-pool
_Shceduler.io() -> meant for I/O-bound work such as asynchronous performance of blocking I/O, this scheduler is backed by a thread-pool that will grow as needed;_
In order to not have a race condition when the tracking clients are fetching the ID.
- Sometimes (not always) you can get a random crash while searching
- Changing the tread-pool where we observe for sending the events
- Search a bunch of times 
[NT-1488 Search Crash](https://kickstarter.atlassian.net/browse/NT-1488)
> NT-1488:Crash on search

- app/src/main/java/com/kickstarter/ui/viewholders/RewardViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
- app/src/main/res/layout/item_reward.xml
- app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
A digital reward can have addOns 
| 
|  |  |
- Make sure that a digital reward with AddOns has the tag shown in the Carousel ⚠️ (the AddOns screen is not gonna load anything for now, it expects a location)
> NT-1387: Fix Add-Ons Available tag for Digital Reward

- app/src/main/java/com/kickstarter/viewmodels/ShippingRuleViewHolderViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ShippingRuleViewHolderViewModelTest.kt
Removes the shipping cost from all shipping selectors.
Due to add-ons, the shipping selector showed the shipping cost for the base reward and was not relevant for add-ons as each add-on has it's own shipping cost.
Removed the formatting code from the `ShippingRuleViewHolderViewModel`
|<img width="356" alt="Screen Shot 2020-09-02 at 5 40 07 PM" src="https://user-images.githubusercontent.com/4837246/92039616-59003900-ed43-11ea-8668-174d6583d794.png">|<img width="347" alt="Screen Shot 2020-09-02 at 5 37 51 PM" src="https://user-images.githubusercontent.com/4837246/92039425-0888db80-ed43-11ea-9cfa-84d592d238af.png">|
View a project with add-ons and verify that the shipping selector does not show the shipping costs
Back a project …
> NT-1484: Remove shipping cost from the shipping selector.

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
Add the Add-Ons analytics events to the app. 
Needed to track the impact of Add-Ons
Added Add-Ons to the backing add-on fragment with tests.
[NT-1482](https://kickstarter.atlassian.net/browse/NT-1482)
> NT-1482: Add-Ons Analytics Events

- app/src/main/java/com/kickstarter/ui/adapters/RewardAndAddOnsAdapter.kt
- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
- app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
- The backing fragment was not reflecting the update pledge changes, or changing reward changes unless fragment re-created again
- Allow to load emptyList on AddOns section for the rewards and addOns recyclerView (changing your addOns selection to 0 addOns, or changing from a reward with addOns to one without it was not updating the RecyclerView UI).
- Do not present Any fragment or Dialog unless the current fragment is visible.
- Added .materialize() operator when fetching the BackingObject in ProjectViewModel
|  |  |
- Change from a reward with AddOns to a Reward without AddOns, the BackingFragment should change without any user interaction to reflect the new selection (look at the gif if any doubts)
[NT-1474](https://kickstarter.atlassian.net/browse/NT-1474)
> [NT-1474]: Refresh backing fragment

- app/src/main/res/layout/expandable_header_item.xml
- app/src/main/res/layout/fragment_pledge_section_header_reward_sumary.xml
- For a long text on the converted amount on a reward-addon the expandable header was showing two lines. Now it's just one.
| 
|
|  |  |
- Select a reward/addOn in another currency to have longer texts 
[NT-1512](https://kickstarter.atlassian.net/browse/NT-1512)
> NT-1512: UI adjustment Expandable header

- app/src/main/res/layout/fragment_pledge_section_header_reward_sumary.xml
Reward header total is cut off for large values. The XML is updated to account for larger amounts
When choosing a larger reward amount the total is cut off.
On the one inch straw project, go to the last reward and confirm that the total is viewable.
[NT-1521](https://kickstarter.atlassian.net/browse/NT-1521)
> NT-1521: Reward Total Cutoff for Large amounts

- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- ProjectData was always updated with the outdated backing object
- We fetch project from V1, but backing Object from Graph. In this situation the observable for backingObject still had the previous emission, so added additional logic to make sure we update the project data only if needed
- Pledge to a project, hit manage your pledge, cancel the pledge. Then hit again back this project button, the reward carousel should be in a non backed state without the "You backed" tag
[NT-1520](https://kickstarter.atlassian.net/browse/NT-1520)
> [NT-1520] - Update UI in RewardsFragment when canceling a pledge

- app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
- app/src/main/res/values/strings_i18n.xml
- app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
Show an error alert dialog when there is an error retrieving the add-ons. Also allow user to tap retry to resend the networks calls to get the add-ons. 
To give user more context on why add-ons are not loading correctly. 
Created a new stream that triggers the dialog when the network response is an error. Retry button resends the project data and reason to make a network call.
- Search for the project "one inch straw"
- Select "back project"
- Turn off wifi or put phone in airplane mode
- Select a pledge with add-ons
- Wait to see the error dialog
- Turn on wifi or turn off airplane mode
- Press "retry"
- After network call finishes, should show add-ons
[NT-1442](https://kickstarter.atlassian.net/secure/RapidBoard.jspa?rapidView=9&projectKey=NT&modal=detail&selectedIssue=NT-1442&assignee=5 …
> NT-1442: Android Display an error state if add-ons fail to load

- app/src/main/java/com/kickstarter/libs/utils/RewardUtils.java
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/test/java/com/kickstarter/libs/utils/RewardUtilsTest.java
- The minimum pledge allowed is specified by country, but when we added the RewardMinimum experiment we specified for the Control variant the amount "1". Changing involuntarily for some countries like Mexico (with minPledge 10MX ) the NoReward amount when control variant active to 1MX.
- Previously the stepper increased amount was the minPledge, now is always increased by 1.
If control variant active the No Reward pledge amount was incorrect for some countries with minimum pledge higher than the control variant (IE: Mexico or japan with minPledges 10MX, and 100¥)
- When the stepper button is pressed just update by 1 the amount
- In RewardUtils if the amount active in the experiment is lower than the minimumPledge, use the minPledge value.
- Mexico 
- Japan
|  |  |
- Pledge to a Mexican or …
> NT-1516: Update the Bonus Support Base Amount

- app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
- app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
Remove stacking from alert dialog buttons. Buttons should appear side by side. 
Removing whitespace from alert dialog button text to avoid distortion on certain devices caused by screensize. 
For error alert dialog:
- Search for the project "fadoodle"
- Select "back project"
- Turn off wifi or put phone in airplane mode
- Select a pledge with add-ons
- Wait to see the error dialog
For rewards alert dialog:
- Search for the project "fadoodle"
- Select "back project"
- Select a pledge with add-ons
- Pledge to project
- Go to manage project
- Select "change reward"
- Select reward with no add-ons
- View alert dialog
> Backing Add Ons Alert Dialog Cleanup

- app/src/main/graphql/fragments.graphql
- app/src/main/java/com/kickstarter/mock/factories/RewardFactory.java
- app/src/main/java/com/kickstarter/models/Reward.java
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
- update reward graphql-fragment to fetch the "available" field from GraphQL
- updated Reward model and builder to support the "available" field
- when getting addOns from graph filterOut the ones unavailable
- updated RewardFactory addOn object to always available
- new test for unavailable filteredOut addOns
- Previously we where always fetching and offering all addOns for a project, now we just offer the available ones
- In the before gif we offer 6 addOns
- In the filtered gif we offer 5 addOns (one of the 6 addOns is unavailable) 
| Before 🐛 |
| After 🦋 |
|  |  |
- Go to the project https://staging.kickstarter.com/projects/microcosmpublishing/how-to-be-accountable-take-responsibility-change-behavior?ref=checkout_rewards_page
- Select one of the shipping worldwide rewards
- Change …
> NT-1534: Sold-out add-ons

- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/main/res/layout/fragment_pledge_section_pledge_amount.xml
- app/src/main/res/values/integers.xml
After reviewing the crash reports from the latest releases we found 2 crashes that should be fixed in the next release.
Native is targeting a 99% crash free score for each release and to hit that we need to manage and fix crashes when we release a new version of the app.
1. [BackingFragment line 56](https://console.firebase.google.com/u/0/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/e752de039a17ee3800f737f3ba536282?time=last-seven-days&sessionId=5F6A1F9E015E000170AEB3D9D6D07138_DNE_0_v2) - "backer_name" must not be null
Reproducing this issue was difficult, to prevent the backer_name from returning null, I added a check to filter out null before updating the UI
2. [PledgeFragment line …
> NT-1518 | NT-1519 - Fix Firebase Crashlytics Crashes

- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
Fixed an issue where the maximum pledge amount is showing for the incorrect value of the max pledge.
When the user adds bonus support, the max amount should be the following:
X = [max pledge amount] – [base reward + base reward shipping + addons + addons shipping]
The stream that determines if the bonus support amount error string should show is based off of the PledgeMaximum instead of the CurrencyMaximum.
- Navigate to any project and select a non digital reward and enter the correct bonus support. The Total can equal 10,000 for USD projects but to never exceed that amount
[NT-1453](https://kickstarter.atlassian.net/browse/NT-1453)
> [NT-1453] Bonus Support Max Pledge String Fix

- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
Updated the PledgeFragment to check the backing object on the main PledgeData as well as the project object. 
As a user, I may only want to change a portion of the backing and resetting the bonus support is an action that the user might not expect.
In the PledgeFragment view, the bonus amount is only checked on the top backing object where in some cases that is null, in those instances we check the project's backing model for the bonus support.
- Back a project with add-ons and add a bonus amount.
- Then manage that reward
- Select "choose another reward"
- Select the same reward and update the number of add-ons
- Continue and verify that the original bonus support is present before re-pledging
[NT-1497](https://kickstarter.atlassian.net/browse/NT-1497)
> NT-1497: Preserve Bonus Support when Editing a Reward with Add-ons

- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
In the manage pledge view, the pledge line item does not show up when the user backs for a digital reward.
The user should be able to see what their pledged amount is and how that value is separate from the total value and the bonus support.
The logic to determine if the pledge line should be visible is no longer based on the location id but on if the reward on the backing object is null.
View a project that has a digital reward and back it. Navigate to the manage pledge view to verify the pledge line item.
[NT-1542](https://kickstarter.atlassian.net/browse/NT-1542)
> NT-1542: Pledge Amount Missing from Manage Pledge

- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
We want to hide the shipping selector when there is a network call error to fetch addons, and only show when addons are fetched correctly. 
Update `shippingSelectorGone` stream when there is a network error. 
For error alert dialog:
- Search for the project "fadoodle"
- Select "back project"
- Turn off wifi or put phone in airplane mode
- Select a pledge with add-ons
- Upon error dialog popping up, location selector should disappear
- Before tapping "retry", turn wifi on or take phone off airplane mode
- Press "retry"
- Network call should be successful and location selector should reappear
[Android Display an error state if add-ons fail to load
](https://kickstarter.atlassian.net/browse/NT-1442)
> Android NT-1442: Hide shipping selector on network error

- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
Added a additional filter and check to prevent the alert from presenting when navigated away from the app.
When the user updates their pledge, and decides to select another reward a modal pops up confirming that their selected add-ons might not be available if they switch. This alert also pops up when the user navigates to another app and comes back to the kickstarter app.
The project activity notifies the other sub fragments when the user resumes their session and this toggles an update to the reward clicked stream. If the user already prompted the modal before, this modal will come up again. The fix was to apply a filter on the reward clicked so that the alert only shows when it is prompted from a selection of the reward
See steps to reproduce in ticket …
> NT-1539: Unprompted Edit Rewards Alert

- app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
- False negative when using .distinctUntilChanged()
- Clean up to avoid memory leaks in the fragments.
- Remove the distinctUntilChanged operator
- When onDetach is called remove the viewModel.
|  |  |
- Choose the same reward, update your addOns, choose the same reward again without leaving manage your pledge screen, make sure the addOns screen is reflecting your changes.
[Updated Add-ons Quantity Not Updated](https://kickstarter.atlassian.net/browse/NT-1541)
> NT-1541: Updated Add-ons Quantity Not Updated

- app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
- If you backed addOns, the Choose new reward let you ALWAYS edit that same reward to modify your addons selection, no matter the state of that reward.
- You may have the reward unavailable and still be able to update your addOns selection because the are available (availability of addOns to offer is handled in the AddOns Screen)
- Modified pre-existing logic
- No actual project to test with that I've found, but test covering that use case updated and passing.
|  |  |
- I haven't found a project to test with but follow this scenario: 
1 - Find a limited reward with just one reward left if possible and with addOns (pledge to the reward + addons)
2- Choose another reward flow -> 
BEFORE: Choosing same reward was impossible because that reward wasn't selectable (disabled button).
NOW: You …
> NT-1534: Android Sold-out add-ons fix

- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
There is a `reward` stream that combines the selected reward, `rewardPledge` and the user's backing `backingReward`. If there is no backing the rewardPledge is used. In the case where the user updates their pledge with another reward, the  `backingReward` is not null and is used as the main reward even though the user selected another reward.
The bug that was created happens when they change their reward from non digital to digital. When this happens rewards that are non digital are showing..
Steps to reproduce in the ticket
[NT-1549](https://kickstarter.atlassian.net/browse/NT-1549)
> NT-1549: Edit Reward Flow

- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
When the user selects a reward that equals the max pledge for the currency, the validation logic for the bonus support prevents the user from pledging
The user should be able to pledge a reward that is the maximum for the currency. No bonus support should be added.
The currency max is what is used to determine the max. A bonus support max stream is added to update the max error string for the bonus support
- Go to the "Picton Magazine" project
- Pledge for the maximum reward (8,500)
- Confirm pledge and ensure the user cannot pledge with bonus support.
> Max Pledge Fix

- app/src/main/assets/json/server-config.json
- app/src/main/res/layout/item_reward.xml
- app/src/main/res/values-de/strings_i18n.xml
- app/src/main/res/values-es/strings_i18n.xml
- app/src/main/res/values-fr/strings_i18n.xml
- app/src/main/res/values-ja/strings_i18n.xml
- app/src/main/res/values/strings_i18n.xml
- new copy for your selected reward tag in rewards carrousel
- pre-existing translations updated
|  |  |
- before the tag was saying in english "You backed" now is "Your selection"
[Android Update Backed Reward Copy](https://kickstarter.atlassian.net/browse/NT-1525)
> NT-1525: Update Backed Reward Copy

- app/src/main/assets/json/server-config.json
- app/src/main/java/com/kickstarter/libs/models/Country.kt
- app/src/main/java/com/kickstarter/libs/utils/RewardUtils.java
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/test/java/com/kickstarter/libs/utils/RewardUtilsTest.java
- We have the Suggested Amount experiment active for android. We need to check that that any variant amount is lower that the country minimum allowed pledge
- Updated values for `trailing_code` to match the backend
- Set the minimum pledge to the county minimum pledge instead of the reward.minimum
- com.kickstarter.libs.utils.RewardUtils#rewardAmountByVariant -> In case some variant amount is lower that the country allowed minimum pledge, return the minimum pledge instead of the variant amount.
- Poland project with minPledge value 5 
|  |  |
- Pledge to a reward no reward from Poland, or Japan or Mexico .. any country with minPledge not 1. Make sure the minimum amount is higher or the same as the minimum Pledge allowed by the country 
> NT-1564: Min pledge value for no Reward

- app/src/main/java/com/kickstarter/libs/utils/RewardViewUtils.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
- app/src/test/java/com/kickstarter/libs/utils/RewardViewUtilsTest.kt
- app/src/test/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModelTest.kt
AC description: 
- Before if an addOn was unavailable, that addOns was filtered out and the user was unable to modify their selection
- Now we show the unavailable addOn and we let the user modify their selection **BUT just decreasing it**.
- Filter out Unavailable addOns in the combined list **JUST IF **  they weren't backed 
- Modified the maxLimit function, if the addOns is unavailable, the actual limit is the quantity, this way the increase button is disabled, and the user is able to **ONLY DECREASE**
|  |  |
- Go to bots up project, select the Upgraded bot reward, select the 2 left unit for the add on Early prototype 
& mats package -> pledge 
- Choose select another reward -> choose same reward -> make sure the add on Early prototype 
& mats package is in the list and it has 0 items …
> NT-1534: Modify previously backed AddOns if unavailable

- app/src/main/graphql/checkout.graphql
- app/src/main/graphql/fragments.graphql
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- if a creator was also an admin, the query from the creators perspective was getting this error for fetching the field `        requiresAction`. With this changes the fields related to the checkout mutation won't be fetched from any query either backer or creator perspective.
- Backing object null if trying to query a checkout related field.
- Modified the backing fragment to not fetch fields
`     clientSecret
requiresAction
status
`
- Added new fragment `checkoutBacking` for those same fields 
- modified `CreateBacking` and `UpdateBacking` mutations to use the new fragment
|  |  |
- Log in as creator @louisaadjadja can help with this step, she provided the credentials : 
- Go to dashboard -> hit messages -> hit view pledge button. The view/manager pledge screen should have content.
- …
> NT-606: FIX Display a string indicating backing state for creators on View/Manage Pledge screen

- app/src/main/java/com/kickstarter/libs/utils/RewardUtils.java
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
- app/src/test/java/com/kickstarter/libs/utils/RewardUtilsTest.java
**New Pledge:** Currently, add-ons with start dates in the future are being shown in the add-ons screen. These should be hidden from view until the start date set by the creator.
**Updating same reward:** when a user is editing their reward, they are able to tap on the initial reward that they pledged for and then should see all available add-ons, as well as any that are not available that were in their original pledge (with their qty selection retained). this is so that they can adjust the quantity downward, or remove them
**Updating to another reward:** same behaviour as new pledge
- RewardUtils new method for checking if a reward is within a valid time range
- Extended `filterOutUnAvailableExceptIfBacked` to `filterOutUnAvailableOrEndedExceptIfBacked` to filter out if the addOn is …
> NT-1589: Add-on with future start date is available in add-ons screen

- app/src/main/graphql/fragments.graphql
- app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
- app/src/main/java/com/kickstarter/libs/utils/RewardUtils.java
- app/src/main/java/com/kickstarter/models/Reward.java
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
- app/src/test/java/com/kickstarter/libs/utils/RewardUtilsTest.java
- app/src/test/java/com/kickstarter/viewmodels/RewardsFragmentViewModelTest.kt
Several bugs have occurred that allow a backer to back for rewards outside of the time frame that creators set for them. We solved this for when a reward has expired (is past the end date and time the creator set), but there is an additional scenario we missed which is when a reward should not yet be available (because it is before the start date and time the creator set). Currently, backers are able to see these rewards in the carousel and back for them.
- Fetch `startsAt` field for GraphQL and V1 APIs. 
- Filter out from the rewards list on RewardsFragmentViewModel the ones that hasn't started yet
- Added new method on RewardsUtils to check if a Reward is limited on staring time
- Added new method on RewardsUtils to check if a Reward has started or not
- Before 🐛  you could see the not …
> NT-1585:Reward with starting time restriction not started yet.

- app/src/main/graphql/fragments.graphql
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- **Before** we where fetching field `shippingRules` which do not contains all the possible configurations a creator can do for shipping locations 
- **Now** we fetch the field `shippingRulesExtended` instead that covers all the possible configurations a creator can make (worlwide, european union or other regions, concrete countries ... etc).
- in `fragments.graphql` the fragment for reward has been updated to fetch `shippingRulesExpanded` instead of `shippingRule`
- Take a look into the shipping costs in each addOn here, United states is 0, the rest of the countries is 5
|  |  |
1- Visit project: https://www.kickstarter.com/projects/tommy-chonkers/chonkers-naturally-calming-weighted-stuffed-animals?ref=checkout_rewards_page (in production)
2 - Tap reward Early Backer Bundle ($58)
3 - See …
> NT-1587: AddOns costs 

- app/src/main/graphql/fragments.graphql
- app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
- app/src/main/java/com/kickstarter/libs/utils/RewardUtils.java
- app/src/main/java/com/kickstarter/models/Reward.java
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
- app/src/test/java/com/kickstarter/libs/utils/RewardUtilsTest.java
- app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardsFragmentViewModelTest.kt
- Bug when changing reward from digital to one with location
- **Before**: emmiting default location to selectedShipping rule always, Emmiting shipping location from Backing object
- **now** : default location is emmited just in case the reward isShippable and not digital, emmited shipping location from backing object just if it's the same reward.
-  added new test modified previous one
- Update reward from digital to another one with location 
- Updated reward from located to a digital one
|  |  |
1 - Navigate to a project (Bring Back Weekly World News on staging)
2 - Select a reward with no shipping
3 - Pledge to a digital reward
4 - Tap overflow menu, selected Edit Reward
5 - Choose a reward that includes shipping and offers add-ons
Expected: Shipping selector populates available …
> NT- 1591:Blanck screen edit reward flow

- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
- **BEFORE** : every time the amount was updated, the addOn item was re-builded to reflact that amount, by doing that the rx-chains where triggered again.
- **NOW**: will keep the reference to the selected addOns. We will update the quantity of the items just once the continue button has been pressed.
- On projects with large amount of addOns there was performance issues when selecting the addOns try for example the this project with 25 addOns ->  https://www.kickstarter.com/projects/jake61341/santa-claus-mug-enamel-pin?ref=nav_search&result=project&term=santa%20claus%20pin
- Select many addOns from a list of 25 addOns
- memory usage screenshoot
|  |  |
- ⚠️ in order to about the current timeout, if testing this PR, query for now shippingRules instead of shippingRulesExtended in case not …
> NT-1587: Improve performance

- app/src/main/res/layout/item_add_on_pledge.xml
Design polish on add-ons "Add" button. 
To align add-ons with standard Kickstarter button style. 
Update XML from `AppCompatTextView` into an `AppCompatButton`, add an elevation attribute, and correct the text appearance to be a button. 
|  |  |
- Select project with add-ons
- Tap "Back Project"
- Tap a reward with add-ons
- View "Add" button on add-on card
[NT-1454: Android Add-ons Button Polish](https://kickstarter.atlassian.net/browse/NT-1454?atlOrigin=eyJpIjoiMTlkNmZhZGQ0ZDFlNDhjYzg2N2Q3MzE4OWIwYjYxNDYiLCJwIjoiaiJ9)
> NT-1454: Android Add-ons Button Polish

- app/src/main/graphql/fragments.graphql
- app/src/main/graphql/project.graphql
- app/src/main/graphql/schema.json
- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/models/Location.java
- app/src/main/java/com/kickstarter/services/ApolloClientType.kt
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
- the backend has provided has a new query for filtering shippingRulesExtended by locationId
- Modified Rewards graphql fragment to not retrieve shippingRulesExpanded
- modified GetProjectAddOns query receive a new parameter for locationId
- in addOns nodes item use the new ShippingRulesExtended query with the locationId as parameter
- removed unnecessary fields from location graphql fragment
- modified KsApolliClient to parser the new structure for shippingRulesExtended
- When updating backed addOns modify the bakedAddOn item to hold the shippingRules from that same item from graphql
- in pledge fragment do not use the backing shippingRule if the selected reward has backed addOns
- **Before networking**  10 Second
- **Now networking** less than 1 second
- In the …
> NT-1587: Query with filtering for shippingRules

- app/src/main/res/layout/fragment_pledge_section_bonus_support.xml
- app/src/main/res/layout/fragment_pledge_section_editable_shipping.xml
- app/src/main/res/layout/fragment_pledge_section_shipping.xml
Padding above the shipping selector was too large compared to the padding above the bonus support fragment. 
Before: 
After:
- Find a project with multiple shipping locations
- On the pledge screen, observe the spacing above the shipping selector
[NT-1479: Android Pledge Screen Polish](https://kickstarter.atlassian.net/browse/NT-1479)
> NT-1479: Android Pledge Screen Polish

- app/build.gradle
- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/KSApplication.java
- app/src/main/java/com/kickstarter/libs/BaseActivity.java
- app/src/main/java/com/kickstarter/libs/TrackingClient.kt
- app/src/main/java/com/kickstarter/services/TrackingWorker.kt
- app/src/main/java/com/kickstarter/services/firebase/RegisterTokenWorker.kt
- app/src/main/java/com/kickstarter/services/firebase/ResetDeviceIdWorker.kt
- app/src/main/java/com/kickstarter/services/firebase/UnregisterTokenWorker.kt
- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/ui/adapters/KSAdapter.java
- app/src/main/java/com/kickstarter/ui/adapters/KSListAdapter.kt
- app/src/test/java/com/kickstarter/TestKSApplication.java
- Deprecate crashlytics dependecy to use Firebase crashlytics
- they are shutting down crash reports 
- Following this migration guide https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=android&authuser=1
- Created a few test builds with versions 2.10.0 one for internalRelease variant and another one for externalRelease variant
|  |  |
- Take a look into this PR and follow the QA steaps inside it [internal steps](https://github.com/kickstarter/native-secrets/pull/74)
[NT-1428](https://kickstarter.atlassian.net/browse/NT-1428)
> NT-1428- Migration from Crashlytics to firebase crashlytics

- app/src/main/java/com/kickstarter/ui/activities/UpdateActivity.java
- We cannot reproduce the error, we are just trying to avoid it.
- Avoid any possible memory leak from the webView or having the webview runnig but dettached from the Activity cleaning up those two components when onDestroy.
- This PR goes along with another one in [here](https://github.com/kickstarter/native-secrets/pull/75), more detail inside.
- Once that PR is merged run `make secrets` in your local environment.
- Start the QA specified in that PR
|  |  |
> NT-1630: Fix UpdateActivity crash 

- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- In case using the GraphQL query for backing we receive a backing object, without backer information, feed empty instead of null to the dataModel.
- avoid null on backer name
- avoid shadowing it parameter
[Crash report](https://console.firebase.google.com/u/1/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/310732673fa17a383580c28e897e2993?time=last-twenty-four-hours&versions=2.9.0%20(2010151641)&sessionEventKey=5F9076F502EC00017613A6D13BB67AFF_1464580771640330662)
|  |  |
- we could not reproduce it
[NT-1625](https://kickstarter.atlassian.net/browse/NT-1625)
> NT-1625: Fix crash 

- app/src/main/java/com/kickstarter/libs/utils/RewardViewUtils.kt
- app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
- app/src/test/java/com/kickstarter/libs/utils/RewardViewUtilsTest.kt
- Backed reward with available addOns always available button text should read "Continue" instead of "Select"
| Before 🐛 |
| After 🦋 |
|  |  |
1. Pledge to project project
2. Select a reward that has add-ons available
3. Skip add-ons
4. Complete pledge
5. Enter edit reward flow
6. Actual: Disabled button that reads "Selected" 
Expected: Button reads continue, allows user to continue in flow
[NT-1615](https://kickstarter.atlassian.net/browse/NT-1615)
> NT-1615:copy change

- app/src/main/java/com/kickstarter/models/Backing.java
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
- Reward delivered checkbox not being persisted
- When the migration to graphql took place, we did not realize the field `DateTime backerCompletedAt` from V1, in graphQl is `backerCompleted`
- We already query the field `backerCompleted` when getting the backing, in the Pr we serialize it into a new field on Backing Object `completedByBacker`
|  |  |
1. Tap into profile
2. Tap into a project you've backed
3. Tap View your pledge
4. See "Reward delivered?" checkbox
5. Tap checkbox
6. Return to profile
7. Repeat steps 1-4
Expected:  "Reward delivered?" checkbox is checked
[NT-1634](https://kickstarter.atlassian.net/browse/NT-1634)
> NT-1634: Persist reward delivered checkbox

- app/src/internal/java/com/kickstarter/ui/activities/InternalToolsActivity.java
- app/src/internal/res/layout/internal_tools_layout.xml
- app/src/main/java/com/kickstarter/ui/fragments/EmailVerificationInterstitialFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/EmailVerificationInterstitialFragmentViewModel.kt
- app/src/main/res/drawable/ic_email.xml
- app/src/main/res/layout/fragment_email_verification_interstitial.xml
- app/src/main/res/values/strings_i18n.xml
Included in this PR: 
- Interstitial layout, viewmodel, and fragment
- Button added to internal tools screen to launch the interstitial fragment
- Added new copy 
- Added new email icon drawable
- Tap on the overflow menu on the discovery screen
- Tap "internal tools" 
- Scroll to the bottom of this screen, should see a green button that reads "Email Verification Interstitial"
- Tap this button, should see the interstitial fragment popup.
[Build Interstitial Screen UI](https://kickstarter.atlassian.net/browse/NT-1648)
> NT-1648: Email Verification Interstitial UI (#1033)

- app/src/internal/java/com/kickstarter/ui/activities/InternalToolsActivity.java
- app/src/main/java/com/kickstarter/mock/factories/UserFactory.java
- app/src/main/java/com/kickstarter/ui/ArgumentsKey.java
- app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
- app/src/main/java/com/kickstarter/ui/fragments/EmailVerificationInterstitialFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
- app/src/main/res/layout/login_layout.xml
- app/src/test/java/com/kickstarter/viewmodels/LoginViewModelTest.kt
- Attached Interstitial screen into login flow
- Created new output in LoginViewModel for the interstitial screen
- Launch EmailVerificationInterstitialFragment new Instance with the user returned from the login request
|  |  |
- Log in with an user that has not validated their email ->user: isatest@test.com, password: isatest
- - if you have the feature flag active: Interstitial screen is shown
- - if you don't have the feature flag active: you can log in into the app without problems
[NT-1652](https://kickstarter.atlassian.net/browse/NT-1652)
> NT-1652: Connect login flow to interstitial

- app/src/main/java/com/kickstarter/ui/fragments/EmailVerificationInterstitialFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/EmailVerificationInterstitialFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/EmailVerificationInterstitialFragmentViewModelTest.kt
When the user taps "Open Inbox", they will either be taken to their default application, or shown a list of apps that they can choose from to open their email. If they have no apps available for email, it will show an "empty state" bottom sheet.
We want users to be able to open their inbox application immediately upon receiving the verification email from kickstarter. 
When the user taps on the "Open Inbox" button, the viewmodel responds by sending at intent with parameters attached that indicate we would like to open an email application. This is built into the Android framework. 
- Tap on ovreflow menu
- Tap on "Internal Tools"
- Scroll to bottom, tap "Email Verification Interstitial"
- Tap "Open Inbox"
- Default email app or a list of email applications should appear. 
[NT-1650: The …
> NT-1650: The user can navigate to their inbox from the app

- app/src/main/java/com/kickstarter/libs/utils/LoginHelper.kt
- app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/SignupActivity.java
- app/src/main/java/com/kickstarter/viewmodels/SignupViewModel.java
- app/src/main/res/layout/signup_layout.xml
- app/src/test/java/com/kickstarter/viewmodels/SignupViewModelTest.java
- Present Interstitial Screen on CreationAccount flow
- Adde new method in LoginHelper.kt `showInterstitialFragment(supportFragmentManager: FragmentManager, user: User, loginViewId: Int)` 
- Added new output to present the Interstitial screen on SignUpViewModel.java
- new tests
|  |  |
- Create account with feature flag enabled presents the Interstitial screen
- Create account with feature flag disabled do not present Interstitial screen and let's you continue flow.
[NT-1653](https://kickstarter.atlassian.net/browse/NT-1653)
> NT-1653: Create account flow

- app/src/main/graphql/fragments.graphql
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/main/res/layout/backing_toolbar.xml
- app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
- Visual tweecks for the View Pledge screen, creator and backer perspective
- **The title of the creator View Pledge screen reads “View pledge”**
- **The title of the reward is shown in the reward card**
- **The estimated delivery date of the reward is shown above the reward card when no reward in Backer perspective**
| --- | --- |
|  |  |
- For the first two points log as a creator, go to a message from a backer and press the view pledge button on the ThreadMessages screen
- For the last point pledge to any reward no reward, the go to the view pledge screen
[Android creator view pledge adjustments](https://kickstarter.atlassian.net/browse/NT-1595)
> NT-1595: Creator view adjustments

- app/src/main/java/com/kickstarter/libs/Koala.java
- app/src/main/java/com/kickstarter/libs/LakeEvent.kt
- app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
- app/src/main/java/com/kickstarter/viewmodels/EmailVerificationInterstitialFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/EmailVerificationInterstitialFragmentViewModelTest.kt
Added two new tracking events: 
- when the Interstitial screen is presented: "Verification Screen Viewed"
- when the skip verification button is clicked: "Skip Verification Button Clicked"
|  |  |
- Take a look into the logs filtering by "TrackingClient" when presenting the interstitial screen you'll see the "Verification Screen Viewed" event
- If the feature flag is active you'll be able to see and press the skip button, so press it and take a look into the logs filtering by "TrackingClient" you'll be able to see the "Skip Verification Button Clicked" event
[NT-1656](https://kickstarter.atlassian.net/browse/NT-1656)
> NT-1656: Tracking Events

- app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
- app/src/main/java/com/kickstarter/viewmodels/EmailVerificationInterstitialFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/EmailVerificationInterstitialFragmentViewModelTest.kt
- When the interstitial is presented we send the validation email
|  |  |
- Every time you open the Interstitial with an user logged in you should get an email.
[NT-1680](https://kickstarter.atlassian.net/browse/NT-1680)
> NT-1680: Send Email when interstitial presented

- app/build.gradle
- Update to latest Facebook SDK
- Spike on crashes related to Facebook SDK 
- [Firebase report](https://console.firebase.google.com/u/1/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/060f7462f52530baa36a02097ec5a4b1?time=last-seven-days&sessionEventKey=5FCE67A802B0000156333B2EFFFF4B3B_1482014854853983481)
|  |  |
- Make sure you are on production not staging and try to log in using Facebook
[NT-1694](https://kickstarter.atlassian.net/browse/NT-1694)
> NT-1694: Update facebook SDK version

- app/build.gradle
Now we adopted the latest Kotlin version, that allow us to upgrade some other dependencies that do not require implementation changes to the current code base: 
**Google depencies:**
```
'androidx.recyclerview:recyclerview:1.1.0-beta01' → 'androidx.recyclerview:recyclerview:1.2.0-beta01'
'androidx.work:work-runtime-ktx:2.3.4' → 'androidx.work:work-runtime-ktx:2.4.0'
'com.android.support.constraint:constraint-layout:1.1.3' → 'com.android.support.constraint:constraint-layout:2.0.4'
"com.google.android.gms:play-services-wallet:18.0.0" → "com.google.android.gms:play-services-wallet:18.1.2"
'com.google.android.material:material:1.1.0-alpha08' → 'com.google.android.material:material:1.3.0-alpha04'
"com.google.dagger:dagger:2.11" → "com.google.dagger:dagger:2.28.3"
buildToolsVersion '29.0.2' → …
```
> NT-1695: Update dependencies

- app/src/main/java/com/kickstarter/ui/itemdecorations/TableItemDecoration.kt
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
- app/src/main/res/color/white_enabled_gray_disabled.xml
- app/src/main/res/drawable/circle_gray_filled.xml
- app/src/main/res/drawable/circle_gray_outline.xml
- app/src/main/res/drawable/circular_click_indicator_light.xml
- app/src/main/res/drawable/rect_grey_rounded.xml
- app/src/main/res/drawable/text_view_rect_background.xml
- app/src/main/res/layout/activity_settings_payment_methods.xml
- app/src/main/res/layout/fragment_backing.xml
- app/src/main/res/layout/fragment_cancel_pledge.xml
- app/src/main/res/layout/fragment_pledge_section_accountability.xml
- app/src/main/res/layout/item_errored_backing.xml
- app/src/main/res/layout/message_view.xml
- app/src/main/res/layout/qualtrics_prompt.xml
- app/src/main/res/values/colors.xml
- Added KDS-support-200 (#E6E6E6)
- Substitute kds_support_300 over kds_support_100 or kds_support_200
* **background on the Updates and Comments counter to support-100.**
* **background on the disabled state of the stepper to be support-200.**
* **background color on the “KSR is not a store” component to KDS-support-200**
* **state of a pledge to KDS-support-200 to background of the “Delivery dates are not guaranteed” cell to KDS-support-200**
* ** background of these circles to KDS-support-100.**
* **status bar globally to support-100.**
|  |  |
[NT-1689](https://kickstarter.atlassian.net/browse/NT-1689)
> NT-1689: Grey adjustments

- app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ResetPasswordActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/ResetPasswordViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ResetPasswordViewModelTest.kt
fill email field in reset password screen with the email from the login screen  
If the user enters an email address on the login screen and they navigate to the forgot password screen
- Pass email from Login Activity through Intent to Reset Password Activity
| --- | --- |
|  |  |
NT-1580/Android Forgot Password Email
> NT-1580 : Forgot password email

- app/src/main/java/com/kickstarter/libs/LakeTrackingClient.kt
- app/src/main/java/com/kickstarter/libs/SegmentTrackingClient.kt
- app/src/main/java/com/kickstarter/libs/TrackingClient.kt
- app/src/main/java/com/kickstarter/libs/TrackingClientType.kt
- Moved some specific Lake code from the `TrackingClient` class to the `LakeTrackingClient`, on `TrackingClient` we should have generic implementations valid for the two tracking clients(Lake and Segment);
- Added `.disctingUntilChanged` operator when listening to the current user in order to avoid duplicated calls to `Identify`
- Removed koalaProperties specifics to Koala client that was already removed
- All test Ok
- Checkout this branch and launch the app, see that the worker for Lake keep working as before, you can check the logcat successfully tracked line
[NT-1751](https://kickstarter.atlassian.net/browse/NT-1751)
> NT-1751: Small Refactor

- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/libs/LakeTrackingClient.kt
- app/src/main/java/com/kickstarter/libs/SegmentTrackingClient.kt
- app/src/main/java/com/kickstarter/libs/TrackingClient.kt
- app/src/main/java/com/kickstarter/libs/TrackingClientType.kt
- app/src/test/java/com/kickstarter/KSRobolectrictTestCase.kt
- app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
- app/src/test/java/com/kickstarter/libs/SegmentTest.kt
- app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/LoginViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/SignupViewModelTest.java
- Every time a user logs in or sign up we need to identify that user on segment
- Generation of Funnels in Segment requires to Identify Users
- We listen to the currentUser observable on the base `Trackingclient` and call `identify` method.
**- Debug Logcat line for identify call**
**- Android staging source** 
|  |  |
- Check on the android staging source that and identify call is registered when you log in in the app
- Check on the android staging source that and identify call is registered when you log in with an user with tfa challenge in the app
- Check on the android staging source that and identify call is registered when sign up in in the app
- Check on the android staging source that and identify call is registered when sign up with facebook in in the app
- Check no duplicated …
> NT-1747: Identify users on segment

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/libs/SegmentTrackingClient.kt
- app/src/main/java/com/kickstarter/libs/TrackingClient.kt
- app/src/main/java/com/kickstarter/libs/TrackingClientType.kt
- app/src/main/java/com/kickstarter/viewmodels/ChangePasswordViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/CreatePasswordViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/SettingsViewModel.kt
- app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
- app/src/test/java/com/kickstarter/viewmodels/ChangePasswordViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/CreatePasswordViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/SettingsViewModelTest.kt
- `Reset` method from segment SDK needs to be called when a logged in user logs out 
- Added new method `reset` on `AnalyticsEvents` and the rest of the hierarchy
- Logout from the app
- Take a look into logcat, you'll see the debug logs for the reset method being called
[NT-1751: Call reset on logout](https://kickstarter.atlassian.net/browse/NT-1751)
> NT-1751: Reset method called when user logs out

- app/src/main/java/com/kickstarter/libs/TrackingClientType.kt
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
- app/src/test/java/com/kickstarter/libs/SegmentTest.kt
- property `session_client_platform` has been renamed to `session_platform`
- property `session_device_format` has been renamed to `session_device_type`
- property `session_client_type` has been renamed as `session_client`
|  |  |
- Look logcat and search for `session_platform`: 
- Look on logcat and search for `session_device_type`
- Look on logcat and search for `session_client`
[https://kickstarter.atlassian.net/browse/EP-153](https://kickstarter.atlassian.net/browse/EP-153)
> EP-153:Rename properties session_*

- app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
- app/src/test/java/com/kickstarter/libs/SegmentTest.kt
- property `pledge_backer_reward_estimated_delivery_on` as been renamed as `checkout_reward_estimated_delivery_on`
-  property `pledge_backer_reward_is_limited_quantity` as been renamed as `checkout_reward_is_limited_quantity` 
- property `pledge_backer_reward_is_limited_time` as been renamed as `checkout_reward_is_limited_time` 
- property `pledge_backer_reward_shipping_enabled` as been renamed as `checkout_reward_shipping_enabled` 
- property `pledge_backer_reward_shipping_preference` as been renamed as `checkout_reward_shipping_preference` 
- property `pledge_backer_reward_title` as been renamed as `checkout_reward_title`
|  |  |
- Pledge to a project, a reward with shipping location, and search in logcat for `checkout_reward_estimated_delivery_on`:
- Pledge to a project,  and search …
> EP-153: Rename properties checkout_reward_*

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
- Added track event for add-ons continue button clicked that fires when the continue button is pressed on the add-ons screen. 
- Created a new function to our `AnalyticsEvents` class that handles sending the event name and properties to the client. 
- Added this function to our `BackingFragmentViewModel` when the continue button is clicked. 
- Sign into your account on staging
- Find a project with add-ons
- Back Project -> Select Reward -> Tap "Continue" on add-ons screen. 
- Both Segment (CTA Clicked) and DataLake (Add-ons Continue Button Clicked) should appear in the segment dashboard:
- In segment, tap CTA Clicked. On the right should appear a list of properties sent with this event. 
[EP-215: Android: CTA Clicked …
> EP-215: Create event for Add-ons Continue button

- app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
- app/src/main/java/com/kickstarter/libs/utils/extensions/CheckoutDataExt.kt
- app/src/main/java/com/kickstarter/ui/data/CheckoutData.kt
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
- app/src/test/java/com/kickstarter/libs/SegmentTest.kt
- app/src/test/java/com/kickstarter/libs/utils/extensions/CheckoutDataExtTest.kt
- property `project_current_pledge_amount_usd` has been renamed as `project_current_amount_pledged_usd`
- property `checkout_revenue_in_usd_cents` has been exchanged over `checkout_amount_total_usd` is the sum of shipping, bonus support, and add-ons in USD
- Pledge a project and take a look into logcat:
- Pledge to a project with addons with shipping location for addons and reward in other currency different from USD. In this screenshot you can see how 71 uk pounds is transformed to 96.46...USD for the property `checkout_amount_total_usd`
[EP-153: Rename properties](https://kickstarter.atlassian.net/browse/EP-153)
> EP-153: Rename Properties

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Added track event for "pledge initiate" button clicks that fires when the "Back this project" button is pressed on the projects screen.
- Created a new function to our AnalyticsEvents class that handles sending the event name and properties to the client.
- Added this function to the `ProjectViewModel` when the "Back this project" button is pressed.
This is the button that fires this event. 
- Tap on a live project
- Tap "Back this project" CTA at bottom of screen 
Both Segment (CTA Clicked) and DataLake (Project Page Pledge Button Clicked) should appear in the segment dashboard:
- Tap on CTA Clicked, the list of properties should appear on the right side of the screen:
[EP-216: Android: CTA Clicked (pledge_initiate)](https://kickstarter.atlassian.net/browse/EP-216)
> EP-216: Create event for Pledge Initiate CTA

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kickstarter/ApplicationGraph.java
- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/libs/perimeterx/PerimeterXClient.kt
- app/src/main/java/com/kickstarter/libs/perimeterx/PerimeterXClientType.kt
- app/src/main/java/com/kickstarter/libs/utils/Secrets.java.example
- app/src/main/java/com/kickstarter/services/interceptors/ApiRequestInterceptor.java
- app/src/main/java/com/kickstarter/services/interceptors/GraphQLInterceptor.kt
- app/src/main/java/com/kickstarter/services/interceptors/KSRequestInterceptor.java
- app/src/main/java/com/kickstarter/services/interceptors/WebRequestInterceptor.java
- app/src/main/java/com/kickstarter/ui/views/KSWebView.kt
- config/KSWebViewClient.java
Due to the recent security issues we are adding a new authorization layer
- Added dependency
- For each Interceptor, the header is added
|  |  |
- Launch the app, open the network profiles, on the request you should see the header.
- Also take a look into: https://github.com/kickstarter/native-secrets/pull/80 having that PR merged is a requirement for this one.
[NT-1768: PerimeterX](https://kickstarter.atlassian.net/browse/NT-1768)
> NT-1768: PerimeterX-Headers

- app/build.gradle
- app/src/main/java/com/kickstarter/libs/PushNotifications.java
- app/src/main/java/com/kickstarter/ui/activities/EditProfileActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ProfileActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.kt
- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
- app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleFriendBackingViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleFriendFollowViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleProjectViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/CommentViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/FriendBackingViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/FriendFollowViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/MessageThreadViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/MessageViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/ProfileCardViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectCardViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectContextViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectSearchResultViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectSocialViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectStateChangedPositiveViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectStateChangedViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectUpdateViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/SurveyViewHolder.java
- app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/LoggedInViewHolder.kt
integrate  firebase in-app messaging to app
To be able to communicate with app and send the in-app message in case user disable notification 
Add firebase in-app messaging dependencies to the app 
Use the firebase in-app messaging Picasso version to remove Picasso dependence and update code 
| --- | --- |
|  |  |
Test Screen that shows images 
https://kickstarter.atlassian.net/browse/NT-1766
> NT-1766:Add firebase In-App Messaging

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Added track event for "pledge submit" button clicks that fires when the "Pledge" button is pressed on the checkout screen.
Segment Integration
- Created a new function to our `AnalyticsEvents` class that handles sending the event name and properties to the client.
- Added this function to the `PledgeFragmentViewModel` when the "Pledge" button is pressed.
This is the button that fires this event: 
- Tap on a live project
- Tap "Back this project" CTA at bottom of screen
- Select a reward and/or addons
- On the checkout screen, tap "Pledge" 
- Both Segment (CTA Clicked) and DataLake (Pledge Submit Button Clicked) should appear in the segment dashboard. 
You should see `context_cta = "pledge_submit"` as well as `context_type = "credit_card"`
[EP-217: Android: CTA Clicked …
> EP-217: Create event for Pledge Submit CTA

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
Added track event for selecting a reward button clicks that fires when the "Select" button is pressed on the reward carousel.
Segment Integration
Created a new function to our `AnalyticsEvents` class that handles sending the event name and properties to the client.
Added this function to the `RewardViewHolderViewModel` when the "Select" button is pressed on a reward in the reward carousel.
This is the button that fires this event:
- Tap on a live project
- Tap "Back this project" CTA at bottom of screen
- Tap "Select" on a reward in the reward carousel
- Both Segment (CTA Clicked) and DataLake (Select Reward Button Clicked) should appear in the segment dashboard. You should see `context_cta = "reward_continue"`
[EP-218: Android: CTA Clicked …
> EP-218: Create event for Select Reward CTA

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/libs/utils/EventContext.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
- Added track event for add-ons screen that fires when the `BackingAddonsFragmentViewModel` is loaded. 
- Fixed instances of "CTA Clicked" in `ProjectViewModelTest` to use a constant instead of a string literal.
Segment Integration
- Created a new function in the `AnalyticsEvents` class that handles sending the event name and properties to the client.
- Added this function to the `BackingAddonsFragmentViewModel` when the initialization method is called.
This is the screen that fires this event:
- Tap on a live project that has add-ons
- Tap "Back this project" CTA at bottom of screen
- Select a reward which should then proceed to the add-ons screen 
- Both Segment (Page Viewed) and DataLake (Add-Ons Page Viewed) should appear in the segment dashboard.
- You should see `context_page = …
> EP-219: Create event for Add-ons screen viewed

- app/build.gradle
- app/src/main/java/com/kickstarter/libs/PushNotifications.java
- app/src/main/java/com/kickstarter/ui/activities/EditProfileActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ProfileActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.kt
- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
- app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleFriendBackingViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleFriendFollowViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleProjectViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/CommentViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/FeaturedSearchResultViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/FriendBackingViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/FriendFollowViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/MessageThreadViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/MessageViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/ProfileCardViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectCardViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectContextViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectSearchResultViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectSocialViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectStateChangedPositiveViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectStateChangedViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectUpdateViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/ProjectViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/SurveyViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/LoggedInViewHolder.kt
Change Picasso call in viewholder to Picasso.get()
Integrating firebase in-app messaging sdk user higher version from Picasso lib
Change Picasso call in viewholder from Picasso.with(context) to Picasso.get()
| --- | --- |
|  |  |
test all lists that have images to show
https://kickstarter.atlassian.net/browse/NT-1777
> NT-1777:Refactor Picasso code due to integrate firebase in-app sdk

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
- Added track event for add-ons screen that fires when the `PledgeViewFragmentViewModel` is loaded.
Segement integration. 
- Created a new function in the AnalyticsEvents class that handles sending the event name and properties to the client.
- Added this function to the `PledgeViewFragmentViewModel` when the initialization method is called.
- This event only fires when the checkout is loaded from a new pledge, this does not fire when updating or managing a pledge. 
- 
This is the screen that fires this event:
- Tap on a live project 
- Tap "Back this project" CTA at bottom of screen
- Select a reward or no reward
- If project has add-ons, press skip CTA or choose an addon and press continue
- Both Segment (Page Viewed) and DataLake (Checkout Payment Page Viewed) should appear in the …
> EP-220: Create event for Checkout screen viewed

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardsFragmentViewModelTest.kt
- Added track event for the rewards carousel screen that fires when the `RewardsFragmentViewModel` is loaded.
Segment Integration. 
- Created a new function to our AnalyticsEvents class that handles sending the event name and properties to the client.
- Added this function to our `RewardsFragmentViewModel` when this vm is initialized.
This is the screen that triggers the event:
- Select any project
- Tap "Back this project"
- This should open the rewards carousel
- Segment (Page Viewed) should appear in the segment dashboard. There is no datalake event for this analytic event.
- Tapping "Page Viewed"  in segment should show the list of properties sent with this event.
[EP-221: Android: Page Viewed (rewards)](https://kickstarter.atlassian.net/browse/EP-222)
> EP-221: Create event for Rewards Carousel viewed

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
- app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectDataExt.kt
- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ProjectUpdatesActivity.java
- app/src/main/java/com/kickstarter/viewmodels/CampaignDetailsViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/ProjectUpdatesViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/CampaignDetailsViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/ProjectUpdatesViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
- Created a new function to our `AnalyticsEvents` class that handles sending the event name and properties to the client, including which section of the project page is viewed.
- Added this function to our `ProjectViewModel` and all associated sections of the project page when their viewmodels are initialized.
Segment Integration.
- There are 4 "context_sections" that send events in the projects flow: 
1. "overview" the project screen: Updated the event in the `ProjectViewModel`
2. "coments" the comments screen of the project: Added an event to the `CommentsViewModel`
3. "campaign" the campaign details screen of the project: Added event to the `CampaignDetailsViewModel`
4. "updates" the project updates screen: Added event to the `ProjectUpdatesViewModel`
I also had to send additional …
> EP-221: Create event for Project screen viewed

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.java
- Added track event for tracking the Thanks screen viewed.
- Created a new function to our `AnalyticsEvent`s class that handles sending the event name and properties to the client.
- Added this function to our `ThanksViewModel` when the vm is initialized. 
This is the screen that triggers this event:
- Sign into your account on staging
- Select a project
- Back this project with any reward
- After successfully completing checkout, you should see the Thanks screen
- Both Segment (Page Viewed) and DataLake (Thanks Page Viewed) should appear in the segment dashboard.
- Tapping "Page Viewed" in segment should show the list of properties sent with this event with the context_page = thanks, and context_type = new_pledge:
[EP-223: Android Page Viewed …
> EP-223: Create event for Thanks screen viewed

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
- app/src/main/java/com/kickstarter/libs/utils/EventKeys.kt
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
Android: Page Viewed (discover)
- Add segment implementation for discovery sort page views
- For every sort - page selected, an event is submitted
- Data lake Event to Convert for Segment
- To track sort page selected events on the discovery page
- Created a new method in the AnalyticEvent class to submit the new event to segment
- Called method from DiscoveryFragmentViewModel class for every page selected
| --- | --- |
|  |  |
- On the discovery page select "MAGIC, POPULAR,  NEWEST OR ENDING SOON"
- Go to segment console/dashboard, you should see the event registered
https://kickstarter.atlassian.net/browse/EP-247
> EP- 247: Android: Page Viewed (discover)

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
- Added a track event for watch project click events that fire when the "heart" button is tapped on a projects page.
- Created a new function to our `AnalyticsEvents` class that handles sending the event name and properties to the client.
- Added this function to the `ProjectViewModel` that fires when the heart button is tapped and we received the project back from v1.
Note that this event can only be fired from the project screen. This is the button that fires the event:
Logged out:
- Tap on a project
- On the projects screen, tap the empty heart in the upper right corner
- Login
- Upon returning to the project screen, the heart should now be red
- In segment, CTA clicked should appear with properties context_cta = "watch_project" and context_type = "watch"
Logged …
> EP-244: Create event for watch project CTA

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
- Added segment implementation for UPDATE PLEDGE page viewed event
Segment Integration
- Added new method ```trackUpdatePledgePageViewed``` to  ```AnalyticEvents``` class
- Called method from ```PledgeFragmentViewModel``` class on page load
| --- | --- |
|  |  |
- Navigate to the ```profile page```, select from the list of backed projects
- Click ```Manage``` button 
- From the toolbar options menu, select ``` Update Pledge ```
You should see the new event submitted
https://kickstarter.atlassian.net/browse/EP-322
> EP-322: Page Viewed (update_pledge)

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
- app/src/main/java/com/kickstarter/libs/utils/EventName.kt
- app/src/main/java/com/kickstarter/viewmodels/ActivityFeedViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/ProfileViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/ActivityFeedViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
- app/src/test/java/com/kickstarter/viewmodels/ProfileViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/SearchViewModelTest.java
- Added a track event that fires when project cards are clicked.
- Created a new function to our `AnalyticsEvents` class that handles sending the event name and properties to the client.
- Added this function to the `DiscoveryFragmentViewModel`, `ProfileViewModel`, `SearchViewModel`, and `ActivityFeedViewModel` that fires when the project card clicked stream has an emission.
Tapping a project card on any of these screens will fire a card clicked event
Discover:
- Open the app
- Tap on a project on the discover/explore feed
- Segment should log an event named "Card Clicked" with the `context_page = explore` and `context_type = project`
Activity Feed:
- Open the app
- Tap on the overflow menu in the top left corner of the screen
- Select "Activity"
- Tap on a project
- …
> EP-257: Create event for Project Card Clicked

- app/src/main/java/com/kickstarter/models/Backing.java
- app/src/main/java/com/kickstarter/ui/activities/MessagesActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
- When using a payment method with 3DS auth the payment completes successfully but the app ends app crasing.
Once we have a successful pledge, a new request is made to retrieve the baking information from GraphQl, in order to populate the `Manage Pledge Screen`. On our Backing Data Model we have some non-nullable fields that the app expects to always have results for them (in other words it never expects null values), see https://github.com/kickstarter/android-oss/blob/ed7eb8e1fb1c76d1999ca0270ac840f9271ac790/app/src/main/java/com/kickstarter/models/Backing.java#L36 , but in this concrete type of flow the query `GetProjectBacking` give us the field `pledgeAt` as `null` 
- The field `pledgeAt` inside Backing data model has change to be an optional field.
| Before 🐛 | …
> NT-1805: Payment with 3DS card flow

- app/src/main/java/com/kickstarter/mock/factories/BackingFactory.java
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
- Even though when we parse the response from Graph the BackingObject created should have been initialized properly, see https://github.com/kickstarter/android-oss/blob/b1e6070aaf6ee699d9aa2c31a71417f0c238bae6/app/src/main/java/com/kickstarter/services/KSApolloClient.kt#L630
We've been seeing crashes related with nullability issues, an wrong threads trying to Update the UI, none of it was reproduced locally, if you need more details go to Firebase Dashboard and look for all the crashes related to `BackingFragment`
- Make sure no value from the ones above showed on the screenshoots is emited being null from the ViewModel to the Fragment
https://user-images.githubusercontent.com/4083656/110556597-b494f000-80f3-11eb-93a0-22861ed03f53.mp4
|  |  |
- Go to your profile and take a look into …
> NT-1756: Backing fragment crashes

- app/src/main/java/com/kickstarter/services/interceptors/ApiRequestInterceptor.java
`this.currentUser.exists()` is deprecated and should not be used. Instead in order to get the current user, observable method should be used and subscribe to it.
|  |  |
- You should be able to log in and make calls to V1 as usual
> [NO-JIRA]: Remove deprecated method

- .circleci/config.yml
- Makefile
- New workflow on CI, this workflow will be triggered when a release branch is detected
- We want to have an automatic process for release, this is the first step.
- Once a release branch is created you will se these jobs triggered on the public android CI environment
- Once the previous work on the public android CI is done these jobs will be triggered on the android **private** CI environment. At this point on the job called release a new APK for release is created and published into firebase on the External Release lane
|  |  |
- If you want to test this the only thing to do is create a new branch from this branch (master once this PR is merged) on the public repository following the name pattern `release*` you will see how all the previous works mentioned will trigger, but Please keep …
> NT-1806: Automatic Release Process- Step 1

- app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
Previously we were sending the wrong value, `ending_soon`, for the ending soon sort tab. This has been updated to the correct value, `end_date`
This was causing violations in segment:
Small change to the way we are grabbing this property.
- Open the app
- Tap "Ending Soon"
- Segment should display the correct value, `discover_sort = end_date`
[EP-378: (Android) Fix discover_sort property value violation](https://kickstarter.atlassian.net/browse/EP-378)
> EP-378: Update discover sort property to send correct value

- app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
Previously we were sending the wrong value for the context_page property, `explore`, when tapping a project card from the discover screen. This has been updated to the correct value, `discover`.
This was causing a violation in segment:
Just changed the value from `explore` to `discover` in the `DiscoveryFragmentViewModel`
- Open the app
- Tap on a project on the discover screen
- Segment should display the correct value, `context_page = discover`
[EP-379: (Android) Fix value for context_page violation on project card clicks ](https://kickstarter.atlassian.net/browse/EP-379)
> EP-379: Fix value for context_page violation on project card clicks

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
- app/src/main/java/com/kickstarter/viewmodels/SignupViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/SignupViewModelTest.java
Android: CTA Clicked (sign_up_submit)
- Added new method ``` trackSignUpSubmitCtaClicked ``` to ``` AnalyticEvents ```
``` 
/**
* Sends data to the client when the submit button is clicked.
*
*/
fun trackSignUpSubmitCtaClicked() {
val props: HashMap<String, Any> = hashMapOf(CONTEXT_CTA.contextName to SIGN_UP_SUBMIT.contextName)
props[CONTEXT_PAGE.contextName] = SIGN_UP.contextName
client.track(CTA_CLICKED.eventName, props)
}
```
- Called method from ``` SignupViewModel ``` on ``` Sign Up ``` button clicked
``` 
this.signupClick
.subscribe(__ -> {
this.lake.trackSignUpSubmitButtonClicked();
this.lake.trackSignUpSubmitCtaClicked();
});
```
| --- | --- |
|  |  |
- On the ``` Sign Up ``` page, fill in all required …
> EP-281 : CTA Clicked (sign_up_submit)

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
- app/src/main/java/com/kickstarter/viewmodels/LoginToutViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.java
Android: CTA Clicked (sign_up_initiate)
- Created new method ``` trackSignUpInitiateCtaClicked ``` 
``` 
fun trackSignUpInitiateCtaClicked() {
val props: HashMap<String, Any> = hashMapOf(CONTEXT_CTA.contextName to SIGN_UP_INITIATE.contextName)
props[CONTEXT_PAGE.contextName] = LOGIN_SIGN_UP.contextName
client.track(CTA_CLICKED.eventName, props)
}
```
- Called method on ``` Sign up with email ``` button clicked.
``` 
this.signupClick
.subscribe(__ -> {
this.lake.trackSignUpButtonClicked();
this.lake.trackSignUpInitiateCtaClicked();
});
```
| --- | --- |
|  |  |
- On the ``` login or sign up ``` page, click ``` Sign up with email ```
- Go to Segment, you should see the new …
> EP-280 : CTA Clicked (sign_up_initiate)

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/viewmodels/LoginToutViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.java
Android: Page Viewed (log_in_sign_up)
- Created method ``` trackLoginOrSignUpPagedViewed ``` in ``` AnalyticEvents ``` class
```
/**
* Tracks a login or sign up page viewed.
* @param type
* @param page
*/
fun trackLoginOrSignUpPagedViewed() {
val props: HashMap<String, Any> = hashMapOf(CONTEXT_PAGE.contextName to LOGIN_SIGN_UP.contextName)
client.track(PAGE_VIEWED.eventName, props)
}
```
- Called method from ``` LoginToutViewModel ``` class
```
intent()
.map(i -> i.getSerializableExtra(IntentKey.LOGIN_REASON))
.ofType(LoginReason.class)
.subscribe( it -> {
this.loginReason.onNext(it);
this.lake.trackLoginOrSignUpPagedViewed();
});
```
| --- | --- |
|  |  |
- Go to the ``` Login or Sign Up ``` screen, You should see …
> EP-332: Page Viewed (log_in_sign_up)

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/viewmodels/SignupViewModel.java
- app/src/test/java/com/kickstarter/viewmodels/SignupViewModelTest.java
Android: Page Viewed (sign_up)
- Created new method ``` trackSignUpPageViewed ``` in ``` AnalyticEvents ```
``` 
/**
* Tracks sign-up page viewed.
*/
fun trackSignUpPageViewed() {
val props: HashMap<String, Any> = hashMapOf(CONTEXT_PAGE.contextName to SIGN_UP.contextName)
client.track(PAGE_VIEWED.eventName, props)
}
```
- Called method from ``` SignUpViewModel ``` on page initialised
```
...
this.lake.trackSignUpPageViewed();
...
```
| --- | --- |
|  |  |
- Visit the ``` Sign Up ``` screen, you should see the new event registered in the segment console
- 
https://kickstarter.atlassian.net/browse/EP-335
> EP-335: Page Viewed (sign_up)

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
- app/src/main/java/com/kickstarter/viewmodels/TwoFactorViewModel.java
- app/src/test/java/com/kickstarter/libs/SegmentTest.kt
- app/src/test/java/com/kickstarter/viewmodels/TwoFactorViewModelTest.java
Added the two_factor_auth as Page Viewed event
Send segment event for two_factor_auth loads on the TwoFactorActivity Activity  
Create  trackTwoFactorAuthPageViewed and call it 
I had to inject that line to be able to navigate to a two-factor-screen and generate segment event 
https://kickstarter.atlassian.net/browse/EP-347
> EP-347/Android: Page Viewed (two_factor_auth)

- app/src/main/java/com/kickstarter/libs/TrackingClient.kt
- app/src/main/java/com/kickstarter/libs/TrackingClientType.kt
- app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
- app/src/test/java/com/kickstarter/libs/SegmentTest.kt
- Create `session_country` property
- Update `SegmentTest` suite
Added `session_country` to the session properties, which gets its value from the `country code` in the `config` object
- Open app
- Fire any event, for example, tap on a project card
- In segment, under that event, you should see the `session_country` property:
[EP-387: [Android] Phase 1 QA Create Property: session_country](https://kickstarter.atlassian.net/browse/EP-387)
> [Android] EP-387: Phase 1 QA Create Property session_country 

- app/src/main/java/com/kickstarter/libs/TrackingClient.kt
- app/src/main/java/com/kickstarter/libs/TrackingClientType.kt
- app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
- app/src/main/java/com/kickstarter/libs/utils/extensions/ConfigExtension.kt
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
- app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
- app/src/test/java/com/kickstarter/libs/SegmentTest.kt
- app/src/test/java/com/kickstarter/libs/utils/extensions/ConfigExtensionTest.kt
- Updated `session_current_variants -> session_variants_internal`
- Added `user_backed_projects_count` to user properties
- Added `user_launched_projects_count` to user properties
- Updated `currentVariants` to return an array instead of a string
- Updated the `SegmentTest` and `LakeTest` class
- Updated the property `session_current_variants` in the `sessionProperties()` function in the `TrackingClient` class, and updated the method that is populating this field to return an array instead of a string. Updated the tests for this new logic as well. 
- Created the property `user_backed_projects_count` in the `userProperties()` function in the `AnalyticEventsUtils` ext
- Created the property `user_launched_projects_count` in the `userProperties()` function in the …
> [Android] EP-389: Phase 1 QA Feedback Priority 1 properties

- app/src/main/java/com/kickstarter/libs/TrackingClient.kt
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
- app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
- app/src/test/java/com/kickstarter/libs/SegmentTest.kt
- Fix capitalization of values for the `session_device_orientation` property to be all lowercase
- Changed "Portrait" -> "portrait"
- Change "Landscape" -> "landscape" 
- Open app and fire any event. For example, tap a project card
- In segment, you should see `session_device_orientation = "portrait" OR "landscape"`
[EP-391: [Android] Phase 1 QA Fix Properties](https://kickstarter.atlassian.net/browse/EP-391)
> [Android] EP-391: Phase 1 QA Fix Properties

- app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
- app/src/test/java/com/kickstarter/libs/SegmentTest.kt
Added 3 new props to user properties: 
- `user_created_projects_count`
- `user_facebook_connected`
- `user_watched_projects_count`
Updated the `SegmentTest` suite
- Added all three properties to the` userProperties()` function in the `AnalyticEventsUtils` ext
- Updated the `assertUserProperties()` function in the `SegmentTest` class as well as the test case that checks we are returning the correct value if the fields from v1 that are populating these properties are null
- Open app and fire any event. For example, tap on a project card
- In segment, you should see the three new properties:
[EP-390: [Android] Create Properties Phase 1 QA Feedback Priority 2](https://kickstarter.atlassian.net/browse/EP-390)
> [Android] EP-390: Phase 1 QA Feedback Priority 2 properties

- app/src/main/java/com/kickstarter/libs/BaseFragment.java
- app/src/main/java/com/kickstarter/libs/FragmentViewModel.java
- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardsFragmentViewModelTest.kt
- `BaseFragmentViewModel` emits if the fragment is expanded or not
- `BaseFragment` has a new method to setUp the state.
- Fuctionallity to know when a Fragment has suffer a transformation via Animation outside the fragment itself
- For the PageViewed event on the RewardsCarousel you can see this working, every time we show in full screen the rewards carousel the page viewed event should be fired.
- Tests and code already added for the `pageViewed event` for rewards carousel @leighdouglas 
- PlaceHolder on `BackingFragmentViewModel` for the `Manage Pledge Screen PageViewed` event @sunday-okpoluaefe 
|  |  |
- Open the Rewards Carousel you'll see that the event is fired just when the carousel is expanded
[NT-1823](https://kickstarter.atlassian.net/browse/NT-1823)
> NT-1823: isExpanded functionality on BaseFragment

- app/src/main/res/layout/dashboard_referrer_breakdown_layout.xml
Add guideline constraints to show view
the backer feedback for creators on projects was not showing as figma 
https://user-images.githubusercontent.com/1075310/114101990-d5a15a00-98c6-11eb-881e-5e2d3299ff55.mp4
| --- | --- |
|  |  |
1. Log in the App, Production environment, you can use therealnativesquad@gmail.com credentials in 1Password
2. as creator, go to the Dashboard
3. Scroll to the bottom of the selected project
https://kickstarter.atlassian.net/browse/NT-1820
> NT-1820/Creator Dashboard Issues

- app/src/main/res/values/braze.xml
- added `braze.xml` resources file
- added default icon 
- added background color for the icon 
- Braze SDK will look into `braze.xml` for resources 
|  |  |
- Described on comments on this ticket how to QA this work [Braze-PushNotifications](https://kickstarter.atlassian.net/browse/NT-1830) just make sure the icon now is the `kickstarter` logo
[NT-1832](https://kickstarter.atlassian.net/browse/NT-1832)
> NT-1832: Default Icon for Braze Push Notification

- app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
- app/src/main/java/com/kickstarter/models/Project.java
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
Switch logic tied to `prelaunchActivated()` from the `User` payload to rely on `displayPrelaunch()` instead. 
Currently, native is using the field `prelaunch_activated` to determine the display logic of prelaunch deeplinks. We want to change this logic to check `display_prelaunch` instead. 
The backend will be updating `prelaunch_activated` to actually return the correct `project.prelaunch_activated` value. This is also keeping parity with web as they are using this field. Because of this, any instances using prelaunch_activated for display logic will need to be updated to use display_prelaunch instead.
Relevant backend PR: https://github.com/kickstarter/kickstarter/pull/21408
- Update the `User` struct to grab `displayPrelaunch` value available from the API
- Switch instances of …
> NT-1821: Switch prelaunch display logic to use display_prelaunch field from v1 API

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/libs/braze/BrazeClient.kt
- app/src/main/java/com/kickstarter/mock/factories/DiscoverEnvelopeFactory.java
- app/src/main/java/com/kickstarter/mock/services/MockApiClient.java
- app/src/main/java/com/kickstarter/services/apiresponses/DiscoverEnvelope.java
- app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.java
- app/src/test/java/com/kickstarter/libs/SegmentTest.kt
- app/src/test/java/com/kickstarter/viewmodels/SearchViewModelTest.java
Android: Page Viewed (search)
Datalake Event to Convert for Segment
When the user types a search term, the app currently makes a network call to fetch the results. When the results return from the API, call the Page Viewed event with the search term in the discover_search_term property with the correct total count in the discover_search_results_count
- Created method ``` trackSearchResultPageViewed ``` in ``` AnalyticEvents ```
```
/**
* Sends data associated with the search results page viewed to segment.
* @param discoveryParams: DiscoveryParams
* @param count: Int
* @param sort: DiscoveryParams.Sort
*/
fun trackSearchResultPageViewed(discoveryParams: DiscoveryParams, count: Int, sort: DiscoveryParams.Sort) {
val props = AnalyticEventsUtils.discoveryParamsProperties(discoveryParams).toMu …
```
> EP-424: Page Viewed (search)

- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
- app/src/main/java/com/kickstarter/libs/utils/extensions/CheckoutDataExt.kt
- app/src/test/java/com/kickstarter/libs/LakeTest.kt
- app/src/test/java/com/kickstarter/libs/SegmentTest.kt
Android QA: Checkout Amount Total Property
The total amount of my checkout was $602 AUD. Web correctly converted that to 459.51, but Android is sending 555.3922764062881. I don’t know how this is being calculated on Android, but it should be the total pledge amount at checkout, converted to USD from the project currency. 
Should also be a decimal, not a float.
- Changed 
``` fun CheckoutData.totalAmount(usdRate: Float) = this.totalAmount() * usdRate ```
to 
``` fun CheckoutData.totalAmount(usdRate: Float) = this.amount() * usdRate ```
This is because ``` this.amount() ``` is already ``` pledgeAmount + addOns + shippingAmount + bonus ```. 
- Rounded up to 2dp decimal 
```
put("amount", checkoutData.amount().round()) 
put("amount_total_usd", …
```
> EP-483: Checkout Amount Total Property

- app/src/main/java/com/kickstarter/libs/ExperimentsClientType.kt
- app/src/main/java/com/kickstarter/libs/OptimizelyExperimentsClient.kt
- app/src/main/java/com/kickstarter/mock/MockExperimentsClientType.kt
- app/src/test/java/com/kickstarter/libs/SegmentTest.kt
The format with which we were sending `session_variants_optimizely` was incorrect. We want to send an array of strings formatted with the name of the optimizely experiment and the experiment group the user is in:
```
"suggested_no_reward_amount[control]"
```
Segment integration/QA feedback
- Open kickstarter and make sure you are logged in
- Fire any event that include session properties
- Verify on segment that the raw json is formatted correctly (you have to be whitelisted in an optimizely experiment): 
[EP-462: Android QA 4/6 - Session Properties Fixes](https://kickstarter.atlassian.net/browse/EP-462)
> EP-462: Android QA 4/6 - Session Properties Fixes

- app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
- app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
- app/src/main/java/com/kickstarter/models/Project.java
Fix  `project_current_amount_pledged_usd` and `project_goal_usd` to match web 
Segment integration/QA feedback
add the `usdExchangeRate` the same one that backend use 
1. open project that the currency is not in usd"SOLIDTEKNICS 100% Australian Made Iron Cookware"
[https://kickstarter.atlassian.net/browse/EP-485]
> EP-485:Android QA: Project Properties Currency

- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/libs/SegmentTrackingClient.kt
- Segment initialization moved to SegmentTrackingClient.kt
- Isolate the initialization of the dependency in the Client we created for that purpose
- Now the lifecycle events we send to segment are also behind the feature flag.
- The initialization for segment has been moved to `SegmentTrackingClient` in that way we've completely isolated the dependency on it's client.
- `SegmentTrackingClient` has the method `isEnabled()` to check if the feature flag is active
- Check that if you have the feature flag off, no lifecycle event is sent to Segment.
[NT-1852](https://kickstarter.atlassian.net/browse/NT-1852)
> NT-1852: Segment initialization moved to SegmentTrackingClient

- app/src/main/java/com/kickstarter/libs/LakeTrackingClient.kt
- app/src/main/java/com/kickstarter/libs/SegmentTrackingClient.kt
- app/src/main/java/com/kickstarter/libs/TrackingClient.kt
- app/src/main/java/com/kickstarter/libs/TrackingClientType.kt
- app/src/test/java/com/kickstarter/KSRobolectrictTestCase.kt
- app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
- app/src/test/java/com/kickstarter/libs/SegmentTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ChangePasswordViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/CreatePasswordViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/SettingsViewModelTest.kt
- Removed from `TrackingClient.kt` internal variables `config` and `loggedInUser` those two properties have become class properties on `TrackingClientType.kt`
- `LakeTrackingClient.kt ` overrides  it's own `config` and `loggedInUser`
- `SegmentTrackingClient.kt ` overrides  it's own `config` and `loggedInUser`
- For `SegmentTrackingClient.kt` we update the current user only when some of the traits has change with method `updateUserAndCheckTraits`
- Avoid race condition for initializing Segment SDK, call initialize only when we have configuration available
- Added `isInitialized` state for Segment SDK
- Modified several tests
- No visible changes on this PR. It's all around behaviour.
- Make sure when you come from background `identify` it's not called
- Make sure if you change some of …
> NT-1867: eliminate unnecessary identify calls

- app/build.gradle
- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/KSApplication.java
- app/src/main/java/com/kickstarter/libs/LakeTrackingClient.kt
- app/src/main/java/com/kickstarter/libs/SegmentTrackingClient.kt
- app/src/main/java/com/kickstarter/libs/TrackingClientType.kt
- app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
- app/src/test/java/com/kickstarter/libs/SegmentTest.kt
- Segment SDK needs to be initialized on the `OnCreate` method on Application lifecycle AND on the mainThread. otherwise the client disappear on random occasions. 
- Static call to Segment methods via `Analytics.with(context)` instead of using the client.
- Basically the client disappear randomly, that happend when the initialization took place on another thread different from the main thread. 
- We make a networking call to fetch the feature flags (we change threads basically), so we need to be sure to initialize ONCE we have the configuration ready AND the initialization takes place on the main thread.
- `SegmentTrackingClient` now has it's own provider on the `AppModule` for injecting the wrapper client.
- New `initialize` method has been added on `TrackingClientType` that method is …
> Segment not sending events ghost

- app/build.gradle
- app/src/main/java/com/kickstarter/libs/SegmentTrackingClient.kt
- Update segment version + flush queue with 1 event on staging
- We are trying to solve some timestamp issues going on. See -> https://github.com/segmentio/analytics-android/issues/757 and it seems it might be solve on the latest Segment SDK version.
- Updated version from 4.9.0 to 4.9.4
- Added `.flushQueueSize(1)` when instanciating Segment client on testing builds.
- no user facing changes
- 
|  |  |
> [no-jira]: Update segment version + flush queue with 1 event on staging

- app/build.gradle
- build.gradle
- We need to remove all possible references to bintray and jcenter() repositories 
- see -> https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
- ⚠️  one last dependency still needs jcenter() as it has not been moved yet to mavencentral() or google() `implementation 'com.google.android:flexbox:1.1.0'`  see the issue open https://github.com/google/flexbox-layout/issues/566
- No use facing changes
|  |  |
- The app compiles 
[NT-1923](https://kickstarter.atlassian.net/browse/NT-1923)
> NT-1923: remove jcenter()

- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/libs/SegmentTrackingClient.kt
- app/src/main/java/com/kickstarter/libs/braze/BrazeClient.kt
- app/src/main/java/com/kickstarter/libs/braze/InAppCustomListener.kt
- app/src/main/java/com/kickstarter/libs/braze/InAppCustomListenerHandler.kt
- app/src/main/java/com/kickstarter/libs/utils/ConfigFeatureName.kt
- app/src/test/java/com/kickstarter/libs/BrazeClientTest.kt
- app/src/test/java/com/kickstarter/libs/InAppCustomListenerHandlerTest.kt
- Remove Feature Flag for Braze
- Config object removed as dependency on `BrazeClient`,  `InAppCustomListener`, `InAppCustomListenerHandler`
- Any check related with the Feature Flag now is always true or directly removed
- Updated/removed unit tests around feature flag being enabled or disabled
- Make sure Braze client is always initialized when loading the app, you can take a look in logcat a search for `AppBoy` logs
[NT-1853](https://kickstarter.atlassian.net/browse/NT-1853)
> NT-1853: Removed Feature Flag for Braze

- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
Add Cursor to each comment item
There is a cursor attached to every comment. This needed to implement pagination
- Set the cursor field with graphql node cursor
```
createCommentObject(edge?.node()?.fragments()?.comment()).toBuilder()
.cursor(edge?.cursor())
.build()
```
| --- | --- |
|  |  |
https://kickstarter.atlassian.net/browse/NT-1980
> NT-1980: Add Cursor to each comment item

- app/build.gradle
- app/src/main/graphql/replies.graphql
- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/models/Comment.java
- app/src/main/java/com/kickstarter/services/ApolloClientType.kt
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
- Create new method for the GraphQL networking client able to fetch all the replies to a concrete comment
- We will load the Thread screen with the list of replies to a concrete comment
- Added new `replies.graphql` file, note I'm reusing all the fragments previously created :) 
- `apolloClient` has a new method `getRepliesForComment` that executes previous mentioned query and retruns a `CommentEnvelope`
- On `ThreadViewModel` there is a subscription already working that fetches replies, for now it just displays on logcat the retrieved data
- On Logcat you can see the CommentEnvelope Structure 
- it matches the comments on the web
- You can also take a look on the networking profiler 
|  |  |
- Go to any comment with replies, and check logcat on your environment, you should see the …
> NT-953: Fetch a thread query

- app/src/main/java/com/kickstarter/mock/factories/CommentFactory.kt
- app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
- app/src/main/java/com/kickstarter/ui/adapters/CommentsAdapter.kt
- app/src/main/java/com/kickstarter/ui/data/CommentCardData.kt
- app/src/main/java/com/kickstarter/ui/viewholders/CommentCardViewHolder.kt
- app/src/main/java/com/kickstarter/ui/views/CommentCard.kt
- app/src/main/java/com/kickstarter/ui/views/CommentComposerView.kt
- app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
- app/src/main/res/layout/activity_comments_layout.xml
- app/src/main/res/values/attrs.xml
- app/src/test/java/com/kickstarter/ui/view/CommentCardTest.kt
- app/src/test/java/com/kickstarter/viewmodels/CommentsViewHolderViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
We want to disable the reply/comment card action buttons in different user states i.e. logged in or out, backing or not backing, etc.
I also renamed a few variables to be clearer and extracted some functionality into individual methods, for readability and all that good stuff 😄 
- The reply option should only show if the user is logged in and has backed the project, or if they are the project creator. 
- A user should not be able to reply to projects if they are not logged in, or if they are logged in but have not backed the project or they are not the creator. 
- Created a new `CommentCardData` model that holds the `comment`, the `project` the comment is from, and the state of the card (for future use when replying, errored, etc).
- We then transform the list of comments returned in the …
> NT-1977: UX – Not logged in / not backer for Comment Card

- app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
- app/src/main/java/com/kickstarter/ui/views/CommentComposerView.kt
- app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
- app/src/main/res/layout/activity_comments_layout.xml
- app/src/main/res/layout/comment_composer_view.xml
- app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
This change handles the different states of the comment composer in relation to the user state i.e. logged out, not backing, etc.
Also had to update the UI to make the separator disappear as it was still appearing when the composer was gone. 
There are three states -> `ENABLED, DISABLED, GONE`
- `GONE` -> The comment composer should be completely gone if the user is not logged in.
- `ENABLED` -> If the user is logged in and a backer, or is the creator, the comment composer is enabled.
- `DISABLED` -> If the user is logged in but not a backer, then the comment composer should be in the disabled state
Created an enum that holds these three states, and when the comment view model is initiated, it emits this state to the activity and the view responds accordingly. 
Logged in: Backing and not …
> NT-1910: UX – Not logged in / Not backer for Comment Composer

- app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt
- app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
- app/src/main/java/com/kickstarter/ui/viewholders/CommentCardViewHolder.kt
- app/src/main/java/com/kickstarter/ui/views/CommentCard.kt
- app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
- app/src/main/res/layout/comment_card.xml
- app/src/main/res/values/attrs.xml
- app/src/test/java/com/kickstarter/ui/view/CommentCardTest.kt
- app/src/test/java/com/kickstarter/viewmodels/CommentsViewHolderViewModelTest.kt
- New feature flag added that `hides View replies/Reply buttons`
- The Flag button has been removed
- Feature flag added to optimizely
- `CommentCard.kt` will be aware of the feature flag state via a new output from the viewmodel `isCommentEnableThreads`
- All the visibility updates will happend internally on `CommentCard`
- New optimizely Feature Flag
- Backer with feature flag off: reply and view replies buttons are gone
https://user-images.githubusercontent.com/4083656/120713432-bc57fc80-c476-11eb-8e24-6ceb533c805b.mp4
- Backer with feature flag on: reply and view replies buttons are visible and active
https://user-images.githubusercontent.com/4083656/120713769-36888100-c477-11eb-8978-bee459714c44.mp4
- No Backer with feature flag off: view replies buttons is gone …
> NT-1984: Feature flags for threads

- app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/CommentsViewHolderViewModelTest.kt
Add 1 second delay before transitioning from Posting… back to any state
apply the delay to any transition
adding delay before retrying so Posting state can be visiable 
https://user-images.githubusercontent.com/1075310/121569293-eda96d00-ca20-11eb-943d-2857d4224149.mp4
- Add new comments, pull to refresh
- try to post without connection, you'll see the error states, 
- Retry makes sure to see "posting..." state 
- then get back connectivity and retry
https://kickstarter.atlassian.net/browse/NT-2029
> NT-2029:UX – Add delay to "Posting..." error state

- app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
- app/src/main/java/com/kickstarter/ui/adapters/CommentsAdapter.kt
- app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
- app/src/main/res/layout/activity_comments_layout.xml
- app/src/main/res/layout/item_error_pagination.xml
- app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
- Subtask to add the new cell to handle the pagination error state
- ⚠️  the actual UI for the cell will come on next PR's this is just displaying two types of cell within the same RecyclerView and tidying up together the pagination errors logic.
- Error when pagination designs required a a new cell within the actual recyclerview
https://user-images.githubusercontent.com/4083656/121607613-32bfa600-ca05-11eb-8ace-7e1ba5b75586.mp4
|  |  |
- Load comments for a project with many comments, turn off you connection, scroll to the bottom and try to paginate, you'll see the placeholder error cell appearing.
- recover connectivity, try to scroll again, the cell will disappear and you will see more comments added to the list.
[NT-2037](https://kickstarter.atlassian.net/browse/NT-2037)
> NT-2037: Pagination Error Cell displayed at the same time as the comments cells 

- app/src/main/java/com/kickstarter/libs/SegmentTrackingClient.kt
Call the identify call when the Segment SDK is initialized and ready to receive an identify call. We noticed that when opening the app when the user is logged in, the app identifies the user before the SDK is initialized. This prevents the user from being identified. 
Add an additional identify call when the SDK initialization is completed. The trade off of the additional identify call is worth it for ensuring the user is identified. 
[NT-2045](https://kickstarter.atlassian.net/browse/NT-2045)
> [NT-2045] Identify when the Segment SDK is Initialized

- app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
- app/src/main/java/com/kickstarter/ui/adapters/CommentsAdapter.kt
- app/src/main/java/com/kickstarter/ui/viewholders/PaginationErrorViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/PaginationErrorViewHolderViewModel.kt
- app/src/main/res/layout/item_error_pagination.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/kickstarter/viewmodels/PaginationErrorViewHolderViewModelTest.kt
- Added pagination Error cell ViewHolder + ViewModel + ViewHolderViewModelTest
- Retry errorred page callback
https://user-images.githubusercontent.com/4083656/121965519-fdc39400-cd21-11eb-94ce-f148689678a6.mp4
|  |  |
- Load a project with several comments -> Load coments screen - Lose conectivity -> scroll to the bottom -> once the loading indicator has finished you'll see a new cell on the bottom with the error displayed -> touch the cell or pull the bottom of the list -> recover conectivity ->  touch the cell or pull the bottom of the list -> you will see the next page loaded on the list and the error cell disappear 
[NT-2019](https://kickstarter.atlassian.net/browse/NT-2019)
> NT-2038: Cell UI for pagination error & NT-2039: Reload the errored page

- app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
- app/src/main/java/com/kickstarter/ui/adapters/CommentsAdapter.kt
- app/src/main/java/com/kickstarter/ui/viewholders/CommentCardViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
- app/src/main/res/layout/comment_card.xml
- Bug that duplicated comments
- Bug when trying to post to a project without any previous comment
https://user-images.githubusercontent.com/4083656/122138650-fd97c700-cdfb-11eb-8671-34e1e77f1adc.mp4
|  |  |
- Bug 1 when going background after posting
- Bug 2
Look for a project without comments, make the first comment, it should not crash, and it should post the comments successfully.
[NT-2055](https://kickstarter.atlassian.net/browse/NT-2055)
> NT-2055: Duplicated comments

- app/src/main/res/layout/comment_card.xml
- app/src/main/res/values/styles.xml
We were displaying the wrong copy for the "Reply" button on the comment card. This updates to use the correct string.
English and Spanish translations for reply, as examples:
Go to the comments page on a project you have backed and check to make sure the Reply button is spelled correctly. Change device language to another language (Spanish or german for example) and recheck the comments page to make sure the correct translation is being used.
> Fix "Reply" copy

- app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
Fix issue as on master Pagination change scrolling position and crash at the last page
the compare item wasn't working as it was null for project value 
Before issue
https://user-images.githubusercontent.com/1075310/123808314-ecb57e00-d8f0-11eb-9ac1-8f234d2885cb.mp4
the Fix
https://user-images.githubusercontent.com/1075310/123807680-5d0fcf80-d8f0-11eb-9cdd-fc75a668e52d.mp4
Open any project with comments and has more than one page and scroll  and check pagination  
https://kickstarter.atlassian.net/browse/NT-2069
> NT-2069:Refactor Comment Pagination code 

- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
Firebase shows an increased number of crashes on the `OnSubscribeMap.java`. Looking into the logs, the issues is due to an error for a null name. All of the crashes are on the comments activity. 
`com.kickstarter.services.KSApolloClientKt.createCommentObject (KSApolloClient.kt:816)`
At this line, we are building a user object from the comment fragment, however we are not checking if the author is null. If it is the name will be null and would crash the app on the comments activity
The fix is to simply check if the name of the author is null before building the user object.
- In the code, change line 810 in `KSApolloClient.kt` to `.name(null)` 
- This will force it to crash since a user's name should never be null
- Next change line 810 to `name(null) ?: "")`
- This should prevent the …
> [NT-2079] Fix Crash on CommentsActivity

- app/build.gradle
- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/libs/CurrentConfig.java
- app/src/main/java/com/kickstarter/libs/PushNotifications.java
- app/src/main/java/com/kickstarter/models/chrome/ChromeTabsHelper.kt
- app/src/main/java/com/kickstarter/ui/activities/VideoActivity.kt
Update exoplayer, mockito, and timber dependencies to latest versions. 
- Updated the gradle file
- Updated `VideoActivity` to use latest changes in exoplayer and remove deprecated classes
- Updated instances of timber that were being used incorrectly according to the linter
- Test that videos are working properly on the project screen
- Running the application should show timber logs in logcat
- CI should catch any errors that may result from updating mockito
[NT-2071: Update dependencies with major updates](https://kickstarter.atlassian.net/browse/NT-2071)
> NT-2071: Update exoplayer, mockito, and timber dependencies to latest versions

- app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
Navigation – Back button should slide view out
- Changed transision on startActivity
- Navigate to any backed project
- Select comments
- Navigate to replies
- Navigate back to comments, afterwards to project. You should see the transitions
| --- | --- |
|  |  |
https://kickstarter.atlassian.net/browse/NT-2028
> NT-2028: Navigation – Back button should slide view out

- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/ui/adapters/RepliesAdapter.kt
- app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
Crash when we create a new comment and Press the reply button
when we create a new comment and press reply we got crash as the comment wasn't posted  and doesn't have id
The replay button is visible after a comment posted successfully 
https://user-images.githubusercontent.com/1075310/124662572-544b6a80-dea9-11eb-884a-e8a610fa4c33.mp4
https://user-images.githubusercontent.com/1075310/124662856-a2f90480-dea9-11eb-8ba1-7984c27029d4.mp4
1- Post a new comment  and click reply
2- Post a new comment  in offline mode and  then retry after posting click reply
3- add the first comment 
https://kickstarter.atlassian.net/browse/NT-2099
> NT-2099:Crash when we create new comment and Press reply button

- app/src/main/java/com/kickstarter/ApplicationModule.java
- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
Test a 3D Secure card with Strong Customer Authentication
- Updated to the latest version of Stripe SDK
- Updated deprecated method `authenticateSetup` over `handleNextActionForSetupIntent`
- Added initialization for PaymentConfiguration at the same level we initialize stripe SDK
https://user-images.githubusercontent.com/4083656/124675147-f3a03b80-de70-11eb-88a0-ce726a1dfd5b.mp4
|  |  |
- On the video I pledged with the card with number `4000002500003155`
- Pledge to a project using one of these test cards -> [Regulatory Cards](https://stripe.com/docs/testing#regulatory-cards)
[NT-2067](https://kickstarter.atlassian.net/browse/NT-2067)
> NT-2067: 3DS card crash with SCA flow

- app/src/main/java/com/kickstarter/ui/fragments/NewCardFragment.kt
- The postal code in the stripe `CardInputWidget` was showing the Postal code, and our own input for postal code was shown as well at the same time.
- 
- Disabled postal code field on the `CardInputWidget` configuration
| Before 🐛 |
| After 🦋 |
https://user-images.githubusercontent.com/4083656/125126764-6cd9a180-e0b0-11eb-8c95-3e904fde3c18.mp4
|  |  |
- Try to add a new payment method, you should see only one Postal code field 
- be able to successfully pledge to a project.
[NT-2091](https://kickstarter.atlassian.net/browse/NT-2091)
> NT-2091: Remove duplicated Postal code field

- app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
- app/src/main/java/com/kickstarter/ui/views/CommentComposerView.kt
show the confirmation dialog when the user tries to leave the screen with something written in the comment composer.
So we show a dialog in case there is a text in comment composer in comment or replies activity
https://user-images.githubusercontent.com/1075310/126643807-38b9ec09-f285-45d2-9a2b-ef683725dfe7.mp4
1. Open Comment and thread Activity
2. Write a comment in the composer 
3. Press back 
https://kickstarter.atlassian.net/browse/NT-2001
> NT-2001 :UX – Show pending dialog

- app/src/main/graphql/fragments.graphql
- app/src/main/java/com/kickstarter/libs/utils/extensions/CommentListExt.kt
- app/src/main/java/com/kickstarter/mock/factories/CommentCardDataFactory.kt
- app/src/main/java/com/kickstarter/mock/factories/CommentFactory.kt
- app/src/main/java/com/kickstarter/models/Comment.java
- app/src/main/java/com/kickstarter/models/extensions/CommentExt.kt
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
- app/src/main/java/com/kickstarter/ui/adapters/RootCommentAdapter.kt
- app/src/main/java/com/kickstarter/ui/viewholders/CommentCardViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/RootCommentViewHolder.kt
- app/src/main/java/com/kickstarter/ui/views/CommentCard.kt
- app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/RootCommentViewHolderViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
- app/src/main/res/layout/comment_card.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/kickstarter/ui/view/CommentCardTest.kt
- app/src/test/java/com/kickstarter/viewmodels/CommentsViewHolderViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/RootCommentViewHolderViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ThreadViewModelTest.kt
Comments from users who have cancelled their pledge should be hidden at first.
To mark the canceled pledge users comments
- Add flagged to cancled pledge 
- ![image](https://user-images.githubusercontent.com/1075310/126830975-1023b5b1-add0-460f-84dc-1f526e340480.png)
- Add new status to Comment card
- ![image](https://user-images.githubusercontent.com/1075310/126831046-c16882ea-a628-4660-ae2c-fa1a4b03affa.png)
- Handle new UI for Show canceled comment 
- Handle on show comment in comment and thread activity 
- Handle Root comment and pass status to thread Activity 
https://user-images.githubusercontent.com/1075310/126831207-1d562fcd-e077-40ee-9d4e-9250eb56e727.mp4
Check Project "Keep Moms in the Game "
https://kickstarter.atlassian.net/browse/NT-1965
> NT-1965:UX – Show not-a-backer-anymore comments

- app/src/main/java/com/kickstarter/libs/loadmore/ApolloPaginate.kt
- app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
- Fixed duplicated comments when errored comments present on the list
- Fixed empty state showing when pull to refresh
https://user-images.githubusercontent.com/4083656/129404038-7243b848-b10e-482b-829e-b373dc3ba636.mp4
|  |  |
Steps to reproduce: 
1- Go to a project comments
2 - Pull to refresh
**BEFORE**
Notice how the empty screen shows up while loading
**NOW**
Empty state do not show while loading
[NT-2180](https://kickstarter.atlassian.net/browse/NT-2180)
> NT-2180: Empty state showing when pull to refresh

- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
- Users were unable to update payment when a reward had addons
- Also found that updating the payment was crashing on pledges with no rewards
- Added functionality that fixes both of these use cases 
- The "Confirm" button being enabled is tied to a few different streams, one of which is `totalIsValid`. Up the line, this stream is tied to the shippingRule. For some reason, when a project had addons, we were not emitting a shipping rule, and therefore we were not emitting a total. Down the line, this meant that totalIsValid was never evaluated, and therefore the button never enabled. 
- This functionality is specific to backings with addons, but it seems that this use case is for rewards before the user backs the project. 
- This functionality was also causing a crash when updating the …
> Nt-2068: Fix update payment fails on pledges with addons, and no rewards

- app/src/main/graphql/replies.graphql
- app/src/main/java/com/kickstarter/libs/utils/UrlUtils.kt
- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/services/ApolloClientType.kt
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/ui/IntentKey.java
- app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/DeepLinkActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/UpdateActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/UpdateViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/UpdateViewModelTest.java
Add deep-link to Thread activity comments
So users can access the project thread activity from a shared link
Deep Link to thread activity by sending a commendable_id
Check type of project screen Comment/Update
Set intent with commendable_id to open update activity Or CommentActivity
LoadComment from Graph-ql
Fire to. open the Thread activity from Comment activity 
https://user-images.githubusercontent.com/1075310/132056437-1e840ac7-6a20-4e9f-b7e6-5a22b7bbb9d8.mp4
https://user-images.githubusercontent.com/1075310/132056553-92d0532b-9d15-485b-82d1-64d51a59b1d7.mp4
Run branch on the device 
open Link [ https://www.kickstarter.com/projects/fjorden/fjorden-iphone-photography-reinvented/posts/3254626/comments?comment=Q29tbWVudC0zMzU2MTY4Ng%3D%3D]From device 
and use the previous command with …
> NTV-10: Add deep link to comment thread

- app/src/main/java/com/kickstarter/services/DiscoveryParams.java
- app/src/test/java/com/kickstarter/services/DiscoveryParamsTest.java
We can now deeplink into the discovery activity with a sort parameter.
Updated the DiscoveryParams fromUri() method to check for the collections parameter being set to true or false. 
It seems that in the past we had urls where the query param would be true instead of 1, so  I updated the existing functionality to account for both instances. 
(I'm not following anyone so the social deeplink comes up blank 😅 )
https://user-images.githubusercontent.com/19390326/132756051-de59ceca-ef6f-476a-af45-b2d1502f263e.mp4
Thoroughly test all discovery deeplinks
[NTV-41: Handle collections](https://kickstarter.atlassian.net/browse/NTV-24)
> NTV-41: Add deeplink for discovery with collections

- app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
After introducing the new deeplinking logic to the discovery screen, we ran into a crash that was happening when choosing a category from the navigation drawer, and then selecting a sort different sort. This crash was happening if you followed these steps right after app bootstrap. 
**TLDR; We updated the discovery params sent with navigation drawer clicks to take the current sort if the sort is null. This sometimes null sort was causing a crash when trying to be sent to our analytics client. Below is an in-depth and possibly unnecessary explanation, feel free to skip 😅** 
A discovery params object holds all of the configurations for the discovery screen (which sort the user is on, category, collections, etc). Everytime the user interacts with the screen, we send a new discovery params …
> NTV-183: Fix discovery crash when changing sort after choosing category

- app/src/main/graphql/fragments.graphql
- app/src/main/graphql/schema.json
- app/src/main/java/com/kickstarter/libs/utils/RewardUtils.kt
- app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectExt.kt
- app/src/main/java/com/kickstarter/mock/factories/ConfigFactory.java
- app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
- app/src/main/java/com/kickstarter/mock/factories/UserFactory.java
- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/models/User.java
- app/src/main/java/com/kickstarter/services/ApolloClientType.kt
- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
- app/src/main/java/com/kickstarter/ui/intentmappers/ProjectIntentMapper.java
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/test/java/com/kickstarter/libs/utils/extensions/ProjectExtTest.kt
- app/src/test/java/com/kickstarter/ui/intents/ProjectIntentMapperTest.java
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Merge feature branch for migration to Project Page from V1 to GraphQL
- All PR's involving this feature branch have already been reviewed + QA
> NTV-181: Migrate Project Page to GraphQL 

- app/src/main/java/com/kickstarter/libs/utils/RewardUtils.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.java
- app/src/test/java/com/kickstarter/libs/utils/RewardUtilsTest.kt
Reports from CS telling the bonus support is multiplied by 10 when trying to update pledge or fixing pledge.
We haven't been able to reproduce the issue but fixed on the way for that investigation other issues.
- - Update pledge with addOns and shipping 
- - Deleted old code related to an experiment with the minimum pledge
- - Exchenged `flatmap` over `switchmap` on Thanks Page.
- BOFORE: Pledge to a project with addons with shipping -> update pledge not working
- NOW: Pledge to a project with addons with shipping -> update pledge 
https://user-images.githubusercontent.com/4083656/134253919-f2821c2e-a86d-461b-acc4-2e4aa2b0b7b7.mp4
- Minimum pledge by country keeps working after refactor: Japan min pledge …
> NTV-189: Bug investigation

- app/src/main/java/com/kickstarter/libs/models/OptimizelyExperiment.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
- Remove any code related to the "suggested_no_reward_amount" experiment
- No user facing changes, the experiment has been off some time now.
|  |  |
- Pledge to a japaneese project with the reward no reward- the amount should be ¥100
- Pledge to a Hong Kong based project with reward no reward- the amount should be $10
- Pledge to a US based project with reward no reward- the amount should be $1
- Pledge to a EUR based project with reward no reward- the amount should be €1
> [no-jira]: Remove "suggested_no_reward_amount" experiment

- app/src/main/res/layout/activity_project_page.xml
- you could scroll the toolbar away, now is a fix toolbar
- Before
https://user-images.githubusercontent.com/4083656/135364133-18ad3598-b9df-4e63-afb6-1110ebd20702.mp4
- After
https://user-images.githubusercontent.com/4083656/135364165-53024be8-361f-4c1a-aaf5-689fdbfe04e9.mp4
|  |  |
- Try to scroll the toolbar, now you cannot do it as in the first video
[NTV-205](https://kickstarter.atlassian.net/browse/NTV-205)
> NTV-205: Fix scrolling toolbar

- .circleci/config.yml
- app/src/main/java/com/kickstarter/ui/intentmappers/ProjectIntentMapper.java
- app/src/test/java/com/kickstarter/ui/intents/ProjectIntentMapperTest.java
- app/src/test/java/com/kickstarter/viewmodels/ProjectPageViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
- Reduce number of emissions for the initial project, to emit ONLY after the network call is successful.
- Fixed snapshot tests 
- Modified Unit test the reflect the reduced number of emissions
- The tab/fragment for EnvironmentalCommitment on the navigation selector needs to be hidden when empty, we were getting false negative emissions
- Snapshot tests were having issues
|  |  |
- Load the project page as usual
- All test passing again
[NTV-238](https://kickstarter.atlassian.net/browse/NTV-238)
> NTV-238: projectData emitted several times with different values on "EnvironmentalCommitment"

- app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
- Bring back the check around the current user being a backer
- we recently added the field `canComment` to the project, it works perfectly for comments on a project. We did not had in mind though the comments on updates. 
https://user-images.githubusercontent.com/4083656/140171554-a138ba0b-5871-430a-9299-02330d13b4d6.mp4
| --- | --- |
|  |  |
- Try to comment as a backer into a update from the project page
- Try to comment as a backer into a update from the activities page
- Check that you cannot comment on any update or project in which you are not backer
[NTV-277](https://kickstarter.atlassian.net/browse/NTV-277)
> NTV-277: Backer cannot comment on updates

- app/src/main/java/com/kickstarter/libs/htmlparser/HTMLModels.kt
- app/src/main/java/com/kickstarter/libs/htmlparser/HTMLParser.kt
- app/src/main/java/com/kickstarter/ui/adapters/projectcampaign/ViewElementAdapter.kt
- app/src/test/java/com/kickstarter/libs/htmlparser/HTMLParserTest.kt
Detect iframes for Youtube videos or audio media
Add to Html parser Youtube videos or audio media
Detect the div that has external sources `iframe`
Added unit testing for html 
https://kickstarter.atlassian.net/browse/NTV-269
> NTV-269 :Parser – Handle external sources

- app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
- A collaborator can comment on updates
- Project was being fetch from V1 instead of graph, reason why the field `canComment` was not populated for updates
- Exchange the call to project from V1 to the GraphQL one
https://user-images.githubusercontent.com/4083656/140186073-a534861a-d12a-49a0-8e21-f7fb77e67757.mp4
|  |  |
- Try to comment as a backer into an update from the project page
- Try to comment as a backer into an update from the activities page
- Try to comment as Collaborator into an update from the project page 
- Try to comment as Collaborator into a project from the project page
- Check that you cannot comment on any update or project in which you are not backer
> NTV-277: Collaborator & Baker can comment on project updates and project

- app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
- app/src/main/res/layout/project_creator_dashboard_header.xml
- Remove rectangle visible previous to the project finish loading.
- The rectangle is the button from the Creator Dashboard piece of UI, only should be visible when the creator of the project is loading the project. 
| 
| 
|
|  |  |
- Load a project, you'll see in the time before the data is collected and rendered the rectangle has disappeared.
[NTV-278](https://kickstarter.atlassian.net/browse/NTV-278)
> NTV-278: UI pre-load polish

- app/build.gradle
Upgrade PerimeterX SDK
Upgrade PerimeterX SDK from Android SDK/1.13.1 to 1.16.2.
PerimeterX keeps working as usual, you can look for `PerimeterXClient` on logcat
https://kickstarter.atlassian.net/browse/NTV-286
> NTV-286  Upgrade PerimeterX SDK to latest version

- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Remove old awareness component from checkout page on variant
Our experiment was slightly flawed from the very start, as we forgot to remove the old component from the checkout flow.
Run control side of the experiment and confirm the component is present
Run variant side of the experiment and confirm the component is gone
https://user-images.githubusercontent.com/1075310/141837821-304c44b9-03ba-4d52-897a-cbabe6ef71a9.mp4
Add your user ID to the whitelist here: Native Risk Messaging Whitelist
Test both the control flow and the variant_1 flow by changing your group on the whitelist. control should not show dialog, variant_1 should show dialog
https://kickstarter.atlassian.net/browse/NTV-289
> NTV-289 :Remove old awareness component for experiment

- app/src/test/java/com/kickstarter/libs/utils/extensions/ProjectExtTest.kt
- For some tests two DateTime Objects were created, making the test flaky, failing randomly
> no-jira: flaky tests around datetime

- app/src/main/java/com/kickstarter/libs/htmlparser/ElementExt.kt
- app/src/main/java/com/kickstarter/libs/htmlparser/HTMLModels.kt
- app/src/main/java/com/kickstarter/libs/htmlparser/HTMLParser.kt
- app/src/test/java/com/kickstarter/libs/htmlparser/HTMLParserTest.kt
modify the parser to return a VideoViewElement(url:String) instead of VideoViewElement(list:ArrayList)
we use the high URL else use the first URL 
Check parser and test class
https://kickstarter.atlassian.net/browse/NTV-271
> NTV-271:Parser – Fix video element

- app/src/test/java/com/kickstarter/libs/utils/extensions/ProjectExtTest.kt
- The project extension method `deadlineCountdownValue()` depending on when was executed will fail the test for the deadline countdown.
- added some extra milliseconds to the tests to allow processing time
- execute several times the test `com.kickstarter.libs.utils.extensions.ProjectExtTest#testDeadlineCountdownValue_testAllCases_shouldReturnCorrectValueOfTime`, should no longer fail some times
- 
|  |  |
> no-jira: flaky tests related to DateTime.now

- app/src/test/java/com/kickstarter/libs/utils/extensions/ProjectExtTest.kt
The test `testDeadlineCountdown_shouldReturnCorrectString` failed from time to time 
- Added a few milliseconds to allow processing time 
|  |  |
- Execute several times the test `testDeadlineCountdown_shouldReturnCorrectString` should never fail
> no-jira: one more flacky test related to DateTime.now()

- app/src/main/res/layout/view_element_image_from_html.xml
Gray line was appearing above images rendered from the html parser. This fix removes that line. 
Added an attribute to the image view
Before and After
Visit any project with images and there shouldn't be a gray line.
[NTV-301: Remove gray line above images](https://kickstarter.atlassian.net/browse/NTV-301)
> NTV-301: Remove gray line above images

- app/src/main/java/com/kickstarter/ui/adapters/projectcampaign/ViewElementAdapter.kt
- app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectCampaignFragment.kt
- app/src/main/java/com/kickstarter/ui/viewholders/projectcampaign/ExternalViewViewHolder.kt
- app/src/main/java/com/kickstarter/ui/viewholders/projectcampaign/VideoElementViewHolder.kt
- app/src/main/java/com/kickstarter/ui/views/WebChromeVideoFullScreenClient.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectCampaignViewModel.kt
- app/src/main/res/layout/fragment_project_campaign.xml
when exiting fullscreen we go back to the top of the campaign tab, we can prevent this and keep the previous position
Add a delegate to fire callback when the fullscreen closed and smooth scroll to the video position 
https://user-images.githubusercontent.com/1075310/145255706-42b95cbe-518d-4ebd-a522-8ea5901a6ffa.mp4
open Projects with videos or youtube and check fullscreen 
"HipLok" and "Organicar"
(https://kickstarter.atlassian.net/browse/NTV-291)
> NTV-291: Add Youtube fullscreen support

- app/build.gradle
- app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
- build.gradle
- Updated dependencies and gradle plugin
- ℹ️ Found the depency causing jacoco to drop coverange to 0%, the Firebase performance monitor, further investigation will occur on that end but for now do not update the firebase performance plugin just yet
- Those dependencies introducing braking changes have their own Jira task assigned.
|  |  |
- Everything keeps working as usual. You can try to pledge a project, review some old backings ... 
[NTV-318](https://kickstarter.atlassian.net/browse/NTV-318)
> NTV-318: Update dependencies

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
- Block the project page rotation for the project screen.
- Only screens allowed to go landscape now with the project are videos on full screen.
|  |  |
- Try to play a video from a campaign in the video player on landscape, make sure when you close the full screen video, the advance playing the video is correct-
- Try the same use case for the youtube iframes.
> [no-jira]: Block Project page rotation to portrait

- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
- Could not fix a pledge, when the pledge contained a reward + addOns and they were shippable.
| --- | --- |
|  |  |
[NTV-359](https://kickstarter.atlassian.net/browse/NTV-359)
> NTV-359: Fix pledge with Reward+AddOns that are shippable

- app/src/main/java/com/kickstarter/libs/utils/extensions/DiscoveryParamsExt.kt
- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
- app/src/test/java/com/kickstarter/libs/utils/extensions/DiscoveryParamsExtKtTest.kt
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
- Hide from the drawer menu the options for `Backed by people you follow` until further notice.
- Exchanged V1 call to fetch projects over GraphQL
- GraphQL migration.
- Reduce the network bandwidth the app consumes.
- On this video the projects are loaded calling GraphQL
https://user-images.githubusercontent.com/4083656/151246645-5520fcbd-18e4-4a81-a2b8-5e9dbad089f6.mp4
- Drawer menu option deleted for `Backer by people you follow`
| --- | --- |
- In this screenshot you can see the difference in between V1 vs GraphQL when fetching all project with sort `Magic`, in terms of size and latency
|  |  |
- launch the app without being logged, navigate a bit over the sorting tabs, and the drawer options.
- log in, navigate over every option on the drawer, and every sorting …
> NTV-363: Hide collection option Social

- app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt
- app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
- app/src/main/java/com/kickstarter/ui/adapters/ProjectPagerAdapter.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
- app/src/main/res/layout/activity_project_page.xml
- app/src/test/java/com/kickstarter/viewmodels/ProjectPageViewModelTest.kt
- Added feature flag to show/hide the campaign tab.
- Small refactor, in how we show/hide tabs, group together when to update tabs to reduce the number of times the pager needs to be configured.
- Feature Flag Enable, on the video you can see a project without environmental commitments, and a project with environmental commitments: 
https://user-images.githubusercontent.com/4083656/152074346-8f6b0577-d2f0-4d69-9569-0aa46b2d26d0.mp4
- Feature Flag Disabled, on the video you can see a project without environmental commitments, and a project with environmental commitments:
https://user-images.githubusercontent.com/4083656/152074051-a99eae48-e5f0-45e2-b3cd-69dd5dd79110.mp4
|  |  |
- Check when there is "Environmental Commitments" the tab shows
- Use optimizely dashboard to activate/deactivate …
> NTV-296: Feature flag fro Story Tab

- app/src/main/graphql/fragments.graphql
- app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
- The percentage was missing after the migration to GraphQL
- `percentage` field was not queried
| Before 🐛 | A
fter 🦋 |
|  |  |
- Check the percentage and progress bar are loading correctly
> [no-jira]: percentage funded

- app/build.gradle
- app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
- app/src/main/java/com/kickstarter/ui/extensions/ImageViewExt.kt
- app/src/main/java/com/kickstarter/ui/views/ImageWithCaptionView.kt
- app/src/main/res/layout/view_image_with_caption.xml
- build.gradle
- Zoomimg images on campaign tab
- Added new dependency
- Added placeholder below the zooming image, as it was causing jumps up and down when resizing the image out of the layout.
https://user-images.githubusercontent.com/4083656/153312882-2de2be8e-acfd-4618-942b-40b645ae4f2c.mp4
|  |  |
- Go into any campaign and zoom some of the images.
[NTV-360](https://kickstarter.atlassian.net/browse/NTV-360)
> NTV-360: Zoom on campaign images

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kickstarter/libs/utils/UrlUtils.kt
- app/src/main/java/com/kickstarter/libs/utils/extensions/UriExt.kt
- app/src/main/java/com/kickstarter/ui/IntentKey.java
- app/src/main/java/com/kickstarter/ui/activities/DeepLinkActivity.kt
- app/src/main/java/com/kickstarter/ui/intentmappers/ProjectIntentMapper.kt
- app/src/main/java/com/kickstarter/viewmodels/DeepLinkViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
- app/src/test/java/com/kickstarter/services/UriExtTest.kt
- app/src/test/java/com/kickstarter/ui/intents/ProjectIntentMapperTest.kt
- app/src/test/java/com/kickstarter/viewmodels/DeepLinkViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectPageViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
enable saving a project through Braze interactions
We can save a project from a Braze surface
1- handle URL deep linking in `ProjectViewModel` and `ProjectPageViewModel` in android manifest  
2-handle URL deep linking from deeplinking activity to `ProjectViewModel` and `ProjectPageViewModel` 
https://user-images.githubusercontent.com/1075310/153472839-965aa8ba-2405-4964-bfd1-225640919320.mp4
Create a dummy in-app message on Braze and double-check if the project is added to saved projects user should be login
I tested using 
`adb shell am start -a android.intent.action.VIEW     -c android.intent.category.BROWSABLE     -d "ksr://staging.kickstarter.com/projects/fjorden/fjorden-iphone-photography-reinvented?save=false"`
https://kickstarter.atlassian.net/browse/NTV-350
> NTV-350 :Add Save Project deep link

- app/src/main/java/com/kickstarter/ui/viewholders/projectcampaign/ImageElementViewHolder.kt
- app/src/main/java/com/kickstarter/ui/views/ImageWithCaptionView.kt
- You could see captions on images where there were really not caption on the original HTMl, or even see them appear after scrolling up and down
- When the cell was recycled with a new Image element, the caption UI piece was not updated therefore showing caption data if the previous loaded image element had it.
- Clear the caption text
* Before Video: You can see wild captions appear on images that should not have them
https://user-images.githubusercontent.com/4083656/153964256-f050f45b-8174-44d8-85a2-357f53772c19.mp4
* After Video: No wild captions anymore
https://user-images.githubusercontent.com/4083656/153964280-7b5358be-0630-48a2-8f4d-ac249fe93b78.mp4
|  |  |
- Load [this project](https://www.kickstarter.com/projects/tanyassmith/make-100-intentscents) and pay close attention to the …
> NTV-395: UI – Out of place image captions

- app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectOverviewViewModel.kt
- app/src/main/res/layout/fragment_project_overview.xml
- app/src/test/java/com/kickstarter/viewmodels/ProjectOverviewViewModelTest.kt
- If campaign tab is visible, hide the access to the old campaign webview activity
|  |  |
- Check with the FF on, you cannot access the old campaign webview activity
- Check with the FF off, you can access the old campaign webview activity
- 
[NTV-412](https://kickstarter.atlassian.net/browse/NTV-412)
> NTV-412: Hide old campaign links

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
- Removed allow backup from manifest
- Avoid using Transformers.neverError() operator
- Exchange flatmap over switchmap
- Added unit testing around failed calls to `fetchActivities` to make sure the networking request occurs only once
- Take a look into [this datadog query](https://app.datadoghq.com/logs?cols=host%2Cservice%2C%40network.client.ip&event&from_ts=1645033326959&index=&live=false&messageDisplay=inline&query=%40http.url_details.path%3A%5C%2Fv1%5C%2Factivities+status%3Awarn+source%3Afastly&stream_sort=desc&to_ts=1645638126959&viz=stream), you'll see way too many calls from the same IP, with milliseconds of difference. 
|  |  |
- Not a simple way to reproduce it, as you need to get 401, 429 errors when calling `fetchActivities`, but test all keeps working as usual on the …
> NTV-414: /v1/activities was called from the app several times

- app/src/main/java/com/kickstarter/ui/adapters/projectcampaign/ViewElementAdapter.kt
- app/src/main/java/com/kickstarter/ui/extensions/ImageViewExt.kt
- app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectCampaignFragment.kt
- app/src/main/java/com/kickstarter/ui/views/ImageWithCaptionView.kt
- app/src/main/res/layout/view_image_with_caption.xml
- Sometimes you could see image placeholder on top of the images available to pinch and zoom
- Campaign tab name replicated on the rest of the tabs
- The images able to pinch and zoom had the same image below it to keep the structure of the content when doing the pinch  and zoom, the placeholder was loaded with the same drawable as the top image exchanged `setImageBitmap(target.drawable.toBitmap())` over `.setImageDrawable(target.drawable)` in order to avoid the `.toBitmap` transformation
- When a cell from the recyclerview is recycled clean the previous image 
- Load many campaigns, you should not see the placeholder image on top anymore. 
- Make sure you don't see the repeated Campaign name on the tabs
[NTV-423](https://kickstarter.atlassian.net/browse/NTV-423)
> NTV-423: bug fixing on Campaign tabg

- app/src/main/java/com/kickstarter/mock/factories/CheckoutBackingFactory.kt
- app/src/main/java/com/kickstarter/mock/factories/CheckoutFactory.kt
- app/src/main/java/com/kickstarter/models/Checkout.kt
- app/src/main/java/com/kickstarter/models/SurveyResponse.kt
- app/src/test/java/com/kickstarter/models/CheckoutTest.kt
- Migrated to kotlin
- Adopt @Parcelize 
- Remove all references to the AutoParcel library in Models, eventually, we will be able to remove that dependency.
https://user-images.githubusercontent.com/1075310/160469127-30603321-b6cf-4979-8b3d-ca570229f089.mp4
test backing project 
https://kickstarter.atlassian.net/browse/NTV-438
> NTV-438: Deprecate autoparcel for checkout

- app/src/main/java/com/kickstarter/services/apiresponses/EmailVerificationEnvelope.kt
- app/src/test/java/com/kickstarter/models/EmailVerificationEnvelopeTest.kt
- Migrated to kotlin
- Adopt @Parcelize 
- Remove all references to the AutoParcel library in Models, eventually, we will be able to remove that dependency.
Test Email Verification
https://kickstarter.atlassian.net/browse/NTV-492
> NTV-492 :Deprecate Autoparcel for EmailVerificationEnvelope.kt

- app/src/main/java/com/kickstarter/libs/utils/RewardUtils.kt
- app/src/main/java/com/kickstarter/mock/factories/RewardFactory.kt
- app/src/main/java/com/kickstarter/models/Reward.kt
- app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
- app/src/main/java/com/kickstarter/ui/viewholders/RewardViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
- app/src/main/res/layout/add_on_card.xml
- app/src/main/res/layout/item_add_on.xml
- app/src/main/res/layout/item_reward.xml
- app/src/main/res/layout/reward_item_local_pickup.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/kickstarter/libs/utils/RewardUtilsTest.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
A new type of shipping preference has been added. Now a reward can be collected locally
- The reward model has been extended with a new optional Location field named `localReceiptLocation`
- A New shippingPreference type has been added `LOCAL`
https://user-images.githubusercontent.com/4083656/165413650-55a43750-8453-472e-a78f-e1eedfddee79.mp4
|  |  |
- Load this project https://staging.kickstarter.com/projects/alexa-test-1/reclaimed-chocolate-reprinting?ref=nav_search&result=project&term=reclaimed
two of the rewards have `Reward Location` make sure you can see the UI displayed on each card on the rewards carousel with the feature flag active
- Load the same project with the feature flag disabled, the `Reward Location` section is not visible
- Load any other project, make sure the `Reward …
> PAY-1571: Rewards Carousel can display localReceiptLocation UI

- app/src/main/java/com/kickstarter/libs/utils/ApplicationLifecycleUtil.java
- app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
- app/src/main/java/com/kickstarter/ui/intentmappers/DiscoveryIntentMapper.kt
- app/src/main/java/com/kickstarter/viewmodels/ActivityFeedViewModel.java
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ProfileViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.kt
- jacoco.gradle
Investigate all the early network related crashes, and look for those network calls without error handling, or using deprecated transformers.
|  |  |
- Turn off any connectivity you might have and launch the app on discovery screen, activity screen and any project screen.
[NTV-535](https://kickstarter.atlassian.net/browse/NTV-535)
> NTV-535: Fix crashes

- app/src/main/java/com/kickstarter/services/apiresponses/ProjectStatsEnvelope.kt
- app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardReferrerBreakdownViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardReferrerBreakdownHolderViewModel.java
- app/src/test/java/com/kickstarter/services/apiresponses/ProjectStatsEnvelopeTest.kt
- app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardReferrerBreakdownHolderViewModelTest.java
The creator dashboard is crashing when scrolling to the bottom of the screen. 
Steps to reproduce
1- Sign in with a creator account
2- Tap the hamburger button and tap “Dashboard” in the menu
3- On that screen, scroll to the bottom → crash occurs
https://user-images.githubusercontent.com/4083656/171290538-3c3b186c-677a-46f1-99ca-de56446150af.mp4
|  |  |
[NTV-550](https://kickstarter.atlassian.net/browse/NTV-550)
> NTV-550: Creator facing crash

- app/src/main/java/com/kickstarter/services/KSApolloClient.kt
remove redundant observable subscription
- Crash found on debug mode -> https://console.firebase.google.com/u/1/project/android-internal-debug/crashlytics/app/android:com.kickstarter.kickstarter.internal.debug/issues/b8212ae8eda97df540f406bc64f0206d?time=last-seven-days&sessionEventKey=62A0D052013F00013C299D0103B10107_1685371054770622520
|  |  |
- Load addOns with world wide shipping base reward
- Load addOns with restricted shipping base reward
> [no-jira]: remove redundant observable subscription

- app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
- When the user hits the `Campaign` tab, an analytic events should be sent to segment with the format: 
Event type: Page Viewed
context_page: project
context_section: campaign
- The code was already in place, sending incorrect `context_section`
- Logcat screenshot
- Segment debugger
|  |  |
- Take a look in logcat when hitting the campaign tab, make sure the event is triggered with the correct properties.
- Take a look at Segment debugger, event should be there.
[NTV-587](https://kickstarter.atlassian.net/browse/NTV-587)
> NTV-587: Segment event for campaign tab

- app/src/main/java/com/kickstarter/libs/utils/extensions/IntentExt.kt
- app/src/main/java/com/kickstarter/ui/IntentKey.kt
- app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ResetPasswordActivity.kt
- app/src/main/java/com/kickstarter/ui/data/ResetPasswordScreenState.kt
- app/src/main/java/com/kickstarter/viewmodels/LoginToutViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ResetPasswordViewModel.kt
- app/src/main/res/layout/reset_password_layout.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/test/java/com/kickstarter/libs/utils/extensions/IntentExtTest.kt
- app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ResetPasswordViewModelTest.kt
[Android] ask user to reset password with facebook login error  
https://www.figma.com/file/lmJlSlEk5Wp7BfxCVtKplU/Deprecrating-FB-Authentication?node-id=192%3A2368
Facebook login completely unavailable due to revoked API, user clicks FB CTA
Check under feature flag with facebook login error to show dialog to user to reset password or login normally 
https://user-images.githubusercontent.com/1075310/184010350-04676813-27d4-4e77-bbcb-a27e47bbdbce.mp4
Test on staging as we already have facebook error and feature flag enabled to work as demo 
Test production with normal flow login with facebook 
https://kickstarter.atlassian.net/browse/WEB-695
> WEB-695  : [Android] Facebook login completely unavailable due to revoked API, user clicks FB CTA open reset password screen

- app/src/main/java/com/kickstarter/libs/utils/extensions/IntentExt.kt
- app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
- app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectUpdatesViewModel.kt
- app/src/test/java/com/kickstarter/libs/utils/extensions/IntentExtTest.kt
- Go to the project https://staging.kickstarter.com/projects/kimeramodels/tenebrae-fate-of-asteria
- Press Updates
The intent generated is exceeding the limit of 1MB forcing the app to crash. Take a look to the android documentation :  [Parcelables and Bundles  |  Android Developers](https://developer.android.com/guide/components/activities/parcelables-and-bundles#sdbp)
By looking at logcat you can see the exception TransactionTooLargeException
```
08-22 13:00:22.436  1190  1370 W UsageStatsService: Unexpected activity event reported! (com.kickstarter.kickstarter.internal.debug/com.kickstarter.ui.activities.DiscoveryActivity event : 23 instanceId : 141828132)
08-22 13:00:22.436  1190  2519 E ActivityTaskManager: Transaction too large, intent: Intent { …
```
> NTV-602 && SD-1499: Crash when opening updates for concrete project

- app/build.gradle
Stipes SDK upgrade
- Previous version had a bug for validating postal code
- Targeted API 32 (stripe's restriction)
- Updates to latest stripe version
- pledge 
https://user-images.githubusercontent.com/4083656/187749061-12ec5bf7-2687-4bc2-a25e-ca4532837f5d.mp4
- Validate postal code with paymentsheet, update pledge (update pledge currently works with previously added payment methods, not yet with the added via PaymentSheet)
https://user-images.githubusercontent.com/4083656/187749262-c3f3b02b-7f5f-420f-9766-98009f09908a.mp4
|  |  |
- Pledge
- Add payment methods
- Update pledge
[PAY-1931](https://kickstarter.atlassian.net/browse/PAY-1931)
> PAY-1931: Upgrade stripe SDK to latest version

- app/src/main/java/com/kickstarter/libs/utils/RewardUtils.kt
- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/main/res/layout/fragment_backing_section_reward_delivery.xml
- app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
- load  manage your pledge screen for a reward that has an estimated delivery date, and is shippable. If you reload the screen, the mark as received UI disappears. Now it has a consistent behaviour.
- A reward "no reward" is considered as such when the ID == 0 , but only for graphQL API, when the request is made to V1 API the entire the consideration of reward no reward within the backing object is reward == null && rewardId == null
- The input data to the screen has two entry points for the reward:
- - ProjectData -> baking -> reward
- - ProjectData -> Project -> backing -> reward
When hitting refresh the observable for showing the "Mark as received UI" was not emiting properly, now obtained both rewards if available and merged on a single observable.
| Before 🐛 | …
> NTV-603: Mark as received UI inconsistent behaviour

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kickstarter/ui/viewholders/ThanksShareViewHolder.kt
- app/src/main/res/values/strings_config.xml
Update the Facebook sdk to latest
Login with facebook stopped 
Before 
After
https://user-images.githubusercontent.com/1075310/189166436-bb79ec49-0ef2-4276-8e7a-e93c2027b7df.mp4
https://user-images.githubusercontent.com/1075310/189166640-94783d4a-86c4-4929-9df3-2b51581da93e.mp4
1- test login with facebook
2- test share facebook button on thanks activity  apledgeeldge project 
[NTV-607](https://kickstarter.atlassian.net/browse/NTV-607)
> NTV-607 : upgrade facebook sdk to latest for android 13

- .circleci/config.yml
- app/src/test/java/com/kickstarter/libs/utils/extensions/IntentExtTest.kt
Take a look into the internal pipelines -> https://app.circleci.com/pipelines/github/kickstarter/android-private
Take a look into the external pipelines (Open source repository) -> https://app.circleci.com/pipelines/github/kickstarter/android-oss
The internal ones where failing due to a time out on the code coverage generation 
- Updated the orbs for `Android` and `codecov`
- Deleted redundant step for testing, executing `jacocoExternalReleaseReport` set will call internally `testExternalRelease`
- Internal branch successfully running all the stepsthat previously failed -> https://app.circleci.com/pipelines/github/kickstarter/android-private/772/workflows/20c45591-46ac-41d3-804c-a7da6d93b3d6/jobs/8145
|  |  |
- Nothing to QA, it's CI integration step, once this PR is merged the internal …
> NTV-622: Internal builds not being generated

- app/src/main/java/com/kickstarter/ui/activities/PaymentMethodsSettingsActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/PaymentMethodsViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/PaymentMethodsViewModelTest.kt
- Error during 3DS validation flow
- `SavePaymentMethod` mutation was being called before the validation process was completed by the user, when receiving the user input through `onPaymentOption` there was no warrant for the 3DS validation process to be completed. To be completely sure the validation process is finalized `SavePaymentMethod` has being moved to `onPaymentSheetResult` ONLY when the result is completed.
- Added additional UI loading  starting from the moment where we have the payment method available, until some result is obtained from `onPaymentSheetResult`
- Differentiate between success state for deleting payment methods, and success state for saving payment method
| Before 🐛 |
- Not saving the payment method, as it was attempting to save the payment methods once …
> PAY-1988:  Fixed 3DS validation error

- app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
- app/src/main/java/com/kickstarter/ui/views/MediaHeader.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectPageViewModelTest.kt
Hide backer tag when video clicked
Update video for projects to play in the same screen
| Before 🐛 | 
https://user-images.githubusercontent.com/1075310/201140703-93ca2290-6d2d-41e3-b8d1-6e0af3f2b737.mp4
| After 🦋 |
https://user-images.githubusercontent.com/1075310/201140656-18bf85f7-ba7e-44a4-9917-876853102b49.mp4
Play a video on the backed project
> [no-jira]: Fix Hide backer tag when video clicked

- app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ThreadViewModelTest.kt
newly posted comments as soon as we load more pages of comments /Replies disappear 
newly posted comments as soon as Pull to refresh duplicated
Fix comments issue
Add a list of newly posted comments and append to the pagination source 
Before 
Uploading device-2022-11-28-215421.mp4…
After 
https://user-images.githubusercontent.com/1075310/204365417-b34cfbd3-b643-44a2-bf12-c2764f7cb51f.mp4
1. Go to a project comments / Replies screen
2. Post a comment
3. Scroll down until more comments are loaded
4. Scroll back up and look for your latest comment
5. Pull to refresh
https://kickstarter.atlassian.net/browse/NTV-141
> NTV-141 :  New comments disappearing on pagination

- app/build.gradle
- app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectExt.kt
- app/src/main/java/com/kickstarter/ui/activities/ActivityFeedActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ThanksActivity.kt
- app/src/main/java/com/kickstarter/ui/fragments/DiscoveryFragment.kt
- app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
- app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/test/java/com/kickstarter/libs/utils/extensions/ProjectExtTest.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Several points in the PR: 
- 1 - Fix for crash with exception `Fatal Exception: java.lang.IllegalArgumentException: Invalid Setup Intent client secret: ...` discovered during QA party for Checkout flows with PaymentSheet. [Firebase report](https://console.firebase.google.com/u/1/project/android-internal-debug/crashlytics/app/android:com.kickstarter.kickstarter.internal.debug/issues/b2711e4d175f0a1b5a96b4e149dffb37)
Refined a bit the user facing error messages for this point with, instead of presenting the generic "Something went wrong" message, now the Stripe error localized message is displayed to the user.
- 2 - Discovered `TransactionTooLargeException` for certain projects when triggering 3DS flow after adding payment method using `PaymentSheet` [Firebase …
> PAY-2080: Retry pledge after error with PaymentSheet

- app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
- app/src/main/java/com/kickstarter/libs/utils/DateTimeUtils.kt
- app/src/main/java/com/kickstarter/mock/factories/RewardFactory.kt
- app/src/main/java/com/kickstarter/models/Reward.kt
- app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
- app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
- app/src/test/java/com/kickstarter/libs/utils/DateTimeUtilsTest.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
For this project, the estimated delivery date is different between  Android and web
User report the estimated delivery date is different between  Android and web
as `estimatedDeliveryOn` date is formatted without the time change the android uses the date object replacing DateTime and removes the timezone to fix the issue for `estimatedDeliveryOn` 
| Before 🐛 |
https://user-images.githubusercontent.com/1075310/204814377-032da11c-73b4-4dc2-9375-dae32e757ba1.mp4
| After 🦋 |
https://user-images.githubusercontent.com/1075310/204814115-733d629a-e783-4ff0-818a-7c4963087c9e.mp4
Open projects [https://www.kickstarter.com/projects/alstup/the-first-connected-round-counter-and-timer-in-the-world](https://www.kickstarter.com/projects/alstup/the-first-connected-round-counter-and-timer-in-the-world) on …
> NTV-601 : Android displaying inaccurate estimated delivery date

- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentLegacyViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentLegacyViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Updating amount using input text on update pledge flow did not enabled the continue button.
| Before 🐛 |
https://user-images.githubusercontent.com/4083656/204927340-d1a4bbb2-5e02-46f1-9ee5-a97928d5799e.mp4
|After 🦋 |
https://user-images.githubusercontent.com/4083656/204927349-f068208c-bafe-4b54-8468-d731ec4eac8d.mp4
|  |  |
- Update a pledge, update the bonus amount using only the text field, not the steppers
[PAY-2077](https://kickstarter.atlassian.net/browse/PAY-2077)
> PAY-2077: Updating amount using input text on update pledge flow did not enabled button

- app/src/main/java/com/kickstarter/libs/RecyclerViewPaginator.java
- app/src/main/res/layout/message_thread_view.xml
The messages screen was loading only the first batch of messages, never retrieving more.
- It was a UI related problem, when the first batch of elements was not big enough to trigger scroll events on `RecyclerViewPaginator.java` it was imposible to trigger the next call page.
- `RecyclerViewPaginator.java` filter `canScrollVertically` removed, now relying only in the last item visible to call nextPage.
- Took the chance to change the `message_thread_view` to a flat hierarchy without relative|linearLayouts
| Before 🐛 |
https://user-images.githubusercontent.com/4083656/206320598-8145e428-58dd-418b-b33b-b8ebcd5d2e2a.mp4
| After 🦋 |
- Tablet simulator
https://user-images.githubusercontent.com/4083656/206320515-665c3ca8-720c-4e1f-8ff7-0156e400f5f8.mp4
- Real phone device …
> NTV-637: Messages screen unable to load more messages

- app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectRiskFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectRiskViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectRiskViewModelTest.kt
The `ProjectRiskFragment` UI has been targeted as the first one to be migrated to Compose, but in order to be able to successfully do so a few steps are required prior to it:
- Adopt `ViewModel` -> https://developer.android.com/topic/libraries/architecture/viewmodel
- Upgrade to RxJava 2.2 
- Remove inheritance from `BaseFragment` and `FragmentViewModel`
Engineering plan detailing how and why to tackle the previous 3 points https://kickstarter.atlassian.net/wiki/spaces/~420550558/pages/2028339209/H2+2022+Android+Tech+Plan
No user facing changes, it should all look prior to these changes
https://user-images.githubusercontent.com/4083656/208513618-068300c9-867b-4cdf-8cca-d37ed92e509e.mp4
|  |  |
- Load several projects and go to the risks tab …
> PAY-2100: Compose spike

- app/src/main/java/com/kickstarter/ui/SharedPreferenceKey.kt
- app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.kt
Show the consent management dialog on bootstrap when a user has not set consent preferences. 
Consent management
We show the dialog if:
- There is no consent preference saved in shared preferences
- The feature flag is on for the user 
The consent preference cannot be dismissed unless a user selects allow or deny
- Make sure you are on staging
- Open app, dialog should appear on bootstrap
[WEB-875: [Android] Show dialog on bootstrap when preference has not been set]( https://kickstarter.atlassian.net/browse/WEB-875)
> WEB-875: [Android] Show dialog on bootstrap when preference has not been set

- app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
- app/src/main/java/com/kickstarter/ui/fragments/ConsentManagementDialogFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/ConsentManagementDialogFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ConsentManagementDialogFragmentViewModelTest.kt
Saves user consent preference in local storage in response to tapping "Allow" or "Deny" on the consent preference dialog.
Consent management feature
- Created a view model for the `ConsentManagementDialogFragment`
- When a user taps "Allow" or "Deny" on the dialog, the preference is emitted to the view model, which then saves the preference in shared prefs
- Consent management pops up upon app bootstrap
- Once user selects a preference, it should not appear again after restarting the app
https://user-images.githubusercontent.com/19390326/213270821-bdde79f5-99ed-437a-ac18-976077183933.mp4
- Make sure you are on staging
- Open app upon fresh install
- Consent management popup should appear
- Tap "allow" or "deny"
- Quit and restart app -> dialog should not appear again
- Clear app data and …
> WEB-878: [Android] Save consent preference on user interaction with dialog

- app/src/main/java/com/kickstarter/viewmodels/ConsentManagementDialogFragmentViewModel.kt
Since we have migrated away from using `BaseFragment`, we need to clear any subscriptions we create in the viewmodel. 
Add a composite disposable to the view model, add any subscriptions to it, and then dispose of them when the view model is cleared. 
No visual changes
> [no-jira] Add subscriptions in ConsentManagementViewModel to disposable

- app/src/main/java/com/kickstarter/ui/viewholders/ProjectSearchResultViewHolder.kt
- app/src/main/res/layout/project_search_result_view.xml
Fix coming soon label alignment in the search result 
match [figma](https://www.figma.com/file/Wt14jhetT6UVq0HpzMtXFe/Native-Pre-Launch?node-id=85-1451&t=xfwVI70zFKuMTj3Y-0)
overlay coming soon to replace fund labels 
| --- | --- |
test on staging with the search keyword "ion"
> [no-jira]:  Fix issue for search result Coming soon label

- app/src/main/res/layout/comment_card.xml
In comments activity, constrain the "This comment has been removed by Kickstarter. Learn more about comment guidelines" textview's bottom constraint so that it does not overlap replies.
The textview lacked a bottom constraint and overlapped replies UI below it.
| --- | --- |
|  ![mbl-676-before](https://user-images.githubusercontent.com/129205442/229895286-13643e28-8a92-420e-b402-fee050779de6.jpeg) | ![Screenshot_20230404_151943](https://user-images.githubusercontent.com/129205442/229897976-0dcae03d-a3e8-44f9-b48a-e968531231ae.png) |
To force a comment to be removed, temporarily override the visibility of commentBody and removedMessage in CommentCard.kt line 169:
```
binding.commentBody.isVisible = false
binding.removedMessage.isVisible = true
```
Also override …
> MBL-676: Constrain bottom of removed comment textview

- app/src/main/java/com/kickstarter/models/extensions/CommentExt.kt
- app/src/main/res/layout/comment_card.xml
- app/src/test/java/com/kickstarter/viewmodels/CommentsViewHolderViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/RootCommentViewHolderViewModelTest.kt
Previously https://github.com/kickstarter/android-oss/pull/1337 prioritized user badges in this order:  `You, Creator/Collaborator, Superbacker` per product requirements
Update priority to `Creator/Collaborator, Superbacker, You` 
Superbacker users expressed a preference to see a `Superbacker` badge on their own comments rather than just a regular `You` badge
| --- | --- |
| ![superbacker_badge_before](https://user-images.githubusercontent.com/129205442/230150785-af188c52-85de-4f31-8696-0ba537e18085.png) | ![superbacker_badge_after](https://user-images.githubusercontent.com/129205442/230150807-0f14e200-267f-4721-a463-9482c76824ff.png) |
Temporarily override `Comment.kt` L31 to set your own user as a Superbacker. 
```
fun authorBadges() : List<String>? {
return if …
```
> MBL-693 Prioritize superbacker badge before you badge

- app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/LoginToutViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ResetPasswordViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ResetPasswordViewModelTest.kt
In the viewModel/viewModelTests level change the calls:
optimizely.isFeatureEnabled(OptimizelyFeature.Key.ANDROID_FACEBOOK_LOGIN_REMOVE)  
to 
featureFlagClient.getBoolean(FlagKey.ANDROID_FACEBOOK_LOGIN_REMOVE)
This is one feature flag migration as part of overall migration from optimizely to firebase remote config [MBL-661](https://kickstarter.atlassian.net/browse/MBL-661)
No visible changes.
In firebase console, change the value of ANDROID_FACEBOOK_LOGIN_REMOVE in the three build variants. Verify that the facebook login is shown or not shown in the login screen. 
https://kickstarter.atlassian.net/browse/MBL-681
[MBL-661]: https://kickstarter.atlassian.net/browse/MBL-661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MBL-684: Migrate feature flag ANDROID_FACEBOOK_LOGIN_REMOVE

- app/build.gradle
- app/src/main/java/com/kickstarter/libs/utils/DateTimeUtils.kt
- app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
- app/src/test/java/com/kickstarter/libs/utils/DateTimeUtilsTest.kt
…o page to display correct time and the phones timezone
- Add desugaring to allow access to java 8 libraries (normally only available natively with API 26+ (current app minimum is 23)
- Fix issue where end time/deadline for project description was not in the users current time zone (was always UTC)
- Added timezone abbreviation to time for further clarrification
Users could not tell when a project would actually be finished relative to their local time
Added desugaring and used the newer standard java.time libraries.  Joda time has been out of date as of Java 8SE libraries:
https://www.joda.org/joda-time/#:~:text=Note%20that%20from%20Java%20SE%208%20onwards%2C%20users%20are%20asked%20to%20migrate%20to%20java.time%20(JSR%2D310)%20%2D%20a%20core%20part%20of%20the%20JDK%20which%20replaces%20t …
> MBL-691: Fix incorrect end time being displayed for project descriptions

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
- app/src/main/res/drawable/ksr_logo_rgb_white.xml
- app/src/main/res/values/styles.xml
Added the android splash screen api to our app. 
Add the api, create the theme/style, add the manifest and call from onCreate before `super.onCreate(savedInstanceState)`
Splash screen is automatically dismissed once the first view element in discovery activity is drawn
Make sure splash screen loads on devices both below and above api 33
[MBL-727: Create splash screen and launch from Discovery Activity](https://kickstarter.atlassian.net/browse/MBL-727)
> MBL-727: Create splash screen and launch from Discovery Activity

- app/src/main/java/com/kickstarter/libs/utils/NumberUtils.java
- app/src/main/java/com/kickstarter/libs/utils/extensions/StringExt.kt
- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/main/res/layout/fragment_pledge_section_bonus_support.xml
- app/src/test/java/com/kickstarter/libs/utils/extensions/StringExtKtTest.kt
Fixes an issue where the bonus amount on pledge pages could not pass 3 digits.  This makes it so it will allow any normal formatting from the locale of the device
You could not pledge up to the limit before
Removed the use of deprecated calls and updated formatting/parsing to use standard libraries
| Before (ANY) 🐛 | After USA 🦋 | After Germany | After France |
| --- | --- | --- | --- |
| https://github.com/kickstarter/android-oss/assets/7563288/fc5202f0-b8b4-405a-a058-84c60e4c81f8 | https://github.com/kickstarter/android-oss/assets/7563288/58d4c723-a121-4adb-9c8c-72de97c8a373 | https://github.com/kickstarter/android-oss/assets/7563288/a9d30296-8715-4153-8767-c07c9da19bf7 | https://github.com/kickstarter/android-oss/assets/7563288/889428a4-bf1f-4a5f-8b44-1f8cb130fa72 |
1. Set your …
> MBL-700 : Fix bonus amount not being able to go past 3 digits

- app/src/main/java/com/kickstarter/libs/rx/transformers/ObserveForUITransformerV2.kt
- app/src/main/java/com/kickstarter/libs/rx/transformers/Transformers.java
- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
- app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/ChangePasswordViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ChangePasswordViewModelTest.kt
Remove older library (rx1) and replace with newer version for the change password screen, viewmodel and tests
Rx1 is out of date so we are updating most classes to rx2
See code, mostly updating libraries and updating calls as needed
No Visual changes
Go to the change password screen under account in the app and attempt to change your password, including attempts with invalid passwords (under character minimum of 6)
[MBL-748](https://kickstarter.atlassian.net/browse/MBL-748)
[MBL-748]: https://kickstarter.atlassian.net/browse/MBL-748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-748] Update ChangePassword Activity, Viewmodel, and tests to RX2

- app/src/main/java/com/kickstarter/ui/activities/TwoFactorActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/TwoFactorViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/SignupViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/TwoFactorViewModelTest.kt
Used Jetpack ViewModel() and updated rxjava disposables in TwoFactorActivity and TwoFactorViewModel by following these steps: https://kickstarter.atlassian.net/wiki/spaces/NT/pages/2350317579/ViewModel+Tech+Debt+Epic#Technical-details
[ViewModel Tech Debt Epic](https://kickstarter.atlassian.net/wiki/spaces/NT/pages/2350317579/ViewModel+Tech+Debt+Epic)
No visible changes
[MBL-829](https://kickstarter.atlassian.net/browse/MBL-829)
[MBL-829]: https://kickstarter.atlassian.net/browse/MBL-829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Migrate TwoFactorViewModel.kt to Jetpack ViewModel and RxJava2.2

- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
- app/src/main/java/com/kickstarter/ui/activities/AccountActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/AccountViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/AccountViewModelTest.kt
One more migration
- Take a look to the engineering plan [here](https://kickstarter.atlassian.net/wiki/spaces/NT/pages/2350317579/ViewModel+Tech+Debt+Epic) if needed 
|  |  |
- You should be able to navigate to all the items presented [Change email, change password ... etc]
- Change your selected currency. ⚠️ once you change your currency kill the app and start again, load a project page, you should see the new selected currency applied.
[MBL-738](https://kickstarter.atlassian.net/browse/MBL-738)
[MBL-738]: https://kickstarter.atlassian.net/browse/MBL-738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MBL-738: AccountActivity-ViewModel Migrated to RXJava2 + JetpackViewModel

- app/src/main/java/com/kickstarter/libs/featureflag/FeatureFlagClient.kt
- app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
- app/src/main/java/com/kickstarter/ui/adapters/DiscoveryDrawerAdapter.kt
- app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/LoggedInViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectOverviewViewModel.kt
Added a feature flag that will hide the dashboard feature when set to true
We will be removing this feature in the future so we want to be able to turn it off from this version onward before removal
Added the variable in the remote config and read that value where needed in the app
1) Log in as a creator
2) turn the feature flag on/off depending on what you are testing
3) Check to see if the entry point on both the discovery menu and the project page are gone when the flag is set to true, there when set to false
[MBL-857](https://kickstarter.atlassian.net/browse/MBL-857)
[MBL-857]: https://kickstarter.atlassian.net/browse/MBL-857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-857] Add feature flag to remove dashboard feature

- app/quality.gradle
- app/src/main/java/com/kickstarter/ui/fragments/projectpage/FrequentlyAskedQuestionFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/FrequentlyAskedQuestionViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/FrequentlyAskedQuestionViewModelTest.kt
Migration to rxjava 2.2 and jetpacks viewmodel
- Find a project with FAQs (search "FLEXTAIL EVO ICER") , and a project without FAQs (Search "The golden era" tarot deck)
- Test all states:
- Logged in user, project with FAQs: Should see list of FAQs
- Logged in user and backer, project without FAQs: Empty state with button prompting users to ask a question, button opens message thread with creator 
- Logged in user and not backer, project without FAQs: Empty state with button prompting users to ask a question, button opens an edit text to message creator
- Logged out user, project with FAQs: Should see list of FAQs
- Logged out user, …
> MBL-767: FrequentlyAskedQuestionViewModel.kt to Jetpack ViewModel and RxJava2.2

- app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
- Duplicated network calls for: `this.apolloClient.getShippingRules(rewardId)` && `this.apolloClient.createSetupIntent()`, for the `getShippingRules` no unit tests changed required as some `dictinctUntilChanged()` was hiding the second emission, but for `createSetupIntent` unit test you will see how the number of emissions for the loading state and pledge button enabled have been reduced.
- Performance improvements
- Both network request were hosted by Observables, having several subscriptions to that observable, executing the `switchMap` block as many times as subscriptions. Now both network requests are hosted on Subjects, able to multicast to other observables subscribed.
No user facing changes, but you can double check with the Android studio Network Profiles, before when loading …
> [No-jira]: Performance improvements

- app/src/internal/java/com/kickstarter/ui/activities/DesignSystemActivity.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/ChangePasswordScreen.kt
- app/src/main/java/com/kickstarter/ui/compose/designsystem/KSAlerts.kt
- app/src/main/java/com/kickstarter/ui/compose/designsystem/KSTextInput.kt
- Updated KS Alerts to have actual snackbars and name components accordingly
- Use scaffold for changepassword screen
- move topbar into scaffold
- use new snackbars for the snackbar message
Had to do custom work to make current snackbar show at the top, but we will be moving forward with android standards where we can, so started with that here
- Added keyboard options to compose ks input texts
- created new snackbars for ks alerts
- updated logic on change password screen to use error as a state
https://github.com/kickstarter/android-oss/assets/7563288/6277c9e8-26bf-48ba-8add-0849f531be07
None/My Head/Slack convos
> [NoTicket] Adjust usage and visuals of compose screen based on learnings

- app/src/main/java/com/kickstarter/ui/activities/SetPasswordActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/SetPasswordViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/SetPasswordViewModelTest.kt
Migration to rxjava 2.2 and jetpacks viewmodel
This feature is tricky to test - I had to manually set the `needsPassword` field in the User struct to `true`. I then had to make sure the feature flag for facebook login deprecation was on or the condition was commented out in the discovery view model. This is what made the set password screen appear after logging in.
On the actual set password screen: 
Make sure that the warning text changes if the passwords in each field do not match, or if the password in the first field is fewer than 6 characters. 
To test success or failure in setting the password, some work is required from the backend …
> MBL-798: SetPasswordViewModel.kt to Jetpack ViewModel and RxJava2.2

- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AiDisclosureScreen.kt
- app/src/main/java/com/kickstarter/ui/compose/designsystem/KSDimensions.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/kickstarter/ui/activities/compose/AiDisclosureScreenTest.kt
Add the questions and vertical bars to the use of AI tab
Design reasons
Compose with our componenets
[MBL-927](https://kickstarter.atlassian.net/browse/MBL-927)
[MBL-927]: https://kickstarter.atlassian.net/browse/MBL-927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-927] Add questions and vertical flag dividers to use of UI tab

- app/build.gradle
- app/src/internal/java/com/kickstarter/ui/activities/PlaygroundActivity.kt
- app/src/internal/res/layout/playground_layout.xml
- app/src/main/java/com/kickstarter/libs/htmlparser/ElementExt.kt
- app/src/main/java/com/kickstarter/libs/htmlparser/HTMLModels.kt
- app/src/main/java/com/kickstarter/ui/viewholders/projectcampaign/TextElementViewHolder.kt
- app/src/main/res/values/dimens.xml
- app/src/test/java/com/kickstarter/libs/htmlparser/HTMLParserTest.kt
The HTMLParser was able to recognize only the `h1` html tag, now it supports h1 to h6 following [html headings guideline](https://www.w3schools.com/html/html_headings.asp)
- The website has a new WYSIWYG editor (ckeditor) on the creator experience, it also has been added header anchors for the story campaign, requiring proper headings tag usage.
- Added tags to be recognized  on `TextBlockType`
- Added new styles to enum class `TextStyleType`
The parser will do it's work, and recognize the new added tags and will apply the new styles without further changes.
- [Took the change to upgrade `jsoup` dependency ](https://mvnrepository.com/artifact/org.jsoup/jsoup), the previous version had several vulnerabilities.
- Added on the Playground activity a sample HTML displaying the styles as …
> MBL-942: HTMLParser now accepts headers

- app/src/internal/java/com/kickstarter/ui/activities/InternalToolsActivity.kt
As apart of android 14 updates, we need to add a broadcast receiver flag when registering any context registered receivers. 
[More information here](https://kickstarter.atlassian.net/wiki/spaces/NT/pages/2446065708/Android+14+spike#Runtime-registered-broadcasts-receivers-must-specify-export-behavior )
Add broadcast receiver flag to internal tools activity when registering a receiver.
The flags parameter was added in Android 33, so we will call this function in devices above android 33. Anything below defaults to old behavior.
no user facing changes
Run app on device with android 34, as well as anything below android 33. Navigate to internal tools, should be no crashes. 
[MBL-921: Broadcast receiver needs flags for "Internal tools" screen](https://kickstarter.atlassian.net/browse/MBL-912)
> MBL-921: Broadcast receiver needs flags for "Internal tools" screen

- .circleci/config.yml
- app/build.gradle
- app/src/main/java/com/kickstarter/libs/BaseActivity.java
- app/src/main/java/com/kickstarter/services/ConnectivityReceiver.kt
- app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
- build.gradle
- Upgraded connectivity status check
- Upgraded gradle version
- Upgraded CI image tag
- `activeNetworkInfo` [was deprecated on API 29 ](https://developer.android.com/reference/android/net/NetworkInfo) substituted by [`registerNetworkCallback()`](https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback) 
- `compileSdkVersion` [is deprecated](https://developer.android.com/reference/tools/gradle-api/7.2/com/android/build/api/dsl/CommonExtension#compileSdkVersion(kotlin.Int)) substituted by `compileSdk`
- [CI image now includes API 34](https://circleci.com/developer/images/image/cimg/android)
https://github.com/kickstarter/android-oss/assets/4083656/ff0e0695-d3c2-4132-b431-d8f8448ec631
|  |  |
- On `Discovery` or search or any of the activities still inheriting …
> MBL-932: Connectivity status check

- app/src/main/java/com/kickstarter/ui/activities/CreatePasswordActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/SetPasswordActivity.kt
- During QA, we discovered a crash on the create password screen after resetting the password
- Set password activity also allows user to back out of screen
Migration to rxjava2 of login milestone required QA of setting a password for facebook kickstarter accounts
- Crash was happening due to a threading issue in the CreatePasswordActivity, added `.observeOn(AndroidSchedulers.mainThread())` to fix
- Override the backpress in the SetPasswordActivity to do nothing when a user hits the back button
- Testing is tricky, you have to have a kickstarter facebook account on prod. If you have one and have already set a password, you of the backend engineers has to remove your password in order to trigger these flows to happen. 
- to test the back press functionality, you can manually trigger the …
> MBL-933: Facebook Login QA Fixes for release

- app/src/main/java/com/kickstarter/ui/compose/designsystem/KSColors.kt
Added the colors from the web side for both light and dark modes, reformatted colors so colors were not being re-written in themes
We know web has had work for their dark mode done by design, these colors will most likely be used in apps to some degree
see:
https://kickstarter.slack.com/files/U04TWT3JFF0/F05MYHU76E8/variables.json?origin_team=T024BHJ4H&origin_channel=D05CRPALC65
No visual changes in app.  Colors were added to themes but not used yet
[MBL-880](https://kickstarter.atlassian.net/browse/MBL-880)
[MBL-880]: https://kickstarter.atlassian.net/browse/MBL-880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-880] Added colors and theming from web for light and dark mode

- app/src/main/java/com/kickstarter/libs/BaseActivity.java
- app/src/main/java/com/kickstarter/services/ConnectivityReceiver.kt
- app/src/main/java/com/kickstarter/ui/activities/AccountActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ChangeEmailActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/PaymentMethodsSettingsActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/SearchActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/SetPasswordActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/SignupActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/TwoFactorActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/UpdateActivity.kt
- app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
- build.gradle
- Registering to the connectivity status check is now made using `lifecycle`. Moving functionalities away from `BaseActivity` inheritance hierarchy. 
- Connectivity status check on `Activities` not inheriting from `BaseActivity`, as example on the video we have `SearchActivity` and `UpdatesActivity` displaying the lost connection message
https://github.com/kickstarter/android-oss/assets/4083656/f1185cdb-eaba-4559-98f4-1a4a7ee2e6d1
|  |  |
- Try loosing connection on any of the activities where `setUpConnectivityStatusCheck(lifecycle)` is called
[MBL-950](https://kickstarter.atlassian.net/browse/MBL-950)
[MBL-950]: https://kickstarter.atlassian.net/browse/MBL-950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MBL-950: Connectivity status check refactor

- app/src/main/java/com/kickstarter/ui/activities/VideoActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/VideoViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/VideoViewModelTest.kt
- Migration, take a look at the [engineering plan](https://kickstarter.atlassian.net/wiki/spaces/NT/pages/2350317579/ViewModel+Tech+Debt+Epic) if any doubt 
- Most of the integration with Exoplayer was using deprecated methods, integration upgraded.
https://github.com/kickstarter/android-oss/assets/4083656/c4578a8f-651f-447a-9201-e21d1d99ca53
| --- | --- |
|  |  |
- Play a video, press fullScreen, the video should play keep player over the same time as when it was in reduce screen.
- Dismiss the fullScreen, player should keep playing at the same time when changed screens. 
- Complete the video, play again, touch the controllers ... 
[MBL-805](https://kickstarter.atlassian.net/browse/MBL-805)
[MBL-805]: https://kickstarter.atlassian.net/browse/MBL-805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3M …
> MBL-805: VideoPlayer Screen

- app/src/main/java/com/kickstarter/viewmodels/ProjectUpdatesViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/UpdateCardViewHolderViewModel.kt
Occasionally the backend will send a blank update.  In debug mode this will crash the app.  To prevent that, filtering out a null field.
Some weird behavior with updates on some projects
| --- | --- |
| ![Screenshot_20231023-144439](https://github.com/kickstarter/android-oss/assets/7563288/a9bcc56a-b4e5-479c-8a6a-e4240337bcad) | ![Screenshot_20231023-144505](https://github.com/kickstarter/android-oss/assets/7563288/257c4262-05a0-402a-b3ac-887ceb069d2b) |
> [Bugfix] Fix crash (debug only) and prevent showing blank updates

- app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
- app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardsFragmentViewModelTest.kt
- Migration RXJava2 + ViewModel, take a look at the [engineering plan](https://kickstarter.atlassian.net/wiki/spaces/NT/pages/2350317579/ViewModel+Tech+Debt+Epic) if any doubt 
https://github.com/kickstarter/android-oss/assets/4083656/101e41c6-7267-4087-923d-8f56a63581a8
| --- | --- |
|  |  |
- Browse several projects open the rewards carousel for addons, rewards, as backer, ... etc.
- Browse several finalized projects open the rewards carousel if no backer.
- Browse several finalized projects as backer, the manage pledge screen should appear.
[MBL-795](https://kickstarter.atlassian.net/browse/MBL-795)
[MBL-795]: https://kickstarter.atlassian.net/browse/MBL-795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MBL-795: RewardsFragment Screen

- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
- app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/ProjectUpdatesViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectUpdatesViewModelTest.kt
- Migration RXJava2 + ViewModel, take a look at the [engineering plan](https://kickstarter.atlassian.net/wiki/spaces/NT/pages/2350317579/ViewModel+Tech+Debt+Epic) if any doubt 
- Added connectivity check
- Improved back navigation
- Using loading indicator on top screen instead of bottom to unify user experience
https://github.com/kickstarter/android-oss/assets/4083656/b5db31e8-1f1e-4329-9aa2-de1f2ffe257c
|  |  |
- As logged off user you can just see comments on a Project/Update, but comment composer is not visible
- As logged in user, but no backer, you can see comments, but no posting allowed
- As logged in user, and backer, you are allowed to post a comment, on a Project or Update.
- - When posting a comment there will be scroll to the top
- - When posting a comment there will be …
> MBL-750: CommentsScreen to RXJava2 + ViewModel

- app/src/main/java/com/kickstarter/ui/SharedPreferenceKey.kt
- app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/CreatePasswordActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ResetPasswordActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/SearchActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/SetPasswordActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/SignupActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/TwoFactorActivity.kt
- app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectAIFragment.kt
- app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/LoggedOutViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/SettingsViewModel.kt
- app/src/main/res/layout/discovery_drawer_logged_out_view.xml
- app/src/main/res/layout/settings_layout.xml
- app/src/main/res/values/strings.xml
Add a shared prefs value for the selected app theme mode (match system[0], light[1], or dark[2])
Users should have a way to set the app theme once we are ready to let them use dark mode (defaults to system)
Add a shared prefs value (default pulls to match system)
1) Log in
2) Go to settings
3) Change mode to desired choice
4) GO to search or login flow to check selection changed theme
5) Log out
6) Do it again
[MBL-1060](https://kickstarter.atlassian.net/browse/MBL-1060)
[MBL-1060]: https://kickstarter.atlassian.net/browse/MBL-1060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-1060] Add dark mode toggle in settings, make settings visible to non logged in users

- app/src/main/java/com/kickstarter/viewmodels/MessagesViewModel.kt
Some creator messages were not able to be sent (button would click, but nothing happened)
Many of our RX observable chains require the previous parts to succeed to move on, in this case:
```
val thread = initialMessageThreadEnvelope
.filter { it.messageThread().isNotNull() }
.map { it.messageThread() }
// If view model was not initialized with a MessageThread, participant is
// the project creator.
val participant =
Observable.combineLatest(
thread,
project
) {
```
Here you can see the `thread` observable is used in the `participant` observable, but if thread would fail to exist then participant would never get populated and the observables observing it would not get updated or initialized
the `thread` object will now always return something, even if its an empty object so that the …
> [Bigfix] Fix issue where messages to some creators dont get sent

- app/src/main/java/com/kickstarter/ui/activities/ThanksActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.kt
- New crash raised while releasing Android 3.17.0
[Firebase Crash](https://console.firebase.google.com/u/1/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/d31b6ef2fb9b37c8bf68e349eaf72e2d?time=last-seven-days&versions=3.17.0%20(2014150890)&types=crash&sessionEventKey=6570BBD2038C00014D62F3C7BD843843_1887996047463586090)
Wrong Thread issues
|  |  |
- Back a project from games category, without being subscribed to the games newsletter, if pressing the `yes please` button on the Dialog the user will be opted-in to the games newsletter 
[MBL-1086](https://kickstarter.atlassian.net/browse/MBL-1086)
[MBL-1086]: https://kickstarter.atlassian.net/browse/MBL-1086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MBL-1086: ThanksActivity.showGamesNewsletterDialog crash

- app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.kt
A new crash was found on 3.17.0:
https://console.firebase.google.com/u/0/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/aafc872fb1f42423f44fb9fde52ebd45?time=last-seven-days&versions=3.17.0%20(2014150890)&types=crash&sessionEventKey=65702C2803D000015FAF94B5C6FCD33A_1887839482962394042
This should remove this crash
Crashes suck
Make the observable adjusting the UI run on the UI thread
Make sure settings activity loads correctly
[MBL-1089](https://kickstarter.atlassian.net/browse/MBL-1089)
[MBL-1089]: https://kickstarter.atlassian.net/browse/MBL-1089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-1089] SettingsActivity crash fix, Observe on UI thread

- .circleci/config.yml
- Upgraded machine version, installing firebase CLI was erroring due to an old version of node, this new machine has newer node version.
> [no-jira]: Upgrade android machine version

- app/src/main/java/com/kickstarter/ui/viewholders/RootCommentViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/RootCommentViewHolderViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/RootCommentViewHolderViewModelTest.kt
Update RootCommentViewHolderViewmodel to Rx2
Refactoring all the things
🧠 
This is only used in threads for the original post, so go to some threads and confirm the "root" comment still renders correctly
[MBL-797](https://kickstarter.atlassian.net/browse/MBL-797)
[MBL-797]: https://kickstarter.atlassian.net/browse/MBL-797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-797] Update root comment viewholder to rx2

- app/src/main/java/com/kickstarter/ui/viewholders/MessageViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/MessageHolderViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/MessageHolderViewModelTest.kt
Goal is to validate links sent in messages by creators to open app links in-app where applicable.
Previously, urls sent by creators would always open an external browser. Now, when it is a kickstarter link, it will open in app. All other links will continue to go to an external browser. 
- Update messages view holder and view model to rxjava 2
- Add functionality to check if textview contains a url
- Open deeplink activity and supply with url, this will handle the url validation
https://github.com/kickstarter/android-oss/assets/19390326/e46e5b09-4043-4090-b20d-c642465873c3
- Sign-in
- Go to your messages
- Find a kickstarter link, tap, should not redirect out of app
- Find a non-kickstarter link, tap, should redirect to system browser
[MBL-1053: Identify if https links in messages are KSR …
> MBL-1053: Identify if https links in messages are KSR links

- app/src/main/java/com/kickstarter/ui/viewholders/ErroredBackingViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/ErroredBackingViewHolderViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ErroredBackingViewHolderViewModelTest.kt
RX2 update to the erroedviewmodel/view
Refactoring is needed
Make sure tests pass and views can popular successfully
[MBL-764](https://kickstarter.atlassian.net/browse/MBL-764)
[MBL-764]: https://kickstarter.atlassian.net/browse/MBL-764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-764] Update ErroredBackingViewModel to RX2

- app/src/main/java/com/kickstarter/libs/TrackingClient.kt
- app/src/main/java/com/kickstarter/libs/TrackingClientType.kt
- app/src/test/java/com/kickstarter/libs/MockTrackingClient.kt
- app/src/test/java/com/kickstarter/libs/SegmentTest.kt
Add an analytic property for the session if the user is in force dark mode
We want to see if there is any sort of impact for users in dark mode vs not
Add the session property after checking the system version and dark mode setting
Run the app and confirm the `session_force_dark_mode=XXXX` is correct based on system setting and version
[MBL-1135](https://kickstarter.atlassian.net/browse/MBL-1135)
[MBL-1135]: https://kickstarter.atlassian.net/browse/MBL-1135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-1135] Add analytics value for session_force_dark_mode

- app/src/main/java/com/kickstarter/ui/activities/NotificationsActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/NotificationsViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/NotificationsViewModelTest.kt
Update NotificationActivity to RX2
Getting close y'all
🧠 
Make sure the toggling of notification settings still works, even after closing the app
[MBL-782](https://kickstarter.atlassian.net/browse/MBL-782)
[MBL-782]: https://kickstarter.atlassian.net/browse/MBL-782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-782] Update NotificationActivity to RX2

- app/src/main/java/com/kickstarter/ui/viewholders/ExpandableHeaderViewHolder.kt
- app/src/main/java/com/kickstarter/viewmodels/ExpandableHeaderViewHolderViewModel.kt
- app/src/main/res/layout/fragment_pledge_section_header_reward_sumary.xml
- app/src/test/java/com/kickstarter/viewmodels/ExpandableHeaderViewHolderViewModelTest.kt
Add-ons view was not being populated on pledge screen. Also the delivery date view was overlapping with a divider so I fixed that too.
We needed to import android.util.Pair otherwise it defaults to kotlin.Pair and the data never gets observed.
Import android.util.Pair and change the Guideline constraint % from left from 0.60 to 0.65 to keep delivery date to one line
| Before 🐛 | After fixing Pair type | After fixing constraint |
| <img src="https://github.com/kickstarter/android-oss/assets/129205442/b383b475-e243-4424-b944-ee7e13a86644" width="200"> | <img src="https://github.com/kickstarter/android-oss/assets/129205442/21b3b2d3-5818-4f6b-937e-76ad01ccc3a9" width="200"> | <img src="https://github.com/kickstarter/android-oss/assets/129205442/76cacb5b-6d7a-401b-966a-d3092 …
> Fix Add-ons field not appearing on pledge screen

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kickstarter/libs/featureflag/FeatureFlagClient.kt
- app/src/main/java/com/kickstarter/libs/utils/extensions/IntentExt.kt
- app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/OAuthActivity.kt
- app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
- app/src/main/java/com/kickstarter/viewmodels/LoginToutViewModel.kt
- app/src/test/java/com/kickstarter/libs/utils/extensions/IntentExtTest.kt
- app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.kt
- Feature flag configured on remote config for "Internal Debug", "Internal Release" and "External Release"
if feature **flag off** the old flow is enabled showing to the user LoginActivity
if the feature **flag is on** the new flow will be presented to the user (empty activity for now).
if feature flag off the old flow is enabled showing to the user SignUpActivity
if the feature flag is on the new flow will be presented to the user (empty activity for now).
- The Intent generated will be different depending on the fflag value
- Change the value to the ff to off, no user facing changes for login or sign up
- Change the value to the ff to on, both login and sign up will present an empty screen.
[MBL-1171](https://kickstarter.atlassian.net/browse/MBL-1171)
[MBL-1171]: …
> MBL-1171: Feature flag for OAuth 

- app/src/main/java/com/kickstarter/libs/utils/Secrets.java.example
- app/src/main/java/com/kickstarter/ui/activities/PrivacyActivity.kt
Update links in Privacy Activity for "Request My Personal Data" and "Delete My Kickstarter Account" to point to new Trascend flow
Need to use new Trascend flow
https://www.kickstarter.com/profile/request-export-data and https://www.kickstarter.com/profile/destroy -> https://legal.kickstarter.com/policies/en/?modal=take-control
Secrets.java also updated
Profile → Settings → Account → Privacy -> click on "Request My Personal Data" and "Delete My Kickstarter Account" to start Trascend flow. Verify user can initiate the process of a privacy request by choosing a request type and entering their email on the page.
https://kickstarter.atlassian.net/browse/MBL-1064
> MBL-1064 Update links for Request My Personal Data and Delete Account

- app/build.gradle
- app/src/main/java/com/kickstarter/models/chrome/ChromeTabsHelperActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/OAuthActivity.kt
- app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
- build.gradle
Getting ready for OAuth! 
- OAuth 2.0 implementation for Login & Signup, for more info take a look at the[ Eng plan ](https://kickstarter.atlassian.net/wiki/spaces/NT/pages/2571272239/OAuth+2.0+for+Native+Applications)
- Set the ChromeTabs that will load  **(OAuth authorization endpoint)** with navigationEvents callback to detect when the tab was closed.
- Updated from `androidx.browser:browser:1.4.0` -> `androidx.browser:browser:1.7.0`
- Updated from `com.android.tools.build:gradle:8.2.0`-> `com.android.tools.build:gradle:8.2.2`
- Using coroutines instead of rxjava
You can see the navigation events on Logcat filtering the the class name `CustomTabSessionAndClientHelper`
https://github.com/kickstarter/android-oss/assets/4083656/07ce6419-4735-405e-a2ae-0ec1091d8909
|  |  |
- Not much to QA …
> MBL-1167: New Login/Sign up Screen with Chrome Tabs (Phase 2)

- app/src/main/java/com/kickstarter/libs/utils/CodeVerifier.kt
- app/src/main/java/com/kickstarter/ui/activities/OAuthActivity.kt
- app/src/test/java/com/kickstarter/libs/utils/CodeVerifierTest.kt
Class that generates code verifiers and challenges for PKCE exchange, take a look at the RFC [Proof Key for Code Exchange by OAuth Public Clients](https://datatracker.ietf.org/doc/html/rfc7636)
- Generate a code `verifier` and a `code_challenge`, the `code_challenge` will be sent to the **(authorization endpoint)** on following tickets 
- Take a look at the RFC [Proof Key for Code Exchange by OAuth Public Clients 4.1](https://datatracker.ietf.org/doc/html/rfc7636#section-4.1) for the code verifier 
- Take a look at the RFC  [Proof Key for Code Exchange by OAuth Public Clients 4.2](https://datatracker.ietf.org/doc/html/rfc7636#section-4.2) for the code challenge
|  |  |
You can use this [website](https://oauth.school/exercise/refresh/) to generate encypted …
> MBL-1168: PKCE class

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kickstarter/libs/utils/CodeVerifier.kt
- app/src/main/java/com/kickstarter/libs/utils/extensions/IntentExt.kt
- app/src/main/java/com/kickstarter/models/chrome/ChromeTabsHelperActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/OAuthActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/OAuthViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/OAuthActivityViewModelTest.kt
- On `AuthorizationStep` the authorization URL is generated adding PKCE parameters to the url
- On redirectionStep an appplink redirects back to the app, so far the redirection only contains `code`, not ready yet to call the token endpoint (WIP) on the backend side.
- OAuth 2.0 on the apps
- The VM now receives an `Intent` is able to build the authorization URL is staging and production on the `AuthorizationStep`
-  the VM now receives an `Intent` and is able to collect from it the `code` that will be used later on to call the Token endpoint.
- `OAuthActivity` registers the `redirectionUrl` deeplink.
- Added tests
- Added an Interface wrapper on `CodeVerifier` to be able to mock it on tests.
- Chroma tab should be able to load AuthorizationUrl
- Once the user has introduced email + …
> MBL-1169: Redirection step

- app/src/main/java/com/kickstarter/ui/extensions/ImageViewExt.kt
- app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/CommentsViewHolderViewModelTest.kt
- Crash caused due to sending empty string to `ImageView.loadCircleImage(url: String?)` empty paths. Picasso fails with an exception 
- If path for avatar.medium is empty, try to load avatar.small, if this is empty too send empty
- On `ImageView.loadCircleImage(url: String?)` check if the string is empty, if so load a local drawable
- On `ImageView.loadCircleImage(url: String?)` Added placeholder drawable
- See by the end of the video, how the placeholder is transitioned over the real avatar image, providing a way better user experience than suddenly appearing images
https://github.com/kickstarter/android-oss/assets/4083656/73ea967b-65b3-4023-92dc-6906670e36d5
| --- | --- |
|  |  |
- Cannot reproduce, but if you want to, modify the source code to always send `""` on  and launch the …
> MBL-1202: Crash on CommentsViewHolderViewModel

- app/src/main/java/com/kickstarter/viewmodels/TwoFactorViewModel.kt
Cleanup for TwoFactorViewModel to fix [this crash](https://console.firebase.google.com/u/1/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/6a6721723e30904ab3b6c99276d224e1?time=last-seven-days&types=crash&sessionEventKey=65CE6DE202B7000110ADF28BDECB56CF_1914367294431191217)
Knockin out bugs
Can't easily reproduce but:
- Made the intent passed into the viewmodel nonnull
- return an empty string if password or email from intent is null - if an empty string is passed down because there is no email or password in the intent, it will not allow login with an error message. doing the normal filtering for null values will cause there to be no reaction when the user taps submit and there wont be an error message. I figured empty string route is better
no …
> MBL-1182: Crash from rx chain returning null in TwoFactorViewModel.kt

- app/src/main/graphql/checkout.graphql
- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/models/CreatePaymentIntentInput.kt
- app/src/main/java/com/kickstarter/models/PaymentValidationResponse.kt
- app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
Added the last couple query and mutations for the post campaign checkout flow, also a renaming of a variable
They are needed for the flow for validations and actually doing the backing
Tested the mutation and query in staging, put them in the app and in the Apollo Client
Not implemented yet
[MBL-1165](https://kickstarter.atlassian.net/browse/MBL-1165)
[MBL-1165]: https://kickstarter.atlassian.net/browse/MBL-1165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-1165] Add Query and Mutation for Checkout Flow

- app/src/main/java/com/kickstarter/ui/adapters/RewardsAdapter.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardsFragmentViewModelTest.kt
We want the rewards carousel to show available rewards first and push unavailable rewards to the end of the list. 
Available rewards are more relevant
Adding additional sorting to the rewards list passed to the recyclerview
https://github.com/kickstarter/android-oss/assets/19390326/a3815ab0-d98e-4bd7-b8e1-abffd28478eb
Test that rewards carousel is properly sorting rewards on a live project that you have not backed yet
For an already backed project, test that rewards are also sorted in manage pledge -> choose different reward 
[MBL-1198: Reorder rewards so that unavailable ones show last](https://kickstarter.atlassian.net/browse/MBL-1198)
> MBL-1198: Reorder rewards so that unavailable ones show last

- app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.kt
[Crash appearing in crashlytics for index out of bounds in search view model](https://console.firebase.google.com/u/1/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/d6637e45ec6367d6c866fc464ca87b1e?time=last-seven-days&types=crash&sessionEventKey=65BB3C3401D6000156F1B67ACD784C05_1908965023381374439)
Could not reproduce but i gated the project list with an empty check to ensure we aren't trying to pull from an empty list. 
Since i could not reproduce this, just mess around in the search screen and make sure it doesn't crash, even if you try really really hard to break it 😅 
[MBL-1183: Crash caused by index out of bounds in SearchViewModel.kt](https://kickstarter.atlassian.net/browse/MBL-1183)
> MBL-1183: Crash caused by index out of bounds in SearchViewModel.kt

- app/src/main/java/com/kickstarter/libs/utils/extensions/IntentExt.kt
- app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/login/LoginToutScreen.kt
- app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
- app/src/main/java/com/kickstarter/viewmodels/LoginToutViewModel.kt
- app/src/test/java/com/kickstarter/libs/utils/extensions/IntentExtTest.kt
- app/src/test/java/com/kickstarter/ui/activities/compose/LoginToutScreenTest.kt
- app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.kt
- Unified buttons, `Log in with email` and `Sign up` now happen on the web formulary after OAuth2.0
FF ON
FF OFF
|  |  |
- With feature flag on, you will see only one button for `sign up or log in`
- With feature flag off, you will see the old flow with two separated buttons to `log in with email` and `sign up`
[MBL-1232](https://kickstarter.atlassian.net/browse/MBL-1232)
[MBL-1232]: https://kickstarter.atlassian.net/browse/MBL-1232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MBL-1232: Unify and verify sign up/log in buttons

- app/src/main/graphql/fragments.graphql
- app/src/main/java/com/kickstarter/models/Project.kt
Add two fields to the project model in graphql and in app:
-isPostCampaignEnabled
-postCampaignPledgingEnabled
These fields will be used to determine if the campaign will be allowed to go into the post campaign flow (only if both are true)
Added the fields to the fragments for graph, added them to the model for app model
Check the logs on staging for these fields:
(Look up the project Baconbaconbacon on staging for a true result)
`"isInPostCampaignPledgingPhase":true,"postCampaignPledgingEnabled":true,`
(Most projects will be false as its not enabled creator side yet)
`"isInPostCampaignPledgingPhase":false,"postCampaignPledgingEnabled":false,`
[MBL-1164](https://kickstarter.atlassian.net/browse/MBL-1164)
[MBL-1164]: https://kickstarter.atlassian.net/browse/MBL-1164?atlOrigin=eyJpIjoiNWRkNT …
> [MBL-1164] Add post campaign fields to project queries/mutations

- app/src/external/java/com/kickstarter/ExternalApplicationModule.java
- app/src/internal/java/com/kickstarter/InternalApplicationModule.java
- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
This PR is for Step 5 of https://kickstarter.atlassian.net/wiki/spaces/NT/pages/2699100255/Event+Attribution+Engineering+Plan+AKA+How+To+Wire+Up+a+New+GraphQL+Endpoint+on+Android#5.-In-KSApolloClientV2%2C-add-a-createAttributionEvent-method
Note this is dependent on merging in https://github.com/kickstarter/android-oss/pull/1969 as it has a dependency on [GraphQLTransformers.kt]
| --- | --- |
|  |  |
Nothing to QA at this time as this method is not called anywhere.
https://kickstarter.atlassian.net/browse/MBL-1252
> MBL-1252 Add a createAttributionEvent method to the Apollo client

- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsScreen.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ConfirmPledgeDetailsScreen.kt
- app/src/main/java/com/kickstarter/ui/compose/designsystem/KSStepper.kt
Adding the visuals for the pledge confirmation screen
Need to build al the screens for the flow so we can implement them
Used compose to build the screen based on designs:
https://www.figma.com/file/sFfDKxlJ2tiuq1xgIsaoiI/Late-Campaign-Backings?type=design&node-id=73-5019&mode=design&t=1RH9kA65yKmzeZ8X-4
Here are all the variations from the designs (all in preview code, for dark mode pull branch and view previews):
No Rewards:
Reward only/No Add-ons or Bonus Support:
Reward + Add-ons Only:
Reward + Bonus Support Only
Reward+Add-ons+Bonus Support:
Needs implementation
[MBL-1254](https://kickstarter.atlassian.net/browse/MBL-1254)
[MBL-1254]: https://kickstarter.atlassian.net/browse/MBL-1254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-1254] Add the confirm pledge screen and views

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
3 bug fixes in this PR :) 
1 - Navigate away to other apps while chrome tab is presented: 
- the chrome tab no longer gets killed when lost foreground.
- the activity task remains the parent, not a new one.
https://github.com/kickstarter/android-oss/assets/4083656/187a88af-64de-4d1a-8b9d-5a5874b51217
2 - Not related with OAuth bot found it by chance :) the issue is with verified deeplinks, the '*' wildcard regex, even though specified in the manifest as auto-verified, it had to manually by added as verified link, exchanged over `www` to not have to manually add it.
| Before 🐛 | 
https://github.com/kickstarter/android-oss/assets/4083656/54e14052-0e26-4020-a1eb-1020de560a41
After 🦋 |
https://github.com/kickstarter/android-oss/assets/4083656/05a7a959-a41a-4532-8a56-6b74414766a9
3 - During …
> MBL-1262: QA party bug fixes

- app/src/main/java/com/kickstarter/viewmodels/OAuthViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/OAuthViewModelTest.kt
- With the implementation of OAuth, the analytic events tied to the login button got lost. The website will send some, but lacking all the mobile specific context_properties such as build version/name device, OS version ... .
- In order to not lost events around login, it has been decided to sent the same event (-with the exact same properties), as the one that was tied to the non-OAuth login button. The event is tied to the successful response of the token &  user calls being persisted on the app.
- Analytic event
|  |  |
- Log in with OAuth (feature flag on), double check on Segment you get the Identify call **AND**  the button clicked with the context_page = 'log_in'
> [No-jira]: Analytic event added

- app/src/main/java/com/kickstarter/libs/AttributionEvents.kt
- app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectExt.kt
- app/src/main/java/com/kickstarter/ui/activities/DeepLinkActivity.kt
- app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
- app/src/main/java/com/kickstarter/viewmodels/DeepLinkViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/PrelaunchProjectViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/DeepLinkViewModelTest.kt
This PR is for Step 7 of the event attribution eng plan https://kickstarter.atlassian.net/wiki/spaces/NT/pages/2699100255/Event+Attribution+Engineering+Plan+AKA+How+To+Wire+Up+a+New+GraphQL+Endpoint+on+Android#7.-Send-event-from-Prelaunch-page-as-well
See PR for sending Project Page Viewed event on Project page for reference: https://github.com/kickstarter/android-oss/pull/1972
Because the Prelaunch page is a separate page from Project page on Android, also send the Project Page Viewed attribution event from the Prelaunch page.
No visible changes in app. Check segment to see new events being fired from Android -> backend -> segment: https://www.kickstarter.com/projects/paintbucketgames/the-darkest-files
In both logged in and logged out states, open
a prelaunch project from the discovery …
> MBL-1237 Send project page viewed event on Android on the prelaunch page

- app/src/main/graphql/checkout.graphql
- app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
Adding a new field to the setupintent mutation as requested by backend
They want to know when a payment method is added, why/where it was added
Graph was updated to have the new ENUM we can use to provide these fields
{"operationName":"CreateSetupIntent","variables":{"projectId":"UHJvamVjdC0xNzg5OTAyNzU3","setupIntentContext":"CROWDFUNDING_CHECKOUT"},"query":"mutation CreateSetupIntent($projectId: ID, $setupIntentContext: StripeIntentContextTypes) { createSetupIntent(input: {projectId: $projectId, setupIntentContext: $setupIntentContext}) { __typename clientSecret } }"}
{"operationName":"CreateSetupIntent","variables":{"setupIntentContext":"PROFILE_SETTINGS"},"query":"mutation CreateSetupIntent($projectId: ID, $setupIntentContext: StripeIntentContextTypes) { createSetupIntent(input: …
> [MBL-1283] Add SetupIntentContext to SetupIntent calls

- app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsScreen.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/CheckoutFlowViewModel.kt
- fix shipping display on add-ons screen (was using default shipping rule before, now its the rewards shipping rule)
- updating the shipping rule updates the prices on the add-ons screen (and reward selected shipping amount on confirm details screen)
- add-ons shipping are now properly displayed in the confirm details screen
- this filters the add-ons so only non shippable add-ons are displayed for a non shippable reward
Need to hammer out them bugs
https://github.com/kickstarter/android-oss/assets/7563288/419d981b-74cb-43a6-85be-d517deb57a0c
- Go to a project
- select a reward with shipping/add-ons
- select any add-ons
- if changing shipping rule, make sure add-on selection is cleared and new prices are reflected
- confirm prices add up correctly in confirm details screen
> [NoTicket] Fix add-ons shipping rule logic 

- app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/CheckoutFlowViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/usecases/CheckoutFlowViewModelTest.kt
- If there is no user logged in, when hitting continue button the `LoginFlow` it's triggered
- To pledge we need a logged in user
- Launching `LoginToutActivity` will take care of everything.
- Added test
https://github.com/kickstarter/android-oss/assets/4083656/e50ad44d-c4fe-42f7-9e4d-8009e5b727a6
|  |  |
- Logout -> Reach the `Confirm your pledge` screen on project `baconbaconbacon` -> hit continue -> Login flow is triggered -> hit continue -> navigates to following page.
[MBL-1292](https://kickstarter.atlassian.net/browse/MBL-1292)
[MBL-1292]: https://kickstarter.atlassian.net/browse/MBL-1292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MBL-1292: Launch LogIn user when Continue button clicked

- app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsScreen.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ConfirmPledgeDetailsScreen.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ProjectPledgeButtonAndFragmentContainer.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/CheckoutFlowViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/ConfirmDetailsViewModel.kt
Make it so that the default location is user based not project based by using the add-ons logic to populate the fields
It was always defaulting to the United States
See code
Go to a project that has shippable rewards
Confirm a reward selection that has no add-ons
see if the country matches your users country
[MBL-1300](https://kickstarter.atlassian.net/browse/MBL-1300)
[MBL-1300]: https://kickstarter.atlassian.net/browse/MBL-1300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-1300] Make confirm details screen use same default location logic as add-ons

- app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
- app/src/test/java/com/kickstarter/libs/SegmentTest.kt
- new property added `project_post_campaign_enabled`
- modified property `project_state` when late pledges activated should say `post_campaign`
Go to Segment, any event with project properties such as page viewed event for example, and look for the property
- When the project has **not** activated late pledges: 
- When the project has activated late pledges:
|  |  |
- navigate a bit to any random project, check segment events that the value of the property `project_post_campaign_enabled` = false
- navigate to the `baconbaconbacon` check segment events that the value of the property `project_post_campaign_enabled` = true
[MBL-1278](https://kickstarter.atlassian.net/browse/MBL-1278)
[MBL-1278]: https://kickstarter.atlassian.net/browse/MBL-1278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
> MBL-1258: Analytics, changes on project properties for Late Pledges

- app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectExt.kt
Make it so that the old view your pledge flow is shown when a user has already backed a late pledge project
Late pledges cannot be changed, and this flow just lets you view, not change your pledges
A boolean
https://github.com/kickstarter/android-oss/assets/7563288/0ae34805-3931-43b4-9a0d-0324aa5c0a25
In a project that is late pledge enabled, back the project and then come back to the project page
[MBL-1299](https://kickstarter.atlassian.net/browse/MBL-1299)
[MBL-1299]: https://kickstarter.atlassian.net/browse/MBL-1299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-1299] Make it so late pledge flow is not shown if user has backed the project

- app/src/main/graphql/checkout.graphql
- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
- app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/LatePledgeCheckoutViewModel.kt
Allows the user to add a payment method and use it in the late pledge checkout
Users may need to add new methods if their current one isnt accepted, etc
Borrowing stripe interactions from pledgefragment
https://github.com/kickstarter/android-oss/assets/7563288/9584eef2-7e47-4ccb-a1f8-2b9f98e13fd1
Go to any late pledge project and get to the checkout screen, from there, add a new payment method and attempt to use to check out.  Watch logs to see if all goes well.  If not, you should be presented with an error
[MBL-1303](https://kickstarter.atlassian.net/browse/MBL-1303)
[MBL-1303]: https://kickstarter.atlassian.net/browse/MBL-1303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-1303] Add adding payment method to the checkout screen

- app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/RewardsSelectionViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardsSelectionViewModelTest.kt
- Analytic events for rewards screen
- Track usage!
- `PageViewed` event triggered when late pledge rewards screen is expanded
- `CTA clicked` event triggered when the user selects a reward
- Page Viewed
- CTA clicked
|  |  |
- Browse to any of the projects with late pledges available, navigate to the rewards screen and select a reward, you should see the events triggered on Segment, before there was non.
[MBL-1278](https://kickstarter.atlassian.net/browse/MBL-1278)
[MBL-1278]: https://kickstarter.atlassian.net/browse/MBL-1278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MBL-1278: Analytic events for rewards

- app/src/main/graphql/checkout.graphql
- app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
- app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/LatePledgeCheckoutViewModel.kt
The payment method was not being saved when doing a full late pledge flow, but this pr adds a field to save the current payment method
If a user adds a new card they should be able to use it for any future purchases
There is a field called paymentSourceReusable and it needed to be set to true in this call
Go through a late pledge flow and add a new card during it, check your saved cards after a successful backing is created
> [Late Pledge Bugs] Add saving payment method to late pledge flow

- app/src/test/java/com/kickstarter/viewmodels/AddOnsViewModelTest.kt
Just the tests for AddOnsVM. Was running into a race condition with trying to replace subscriptions/disposables with flows so will include that change in a separate PR for now.
Original PR didn't include tests https://github.com/kickstarter/android-oss/pull/1980
https://kickstarter.atlassian.net/browse/MBL-1295
> MBL-1295 Test suite for AddOns view model

- app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
- app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
- app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/LatePledgeCheckoutViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/LatePledgeCheckoutViewModelTest.kt
- Added `PageViewed` when latePledge checkout screen presented
- Added `CTAClicked` when the user hits pledge on latePledge checkout screen with new `context_cta` = `late_pledge`
- Track usage and money collection
- Used same format & property as crowdfunding checkout analytics
- PageViewed
- CTAClicked
| --- | --- |
|  |  |
- Navigate to a project that has late pledges active, and complete a pledge, you should see on Segment both the `PageViewed` event and the `CTAClicked`
[MBL-1278](https://kickstarter.atlassian.net/browse/MBL-1278)
[MBL-1278]: https://kickstarter.atlassian.net/browse/MBL-1278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MBL-1278: Analytics on late pledge checkout screen

- app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
Somewhere in all the chaos of merging we duplicated the call to add a new payment method, so it was causing issues (being presented twice, continue adding multiple of the same card)
Bugs are bad and we want to squash them
Removed duplicate code
Go through the checkout flow and add a new card, make sure its only presented once and added only once
[MBL-1321](https://kickstarter.atlassian.net/browse/MBL-1321)
[MBL-1322](https://kickstarter.atlassian.net/browse/MBL-1322)
[MBL-1321]: https://kickstarter.atlassian.net/browse/MBL-1321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MBL-1322]: https://kickstarter.atlassian.net/browse/MBL-1322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-1321/1322] Fix payment sheet being presented multiple times

- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ConfirmPledgeDetailsScreen.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/ConfirmDetailsViewModel.kt
Fixes the following issues for bonus amount:
- Allow you to decrement back to 0 additional bonus support on a "No Reward" pledge
- Shows "No reward" pledges as such on the checkout screen list of items
- Reverts bonus amount back to 0 when selecting a new reward
Gotta get the flow to feel like it should
Small logic and display fixes, see code
https://github.com/kickstarter/android-oss/assets/7563288/8a4663f4-b645-40e1-ad14-0d87a9d812e7
Go to a late pledge project and test bonus support using a "no reward" pledge and confirm the checkout screen reflects this correctly
Switch rewards after setting a bonus amount and confirm it resets the bonus amount added
[MBL-1320](https://kickstarter.atlassian.net/browse/MBL-1320)
[MBL-1323](https://kickstarter.atlassian.net/browse/MBL-1323)
[MBL-1320]: …
> [MBL-1320/1323] Fix bonus amount issues

- app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
Fixed an issue where digital/non shippable rewards could select shippable add-ons
Also removed a duplicated add-on call
We dont want the shippables/non shippables mixed with rewards and add-ons
🧠 
Go to any late pledge campaign with digital rewards and add-ons as well as physical (bacon bacon bacon was recently changed to have this) and confirm when picking a digital reward only digital add-ons are presented and when picking a physical reward all add-ons are presented
[MBL-1342](https://kickstarter.atlassian.net/browse/MBL-1342)
[MBL-1342]: https://kickstarter.atlassian.net/browse/MBL-1342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-1342] Fix non-shippable rewards being able to select shippable add-ons

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/kickstarter/libs/utils/extensions/ContextExt.kt
- app/src/main/java/com/kickstarter/ui/IntentKey.kt
- app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/OAuthWebViewActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/WebViewActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/OAuthViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/OAuthViewModelTest.kt
- When default browser not Chrome, load a webview to handle OAuth.
- The issue when default browser not Chrome, customTabs behave differently: redirection does not take place though `onNewIntent`, and tab was never dismissed.
https://github.com/kickstarter/android-oss/assets/4083656/a40b58fe-7a10-45be-885c-84ae7445b757
|  |  |
- Install any other browser (Firefox, Opera, Duck Duck Go, Arc ...) and try to log in.
- Have only Chrome and log in, just to make sure all keeps working as usual.
- Try logIn with facebook (fyi only works in production environment), just to make sure all keeps working as usual.
[MBL-1286](https://kickstarter.atlassian.net/browse/MBL-1286)
[MBL-1286]: https://kickstarter.atlassian.net/browse/MBL-1286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …
> MBL-1286: OAuth when default browser not chrome

- app/src/main/res/layout/toast_error.xml
Changed ImageView to AppCompatImageView in order to tint the alert icon vector a white color
"Something went wrong" alert icon was black instead of white because white tint was not properly applied
| --- | --- |
| ![Screenshot_20240415-105200](https://github.com/kickstarter/android-oss/assets/129205442/f497bf26-a4b5-4ba1-85bc-2142bb4d8876) | ![Screenshot_20240415-141134](https://github.com/kickstarter/android-oss/assets/129205442/1a14ac98-8e02-40b5-adb7-52717a7a4c11) |
1. Go through a PBC flow until you get to the confirm pledge details screen
2. Turn on airplane mode
3. Tap "Pledge"
4. Verify that the alert icon on "something went wrong" is white
https://kickstarter.atlassian.net/browse/MBL-1326
> MBL-1324 Fix icon color on "something went wrong" alert

- app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
There is a bug in production for late pledges where if none of the projects rewards are shippable we would not pull add-ons so you could not select any
There are lots of projects with just digital rewards that also have add-ons
Make it so there is always a default shipping rule for pulling add-ons, even if it is a blank one
Staging:
https://github.com/kickstarter/android-oss/assets/7563288/378c091f-1ac7-4129-8c5d-e978c240b7ea
Production:
https://github.com/kickstarter/android-oss/assets/7563288/90740cd8-cf9c-4aaa-9dbd-b9cae8b7fc58
On Production:
Go to the "Master of Realms" project (currently collecting late pledges) and select a reward with add-ons.  Add-ons should be displayed and selectable
On Staging:
Go to any testable late pledge project and confirm add-ons work as expected
> [HOTFIX] Fix issue where add-ons were not displayed if non of the rewards were shippable

- app/src/main/java/com/kickstarter/viewmodels/projectpage/CheckoutFlowViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/usecases/CheckoutFlowViewModelTest.kt
When user logs in within late pledges checkout, after login flow:
-  before: user had to hit continue button to move forward a second time
- now: navigation to checkout screen without user interaction
- One less user interaction required
- smoother checkout process
https://github.com/kickstarter/android-oss/assets/4083656/2029d330-d73e-4bb3-88bf-6c32d7ffda3e
|  |  |
- Make sure you are logged out, go to a project with late pledges active, select reward, on confirm screen hit continue, the login flow will be presented, once successfully logged in the checkout screen will be presented.
[MBL-1343](https://kickstarter.atlassian.net/browse/MBL-1343)
[MBL-1343]: https://kickstarter.atlassian.net/browse/MBL-1343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …
> MBL-1343: Incorrect routing after login

- app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/LatePledgeCheckoutViewModel.kt
Change it so that instead of creating a payment intent and then using that to set up a card via stripe (which would charge immediately) we are using a setupintent and saving the card to backend, similar to what we do in the account card screen.  We then refresh the users stored cards so they show on the list.
When doing the payment intent way it would charge cards immediately, causing double charges via stripe
Changed the code to save the new cards instead of have a temporary copy via payment intent
1) Go to a project that is accepting late pledges ("testing conversion" on staging)
2) Proceed to the checkout screen
3) add a new card
4) proceed with checkout with the new card
5) Confirm card was only charged once (this may require backend help) …
> [MBL-1383] Update adding new payment method flow in late pledge flow

- app/src/main/java/com/kickstarter/viewmodels/projectpage/RewardsSelectionViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardsSelectionViewModelTest.kt
- Do not show unavailable rewards on late pledges rewards carousel
- filtering the rewards by `isAvailable`
https://github.com/kickstarter/android-oss/assets/4083656/5d7e5c48-2262-497d-b437-bab7235b6db4
|  |  |
- Go to project  [The Captain's Logbook: 5E High Seas Adventure & Shipbuilding](https://www.kickstarter.com/projects/captainslogbook/the-captains-logbook-a-journey-of-adventures-for-5e) , before you could select the reward "Access to the pledge manager" which was unavailable, now rewards not available are not presented on the carousel
[MBL-1380](https://kickstarter.atlassian.net/browse/MBL-1380)
[MBL-1380]: https://kickstarter.atlassian.net/browse/MBL-1380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MBL-1380: Reward is showing as available for late pledges despite not being available

- app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/LatePledgeCheckoutViewModel.kt
- After failing 3DS challenge no new card UI is added.
- Better user experience
- Wait until `is PaymentSheetResult.Completed` callback is received from the `PaymentSheet` in `onPaymentSheetResult` before updating any UI/execute any network call.
https://github.com/kickstarter/android-oss/assets/4083656/ab1a9d58-7fda-4541-91c2-e87b5155321e
|  |  |
- On a late pledge project, in staging you can find : [this project](https://staging.kickstarter.com/projects/sfdasf/birbs-in-canada) or [this one](https://staging.kickstarter.com/projects/latepledgetestparty/testing-closing-a-late-pledge-proj)
- Add a new 3DS payment method, that requires the challenge to be completed, [here stripe cards](https://docs.stripe.com/testing#three-ds-cards) to test, but in the video I use `4000000000003220` 
- Fail …
> MBL-1340: 3DS payment method UI removed on error

- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsScreen.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ConfirmPledgeDetailsScreen.kt
Fix an issue where shipping location would not be presented correctly after being changed
We want the flow to feel seamless and have correct information displayed
By adding they key to the remember value it will not reevaluate the variable whenever the input is changed, allowing it to show the correct information on first being presented
https://github.com/kickstarter/android-oss/assets/7563288/cd8aea94-55f8-4ee7-a2f7-3da9efad2c2e
Go to a late pledge flow and go through the add-ons screen, changing the shipping location, make sure it is preserved throughout the flow no matter where it was changed
[MBL-1335](https://kickstarter.atlassian.net/browse/MBL-1335)
[MBL-1335]: https://kickstarter.atlassian.net/browse/MBL-1335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …
> [MBL-1335] Fix issue where shipping location was not preserved after being changed

- app/src/main/java/com/kickstarter/libs/PushNotifications.java
- When poor connectivity or no connectvity the request fails, no generating bitmap
- Added error Glide loading callback
- Return placeholder bitmap if all previous fails
|  |  |
- Not able to reproduce in real life scenario, but try loose connectivity, go to internal tools -> push notifications and filter by warning on logcat, you will see nothing crashes. The logcat screenshot with Glide warning was produced this way 
[MBL-1417](https://kickstarter.atlassian.net/browse/MBL-1417)
[MBL-1417]: https://kickstarter.atlassian.net/browse/MBL-1417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MBL-1417: Crash from PushNotifications.fetchBitmap

- app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/LatePledgeCheckoutViewModel.kt
- app/src/test/java/com/kickstarter/ui/activities/compose/LoginToutScreenTest.kt
Add a trigger for the 3ds flow for stripe in the post campaign flow
Due to other recent changes stripe was not automatically showing the 3ds challenge screen to users in post campaign flow
Observe the payment intent being passed back to us from stripe and react accordingly.
1) Go to a project currently in post campaign phase
2) Select rewards/add-ons and shipping location
3) Either add or use an existing 3ds card for the payment
4) Make sure you are presented the 3ds challenge
5) Confirm that there was a successful backing (may need backend support to know if payment was successful)
[MBL-1530](https://kickstarter.atlassian.net/browse/MBL-1530)
[MBL-1530]: https://kickstarter.atlassian.net/browse/MBL-1530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …
> [MBL-1530] Add trigger for 3ds flow for post campaign payments

- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
A description of the change.
First time: adding a new card (it is selected and at the top of the list as expected)
Second time: adding the card via link again (shouldn't do anything, may want to introduce user messaging)
See link for video:
https://kickstarter.slack.com/archives/C01PNFFUXBR/p1718651586663299?thread_ts=1718651173.743469&cid=C01PNFFUXBR
1) Go to a late pledge project
2) Go to the checkout screen
3) Click add new payment method
Case 1:  New payment method
4a) Add a payment method you dont already have on kickstarter via link
5) Confirm the screen updated with the new payment method selected
Case 2: Existing payment method
4b) Add a payment method you DO already have …
> [MBL-1535] Fix bug when adding existing payment method it unselects a card

- app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectPageViewModelTest.kt
Make it so the play button will always be based on the current project
When entering the project page from discovery we do not have the video as part of the apollo return, so the initial project would not have it so the value would update as expected. On search the video is part of the project because we are still using the api client for that call so the value would not update as expected because its value did not change after initialization.
remove the distinct call until we can switch this to apollo client
Go to a project and confirm its video is working (do this both from discovery and search).  Search was where the issue was, not any individual project.
Ticket mentioned the project Misty Valley on production if you want to test that directly. …
> [MBL-1541] Update viewmodel to always update if the play button is visible on project videos

- app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewActivity.kt
- app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreen.kt
- app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/viewmodel/PledgedProjectsOverviewViewModel.kt
- app/src/main/java/com/kickstarter/libs/MessagePreviousScreenType.kt
- app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
- app/src/test/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreenTest.kt
- app/src/test/java/com/kickstarter/features/pledgedprojectsoverview/viewmodel/PledgedProjectsOverviewViewModelTest.kt
Added message creator navigations to the PPO card
PPO work
When message creator is tapped, performs a network call to grab the project/backing and passes this on to the message activity. 
https://github.com/kickstarter/android-oss/assets/19390326/3080ad16-36cb-4b73-9ac2-47cbb7d981e4
Tested using mocked data, so you will need to grab the slug of one of your backed projects. in the `PledgedProjectsOverviewViewModel`, replace the ppo card list:
with your slug:
```private val ppoCards = MutableStateFlow<PagingData<PPOCardDataMock>>(PagingData.from(listOf(PPOCardDataMock(projectSlug = "insert slug here"))))```
inserting your own slug
to test errors, leave the slug as an empty string or pass in a random string of characters
[MBL-1474: Message creator navigation](Trello link)
> MBL-1474: PPO Message creator navigation

- app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewActivity.kt
- app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreen.kt
- app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/viewmodel/PledgedProjectsOverviewViewModel.kt
- app/src/main/java/com/kickstarter/ui/compose/designsystem/KSAlerts.kt
- app/src/test/java/com/kickstarter/features/pledgedprojectsoverview/viewmodel/PledgedProjectsOverviewViewModelTest.kt
Added the visuals and a way to call the visuals for an error message for PPO
I also updated some of the colors for these to match the newer standards
There can be various times we need to display an error to the user
In this case I leverage that we can intervep the snackbarhost data and use the actionLabel in this case to change which visuals are shown
Alternating between an error and heads up message type
https://github.com/user-attachments/assets/39a03479-610b-4aee-afbe-0a0f9f7ff065
You will need to make a way to trigger these calls (i made the back action invoke a method in the viewmodel to display an error and normal message alternatingly)
[MBL-1480](https://kickstarter.atlassian.net/browse/MBL-1480)
[MBL-1480]: https://kickstarter.atlassian.net/browse/MBL-1480?atlOrigin=eyJpIjoiNWRkNT …
> [MBL-1480] Add error snackbar visuals/a way to call them for PPO

- app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/BackingDetailsActivity.kt
- app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewActivity.kt
- app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreen.kt
- app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
- app/src/main/java/com/kickstarter/ui/IntentKey.kt
- app/src/main/java/com/kickstarter/ui/activities/ReportProjectActivity.kt
- app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
- app/src/test/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreenTest.kt
Added the primary action button actions for take survey and confirm address PPO cards
Both should open the webview and should refresh when you leave sad webview to return to the PPO Page
Adjusted some code to make all Primary Button Actions done on the activity level}
Adjusted the result launcher and finish code to allow the PPO Activity to know to refresh
https://github.com/user-attachments/assets/d8c55425-fa61-4183-9cf5-52474562741c
You should be able to click the "Take Survey" or "Edit" (Address) buttons to be taken to the Webview.  From there whether or not you made any changes when you leave the webview it should refresh the PPO list and either remove cards if the action was successful or display them still if action is still needed. …
> [MBL-1478][MBL-1482] Add Primary Action button actions for Take Survey and Confirm Address

- app/build.gradle
Updating our use of the play:core library for reviews to the more dedicated play:review-ktx library.
This library is not going to be allowed as its not compatible for android 14+ which all libraries must be by end of august
A simnple library swap, no code updates needed (its backwards compatible)
Make sure that the review prompt can still show up and works correctly
> [No Ticket] Update review library from play:core to play:review-ktx library

- app/src/main/java/com/kickstarter/ui/extensions/ImageViewExt.kt
- app/src/main/java/com/kickstarter/ui/views/ImageWithCaptionView.kt
Downsample images based on screen resolution (at least) so images cant cache too much space
Projects with primarily webp were causing crashes in the app
Added a size override and downsampling strategy for glide for WEBP
Project on prod and staging to test with: Dogs with Jobs
Go to the Dogs with Jobs project and make sure all images load and look good
[MBL-1650](https://kickstarter.atlassian.net/browse/MBL-1650)
[MBL-1650]: https://kickstarter.atlassian.net/browse/MBL-1650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-1650] Fix crashes with large WEBP images

- app/src/main/java/com/kickstarter/ui/activities/ProfileActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/ProfileViewModel.kt
When entering the profile with no projects backed it was possible for the layout manager to be assigned outside of the ui thread, so wrapped teh call around the adapter with a runOnUiThread call.
Users were crashing on this page and in testing this removed the crashes
-Create a new profile/log into one with no backed projects
-go to the profile page
-confirm no crashes
-repeat
> [BugFix] Add ui thread call and some null safety to avoid profile crash

- app/src/main/graphql/fragments.graphql
- app/src/main/java/com/kickstarter/libs/utils/extensions/ConfigExtension.kt
- app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
- app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ProjectPledgeButtonAndFragmentContainer.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/RewardCarouselScreen.kt
- app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
- app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/LatePledgeCheckoutViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/RewardsSelectionViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/usecases/GetShippingRulesUseCase.kt
- app/src/test/java/com/kickstarter/viewmodels/AddOnsViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/LatePledgeCheckoutViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardsSelectionViewModelTest.kt
Rewards filtered by the selected location on shipping rules
Better user experience
`GetShippingRulesUseCase` now returns as part of the state the rewards filtered by given location
- Crowdfunding
https://github.com/user-attachments/assets/2184b7f0-91c4-4dce-bdd5-a372c07f76db
- Late pledges
https://github.com/user-attachments/assets/6157c16e-4e19-448b-abd8-d509202dd932
| --- | --- |
|  |  |
- Ideally find a project that has both shipping wordlwide and restricted, or a restricted project outside of your default location (default location based on IP). If you cannot find any as was my case try to find a project with restricted locations, then hardcode your default location and run the app, on the initial load you should get ONLY those rewards shipping your hardcoded location plus …
> MBL-1576: Filter rewards by location

- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsScreen.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ProjectPledgeButtonAndFragmentContainer.kt
- app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
- app/src/main/java/com/kickstarter/ui/views/compose/checkout/BonusSupport.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
Added some visual distinction between add-ons for no rewards vs rewards with no add-ons
We want to user to feel like the experience is relevant to what they picked
🧠 
Late Pledge:
https://github.com/user-attachments/assets/7111fd30-928c-410b-bf84-888ec6a4f4a2
Normal Campaign:
https://github.com/user-attachments/assets/2a4a30ef-7c65-44e6-8b3c-ce968ec23d43
Go to a project (late or currently running doesnt matter)
Confirm that the add-ons screen shows the appropriate visuals for the given selection (no reward, reward with add-ons, reward without add-ons)
[MBL-1583](https://kickstarter.atlassian.net/browse/MBL-1583)
[MBL-1584](https://kickstarter.atlassian.net/browse/MBL-1584)
[MBL-1583]: https://kickstarter.atlassian.net/browse/MBL-1583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
> MBL[1583/1584] Add bonus support visual treatments based on selected reward

- app/src/main/graphql/pledgeProjectsOverview.graphql
- app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/data/PPOCard.kt
- app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/data/PPOCardFactory.kt
- app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PPOCardView.kt
- app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreen.kt
- app/src/test/java/com/kickstarter/ui/activities/compose/PPOCardViewKtTest.kt
- Changed the way we are displaying the red notification dot on a PPO card to be determined by card type
- Also cleaned up unused disabled PPO cards since we are no longer doing pull to refresh to dismiss a card
PPO! 
Red dot is shown if the card type is tier 1.
Make sure any ppo cards displayed had a red dot in the upper right corner
[MBL-1661: Red notification dot in top right corner of PPO tier 1 alert cards](https://kickstarter.atlassian.net/browse/MBL-1661)
[MBL-1666: Remove unused composables](https://kickstarter.atlassian.net/browse/MBL-1666)
> MBL-1661 & MBL-1666: Red notification dot in top right corner of PPO tier 1 alert cards & Remove unused composables

- app/src/main/java/com/kickstarter/libs/utils/RewardViewUtils.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsScreen.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ProjectPledgeButtonAndFragmentContainer.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/RewardCarouselScreen.kt
- app/src/main/java/com/kickstarter/ui/fragments/CrowdfundCheckoutFragment.kt
- app/src/main/java/com/kickstarter/ui/views/compose/checkout/PledgeItemizedDetails.kt
Adding an estimated shipping visual to the checkout screen for pledge flows
We need to show the user at checkout what their estimated shipping will be
🧠 
Campaign checkout:
Late pledge checkout:
Go to a project with estimated shipping (both late pledge and normal) and confirm this view is shown on both versions.  Confirm that the non late pledge does NOT have the immediate charge text near the pledge button
[MBL-1574](https://kickstarter.atlassian.net/browse/MBL-1574)
[MBL-1574]: https://kickstarter.atlassian.net/browse/MBL-1574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-1574] Add estimated shipping visuals to checkout screens

- app/build.gradle
- app/src/main/java/com/kickstarter/libs/ApiCapabilities.java
- app/src/main/java/com/kickstarter/libs/utils/ViewUtils.java
- app/src/main/java/com/kickstarter/libs/utils/extensions/StringExt.kt
- app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
- app/src/main/java/com/kickstarter/ui/viewholders/ThanksShareViewHolder.kt
- app/src/test/java/com/kickstarter/KSRobolectricGradleTestRunner.java
- app/src/test/java/com/kickstarter/viewmodels/usecases/SendThirdPartyEventUseCaseTest.kt
- app/src/test/java/com/kickstarter/viewmodels/usecases/SendThirdPartyEventUseCaseV2Test.kt
Bumping the min sdk version from 23->24
Android 15 devices will require the app minimum to be 24 in order to be installed.  Currently this is the only change needed for kickstarter app to run on android 15, other changes can come later, but this one is required.
see [doc](https://kickstarter.atlassian.net/wiki/spaces/NT/pages/3075538945/Android+15+Spike)
Update the min version in the gradle file and robolectric files and remove any unneeded version checks with min bump
> [NoTicket] Bump up the min sdk version from 23 to 24

- app/src/main/java/com/kickstarter/libs/utils/RewardViewUtils.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsContainer.kt
- Rewards shipping globally where not showing the shipping range
- no location.id matching for this case, as the only shipping rule available id is "1", with name "Rest of the world"
|  |  |
- Go to [this project for crowdfund ](https://staging.kickstarter.com/projects/isabel-martin/sustainable-20-community-space) there is a globally shipping reward with range $1-10. There is a restricted reward shipping only to Canada ($5-9) and United States ($2-7)
- Go to [this project for late pledges](https://staging.kickstarter.com/projects/isabel-martin/dubstep-restoration-video-game)  there is a globally shipping reward with range $1-10. There is a restricted reward shipping only to Canada/ Denmark and Greece with different shippings ranges
Story 📖 …
> MBL-1585: small touch ups

- app/src/main/java/com/kickstarter/ui/activities/PrivacyActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/PrivacyViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/PrivacyViewModelTest.kt
Updating Privacy Viewmodel to RX2
Need to get rid of RX1
Go to the privacy activity and confirm everything works as expected
[MBL-820](https://kickstarter.atlassian.net/browse/MBL-820)
[MBL-820]: https://kickstarter.atlassian.net/browse/MBL-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-820] Update Privacy viewmodel to RX2

- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsContainer.kt
- After selecting addOns, if an scroll event takes place, the UI forgot the state
| Before 🐛 |
https://github.com/user-attachments/assets/7a4bf3a1-cc3f-4e19-949e-c7b8fdfc7796
| After 🦋 |
https://github.com/user-attachments/assets/8aef8e18-2302-456b-b222-5507031c2598
| --- | --- |
|  |  |
- Go to any project with several addOns, scroll to the bottom, select addOns, scroll up and down a few times, the selected number of addOns should state the same.
[MBL-1696](https://kickstarter.atlassian.net/browse/MBL-1696)
[MBL-1696]: https://kickstarter.atlassian.net/browse/MBL-1696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MBL-1696: AddOns add button lost state

- app/src/main/java/com/kickstarter/libs/utils/extensions/PledgeDataExt.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/CrowdfundCheckoutViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/CrowdfundCheckoutViewModelTest.kt
When updating your payment method or reward selection the add-ons IDs were not being flattened for the quantity they had
This was causing a bug where it would not correctly update the pledge
Made it so that instead of a single item in the reward ids list we send to the backend they get flattened ex:
Reward with ID X quantity 1 selected
Add-On with ID Y with quantity 2 selected 
would result in the ID list being < X, Y, Y > 
Update a reward selection with more add-ons and make sure that both the total amount, shipping amount, etc are updated correctly on the summary screen/the information sent to the backend is correct
[MBL-1693](https://kickstarter.atlassian.net/browse/MBL-1693)
[MBL-1693]: https://kickstarter.atlassian.net/browse/MBL-1693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …
> [MBL-1693] Fix add-ons not being flattened for update payment/reward flows

- app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PPOCardView.kt
- app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewActivity.kt
- app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreen.kt
A couple UI tweaks:
-Made it so PPO can use the native animations for pull to refresh and loading states
- Adjusted line heights so one line projets will have the price more close to the bottom of the name
It did not really indicate to the user that a refresh was happening and the spacing for projects looked a little weird.
Instead of our own loading indicator, use the pull to refresh composable that also uses the refresh state to know when to be shown to the user.  Made it so instead of filling space the space between the pledge amount and the name were fixed
https://github.com/user-attachments/assets/208b797d-0eaf-4f6a-9bb3-db5860f61f7f
Go to PPO screen and pull to refresh
> [No Ticket] UI tweaks for PPO

- app/src/main/graphql/fragments.graphql
- app/src/main/java/com/kickstarter/services/interceptors/WebRequestInterceptor.kt
Adjust PPO query to pull the correct endpoint to make it so the user is logged in upon accessing the page
It was asking the user to log in instead of just going to the page
Removed a staging header being added and adjust the PPO query to use a specific tab with creds
https://github.com/user-attachments/assets/9693f020-e3e5-4fe7-ba0b-c1b7c03a0eaa
Go to the PPO page with cards, click on the card/survey/edit address button and confirm the page loads correctly (doesnt ask you to log in)
[MBL-1726](https://kickstarter.atlassian.net/browse/MBL-1726)
[MBL-1726]: https://kickstarter.atlassian.net/browse/MBL-1726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-1726] Make PPO webview use correct endpoint and logs user in automatically

- app/src/main/java/com/kickstarter/viewmodels/projectpage/RewardsSelectionViewModel.kt
Fixes a crash where the currentProjectData was not initialize but being used when a late pledge project was being used for a fix pledge flow
The app would crash when entering the fix payment flow from PPO or Activity
Check if the variable is initialized before using it for analytics
-Sign in on an account that has errored payments on one or more pledged (ppotest1@test.com)
-Go to the activity or PPO flow and click the fix payment button
-App should not crash
[MBL-1758](https://kickstarter.atlassian.net/browse/MBL-1758)
[MBL-1758]: https://kickstarter.atlassian.net/browse/MBL-1758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-1758] Only send event for rewards carousel if the currentProjectData is available

- app/src/main/java/com/kickstarter/libs/utils/extensions/UriExt.kt
- app/src/test/java/com/kickstarter/viewmodels/DeepLinkViewModelTest.kt
Added the URIs for our URI parser to recognize and open deeplinsk for project surveys for redeem/pledge_redemption
These links will need to be supported in order to use the new web pages for pledge redemption
Added the link patters for 
- .../projects/:creator_param/:project_param/backing/pledge_redemption
- ...//projects/:creator_param/:project_param/backing/redeem
in the uri parser 
-Have an account with a pledge redemption backing or create a project for testing and back it
- Have the project send pledge redemption surveys
- confirm the deeplinks work
[MBL-1763](https://kickstarter.atlassian.net/browse/MBL-1763)
[MBL-1763]: https://kickstarter.atlassian.net/browse/MBL-1763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MBL-1763] add redeem and pledge redemption survey deeplinks

- app/src/main/java/com/kickstarter/ui/fragments/projectpage/FrequentlyAskedQuestionFragment.kt
crash here: https://console.firebase.google.com/u/1/project/android-external-release/crashlytics/app/android:com.kickstarter.kickstarter/issues/9ff037ba471aadfd3bdbac8ed439cb02?time=last-seven-days&types=crash&sessionEventKey=6743C9FB036D00014AA402B9083E5BDC_2019459365517263006
Project object is huge, but we dont need that many fields
just reduced the project payload to a few fields
Go to project FAQ and send a message to the creator, no crashes or issues should happen. do this with backed projects and non-backed projects
no-jira
> [no-jira] Fix transaction too large crash on send creator message from project FAQ

- build.gradle
Upgrade gradle plugin to be compatible win sdk 35
To delete a warning on the build and make it compatible with sdk 35
Upgrade gradle plugin version from 8.4.0 to 8.6.1
> Upgrade gradle plugin to be compatible win sdk 35

- app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/MessagesActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
- app/src/main/res/layout/messages_layout.xml
Update layout root padding based on IME insets in `MessagesActivity`
Currently, when the device keyboards opens it covers the messaging input field.
Set the bottom padding of the layout's root view based on IME insets to keep the input field visible.
This is the same logic as in `WindowInsetsUtil.manageEdgeToEdge()` with a slight adjustment to handle the keyboard.
| --- | --- |
| [Video](https://github.com/user-attachments/assets/b27d0059-b106-4f8a-b470-b49249d79222) | [Video](https://github.com/user-attachments/assets/ad37e1fb-8108-42e1-b088-05329fbda124) |
> [MBL-1942] Hotfix for keyboard covering input fields in Messages, Comments, & Replies

- app/src/main/java/com/kickstarter/ui/activities/MessageCreatorActivity.kt
Fix hidden `Send` button in `MessageCreatorActivity`.
When attempting to message a Creator (when not backing their Project), the keyboard hides the Send button. Users must dismiss the keyboard to send the message. This is a regression caused by Android 15 forced edge-to-edge. 
Update layout root padding based on IME insets.
> MBL-1952 Add dynamic root padding to Message Creator screen

- app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
- app/src/main/java/com/kickstarter/ui/fragments/CrowdfundCheckoutFragment.kt
- app/src/main/java/com/kickstarter/ui/views/compose/checkout/CollectionPlan.kt
- app/src/main/java/com/kickstarter/ui/views/compose/checkout/PaymentSchedule.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/CrowdfundCheckoutViewModel.kt
New PLOT checkout UI has a "terms of use hyperlink", we want to open the web page when a user taps this link. Also discovered a bug on checkout screen where the disclaimer and accountability hyperlinks were not hooked up. 
For the new PLOT UI, but we also need all of the hyperlinks to work. 
This PR also fixes an issue discovered where the other hyperlinks on the crowdfund checkout are not working. Using the same logic as in the ProjectPageActivity to open the accountability and disclaimer hyperlinks. 
Test regular crowdfund checkout, as well as PLOT with a pledge that meets the minimum PLOT threshold. Expand the PLOT ui and tap terms of use, should open the terms of use page on web.
Test the other hyperlinks on the screen and make sure they link to their correct respective pages. …
> MBL-1956: Terms of use hyperlink in checkout screen

- app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
On the disclaimer text on the **Manage your pledge screen** for projects with PLOT selected the text should be:
"You have selected Pledge Over Time. If the project reaches its funding goal, the first charge of **%{amount}** will be collected on **%{date}**"
The amount and date should have **BOLD** style
Right now the amount has no BOLD style
Used View ViewUtils.addBoldSpa to add the bold style to the corresponding text on the BakingFragment
| Before 🐛 |
|After 🦋 |
|  |  |
Using test credentials:
Email: [jluna+test01@arkusnexus.com](mailto:jluna+test01@arkusnexus.com)
Password: qwertyuiop
- Go to the profile and select: [Purple Tarot Community Space](https://staging.kickstarter.com/projects/1768690592/purple-tarot-community-space
)
- Go to Manage Your Pledge
- Text should be: "You have …
> MBL-2047 Bold styling not showing on first charge amount for PLOT

- app/src/main/java/com/kickstarter/services/interceptors/GraphQLInterceptor.kt
* Increase of 429 errors detected while rolling out Android 3.28.0. Specially around GraphQL
The rule in graphql_authed was triggered when receiving a header with the word “token “ without any token value associated. (@match_discriminator:token) → [Datadog query](https://app.datadoghq.com/logs?query=%40http.useragent%3A%22Kickstarter%20Android%20Mobile%20Variant%2FexternalRelease%20Code%2F2014150930%20Version%2F3.28.0%22%20source%3Arack_attack%20%40match_discriminator%3Atoken&agg_m=count&agg_m_source=base&agg_q=%40match&agg_q_source=base&agg_t=count&analyticsOptions=%5B%22bars%22%2C%22dog_classic%22%2Cnull%2Cnull%2C%22value%22%5D&clustering_pattern_field_path=message&cols=host%2Cservice%2C%40match&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&top_n=1 …
> MBL-2055: Avoid adding the Authorization header if the token is empty

- app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PPOCardView.kt
- app/src/main/res/drawable/ic_envelope.xml
Changed message creator CTA text to envelope icon button
Cosmetic updates to PPO cards
short and long creator name:
- Every ppo card should have a envelop icon, matching the screenshots above. 
- Tapping the icon opens message creator screen
- try to make sure the row is formatted correctly if creator name is very long
[MBL-2038: [Phase 1] UI Updates: Mail icon for message creator](https://kickstarter.atlassian.net/browse/MBL-2038)
> MBL-2038: [Phase 1] UI Updates: Mail icon for message creator

- app/src/main/java/com/kickstarter/ui/compose/designsystem/KSTypographyV2.kt
Reverted the font used in kSTypographyV2.kt from "Inter" back to "Roboto" to ensure proper rendering of font weights, particularly bold text.
The "Inter" font was causing issues with font weights—most notably, the bold style was not rendering as expected. Switching back to "Roboto" restores the intended visual consistency and reliability across our typography components.
- Updated the kSTypographyV2.kt file to remove reference the "Inter" font.
- Verified that all font weights, especially bold, are rendered correctly after the change.
- Ensured that the change did not introduce any regressions in other parts of the application using the font component.
- Open the application and navigate to DesignSystemScreen where the font component …
> Go back to roboto

- app/src/main/java/com/kickstarter/ui/compose/designsystem/KSProjectCards.kt
- app/src/main/java/com/kickstarter/ui/fragments/projectpage/ui/SimilarProjectsComponent.kt
Fix SPC padding and restore Card ripple on click
UI/UX
Update padding dimensions in the SPC title row, pager, and card placeholder box.
Material Cards in `1.6.2` support `onClick` behind an `ExperimentalMaterialApi` annotation, but this property is stable in Material3. Leverage it here to enable a ripple on click.
| --- | --- |
| <img src="https://github.com/user-attachments/assets/8a929244-8393-4f4e-97f2-7a26e7664ab6" width="256"/> | <img src="https://github.com/user-attachments/assets/619f658f-15bb-4ac0-af93-2d3e4288f01b" width="256"/> |
https://github.com/user-attachments/assets/cd465661-ab38-46d9-9a9c-c4b0f0174757
https://github.com/user-attachments/assets/92117263-aeb3-4265-ba12-0d8e02ae4c4b
Normal usage
[\[MBL-2251\] SPC & project card polish - …
> MBL-2251: SPC & project card polish

- .gitmodules
- Makefile
- Remove submodule for material design icons
- No longer needed!!!
- No user facing changes is jut CI stuff
| --- | --- |
|  |  |
- if you want to do QA over this branch I'll suggest
- -  deinit the submodule -> `git submodule deinit -f vendor/material-design-icons`
- - remove the folder from your local environment -> `git rm -f vendor/material-design-icons`
[MBL-2254](https://kickstarter.atlassian.net/browse/MBL-2254)
[MBL-2254]: https://kickstarter.atlassian.net/browse/MBL-2254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MBL-2254: remove submodule for material-design-icons

- app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectExt.kt
Include the web url in "reduced" Project objects.
Ensure that users of a reduced Project object have access to the web url. For example, when such a Project object is sent to `ThanksActivity`, that web project url is used in the Share text.
Include a Project's `webProjectUrl()` in its reduced form. This change specifically fixes a bug where the web url of a Project is missing from the Share text generated in ThanksActivity.
If the entry points to ThanksActivity are likely to change, or this fix somehow does not cover all entry points, a more complete fix targeting `ThanksShareViewHolderViewModel` can be found in [another PR.](https://github.com/kickstarter/android-oss/pull/2284)
| --- | --- |
| Missing Project web url  | Including Project web url |
| <img …
> MBL-890: Include the web url in "reduced" Project objects

- app/src/main/graphql/project.graphql
- app/src/main/graphql/rewards.graphql
- app/src/main/java/com/kickstarter/mock/services/MockApolloClientV2.kt
- app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/AddOnsViewModelTest.kt
There was an error on some checkouts when selecting add-ons. This was cause previously when this was implemented the Rewards didn't have the AllowedAddOns.
Fixes the issue where users were able to select add-ons that were not allowed for the selected reward, which caused checkout errors later in the pledge flow.
Previously, when a user selected a reward, all available add-ons were loaded, regardless of whether they were permitted for that specific reward. This caused situations where a user could select an invalid reward + add-on combination.
When proceeding to the final pledge step (createCheckout mutation), the backend rejected the request due to the mismatch, resulting in an error that was hard to trace.
- Ensured the app only loads and displays allowed add-ons for the selected reward. …
> MBL-2248 [Pledge] The system does not allow pledging when  adding add-ons

- app/src/main/java/com/kickstarter/features/rewardtracking/RewardTrackingViews.kt
- app/src/main/java/com/kickstarter/ui/compose/KSImageCompose.kt
Created modal in compose for tracking numbers in the view your pledge screen
modified KSAsyncImage to take a null photo
Made some edits/cleaned up the reward tracking composables
| --- | --- |
| ![Screenshot_20250407_173221](https://github.com/user-attachments/assets/588dc8f5-bed3-476b-95bc-42841733c0f4)  | ![Screenshot_20250407_173058](https://github.com/user-attachments/assets/389e9220-87e0-4368-a92e-572a7d8c1667) |
Make sure if you have built something using ksAsyncImage, that it is still working. I checked the similar projects carousel and it was working fine, but please double check if youve used it elsewhere. 
Otherwise, there are no user facing changes
[MBL-2287: Create UI for tracking number modal in view your pledge …
> MBL-2287: Create UI for tracking number modal in view your pledge screen

- app/src/main/java/com/kickstarter/ui/activities/compose/search/CategorySelectionSheet.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/search/FilterMenuBottomSheet.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/search/SearchScreen.kt
- app/src/main/java/com/kickstarter/ui/compose/designsystem/KSDimensions.kt
- app/src/test/java/com/kickstarter/ui/activities/compose/search/CategorySelectionSheetTest.kt
- app/src/test/java/com/kickstarter/ui/activities/compose/search/FilterMenuBottomSheetTest.kt
- app/src/test/java/com/kickstarter/ui/activities/compose/search/SearchScreenTest.kt
- Now the user can navigate between menu options within the same bottomSheet, 
- pressing the filter pillButton, can navigate to the categories screen.
- pressing the categories pillButton,  can navigate back to the main filter menu screen.
- pressing the project status pillButton, has the same behaviour as the filter button.
- Improve filtering experience.
- Feature working on Emulator (MBL-2225)
https://github.com/user-attachments/assets/b2e97fa0-7a31-4dbe-bd8b-f441ae01a084
- Compose preview interactive mode supports the navigation as well (MBL-2223)
https://github.com/user-attachments/assets/5485a33e-f979-4794-b98f-01777eb1b3f5
|  |  |
All related to category selection keeps working exactly as in Phase 1, except for reset button updates.
- Select 1 category
- Apply 1 category
- Reset 1 …
> MBL-2225 && MBL-2223: Navigation between Main Filter menu screen (includes project state filter), and the Category Selection screen

- app/src/main/java/com/kickstarter/viewmodels/projectpage/CrowdfundCheckoutViewModel.kt
- app/src/main/res/menu/manage_pledge_plot_selected.xml
- app/src/test/java/com/kickstarter/viewmodels/CrowdfundCheckoutViewModelTest.kt
Added conditional logic to correctly update the payment method for PLOT (Pledge Over Time) projects and enabled the "Change payment method" option in the manage_pledge_plot_selected.xml menu for such projects.
PLOT projects have strict backend requirements that disallow sending extra pledge data (like amount, reward IDs, or location) when updating the payment method — doing so results in a "Feature unavailable" error. Additionally, the UI previously didn’t offer a way to trigger payment method changes for PLOT pledges, so this needed to be addressed.
In CrowdfundCheckoutViewModel, updated updateBacking() logic for PledgeReason.UPDATE_PAYMENT:
- If the project is PLOT: only the paymentSourceId is sent.
- If the project is not PLOT: legacy behavior remains, sending reward IDs, location, and …
> MBL-2263: [PLOT]The "Change payment method" should enable 

- app/src/internal/java/com/kickstarter/ui/activities/DesignSystemActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/search/MultiCategorySelectionSheet.kt
- app/src/main/java/com/kickstarter/ui/compose/designsystem/KSButtonColorVariables.kt
- app/src/main/java/com/kickstarter/ui/compose/designsystem/KSButtonsColors.kt
- app/src/main/java/com/kickstarter/ui/compose/designsystem/KSButtonsV2.kt
v2 buttons were not formatted for dark mode, and there were a few color mistakes that needed to be corrected. 
This PR fixes those issues. 
Added dark mode colors for v2 buttons
https://github.com/user-attachments/assets/5e70f7ce-7e22-44f3-a1ad-ba0e265e1342 
https://github.com/user-attachments/assets/c4217312-3e31-46b1-9b9c-7f548aec1644
Dark and light mode figma designs are included in the ticket.
Compare dark mode and light mode buttons in the design system to the figma designs
**Note: the sun button in the tool bar changes the design system activity from light to dark, however this does not work for v2 buttons. You will have to manually set the phone to light/dark mode in the system settings to see the changes.** 
[MBL-2414: Fix android v2 buttons for …
> MBL-2414: Fix android v2 buttons for darkmode

- app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/BackingDetailsActivity.kt
- app/src/main/java/com/kickstarter/ui/activities/SurveyResponseActivity.kt
MBL-2431: Apply window insets fix to `SurveyResponseActivity` & `BackingDetailsActivity`
https://github.com/user-attachments/assets/7c73da99-2b60-492f-b93a-124afba1b6dd
https://github.com/user-attachments/assets/3bf6bb88-fef7-4033-a3fd-5d2b0ee807f8
Respond to a Survey that requires keyboard entry in two scenarios:
- `BackingDetailsActivity` is launched from the Backings Dashboard. Open the Backings Dashboard and click 'Take Survey'.
- `SurveyResponseActivity` is launched from a deep link. Visit the Project's backing details  in a browser, and click the 'Open' in app banner at the top of the website.
[\[MBL-2431\] Keyboard hides Survey response form - Jira](https://kickstarter.atlassian.net/browse/MBL-2431)
> MBL-2431: Insets fix for SurveyResponseActivity, BackingDetailsActivity

- app/src/main/graphql/project.graphql
- app/src/main/java/com/kickstarter/features/search/ui/SearchAndFilterActivity.kt
- app/src/main/java/com/kickstarter/services/DiscoveryParams.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/search/CategorySelectionSheet.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/search/FilterMenuBottomSheet.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/search/PercentageRaisedSheet.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/search/SearchEmptyView.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/search/SearchScreen.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/search/SearchTopBar.kt
- app/src/main/java/com/kickstarter/ui/compose/designsystem/KSButtons.kt
- app/src/main/java/com/kickstarter/ui/views/compose/search/SearchTopBar.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/kickstarter/ui/activities/compose/search/CategorySelectionSheetTest.kt
- app/src/test/java/com/kickstarter/ui/activities/compose/search/FilterMenuBottomSheetTest.kt
- app/src/test/java/com/kickstarter/ui/activities/compose/search/PercentageRaisedSheetTest.kt
- app/src/test/java/com/kickstarter/ui/activities/compose/search/SearchScreenTest.kt
- app/src/test/java/com/kickstarter/ui/activities/compose/search/SearchTopBarTest.kt
Phase 4: Percentage raised UI is ready, including navigation
- 📥 Feature flag code moved from gating phase 2: Project status to now gate phase 4.
-  📥 MBL-2345: New pillButton on pillBar
- 📥 MBL-2347: Percentage Raised Screen
- 📥 MBL-2349: Navigation (Percentage Raised Screen within SearchPager)
https://github.com/user-attachments/assets/727f63e9-ba85-40a0-bafd-574ce10e7c20
- Increase search & filter capabilities
- New PillButton added to SearchTopBar
- New screen created `PercentageRaised`
- Added `PercentageRaised` screen to existing pager
https://github.com/user-attachments/assets/117b8386-e0c8-4d7b-8d16-5070960ef253
| --- | --- |
|  |  |
- Load the search experience, if feature flag on you should see the "% raised" pill, be able to navigate to it from the filter menu, and when new …
> MBL-2345 && MBL-2347 && MBL-2349:Percentage raised filter UI

- app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/CheckoutFlowViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
- app/src/main/java/com/kickstarter/viewmodels/projectpage/RewardsSelectionViewModel.kt
- app/src/test/java/com/kickstarter/viewmodels/ProjectPageViewModelTest.kt
- app/src/test/java/com/kickstarter/viewmodels/RewardsSelectionViewModelTest.kt
Refactored the onContinueClicked method in CheckoutFlowViewModel to support a simplified use case where only a continueCallback is needed. This is now used in ProjectPageActivity when login flow is already guaranteed to be completed.
The original onContinueClicked required both logInCallback and continueCallback, even in cases where the user is already logged in and the login check was redundant. This change adds a simpler, cleaner path for flows where login gating is handled earlier in the UI flow, improving readability and responsibility separation.
Implemented the onContinueClicked(continueCallback: () -> Unit) method to:
- Emit the next UI state (currentPage = 4, expanded = true)
- Immediately invoke the provided continueCallback
- Updated ProjectPageActivity to use this simplified …
> MBL- 2489 Late pledges Regression for Android 3.32.0

- app/src/main/graphql/fragments.graphql
- app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
Videos were unable to be played on the project page when the entry point was from search.
This was caused by omitting the video fragment from the project list calls made from search, causing the video urls to be null.
Added the video object to the project card fragment
**Before** 🐛 
https://github.com/user-attachments/assets/ac0b3918-ad0c-4b9b-8917-8149683e62b9
**After** 🦋 
https://github.com/user-attachments/assets/6fcbaeab-d573-4020-9378-fcaec16965a0
Open search screen, tap on a project and observe that video playback is working correctly, search for a project and observe that video is working correctly
[no-jira]
> [no-jira] Fix project video player not working when loaded from search

- app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
- app/src/main/java/com/kickstarter/ui/data/ManagePledgeMenuOptions.kt
- app/src/main/java/com/kickstarter/ui/helpers/ManagePledgeMenuOptionsFactory.kt
- app/src/main/res/menu/manage_pledge.xml
- app/src/test/java/com/kickstarter/viewmodels/ProjectPageViewModelTest.kt
Fix the choose another reward option on new manage pledge menu to be shown when FF is off
On the refactor of the menu for manage pledge the choose another reward was deleted in order to use the Edit Pledge option, but when feature flag is off it should appear and when ff is on it should appear for non-plot projects
- Added choose another reward option to xml menu
- Add validations to show it or not matchin iOS behavior
- FEATURE FLAG OFF NO-PLOT PROJECT
[ff_off_non_plot.webm](https://github.com/user-attachments/assets/401dc5fc-72a8-491c-8792-c95aa4555e37)
- FEATURE FLAG OFF PLOT PROJECT
[ff_off_plot.webm](https://github.com/user-attachments/assets/afd06db1-27cf-4e27-bf92-64734a339e96)
- FEATURE FLAG ON NO-PLOT PROJECT
[ff_on_non_plot_project.webm](https://github.com/user-attachments/assets …
> MBL-2585 [Edit PLOT- FF disabled] The standard promise does not display the edit option

- app/src/main/java/com/kickstarter/features/search/ui/SearchAndFilterActivity.kt
- app/src/main/java/com/kickstarter/features/search/viewmodel/SearchAndFilterViewModel.kt
- app/src/main/java/com/kickstarter/libs/utils/extensions/DiscoveryParamsExt.kt
- app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/search/FilterMenuSheet.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/search/SearchScreen.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/search/SearchTopBar.kt
- app/src/test/java/com/kickstarter/features/search/viewmodel/SearchAndFilterViewModelTest.kt
- app/src/test/java/com/kickstarter/ui/activities/compose/search/SearchScreenTest.kt
- app/src/test/java/com/kickstarter/ui/activities/compose/search/SearchTopBarTest.kt
- MBL-2570: Adds pillbar for new goal filter to SearchTopBar
- MBL-2568: Adds new page to the pager + navigation(opens bottomSheet on GoalSheet page when pressing pillbar and new row added on FilterMenuSheet for Goal Filter)
- MBL-2570:  SearchAndFilterVM handles now a new parameter on DiscoveryParams, and projects query has been extended to support the new parameter
- Added some tests and modified others to consider goal filter
- Adding new filtering options for goal amount(Phase 7)
[Goal filter.webm](https://github.com/user-attachments/assets/b85fbfc5-5674-4a01-a850-aeb31d6a00d5)
- Click Goal pillBar -> should open goal screen, navigate back to the menu, dismiss ... etc.
- Click Goal row ->  should open goal screen, navigate back to the menu, dismiss ... etc
- Execute some searches with …
> MBL-2570 && MBL-2568 && MBL-2572: (Phase 7) Goal filter

- app/src/main/java/com/kickstarter/features/search/viewmodel/FilterMenuViewModel.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/search/FilterMenuSheet.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/search/SearchTopBar.kt
- app/src/test/java/com/kickstarter/features/search/viewmodel/FilterMenuViewModelTest.kt
- app/src/test/java/com/kickstarter/ui/activities/compose/search/FilterMenuSheetTest.kt
- app/src/test/java/com/kickstarter/ui/activities/compose/search/LocationSheetTest.kt
- app/src/test/java/com/kickstarter/ui/activities/compose/search/SearchScreenTest.kt
- app/src/test/java/com/kickstarter/ui/activities/compose/search/SearchTopBarTest.kt
- Show only toggles and pills should be available only for logged in users
- The order of the pills and the "Show Only" row have changed
- `FilterMenuViewModel` now has a state for `loggedInUser`, on init we check if the current user is present or not.
- Now `FilterMenuSheet` and `SearchTopBar` both use `CompositionLocalProvider` to have access to `FilterMenuViewModel`
| Logged In User | 
https://github.com/user-attachments/assets/608b93ea-524c-447d-91e6-ded7dfa42424
| Logged Out User |
https://github.com/user-attachments/assets/0866b067-0b77-4258-8915-37c516cfbd30
| --- | --- |
|  |  |
- Log in and check the "Show only" toggles and pills are visible
- Log out and make sure none of the "Show only" and pills are visible
[MBL-2615](https://kickstarter.atlassian.net/browse/MBL-2615) …
> MBL-2615: Logged in/out user logic

- app/src/main/java/com/kickstarter/libs/utils/extensions/StringExt.kt
- app/src/main/java/com/kickstarter/ui/views/KSWebView.kt
- app/src/test/java/com/kickstarter/libs/utils/extensions/StringExtKtTest.kt
Mask the KSWebView `userAgentString` on Android 16+.
Since around July 27, 2025, KSR hosted assets (among a few other things) started failing to load for requests that included a User-Agent header associated with at least some—if not all—devices running Android 16. By partially masking the User-Agent string, assets successfully load.
See [Android Developers Blog: User-Agent Reduction on Android WebView](https://android-developers.googleblog.com/2024/12/user-agent-reduction-on-android-webview.html) for details on the choice of mask.
https://github.com/user-attachments/assets/743a7055-4197-4ba3-a2f4-58671d111544
https://github.com/user-attachments/assets/855da892-7678-4c4f-97e5-822dc3271e1b
On a physical device running Android 16, all pages opened with a KSWebView should load normally, …
> Mask the KSWebView `userAgentString` on Android 16+

- app/src/main/java/com/kickstarter/libs/utils/SystemClock.kt
- app/src/main/java/com/kickstarter/ui/activities/compose/OnboardingFlowScreen.kt
- app/src/test/java/com/kickstarter/ui/activities/compose/OnboardingFlowScreenTest.kt
Refactor the onboarding flow logic and tests to use an injectable Clock, with a FakeClock implementation that can be manually advanced in time so that we don't have to call Thread.sleep() in tests.
The button debounce in the onboarding flow was implemented using the real clock System.currentTimeMillis(), which required us to call Thread.sleep() to pass real time. But Thread.sleep() slows down our tests because it uses real time and can sometimes cause flakey behavior. 
Create an injectable clock interface with two implementations - SystemClock and FakeClock.
- The real SystemClock is used in code to avoid hardcoding System.currentTimeMillis().
- The FakeClock is injected in tests and can be used to advance the time manually using the advanceBy() method. Use this FakeClock instead of …
> MBL-2727 Refactor onboarding flow tests to avoid calling Thread.sleep()
